### ISSUE TITLE
[Bug] The problem has not been solved yet

### ISSUE THREAD

**Issue by Jzow** [coqui-ai/TTS#1120]
```python
import torch
synthesizer = torch.hub.load('coqui-ai/TTS:dev',
                             'tts',
                             source='github')
wav = synthesizer.tts("This is an open-source library that generates synthetic speech!")


C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe E:/iston_algorithm/util/speech/TextTest.py
Using cache found in C:\Users\Administrator/.cache\torch\hub\coqui-ai_TTS_dev
Traceback (most recent call last):
  File "E:/iston_algorithm/util/speech/TextTest.py", line 2, in <module>
    synthesizer = torch.hub.load('coqui-ai/TTS:dev',
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 427, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 230, in _load_entry_from_hubconf
    _check_dependencies(m)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 219, in _check_dependencies
    raise RuntimeError('Missing dependencies: {}'.format(', '.join(missing_deps)))
RuntimeError: Missing dependencies: mecab-python3, unidic-lite
```

**Comment by Jzow** [comment]
#788

**Comment by erogol** [comment]
We'll drop torch hub support. This issue won't be solved.

**Comment by Jzow** [comment]
@erogol hi, Is there any alternative? I have a long IELTS article that needs TTS operation
