### ISSUE TITLE
[Bug] Syntax Error: invalid syntax (async=True)

### ISSUE THREAD

**Issue by ProgrammingLife** [coqui-ai/TTS#1275]
## 🐛 Description

Installed TTS with: 
```
python3.9 -m pip install TTS
```
and trying to run TTS for the first time.

I have installed a few versions of Python. Maybe TTS chooses wrong version of Python? How does it detect which python to run?

### To Reproduce

I just run: 
```
$ tts --list_models

Traceback (most recent call last):
  File "/home/denis/.local/bin/tts", line 5, in <module>
    from TTS.bin.synthesize import main
  File "/home/denis/.local/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/denis/.local/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 11, in <module>
    from TTS.tts.utils.speakers import SpeakerManager
  File "/home/denis/.local/lib/python3.9/site-packages/TTS/tts/utils/speakers.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/denis/.local/lib/python3.9/site-packages/TTS/utils/audio.py", line 3, in <module>
    import librosa
  File "/home/denis/.local/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/denis/.local/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/denis/.local/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/denis/.local/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/denis/.local/lib/python3.9/site-packages/librosa/util/__init__.py", line 84, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "/home/denis/.local/lib/python3.9/site-packages/librosa/util/files.py", line 11, in <module>
    import pooch
  File "/home/denis/.local/lib/python3.9/site-packages/pooch/__init__.py", line 10, in <module>
    from .core import Pooch, create, retrieve
  File "/home/denis/.local/lib/python3.9/site-packages/pooch/core.py", line 31, in <module>
    from .downloaders import choose_downloader
  File "/home/denis/.local/lib/python3.9/site-packages/pooch/downloaders.py", line 23, in <module>
    import paramiko
  File "/usr/lib/python3/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 66, in <module>
    from paramiko.sftp_client import SFTPClient
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 41, in <module>
    from paramiko.sftp_file import SFTPFile
  File "/usr/lib/python3/dist-packages/paramiko/sftp_file.py", line 66
    self._close(async=True)
                ^
SyntaxError: invalid syntax

$ tts --text "Text for TTS"
... the same output here ....
```
### Expected behavior

Running TTS.

### Environment

- 🐸TTS Version: 0.5.0
- PyTorch Version: 1.10.2+cu102
- Python version: 3.9.10 (my `/usr/bin/python3` points to `/usr/bin/python3.9`)
- OS: Linux Mint 19.1
- CUDA/cuDNN version: 10.2
- How you installed PyTorch (`conda`, `pip`, source): pip

### Additional context

**Comment by Edresson** [comment]
Hello, I guess that you are using an old librosa version. Please make sure that your librosa version is 0.8.0. I tested it with a new anaconda env to guarantee that I haven't old packages installed and it works.

If you like you can try:
```  

conda create -n py39 python=3.9 anaconda

conda activate py39

python3.9 -m pip install TTS

```

**Comment by ProgrammingLife** [comment]
> conda create -n py39 python=3.9 anaconda
> conda activate py39
> python3.9 -m pip install TTS

I've also done all those steps. And now it works! Thanks for the help!
