### ISSUE TITLE
[Bug] The format of config.json for encoder model is not correct?

### ISSUE THREAD

**Issue by hemath1001** [coqui-ai/TTS#1328]
Hi there! Thanks for your great work! 

I tried:
`tts --text "hello, what's your name" --speaker_wav "D:\coqui\wav\textIn.wav" --encoder_config_path "D:\coqui\models\encoder\iter25k\config.json" --encoder_path "D:\coqui\models\encoder\iter25k\best_model.pth.tar" --out_path "D:\coqui\wav\testOut.wav"`  
I downloaded the encoder model from [Released-Models](https://github.com/mozilla/TTS/wiki/Released-Models).
But I got the error:
```
Traceback (most recent call last):   
  File "D:\coqui\TTS\Scripts\tts-script.py", line 33, in <module>   
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "d:\coqui\tts\TTS\bin\synthesize.py", line 260, in main
    synthesizer = Synthesizer(
  File "d:\coqui\tts\TTS\utils\synthesizer.py", line 78, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "d:\coqui\tts\TTS\utils\synthesizer.py", line 122, in _load_tts
    speaker_manager = self._init_speaker_encoder(speaker_manager)
  File "d:\coqui\tts\TTS\utils\synthesizer.py", line 187, in _init_speaker_encoder
    speaker_manager = SpeakerManager(
  File "d:\coqui\tts\TTS\tts\utils\speakers.py", line 84, in __init__
    self.init_speaker_encoder(encoder_model_path, encoder_config_path)
  File "d:\coqui\tts\TTS\tts\utils\speakers.py", line 254, in init_speaker_encoder
    self.speaker_encoder_config = load_config(config_path)
  File "d:\coqui\tts\TTS\config\__init__.py", line 94, in load_config
    model_name = _process_model_name(config_dict)
  File "d:\coqui\tts\TTS\config\__init__.py", line 62, in _process_model_name
    model_name = model_name.replace("_generator", "").replace("_discriminator", "")
AttributeError: 'dict' object has no attribute 'replace'
```
Seems that the key “model" in config dict should be a string, but now it is a dict.
I tried 3 encoder models: 2 from [Released-Models](https://github.com/mozilla/TTS/wiki/Released-Models) and 1 from [GlowTTS](https://github.com/Edresson/SC-GlowTTS) (I found someone successfully run GlowTTS with new speaker wav in [issue465](https://github.com/coqui-ai/TTS/issues/465)), but all of them resulted in the same error.
I compared the config.json in current encoder models and the one in YourTTS, and found there are some differences, for example the key "model" should be "model_params" dict, and "model_name" key should be added to "model_params" dict, etc.
I tried to modified the current config.json and finally made it to run tts.exe with no error, but I am not sure whether it is correct.

I would be very grateful if someone could advise me on how to make the encoder model work :-D

Besides, how can I figure out what kind of loss do the 2 encoder models in  [Released-Models](https://github.com/mozilla/TTS/wiki/Released-Models) use? The config.json of encoder model seems not to include that information.

**Comment by erogol** [comment]
Can you try the dev branch ?

**Comment by hemath1001** [comment]
> Can you try the dev branch ?

Hi @erogol ! I tried dev branch, and got some error...
**First is:**
Traceback (most recent call last):
```
  File "D:\coqui\Coqui-TTS-dev\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "D:\coqui\Coqui-TTS-dev\Scripts\tts-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Anaconda\envs\coqui\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Anaconda\envs\coqui\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\coqui\coqui-tts-dev\TTS\bin\synthesize.py", line 11, in <module>
    from TTS.utils.manage import ModelManager
  File "d:\coqui\coqui-tts-dev\TTS\utils\manage.py", line 10, in <module>
    from TTS.config import load_config
  File "d:\coqui\coqui-tts-dev\TTS\config\__init__.py", line 10, in <module>
    from TTS.config.shared_configs import *
  File "d:\coqui\coqui-tts-dev\TTS\config\shared_configs.py", line 5, in <module>
    from trainer import TrainerConfig
  File "d:\coqui\coqui-tts-dev\lib\site-packages\trainer\__init__.py", line 1, in <module>
    from trainer.trainer import *
  File "d:\coqui\coqui-tts-dev\lib\site-packages\trainer\trainer.py", line 11, in <module>
    from curses import meta
  File "D:\Anaconda\envs\coqui\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```
**I installed "curses" and fixed it. 
Then second error came:**
```
Traceback (most recent call last):
  File "D:\X479\coqui\Coqui-TTS-0.6.1\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "D:\X479\coqui\Coqui-TTS-0.6.1\Scripts\tts-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Anaconda\envs\coqui\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Anaconda\envs\coqui\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\x479\coqui\coqui-tts-0.6.1\TTS\bin\synthesize.py", line 11, in <module>
    from TTS.utils.manage import ModelManager
  File "d:\x479\coqui\coqui-tts-0.6.1\TTS\utils\manage.py", line 10, in <module>
    from TTS.config import load_config
  File "d:\x479\coqui\coqui-tts-0.6.1\TTS\config\__init__.py", line 10, in <module>
    from TTS.config.shared_configs import *
  File "d:\x479\coqui\coqui-tts-0.6.1\TTS\config\shared_configs.py", line 5, in <module>
    from trainer import TrainerConfig
  File "d:\x479\coqui\coqui-tts-0.6.1\lib\site-packages\trainer\__init__.py", line 1, in <module>
    from trainer.trainer import *
  File "d:\x479\coqui\coqui-tts-0.6.1\lib\site-packages\trainer\trainer.py", line 55, in <module>
    multiprocessing.set_start_method("fork")
  File "D:\Anaconda\envs\coqui\lib\multiprocessing\context.py", line 247, in set_start_method
    self._actual_context = self.get_context(method)
  File "D:\Anaconda\envs\coqui\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "D:\Anaconda\envs\coqui\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```
It is strange. Maybe some requiements for packages  are missing?
And also during installation, I found "trainer" had been changed to "coqui-trainer" when "git+https://github.com/coqui-ai/trainer.git", and I just checked commit records and found this had been fixed. Thanks for your work~
