### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'hop_length'

### ISSUE THREAD

**Issue by upskyy** [coqui-ai/TTS#1366]
### To Reproduce

```
 > EPOCH: 0/1000
 --> /home/patrick/TTS/recipes/ljspeech/hifigan/run-March-10-2022_01+04PM-0cf3265a
 ! Run is removed from /home/patrick/TTS/recipes/ljspeech/hifigan/run-March-10-2022_01+04PM-0cf3265a
Traceback (most recent call last):
  File "/home/patrick/.conda/envs/tts/lib/python3.8/site-packages/trainer/trainer.py", line 1403, in fit
    self._fit()
  File "/home/patrick/.conda/envs/tts/lib/python3.8/site-packages/trainer/trainer.py", line 1387, in _fit
    self.train_epoch()
  File "/home/patrick/.conda/envs/tts/lib/python3.8/site-packages/trainer/trainer.py", line 1148, in train_epoch
    self.train_loader = self.get_train_dataloader(
  File "/home/patrick/.conda/envs/tts/lib/python3.8/site-packages/trainer/trainer.py", line 679, in get_train_dataloader
    return self._get_loader(
  File "/home/patrick/.conda/envs/tts/lib/python3.8/site-packages/trainer/trainer.py", line 643, in _get_loader
    loader = model.get_data_loader(
  File "/home/patrick/TTS/TTS/vocoder/models/gan.py", line 337, in get_data_loader
    hop_len=self.ap.hop_length,
AttributeError: 'NoneType' object has no attribute 'hop_length'
```

### Expected behavior

In train_hifigan.py, 
```python
import os

from trainer import Trainer, TrainerArgs

from TTS.utils.audio import AudioProcessor
from TTS.vocoder.configs import HifiganConfig
from TTS.vocoder.datasets.preprocess import load_wav_data
from TTS.vocoder.models.gan import GAN

output_path = os.path.dirname(os.path.abspath(__file__))

config = HifiganConfig(
    batch_size=32,
    eval_batch_size=16,
    num_loader_workers=4,
    num_eval_loader_workers=4,
    run_eval=True,
    test_delay_epochs=5,
    epochs=1000,
    seq_len=8192,
    pad_short=2000,
    use_noise_augment=True,
    eval_split_size=10,
    print_step=25,
    print_eval=False,
    mixed_precision=False,
    lr_gen=1e-4,
    lr_disc=1e-4,
    data_path=os.path.join(output_path, "../LJSpeech-1.1/wavs/"),
    output_path=output_path,
)

# init audio processor
ap = AudioProcessor(**config.audio.to_dict())

# load training samples
eval_samples, train_samples = load_wav_data(config.data_path, config.eval_split_size)

# init model
model = GAN(config, ap)           # Here

# init the trainer and 🚀
trainer = Trainer(
    TrainerArgs(),
    config,
    output_path,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples,
    training_assets={"audio_processor": ap},
)
trainer.fit()
```

because, `ap` default value is None.  

```python
class GAN(BaseVocoder):
    def __init__(self, config: Coqpit, ap: AudioProcessor = None):
        """Wrap a generator and a discriminator network. It provides a compatible interface for the trainer.
        It also helps mixing and matching different generator and disciminator networks easily.
        To implement a new GAN models, you just need to define the generator and the discriminator networks, the rest
        is handled by the `GAN` class.
        Args:
            config (Coqpit): Model configuration.
            ap (AudioProcessor): 🐸TTS AudioProcessor instance. Defaults to None.
        Examples:
            Initializing the GAN model with HifiGAN generator and discriminator.
            >>> from TTS.vocoder.configs import HifiganConfig
            >>> config = HifiganConfig()
            >>> model = GAN(config)
        """
        super().__init__(config)
        self.config = config
        self.model_g = setup_generator(config)
        self.model_d = setup_discriminator(config)
        self.train_disc = False  # if False, train only the generator.
        self.y_hat_g = None  # the last generator prediction to be passed onto the discriminator
        self.ap = ap
```

If `ap` is added, training proceeds, but the loss value does not drop.

<img width="1395" alt="스크린샷 2022-03-10 오후 2 03 52" src="https://user-images.githubusercontent.com/54731898/157593203-556519e4-95f6-4e03-a53c-880890cddbce.png">

### Environment

- 🐸TTS Version (e.g., 1.3.0):  0.6.1
- PyTorch Version (e.g., 1.8) :  1.10.2
- Python version:  3.8.12
- OS (e.g., Linux):  Linux 
- CUDA/cuDNN version:  11.3.1
- GPU models and configuration: GeForce 3090
- How you installed PyTorch (`conda`, `pip`, source): conda
- Any other relevant information:

**Comment by lvialle** [comment]
Yes, exactly the same issue since 0.6
