### ISSUE TITLE
[Bug] V0.5 -> V0.6.1 Throws "size mismatch for text_encoder.emb.weight:"

### ISSUE THREAD

**Issue by automationist** [coqui-ai/TTS#1432]
## 🐛 Description
I have a multi-speaker VITS model that was trained with V0.5 and I'm trying to have inference done with V0.6.1. It seems to have issues loading the model, throwing:
```
Traceback (most recent call last):
  File "/usr/local/bin/tts-server", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts-server')())
  File "/usr/local/bin/tts-server", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/TTS/TTS/server/server.py", line 111, in <module>
    use_cuda=args.use_cuda,
  File "/home/ubuntu/TTS/TTS/utils/synthesizer.py", line 76, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/home/ubuntu/TTS/TTS/utils/synthesizer.py", line 119, in _load_tts
    self.tts_model.load_checkpoint(self.tts_config, tts_checkpoint, eval=True)
  File "/home/ubuntu/TTS/TTS/tts/models/vits.py", line 1458, in load_checkpoint
    self.load_state_dict(state["model"])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Vits:
        size mismatch for text_encoder.emb.weight: copying a param with shape torch.Size([194, 192]) from checkpoint, the shape in current model is torch.Size([131, 192]).
```

I did add an em dash to the character set, I'm wondering if that's related?

**Comment by WeberJulian** [comment]
Yeah there were some issues with VITS character set (punctuation was added twice), It was fixed but it might cause issues with models trained with previous versions. In general, it's best to use the TTS version used at train time during inference.
