### ISSUE TITLE
[Bug] ValueError: numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by 0x11c11e** [coqui-ai/TTS#1442]
Hi,

When typing: tts --models

```
(env) user@localhost:~/Codes/TTS$ tts --models
Traceback (most recent call last):
  File "/home/user/Codes/TTS/env/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/home/user/Codes/TTS/env/bin/tts", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/Codes/TTS/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/user/Codes/TTS/TTS/utils/synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/user/Codes/TTS/TTS/utils/audio.py", line 5, in <module>
    import pyworld as pw
  File "/home/user/Codes/TTS/env/lib/python3.9/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

When trying to upgrade numpy,

```
(env) user@localhost:~/Codes/TTS$ pip install --upgrade numpy
Requirement already satisfied: numpy in ./env/lib/python3.9/site-packages (1.19.5)
Collecting numpy
  Using cached numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tts 0.6.1 requires numpy==1.19.5, but you have numpy 1.22.3 which is incompatible.
```

Python Version: 3.9.2
Linux-Debian

```
anyascii              0.3.0
appdirs               1.4.4
astroid               2.7.3
audioread             2.1.9
Babel                 2.9.1
black                 22.1.0
bokeh                 1.4.0
certifi               2021.10.8
cffi                  1.15.0
charset-normalizer    2.0.12
click                 8.0.4
coqpit                0.0.15
coqui-trainer         0.0.5
coverage              6.3.2
cycler                0.11.0
Cython                0.29.28
dateparser            1.0.0
decorator             5.1.1
docopt                0.6.2
Flask                 2.0.3
fonttools             4.31.1
fsspec                2022.2.0
gruut                 2.0.4
gruut-ipa             0.10.1
gruut-lang-cs         2.0.0
gruut-lang-de         2.0.0
gruut-lang-es         2.0.0
gruut-lang-fr         2.0.0
gruut-lang-it         2.0.0
gruut-lang-nl         2.0.0
gruut-lang-pt         2.0.0
gruut-lang-ru         2.0.0
gruut-lang-sv         2.0.0
idna                  3.3
inflect               5.4.0
isort                 5.10.1
itsdangerous          2.1.1
jieba                 0.42.1
Jinja2                3.0.3
joblib                1.1.0
jsonlines             1.2.0
kiwisolver            1.4.0
lazy-object-proxy     1.7.1
librosa               0.8.0
llvmlite              0.36.0
MarkupSafe            2.1.1
matplotlib            3.5.1
mccabe                0.6.1
mecab-python3         1.0.3
mypy-extensions       0.4.3
networkx              2.7.1
nose                  1.3.7
num2words             0.5.10
numba                 0.53.0
numpy                 1.22.3
packaging             21.3
pandas                1.4.1
pathspec              0.9.0
Pillow                9.0.1
pip                   20.3.4
pkg-resources         0.0.0
platformdirs          2.5.1
pooch                 1.6.0
protobuf              3.19.4
pycparser             2.21
pylint                2.10.2
pynndescent           0.5.6
pyparsing             3.0.7
pypinyin              0.46.0
pysbd                 0.3.4
python-crfsuite       0.9.7
python-dateutil       2.8.2
pytz                  2022.1
pytz-deprecation-shim 0.1.0.post0
pyworld               0.3.0
PyYAML                6.0
regex                 2022.3.15
requests              2.27.1
resampy               0.2.2
scikit-learn          1.0.2
scipy                 1.8.0
setuptools            44.1.1
six                   1.16.0
SoundFile             0.10.3.post1
tensorboardX          2.5
threadpoolctl         3.1.0
toml                  0.10.2
tomli                 2.0.1
torch                 1.11.0
torchaudio            0.11.0
tornado               6.1
tqdm                  4.63.0
TTS                   0.6.1        /home/user/Codes/TTS
typing-extensions     4.1.1
tzdata                2022.1
tzlocal               4.1
umap-learn            0.5.1
unidic-lite           1.0.8
urllib3               1.26.9
webrtcvad             2.0.10
Werkzeug              2.0.3
wrapt                 1.12.1
```

**Comment by WeberJulian** [comment]
Hi first of all, the command to list the available models is `tts --list_models`, but that shouldn't solve your issue...

How did you install TTS?

**Comment by 0x11c11e** [comment]
pip install tts

**Comment by p0p4k** [comment]
uninstall and reinstall numpy <--- Fix

**Comment by 0x11c11e** [comment]
uninstall it using: pip uninstall numpy
then install it again using: pip install numpy
and got this error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tts 0.6.1 requires numpy==1.19.5, but you have numpy 1.22.3 which is incompatible.
```

then uninstall it again using: pip uninstall numpy
then install it using: pip install tts
then run the command: tts --list_models
and got this error:

```
(env) user@localhost:~/Codes/TTS$ tts --list_models
Traceback (most recent call last):
  File "/home/user/Codes/TTS/env/bin/tts", line 5, in <module>
    from TTS.bin.synthesize import main
  File "/home/user/Codes/TTS/env/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/user/Codes/TTS/env/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/user/Codes/TTS/env/lib/python3.9/site-packages/TTS/utils/audio.py", line 5, in <module>
    import pyworld as pw
  File "/home/user/Codes/TTS/env/lib/python3.9/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

**Comment by erogol** [comment]
You got to install pyworld once again after you reinstall numpy.

Or use conda to virtenv to install TTS following the guideline https://tts.readthedocs.io/en/latest/installation.html

**Comment by 0x11c11e** [comment]
> Hey @0x11c11e , have you managed to fix your install with conda or virtenv? I can share my own conda environment if you

it starts working when i used conda but not virtenv. even i saw the same issue on colab.

**Comment by iwater** [comment]
I think this issue should not be closed, because neither pip install tts nor pip install after clone source code doesn't working
