### ISSUE TITLE
RuntimeError:  [!] Mean-Var stats does not match the given feature dimensions. {multispeaker model with multiband-melgan}

### ISSUE THREAD

**Issue by gurpreet395** [coqui-ai/TTS#1499]
Hi Guys, I am trying to use following command to generate audio using yourtts model and multiband-melgan vocoder.

tts --text "there was a crow" --model_name tts_models/multilingual/multi-dataset/your_tts --speaker_idx "female-en-5" --language_idx en --vocoder_name vocoder_models/en/ljspeech/multiband-melgan

The only vocoder seems to be working with multi speaker model is "Griffin-Lim". However, the voice quality of this vocoder is pretty roboti.

Traceback:
Traceback (most recent call last):
  File "/home/gp/anaconda3/envs/tts/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/home/gp/anaconda3/envs/tts/lib/python3.6/site-packages/TTS/bin/synthesize.py", line 287, in main
    wav = synthesizer.tts(args.text, args.speaker_idx, args.language_idx, args.speaker_wav)
  File "/home/gp/anaconda3/envs/tts/lib/python3.6/site-packages/TTS/utils/synthesizer.py", line 269, in tts
    vocoder_input = self.vocoder_ap.normalize(mel_postnet_spec.T)
  File "/home/gp/anaconda3/envs/tts/lib/python3.6/site-packages/TTS/utils/audio.py", line 450, in normalize
    raise RuntimeError(" [!] Mean-Var stats does not match the given feature dimensions.")

**Comment by erogol** [comment]
yourTTS does not need a vocoder model. Just run it alone.
