### ISSUE TITLE
[Bug] Training exits with errors during model.fit() step in ForwardTTS

### ISSUE THREAD

**Issue by pdavlin** [coqui-ai/TTS#1516]
## 🐛 Description
Training exits with errors during model.fit() step after one epoch. I'm running included code for FastSpeech to verify on a different system than my own.

### To Reproduce

I'm running the following command:
```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 python TTS/bin/distribute.py --script recipes/ljspeech/fast_speech/train_fast_speech.py
```
Stack trace is at the bottom of the ticket (for clarity). The model appears to train one full epoch, but crashes during the `.fit()` function call, citing a CUDA RuntimeError.

### Environment

```json
{
    "CUDA": {
        "GPU": [
            "Tesla M40",
            "Tesla M40",
            "Tesla M40",
            "Tesla M40"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu102",
        "TTS": "0.6.1",
        "numpy": "1.22.3"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022"
    }
}
```

### Additional context

```bash
(venv) pdav@poweredge-gpu:/mnt/nvmeDrives/pdav/TTS$ CUDA_VISIBLE_DEVICES="0, 1, 2, 3" python3 TTS/bin/distribute.py --script recipes/ljspeech/ada_speech/train_ada_speech.py
['recipes/ljspeech/ada_speech/train_ada_speech.py', '--group_id=group_2022_04_19-222650', '--use_ddp=true', '--rank=0']
['recipes/ljspeech/ada_speech/train_ada_speech.py', '--group_id=group_2022_04_19-222650', '--use_ddp=true', '--rank=1']
['recipes/ljspeech/ada_speech/train_ada_speech.py', '--group_id=group_2022_04_19-222650', '--use_ddp=true', '--rank=2']
['recipes/ljspeech/ada_speech/train_ada_speech.py', '--group_id=group_2022_04_19-222650', '--use_ddp=true', '--rank=3']
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 13100 files in /mnt/nvmeDrives/pdav/TTS/recipes/ljspeech/LJSpeech-1.1
 | > Found 13100 files in /mnt/nvmeDrives/pdav/TTS/recipes/ljspeech/LJSpeech-1.1
 | > Found 13100 files in /mnt/nvmeDrives/pdav/TTS/recipes/ljspeech/LJSpeech-1.1
 | > Found 13100 files in /mnt/nvmeDrives/pdav/TTS/recipes/ljspeech/LJSpeech-1.1
 > Using CUDA: True
 > Number of GPUs: 4

 > Model has 37022561 parameters

 > EPOCH: 0/1000
 --> /mnt/nvmeDrives/pdav/TTS/recipes/ljspeech/ada_speech/ada_speech_ljspeech-April-19-2022_10+26PM-a7dd9de9




> DataLoader initialization
> DataLoader initialization
| > Tokenizer:
| > Tokenizer:
        | > add_blank: False
        | > add_blank: False
        | > use_eos_bos: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > use_phonemes: True
        | > phonemizer:
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme language: en-us
                | > phoneme backend: gruut
                | > phoneme backend: gruut
| > Number of instances : 12969
| > Number of instances : 12969




> DataLoader initialization
> DataLoader initialization
| > Tokenizer:
| > Tokenizer:
        | > add_blank: False
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > use_eos_bos: False
        | > phonemizer:
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme language: en-us
                | > phoneme backend: gruut
| > Number of instances : 12969
                | > phoneme backend: gruut
| > Number of instances : 12969
 | > Preprocessing samples
 | > Preprocessing samples
 | > Preprocessing samples
 | > Max text length: 188
 | > Max text length: 188
 | > Max text length: 188
 | > Min text length: 13
 | > Min text length: 13
 | > Min text length: 13
 | > Avg text length: 100.90014650319993
 | > Avg text length: 100.90014650319993
 | 
 | 
 | > Avg text length: 100.90014650319993
 | 
 | > Max audio length: 222643.0
 | > Max audio length: 222643.0
 | > Max audio length: 222643.0
 | > Min audio length: 24499.0
 | > Min audio length: 24499.0
 | > Min audio length: 24499.0
 | > Avg audio length: 144984.29755570978
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Batch group size: 0.
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.
 | > Preprocessing samples

 > TRAINING (2022-04-19 22:27:06) 
 | > Max text length: 188
 | > Min text length: 13
 | > Avg text length: 100.90014650319993
 | 
 | > Max audio length: 222643.0
 | > Min audio length: 24499.0
 | > Avg audio length: 144984.29755570978
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.

   --> STEP: 0/102 -- GLOBAL_STEP: 0
     | > loss_spec: 35.17921  (35.17921)
     | > loss_dur: 0.90413  (0.90413)
     | > loss_aligner: 24.39616  (24.39616)
     | > loss_binary_alignment: 4.66675  (4.66675)
     | > loss: 65.14625  (65.14625)
     | > duration_error: 5.96096  (5.96096)
     | > grad_norm: 95.10776  (95.10776)
     | > current_lr: 0.00000 
     | > step_time: 17.62430  (17.62435)
     | > loader_time: 27.84250  (27.84250)


   --> STEP: 50/102 -- GLOBAL_STEP: 50
     | > loss_spec: 35.64729  (35.82967)
     | > loss_dur: 0.91468  (0.96404)
     | > loss_aligner: 24.91524  (24.70225)
     | > loss_binary_alignment: 4.63629  (4.55775)
     | > loss: 66.11349  (66.05370)
     | > duration_error: 6.10005  (6.18036)
     | > grad_norm: 99.88116  (96.21849)
     | > current_lr: 0.00000 
     | > step_time: 7.67750  (5.25822)
     | > loader_time: 0.10150  (0.06705)



> DataLoader initialization
| > Tokenizer:
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: gruut
| > Number of instances : 131


> DataLoader initialization
| > Tokenizer:
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: gruut
| > Number of instances : 131
Traceback (most recent call last):
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1485, in fit
    self._fit()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1471, in _fit
    self.eval_epoch()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1335, in eval_epoch
    self.get_eval_dataloader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 800, in get_eval_dataloader
    return self._get_loader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 712, in _get_loader
    loader = model.module.get_data_loader(
  File "/mnt/nvmeDrives/pdav/TTS/TTS/tts/models/base_tts.py", line 298, in get_data_loader
    dist.barrier()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[W CUDAGuardImpl.h:113] Warning: CUDA warning: the launch timed out and was terminated (function destroyEvent)
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f9b741227d2 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2319e (0x7f9b7438f19e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x22d (0x7f9b74390d3d in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2ffc28 (0x7f9bc745dc28 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f9b7410b005 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #5: std::vector<at::Tensor, std::allocator<at::Tensor> >::~vector() + 0x4a (0x7f9bc746004a in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x57 (0x7f9b7577f017 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x9 (0x7f9b7577f159 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x7e1856 (0x7f9bc793f856 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x7e18aa (0x7f9bc793f8aa in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x1f51e0 (0x7f9bc73531e0 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x1f638e (0x7f9bc735438e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: python3() [0x5ec780]
frame #13: python3() [0x5441f8]
frame #14: python3() [0x54424a]
frame #15: python3() [0x54424a]
frame #16: python3() [0x54424a]
frame #17: python3() [0x54424a]
frame #18: python3() [0x54424a]
frame #19: python3() [0x54424a]
frame #20: python3() [0x5efcd5]
frame #21: python3() [0x5ef9df]
frame #22: python3() [0x6af707]
<omitting python frames>
frame #24: python3() [0x67d99e]
frame #29: __libc_start_main + 0xf3 (0x7f9bc93ac0b3 in /lib/x86_64-linux-gnu/libc.so.6)


   --> STEP: 100/102 -- GLOBAL_STEP: 100
     | > loss_spec: 35.91702  (35.74614)
     | > loss_dur: 0.96682  (0.95849)
     | > loss_aligner: 25.18945  (24.71722)
     | > loss_binary_alignment: 4.61545  (4.55870)
     | > loss: 66.68874  (65.98058)
     | > duration_error: 6.23546  (6.18066)
     | > grad_norm: 94.65023  (96.03946)
     | > current_lr: 0.00000 
     | > step_time: 1.59730  (4.36732)
     | > loader_time: 0.01660  (0.08051)



> DataLoader initialization
| > Tokenizer:
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: gruut
| > Number of instances : 131


> DataLoader initialization
| > Tokenizer:
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: gruut
| > Number of instances : 131
Traceback (most recent call last):
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1485, in fit
    self._fit()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1471, in _fit
    self.eval_epoch()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1335, in eval_epoch
    self.get_eval_dataloader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 800, in get_eval_dataloader
    return self._get_loader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 712, in _get_loader
    loader = model.module.get_data_loader(
  File "/mnt/nvmeDrives/pdav/TTS/TTS/tts/models/base_tts.py", line 298, in get_data_loader
    dist.barrier()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[W CUDAGuardImpl.h:113] Warning: CUDA warning: the launch timed out and was terminated (function destroyEvent)
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f7a15d237d2 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2319e (0x7f7a15f9019e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x22d (0x7f7a15f91d3d in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2ffc28 (0x7f7a6905ec28 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f7a15d0c005 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #5: std::vector<at::Tensor, std::allocator<at::Tensor> >::~vector() + 0x4a (0x7f7a6906104a in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x57 (0x7f7a17380017 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x9 (0x7f7a17380159 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x7e1856 (0x7f7a69540856 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x7e18aa (0x7f7a695408aa in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x1f51e0 (0x7f7a68f541e0 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x1f638e (0x7f7a68f5538e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: python3() [0x5ec780]
frame #13: python3() [0x5441f8]
frame #14: python3() [0x54424a]
frame #15: python3() [0x54424a]
frame #16: python3() [0x54424a]
frame #17: python3() [0x54424a]
frame #18: python3() [0x54424a]
frame #19: python3() [0x54424a]
frame #20: python3() [0x5efcd5]
frame #21: python3() [0x5ef9df]
frame #22: python3() [0x6af707]
<omitting python frames>
frame #24: python3() [0x67d99e]
frame #29: __libc_start_main + 0xf3 (0x7f7a6afad0b3 in /lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1485, in fit
    self._fit()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1471, in _fit
    self.eval_epoch()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1335, in eval_epoch
    self.get_eval_dataloader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 800, in get_eval_dataloader
    return self._get_loader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 712, in _get_loader
    loader = model.module.get_data_loader(
  File "/mnt/nvmeDrives/pdav/TTS/TTS/tts/models/base_tts.py", line 298, in get_data_loader
    dist.barrier()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[W CUDAGuardImpl.h:113] Warning: CUDA warning: the launch timed out and was terminated (function destroyEvent)
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fbee272b7d2 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2319e (0x7fbee299819e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x22d (0x7fbee2999d3d in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2ffc28 (0x7fbf35a66c28 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7fbee2714005 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #5: std::vector<at::Tensor, std::allocator<at::Tensor> >::~vector() + 0x4a (0x7fbf35a6904a in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x57 (0x7fbee3d88017 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x9 (0x7fbee3d88159 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x7e1856 (0x7fbf35f48856 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x7e18aa (0x7fbf35f488aa in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x1f51e0 (0x7fbf3595c1e0 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x1f638e (0x7fbf3595d38e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: python3() [0x5ec780]
frame #13: python3() [0x5441f8]
frame #14: python3() [0x54424a]
frame #15: python3() [0x54424a]
frame #16: python3() [0x54424a]
frame #17: python3() [0x54424a]
frame #18: python3() [0x54424a]
frame #19: python3() [0x54424a]
frame #20: python3() [0x5efcd5]
frame #21: python3() [0x5ef9df]
frame #22: python3() [0x6af707]
<omitting python frames>
frame #24: python3() [0x67d99e]
frame #29: __libc_start_main + 0xf3 (0x7fbf379b50b3 in /lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1485, in fit
    self._fit()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1471, in _fit
    self.eval_epoch()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 1335, in eval_epoch
    self.get_eval_dataloader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 800, in get_eval_dataloader
    return self._get_loader(
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/trainer/trainer.py", line 712, in _get_loader
    loader = model.module.get_data_loader(
  File "/mnt/nvmeDrives/pdav/TTS/TTS/tts/models/base_tts.py", line 298, in get_data_loader
    dist.barrier()
  File "/mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[W CUDAGuardImpl.h:113] Warning: CUDA warning: the launch timed out and was terminated (function destroyEvent)
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f3527cba7d2 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2319e (0x7f3527f2719e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x22d (0x7f3527f28d3d in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2ffc28 (0x7f357aff5c28 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f3527ca3005 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #5: std::vector<at::Tensor, std::allocator<at::Tensor> >::~vector() + 0x4a (0x7f357aff804a in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x57 (0x7f3529317017 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x9 (0x7f3529317159 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x7e1856 (0x7f357b4d7856 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x7e18aa (0x7f357b4d78aa in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x1f51e0 (0x7f357aeeb1e0 in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x1f638e (0x7f357aeec38e in /mnt/nvmeDrives/pdav/TTS/venv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: python3() [0x5ec780]
frame #13: python3() [0x5441f8]
frame #14: python3() [0x54424a]
frame #15: python3() [0x54424a]
frame #16: python3() [0x54424a]
frame #17: python3() [0x54424a]
frame #18: python3() [0x54424a]
frame #19: python3() [0x54424a]
frame #20: python3() [0x5efcd5]
frame #21: python3() [0x5ef9df]
frame #22: python3() [0x6af707]
<omitting python frames>
frame #24: python3() [0x67d99e]
frame #29: __libc_start_main + 0xf3 (0x7f357cf440b3 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by erogol** [comment]
The problem is that your VRAM is not big enough to train the model.

Apart from that you need to update the trainer by ```pip install -U trainer``` which might be a remedy

**Comment by pdavlin** [comment]
I knew I was having problems locally with a 10GB setup but had assumed (erroneously) that running it with pytorch on a 4x12GB VRAM server would be adequate. Is that incorrect?

**Comment by erogol** [comment]
Not sure. It depends on the longest audio in your dataset and the batch size. 

But first update the trainer.

**Comment by pdavlin** [comment]
I upgraded to version `0.0.8` of the trainer and I'm getting the same error.

**Comment by pdavlin** [comment]
Solved this by applying more VRAM to the problem.
