### ISSUE TITLE
Multi-Speaker TTS[Bug] 

### ISSUE THREAD

**Issue by fra1993** [coqui-ai/TTS#1528]
### Describe the bug

Hi, I tried to run the command

`tts  --model_name "<language>/<dataset>/<model_name>" --list_speaker_idxs`

with different models and I always got an error.

### To Reproduce

Run following command (this happens also for other models)

tts  --model_name "tts_models/en/ek1/tacotron2" --list_speaker_idxs

### Logs

```shell
`Traceback (most recent call last):

  File "/usr/local/bin/tts", line 33, in <module>

    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())

  File "/TTS/TTS/bin/synthesize.py", line 281, in main

    print(synthesizer.tts_model.speaker_manager.ids)

AttributeError: 'NoneType' object has no attribute 'ids`
```

### Environment

```shell
"CUDA": {

        "GPU": [],

        "available": false,

        "version": "10.2"

    },

    "Packages": {

        "PyTorch_debug": false,

        "PyTorch_version": "1.10.1+cu102",

        "TTS": "0.6.2",

        "numpy": "1.19.5"

    },

    "System": {

        "OS": "Linux",

        "architecture": [

            "64bit",

            "ELF"


        "processor": "x86_64",

        "python": "3.6.9",

        "version": "#45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022"
```

**Comment by blackmamba1122** [comment]
Maybe dataset is not for multispeaker, you can try vctk dataset

**Comment by erogol** [comment]
You need a multispeaker model.
