### ISSUE TITLE
[Bug] Installation fails on "setup.py" with "requirements.txt not found"

### ISSUE THREAD

**Issue by mpPie** [coqui-ai/TTS#1543]
### Describe the bug

I'm using a raspberry pi and venv.

My procedure
```
sudo apt install -y python3-dev libatlas-base-dev
python3.7 -m venv ./venv
source ./venv/bin/activate
pip install TTS
```

### To Reproduce

EVERYTHING I did on my raspberry pi 4, from a fresh install of a headless raspberry pi OS 32bit

sudo apt update
sudo apt -y upgrade
sudo apt -y install tmux curl virtualenv
tmux new -s main

sudo apt -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev libbz2-dev
wget https://www.python.org/ftp/python/3.7.13/Python-3.7.13.tgz
tar -xf Python-3.7.13.tgz
cd Python-3.7.13
./configure --enable-optimizations
make -j$(nproc)
sudo make altinstall

sudo apt install -y python3-dev libatlas-base-dev
cd ~
python3.7 -m venv ./venv
source ./venv/bin/activate
pip install TTS

### Logs

```shell
(venv) pie@raspberrypi:~ $ pip install TTS
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting TTS
  Using cached TTS-0.6.2.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy>=1.4.0
  Downloading https://www.piwheels.org/simple/scipy/scipy-1.7.3-cp37-cp37m-linux_armv7l.whl (65.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 MB 1.3 MB/s eta 0:00:00
Collecting TTS
  Downloading https://www.piwheels.org/simple/tts/TTS-0.6.1-cp37-cp37m-linux_armv7l.whl (569 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.0/570.0 KB 2.5 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.6.0-cp37-cp37m-linux_armv7l.whl (569 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.0/570.0 KB 3.5 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.5.0-cp37-cp37m-linux_armv7l.whl (588 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.5/588.5 KB 3.7 MB/s eta 0:00:00
Collecting unidic-lite==1.0.8
  Downloading https://www.piwheels.org/simple/unidic-lite/unidic_lite-1.0.8-py3-none-any.whl (47.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 1.6 MB/s eta 0:00:00
Collecting TTS
  Downloading https://www.piwheels.org/simple/tts/TTS-0.4.2-cp37-cp37m-linux_armv7l.whl (573 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 573.0/573.0 KB 2.4 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.4.1-cp37-cp37m-linux_armv7l.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.6/570.6 KB 3.9 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.4.0-cp37-cp37m-linux_armv7l.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.6/570.6 KB 4.0 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.3.1-cp37-cp37m-linux_armv7l.whl (561 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.3/561.3 KB 3.9 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.3.0-cp37-cp37m-linux_armv7l.whl (560 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 560.6/560.6 KB 3.9 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.2.2-cp37-cp37m-linux_armv7l.whl (561 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.5/561.5 KB 3.2 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.2.1-cp37-cp37m-linux_armv7l.whl (547 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 KB 4.3 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.2.0-cp37-cp37m-linux_armv7l.whl (548 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.0/549.0 KB 3.9 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.1.3-cp37-cp37m-linux_armv7l.whl (528 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.9/528.9 KB 4.1 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.1.2-cp37-cp37m-linux_armv7l.whl (520 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 520.6/520.6 KB 4.1 MB/s eta 0:00:00
  Downloading https://www.piwheels.org/simple/tts/TTS-0.1.1-cp37-cp37m-linux_armv7l.whl (520 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 520.7/520.7 KB 4.0 MB/s eta 0:00:00
  Downloading TTS-0.1.0.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 4.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      setup.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(sys.version) < LooseVersion("3.6") or LooseVersion(sys.version) > LooseVersion("3.10"):
      Traceback (most recent call last):
        File "/home/pie/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/pie/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/pie/venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-cfns_38k/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 178, in get_requires_for_build_wheel
          config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-cfns_38k/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cfns_38k/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 282, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-cfns_38k/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 43, in <module>
          requirements = open(os.path.join(cwd, "requirements.txt"), "r").readlines()
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-gnhuci6x/tts_67289fb591094c9e9bbb6926b66a1f84/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) pie@raspberrypi:~
```

### Environment

```shell
-raspberry pi 4
-raspberry OS headless 32bit
-python3.7 (venv)
```

**Comment by yezzerfv** [comment]
I'm also getting this error on the same hardware

**Comment by erogol** [comment]
pip tries to install a very old version of 🐸TTS. Maybe forcing it to TTS==0.6.0 might work?

**Comment by mpPie** [comment]
> pip tries to install a very old version of 🐸TTS. Maybe forcing it to TTS==0.6.0 might work?

This was it. Thank you!
I still have problems finishing the installation, but that is because I'm having some trouble installing torch.

I think this can be closed.
