### ISSUE TITLE
[Bug] VC with the CLI breaks

### ISSUE THREAD

**Issue by WeberJulian** [coqui-ai/TTS#1568]
### Describe the bug

```
Traceback (most recent call last):
  File "/home/julian/miniconda3/envs/TTS/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/home/julian/workspace/TTS/TTS/bin/synthesize.py", line 305, in main
    wav = synthesizer.tts(
  File "/home/julian/workspace/TTS/TTS/utils/synthesizer.py", line 337, in tts
    outputs = transfer_voice(
  File "/home/julian/workspace/TTS/TTS/tts/utils/synthesis.py", line 273, in transfer_voice
    model_outputs = _func(reference_wav, speaker_id, d_vector, reference_speaker_id, reference_d_vector)
  File "/home/julian/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/julian/workspace/TTS/TTS/tts/models/vits.py", line 1089, in inference_voice_conversion
    wav, _, _ = self.voice_conversion(y, y_lengths, speaker_cond_src, speaker_cond_tgt)
  File "/home/julian/workspace/TTS/TTS/tts/models/vits.py", line 1109, in voice_conversion
    g_src = F.normalize(speaker_cond_src).unsqueeze(-1)
  File "/home/julian/miniconda3/envs/TTS/lib/python3.8/site-packages/torch/nn/functional.py", line 4637, in normalize
    denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
AttributeError: 'NoneType' object has no attribute 'norm'
```

### To Reproduce

`tts --model_name "tts_models/multilingual/multi-dataset/your_tts"  --reference_wav ~/Downloads/input_tebboune.wav --speaker_wav ~/Downloads/macron_1_extrait.wav --language_idx "fr-fr"`

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0",
        "TTS": "0.6.2",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022"
    }
}
```

**Comment by WeberJulian** [comment]
Thanks @Edresson for fixing this

**Comment by DillFrescott** [comment]
How was this fixed?

**Comment by DillFrescott** [comment]
its still happening for me
