### ISSUE TITLE
[Bug] Running TTS commands crashes on pyworld import

### ISSUE THREAD

**Issue by JustAHippo** [coqui-ai/TTS#1576]
### Describe the bug

Coqui crashes on pyworld import when running any command.

### To Reproduce

Install Coqui with Python install instructions(not via online pip package), 

### Expected behavior

Commands would run as usual

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\Scripts\tts-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 76, in load
    module = import_module(match.group('module'))
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\coqui\tts\TTS\bin\synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "d:\coqui\tts\TTS\utils\synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "d:\coqui\tts\TTS\utils\audio.py", line 5, in <module>
    import pyworld as pw
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\lib\site-packages\pyworld\__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld\pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu113",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 167 Stepping 1, GenuineIntel",
        "python": "3.8.1",
        "version": "10.0.22000"
    }
}
```

### Additional context

Will restart computer, could possibly be under unstable circumstances. Will comment on issue and close if changes happen.

**Comment by elhamadjidi** [comment]
> 

Could you solve your problem? I am trying to run TTS on UBUNTU but it crashes downloading the requirments.

**Comment by JustAHippo** [comment]
using a venv for some reason fixed it

**Comment by elhamadjidi** [comment]
> using a venv for some reason fixed it

which python version?

**Comment by JustAHippo** [comment]
3.8.1, same VENV version. Really odd.

**Comment by erogol** [comment]
In general it happens when you change the numpy version after you install 🐸TTS since Pyworld is compiled with a different numpy version.

**Comment by elhamadjidi** [comment]
> In general it happens when you change the numpy version after you install 🐸TTS since Pyworld is compiled with a different numpy version.

Thank you!
