### ISSUE TITLE
ljspeech fast_speech recipe for en_US Fails With assert len(out_dict["token_ids"]) > 0

### ISSUE THREAD

**Issue by iprovalo** [coqui-ai/TTS#1624]
### Describe the bug

I am training fast_speech on the ljspeech en_US set using this [recipe](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/fast_speech/train_fast_speech.py) (on dev branch).

The ljspeech is merged into a single set by using these commands as described [here](https://www.caito.de/2019/01/03/the-m-ailabs-speech-dataset/):

```
cat ../by_book/*/*/*/metadata.csv >> metadata.csv
mkdir wavs
cp ../by_book/*/*/*/wavs/* wavs/
```

I am getting this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1492, in fit
    self._fit()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1476, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1254, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 180, in __getitem__
    return self.load_data(idx)
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 230, in load_data
    token_ids = self.get_token_ids(idx, item["text"])
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 213, in get_token_ids
    token_ids = self.get_phonemes(idx, text)["token_ids"]
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 198, in get_phonemes
    assert len(out_dict["token_ids"]) > 0
AssertionError
```

### To Reproduce

Get the data:
```
cd /data/
wget https://data.solak.de/data/Training/stt_tts/en_US.tgz
tar zxf en_US.tgz
rm en_US.tgz
cd en_US/
mkdir ljspeech
cd ljspeech/
cat ../by_book/*/*/*/metadata.csv >> metadata.csv
mkdir wavs
cp ../by_book/*/*/*/wavs/* wavs/
```
(if the `cp` `throws too many arguments`, then just run it by speaker and by book if necessary: `cp ../by_book/female/*/*/wavs/* wavs/`)

Then check if the files exist with python script:

```
import os
with open('metadata.csv') as f:
    for line in f:
        file_name = line.split('|')[0]
        file_exists = os.path.exists('wavs/'+file_name+'.wav')
        if not file_exists:
            print(file_name)
```

Manually remove non-existing files from the `metadata.csv` (there are three missing files at this time).  

Point [train_fast_speech.py](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/fast_speech/train_fast_speech.py#L20) to the data:
`path="/data/en_US/ljspeech/"`

Change the [sample rate](https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/fast_speech/train_fast_speech.py#L24):
`sample_rate=16000`

Run the code:
```
cd TTS
export CUDA_VISIBLE_DEVICES=4
python3 recipes/ljspeech/fast_speech/train_fast_speech.py
```

After `Pre-computing phonemes` completes, it fails to train: `[1m   --> STEP: 0/1433 -- GLOBAL_STEP: 0`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1492, in fit
    self._fit()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1476, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1254, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 180, in __getitem__
    return self.load_data(idx)
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 230, in load_data
    token_ids = self.get_token_ids(idx, item["text"])
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 213, in get_token_ids
    token_ids = self.get_phonemes(idx, text)["token_ids"]
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 198, in get_phonemes
    assert len(out_dict["token_ids"]) > 0
AssertionError
```

### Expected behavior

No exception.

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1492, in fit
    self._fit()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1476, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1254, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 180, in __getitem__
    return self.load_data(idx)
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 230, in load_data
    token_ids = self.get_token_ids(idx, item["text"])
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 213, in get_token_ids
    token_ids = self.get_phonemes(idx, text)["token_ids"]
  File "/apps/tts/TTS/TTS/tts/datasets/dataset.py", line 198, in get_phonemes
    assert len(out_dict["token_ids"]) > 0
AssertionError
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA A100-SXM4-40GB"
        ],
        "available": true,
        "version": "11.5"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cu115",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.7.13",
        "version": "#61~18.04.3-Ubuntu SMP Fri Oct 1 14:04:01 UTC 2021"
    }
}
```

**Comment by p0p4k** [comment]
Check if the phonemes cache folder actually exists first.
Then in the dataset.py file, you can try to debug by printing out the "ids" the __getitem__ method or the compute_or_load method of PhonemeDataset class. Report if the ids are printed or not. You can make the debug quicker by using a temp_metadata.txt file with just a few wav|text lines (~5-10 lines). Try it and report back, good luck.

**Comment by iprovalo** [comment]
@p0p4k thank you for the pointer!

I added this code:

```
     if len(ids) == 0:
          print("Item must be removed from metadata.csv " + str(item) + " => " + str(ids))
```

to the `__getitem__ ` right after 

```
     ids = self.compute_or_load(item["audio_file"], item["text"])
```

per your suggestion and found the item causing the issue (after the tokenization step, it was just whitespaces).  After removing it manually from `metadata.csv`, it is working again.

**Comment by p0p4k** [comment]
Great! Just mark my comment as the answer, so that we can close this issue.  Good luck for your model results 😉

**Comment by iprovalo** [comment]
@p0p4k Thank you!  This is opened as a bug, it doesn't have the 'Mark as answer' as far as I can see. 

I am curious, would it be better to fix this by skipping these bad items in the dataset `__getitem__ ` or at least add the `print` in the codebase so that it tells the next person which item to remove manually (this will happen on the `ljspeech` `en_US` to anyone using the `dataset.py`):

```
  if len(ids) == 0:
          print("Item must be removed from metadata.csv " + str(item) + " => " + str(ids))
          return #should this be added so that an item is skipped?
```

**Comment by iprovalo** [comment]
@erogol I would not consider this as a resolved.  Anyone running into this `ljspeech` dataset issue would have to modify the source code in order to get around it.  There is a related issue, when a file is listed in the `metadata.csv` but is not present on the disk (I found three such files).  In both of these cases it takes a long time to run the code before it crashes.  Error handling would be a more preferable way to fix this.

**Comment by BrukArkady** [comment]
> @p0p4k thank you for the pointer!
> 
> I added this code:
> 
> ```
>      if len(ids) == 0:
>           print("Item must be removed from metadata.csv " + str(item) + " => " + str(ids))
> ```
> 
> to the `__getitem__ ` right after
> 
> ```
>      ids = self.compute_or_load(item["audio_file"], item["text"])
> ```
> 
> per your suggestion and found the item causing the issue (after the tokenization step, it was just whitespaces). After removing it manually from `metadata.csv`, it is working again.

Hi @iprovalo !
I have faced with the same problem.
But after adding the above, I can't see print() results in training log.
Should I run it some other way, not CUDA_VISIBLE_DEVICES="0" python3 train_tacotron_ddc.py ?

**Comment by blackmamba1122** [comment]
> > @p0p4k thank you for the pointer!
> > I added this code:
> > ```
> >      if len(ids) == 0:
> >           print("Item must be removed from metadata.csv " + str(item) + " => " + str(ids))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the `__getitem__ ` right after
> > ```
> >      ids = self.compute_or_load(item["audio_file"], item["text"])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > per your suggestion and found the item causing the issue (after the tokenization step, it was just whitespaces). After removing it manually from `metadata.csv`, it is working again.
> 
> Hi @iprovalo ! I have faced with the same problem. But after adding the above, I can't see print() results in training log. Should I run it some other way, not CUDA_VISIBLE_DEVICES="0" python3 train_tacotron_ddc.py ?

Did you solve it? I got same error

**Comment by iprovalo** [comment]
Here is my fork with [two lines](https://github.com/iprovalo/TTS/blob/dev/TTS/tts/datasets/dataset.py#L564-L565) I added.  This printed the misbehaving file name.  I manually removed it from the metadata.csv in order to make this work.
