### ISSUE TITLE
"tts" command cannot be initialized (ImportError: numpy.core.multiarray failed to import)

### ISSUE THREAD

**Issue by Baquara** [coqui-ai/TTS#1626]
### Describe the bug

Hello,

I installed numpy version 1.21.6 (required by this package) but I'm getting numpy errors when entering "tts". All my other packages are up to date.

### To Reproduce

$ tts

### Expected behavior

Initialize TTS environment

### Logs

```shell
/usr/lib/python3.10/site-packages/torch/_masked/__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  /build/python-pytorch/src/pytorch-1.11.0-cuda/torch/csrc/utils/tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/usr/bin/tts", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/privateserver/TTS/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/privateserver/TTS/TTS/utils/synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/privateserver/TTS/TTS/utils/audio.py", line 3, in <module>
    import librosa
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/util/utils.py", line 6, in <module>
    import scipy.ndimage
  File "/usr/lib/python3.10/site-packages/scipy/ndimage/__init__.py", line 151, in <module>
    from ._filters import *  # noqa: F401 F403
  File "/usr/lib/python3.10/site-packages/scipy/ndimage/_filters.py", line 37, in <module>
    from . import _nd_image
ImportError: numpy.core.multiarray failed to import
```

### Environment

```shell
/usr/lib/python3.10/site-packages/torch/_masked/__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  /build/python-pytorch/src/pytorch-1.11.0-cuda/torch/csrc/utils/tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060"
        ],
        "available": true,
        "version": "11.6"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.10.4",
        "version": "#1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000"
    }
}
```

**Comment by p0p4k** [comment]
Hello, try this `pip install -U numpy`  , re-run tts and report back. Thanks.

**Comment by Baquara** [comment]
> Hello, try this `pip install -U numpy` , re-run tts and report back. Thanks. Other few solutions/discussions you can check out are : [pytorch/pytorch#2731](https://github.com/pytorch/pytorch/issues/2731) https://stackoverflow.com/questions/34051737/numpy-core-multiarray-failed-to-import

This happened:

> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 573, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 891, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 782, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (numpy 1.22.4 (/usr/lib/python3.10/site-packages), Requirement.parse('numpy==1.21.6'), {'TTS'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/tts", line 33, in <module>
>     sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
>   File "/usr/bin/tts", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/privateserver/TTS/TTS/bin/synthesize.py", line 12, in <module>
>     from TTS.utils.synthesizer import Synthesizer
>   File "/home/privateserver/TTS/TTS/utils/synthesizer.py", line 14, in <module>
>     from TTS.utils.audio import AudioProcessor
>   File "/home/privateserver/TTS/TTS/utils/audio.py", line 3, in <module>
>     import librosa
>   File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
>     from . import core
>   File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
>     from .convert import *  # pylint: disable=wildcard-import
>   File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
>     from . import notation
>   File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
>     from ..util.exceptions import ParameterError
>   File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/util/__init__.py", line 83, in <module>
>     from .utils import *  # pylint: disable=wildcard-import
>   File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/util/utils.py", line 10, in <module>
>     import numba
>   File "/usr/lib/python3.10/site-packages/numba/__init__.py", line 19, in <module>
>     from numba.core import config
>   File "/usr/lib/python3.10/site-packages/numba/core/config.py", line 15, in <module>
>     import llvmlite.binding as ll
>   File "/usr/lib/python3.10/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
>     from .dylib import *
>   File "/usr/lib/python3.10/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
>     from llvmlite.binding import ffi
>   File "/usr/lib/python3.10/site-packages/llvmlite/binding/ffi.py", line 175, in <module>
>     from pkg_resources import resource_filename
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3317, in <module>
>     def _initialize_master_working_set():
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3291, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3329, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 575, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'numpy==1.21.6' distribution was not found and is required by TTS
>

**Comment by p0p4k** [comment]
Now you have 2 options, 
1) edit requirements.txt file and remove the "==xx.xx" version in front of numpy and then retry tts.
OR
2) uninstall numpy completely first (using pip/conda), retry installing original requirements.txt OR
My conda environment for 🐸 TTS has numpy 1.21.6, so i am wondering if is it really numpy the issue or any other dependency.. Anyway, try and report back.

**Comment by Baquara** [comment]
> Now you have 2 options,
> 
>     1. edit requirements.txt file and remove the "==xx.xx" version in front of numpy and then retry tts.
>        OR
> 
>     2. uninstall numpy completely first (using pip/conda), retry installing original requirements.txt OR
>        My conda environment for frog TTS has numpy 1.21.6, so i am wondering if is it really numpy the issue or any other dependency.. Anyway, try and report back.

Hello,

I am now having the following problem:
```

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.22.4 (/usr/lib/python3.10/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/usr/bin/tts", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/privateserver/TTS/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/privateserver/TTS/TTS/utils/synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/privateserver/TTS/TTS/utils/audio.py", line 3, in <module>
    import librosa
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/privateserver/.local/lib/python3.10/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/usr/lib/python3.10/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/usr/lib/python3.10/site-packages/numba/core/config.py", line 15, in <module>
    import llvmlite.binding as ll
  File "/usr/lib/python3.10/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/usr/lib/python3.10/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/usr/lib/python3.10/site-packages/llvmlite/binding/ffi.py", line 175, in <module>
    from pkg_resources import resource_filename
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.22.4 (/usr/lib/python3.10/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'})

```

**Comment by p0p4k** [comment]
Hello, these kind of errors will keep repeating since open-source packages are dependent on each other. It is not a big bug, rather you need to keep track of what is installed in your existing environment. Earlier, in your system, numpy was installed but version was too high, now numba is asking you to fallback to specific numpy version (less than v1.22, but yours is v1..22.4) and so on..

- So, if you learn to read and understand the error messages, you can clearly see that first, uninstalling the current numpy (v1.22.4) in your environment and then second, installing something less than v1.22 (for numba to work correctly) will fix the issue.  😃 

`pkg_resources.ContextualVersionConflict: (numpy 1.22.4 (/usr/lib/python3.10/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'})`

- Either try the above step or just [create a new conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands), activate it, download/clone the latest [🐸 TTSv0.7.0](https://github.com/coqui-ai/TTS) and re-install TTS in this new environment.

Hopefully, this fixes your bugs. If not, please comment again. Good luck! 👍

**Comment by p0p4k** [comment]
One more note, I tried fresh install in a new python 3.10 environment and faced similar error. 
I fixed the error using ->
`pip install numba -U `
You can give it a try too and report back. Thanks.

**Comment by erogol** [comment]
Reinstalling TTS fixes this

**Comment by Baquara** [comment]
@erogol This issue was -not- fixed on my end. I tried a fresh install and the same error happened. Tried to reinstall numba, and got the same error.
