### ISSUE TITLE
[Bug] importlib.metadata.PackageNotFoundError: TTS

### ISSUE THREAD

**Issue by chrisbward** [coqui-ai/TTS#1631]
### Describe the bug

```bash
➜  tts git:(dev) sudo make install
[sudo] password for user: 
pip install -e .[all]
Obtaining file:///home/user/Projects/04_MachineLearning/tts
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numba==0.55.1 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.55.1)
Requirement already satisfied: pypinyin in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.46.0)
Requirement already satisfied: umap-learn==0.5.1 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.5.1)
Requirement already satisfied: librosa==0.8.0 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.8.0)
Requirement already satisfied: inflect in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (5.6.0)
Requirement already satisfied: mecab-python3==1.0.5 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.0.5)
Requirement already satisfied: coqpit>=0.0.16 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.0.16)
Requirement already satisfied: torch>=1.7 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.11.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (4.64.0)
Requirement already satisfied: unidic-lite==1.0.8 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.0.8)
Requirement already satisfied: cython==0.29.28 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.29.28)
Requirement already satisfied: trainer in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.0.12)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from TTS==0.6.2) (5.3.1)
Requirement already satisfied: pyworld==0.2.10 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.2.10)
Requirement already satisfied: jieba in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.42.1)
Requirement already satisfied: scipy>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.8.1)
Requirement already satisfied: fsspec>=2021.04.0 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (2022.5.0)
Requirement already satisfied: numpy==1.21.6 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.21.6)
Requirement already satisfied: gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3 in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (2.2.3)
Requirement already satisfied: anyascii in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.3.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (3.5.2)
Requirement already satisfied: pysbd in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.3.4)
Requirement already satisfied: soundfile in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.10.3.post1)
Requirement already satisfied: flask in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (2.1.2)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.11.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.4.2)
Requirement already satisfied: pylint==2.10.2; extra == "all" in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (2.10.2)
Requirement already satisfied: black; extra == "all" in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (22.3.0)
Requirement already satisfied: isort; extra == "all" in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (5.10.1)
Requirement already satisfied: bokeh==1.4.0; extra == "all" in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (1.4.0)
Requirement already satisfied: coverage; extra == "all" in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (6.4.1)
Requirement already satisfied: nose2; extra == "all" in /usr/local/lib/python3.8/dist-packages (from TTS==0.6.2) (0.11.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba==0.55.1->TTS==0.6.2) (45.2.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /usr/local/lib/python3.8/dist-packages (from numba==0.55.1->TTS==0.6.2) (0.38.1)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.8/dist-packages (from umap-learn==0.5.1->TTS==0.6.2) (1.1.1)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.8/dist-packages (from umap-learn==0.5.1->TTS==0.6.2) (0.5.7)
Requirement already satisfied: resampy>=0.2.2 in /usr/local/lib/python3.8/dist-packages (from librosa==0.8.0->TTS==0.6.2) (0.2.2)
Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.8/dist-packages (from librosa==0.8.0->TTS==0.6.2) (1.6.0)
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from librosa==0.8.0->TTS==0.6.2) (5.1.1)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.8/dist-packages (from librosa==0.8.0->TTS==0.6.2) (1.1.0)
Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from librosa==0.8.0->TTS==0.6.2) (2.1.9)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch>=1.7->TTS==0.6.2) (4.2.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from trainer->TTS==0.6.2) (3.19.4)
Requirement already satisfied: tensorboardX in /usr/local/lib/python3.8/dist-packages (from trainer->TTS==0.6.2) (2.5.1)
Requirement already satisfied: gruut-ipa<1.0,>=0.12.0 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (0.13.0)
Requirement already satisfied: Babel<3.0.0,>=2.8.0 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.10.1)
Requirement already satisfied: python-crfsuite~=0.9.7 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (0.9.8)
Requirement already satisfied: networkx<3.0.0,>=2.5.0 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.8.3)
Requirement already satisfied: jsonlines~=1.2.0 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (1.2.0)
Requirement already satisfied: gruut-lang-en~=2.0.0 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: dateparser~=1.1.0 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (1.1.1)
Requirement already satisfied: num2words<1.0.0,>=0.5.10 in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (0.5.10)
Requirement already satisfied: importlib-resources; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (5.7.1)
Requirement already satisfied: gruut-lang-cs~=2.0.0; extra == "cs" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: gruut-lang-de~=2.0.0; extra == "de" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: gruut-lang-es~=2.0.0; extra == "es" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: gruut-lang-fr~=2.0.0; extra == "fr" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.2)
Requirement already satisfied: gruut-lang-it~=2.0.0; extra == "it" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: gruut-lang-nl~=2.0.0; extra == "nl" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.2)
Requirement already satisfied: gruut-lang-pt~=2.0.0; extra == "pt" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: gruut-lang-ru~=2.0.0; extra == "ru" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: gruut-lang-sv~=2.0.0; extra == "sv" in /usr/local/lib/python3.8/dist-packages (from gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2.0.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib->TTS==0.6.2) (2.7.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->TTS==0.6.2) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->TTS==0.6.2) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->TTS==0.6.2) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib->TTS==0.6.2) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib->TTS==0.6.2) (4.33.3)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib->TTS==0.6.2) (7.0.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.8/dist-packages (from soundfile->TTS==0.6.2) (1.15.0)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.8/dist-packages (from flask->TTS==0.6.2) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.8/dist-packages (from flask->TTS==0.6.2) (2.1.2)
Requirement already satisfied: Werkzeug>=2.0 in /usr/local/lib/python3.8/dist-packages (from flask->TTS==0.6.2) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.8/dist-packages (from flask->TTS==0.6.2) (8.1.3)
Requirement already satisfied: importlib-metadata>=3.6.0; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from flask->TTS==0.6.2) (4.11.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas->TTS==0.6.2) (2022.1)
Requirement already satisfied: mccabe<0.7,>=0.6 in /usr/local/lib/python3.8/dist-packages (from pylint==2.10.2; extra == "all"->TTS==0.6.2) (0.6.1)
Requirement already satisfied: toml>=0.7.1 in /usr/local/lib/python3.8/dist-packages (from pylint==2.10.2; extra == "all"->TTS==0.6.2) (0.10.2)
Requirement already satisfied: platformdirs>=2.2.0 in /usr/local/lib/python3.8/dist-packages (from pylint==2.10.2; extra == "all"->TTS==0.6.2) (2.5.2)
Requirement already satisfied: astroid<2.8,>=2.7.2 in /usr/local/lib/python3.8/dist-packages (from pylint==2.10.2; extra == "all"->TTS==0.6.2) (2.7.3)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.8/dist-packages (from black; extra == "all"->TTS==0.6.2) (0.4.3)
Requirement already satisfied: tomli>=1.1.0; python_version < "3.11" in /usr/local/lib/python3.8/dist-packages (from black; extra == "all"->TTS==0.6.2) (2.0.1)
Requirement already satisfied: pathspec>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from black; extra == "all"->TTS==0.6.2) (0.9.0)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from bokeh==1.4.0; extra == "all"->TTS==0.6.2) (1.14.0)
Requirement already satisfied: tornado>=4.3 in /usr/local/lib/python3.8/dist-packages (from bokeh==1.4.0; extra == "all"->TTS==0.6.2) (6.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.22->umap-learn==0.5.1->TTS==0.6.2) (3.1.0)
Requirement already satisfied: requests>=2.19.0 in /usr/lib/python3/dist-packages (from pooch>=1.0->librosa==0.8.0->TTS==0.6.2) (2.22.0)
Requirement already satisfied: appdirs>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from pooch>=1.0->librosa==0.8.0->TTS==0.6.2) (1.4.4)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.8/dist-packages (from dateparser~=1.1.0->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (4.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,<2022.3.15 in /usr/local/lib/python3.8/dist-packages (from dateparser~=1.1.0->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2022.3.2)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python3.8/dist-packages (from num2words<1.0.0,>=0.5.10->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (0.6.2)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from importlib-resources; python_version < "3.9"->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (3.8.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.0->soundfile->TTS==0.6.2) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2>=3.0->flask->TTS==0.6.2) (2.1.1)
Requirement already satisfied: wrapt<1.13,>=1.11 in /usr/local/lib/python3.8/dist-packages (from astroid<2.8,>=2.7.2->pylint==2.10.2; extra == "all"->TTS==0.6.2) (1.12.1)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from astroid<2.8,>=2.7.2->pylint==2.10.2; extra == "all"->TTS==0.6.2) (1.7.1)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.8/dist-packages (from tzlocal->dateparser~=1.1.0->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (0.1.0.post0)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from tzlocal->dateparser~=1.1.0->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (0.2.1)
Requirement already satisfied: tzdata; python_version >= "3.6" in /usr/local/lib/python3.8/dist-packages (from pytz-deprecation-shim->tzlocal->dateparser~=1.1.0->gruut[cs,de,es,fr,it,nl,pt,ru,sv]==2.2.3->TTS==0.6.2) (2022.1)
Installing collected packages: TTS
  Running setup.py develop for TTS
Successfully installed TTS
➜  tts git:(dev) tts "hello world"
Traceback (most recent call last):
  File "/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/bin/tts", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: TTS
```

### To Reproduce

Follow install instructions for Ubuntu (20.04) as per README

### Expected behavior

TTS to run normally

### Environment

```shell
3090 ti, brand new system
```

**Comment by p0p4k** [comment]
type `pip list` and copy paste the output.

**Comment by erogol** [comment]
I close this. If the issue persists reopen t
