### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'norm'[Bug] 

### ISSUE THREAD

**Issue by DillFrescott** [coqui-ai/TTS#1649]
### Describe the bug

AttributeError: 'NoneType' object has no attribute 'norm'

### To Reproduce

Run a voice conversion on cli

### Expected behavior

I expect it to convert the voice :(

### Logs

```shell
C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\autocast_mode.py:162: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\functional.py:695: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:798.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "C:\Users\micro\anaconda3\envs\tts\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\micro\anaconda3\envs\tts\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\anaconda3\envs\tts\Scripts\tts.exe\__main__.py", line 7, in <module>
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\TTS\bin\synthesize.py", line 305, in main
    wav = synthesizer.tts(
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\TTS\utils\synthesizer.py", line 336, in tts
    outputs = transfer_voice(
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\TTS\tts\utils\synthesis.py", line 273, in transfer_voice
    model_outputs = _func(reference_wav, speaker_id, d_vector, reference_speaker_id, reference_d_vector)
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\TTS\tts\models\vits.py", line 1022, in inference_voice_conversion
    wav, _, _ = self.voice_conversion(y, y_lengths, speaker_cond_src, speaker_cond_tgt)
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\TTS\tts\models\vits.py", line 1042, in voice_conversion
    g_src = F.normalize(speaker_cond_src).unsqueeze(-1)
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\nn\functional.py", line 4637, in normalize
    denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
AttributeError: 'NoneType' object has no attribute 'norm'
```

### Environment

```shell
(tts) C:\Users\micro\Downloads>python collect_env_info.py
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cpu",
        "TTS": "0.6.2",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD",
        "python": "3.9.12",
        "version": "10.0.22000"
    }
}
```

**Comment by DillFrescott** [comment]
It was fixed in a recent pr
