### ISSUE TITLE
[Bug] Cannot use vocoders with yourtts

### ISSUE THREAD

**Issue by DillFrescott** [coqui-ai/TTS#1650]
### Describe the bug

Can't use any vocoder except default one with yourtts?

### To Reproduce

Run yourtts with a reference speaker and try to use a custom vocoder.

### Expected behavior

I would expect it to use the vocoder without throwing a random error depending on which vocoder is being requested.

### Logs

```shell
C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\functional.py:695: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:798.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "C:\Users\micro\anaconda3\envs\tts\Scripts\tts-script.py", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "c:\users\micro\downloads\tts\TTS\bin\synthesize.py", line 309, in main
    wav = synthesizer.tts(
  File "c:\users\micro\downloads\tts\TTS\utils\synthesizer.py", line 370, in tts
    waveform = self.vocoder_model.inference(vocoder_input.to(device_type))
  File "c:\users\micro\downloads\tts\TTS\vocoder\models\gan.py", line 66, in inference
    return self.model_g.inference(x)
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\micro\downloads\tts\TTS\vocoder\models\hifigan_generator.py", line 280, in inference
    c = torch.nn.functional.pad(c, (self.inference_padding, self.inference_padding), "replicate")
  File "C:\Users\micro\anaconda3\envs\tts\lib\site-packages\torch\nn\functional.py", line 4397, in _pad
    raise NotImplementedError("Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now")
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.11.0+cpu",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD",
        "python": "3.9.12",
        "version": "10.0.22000"
    }
}
```

**Comment by NeonBohdan** [comment]
@DillFrescott  YourTTS is a end-to-end model
You don't need and can't use vocoder for this, it's solid
Only switch language and voice
