### ISSUE TITLE
[Bug] Can't use tts bash command after using the pip install

### ISSUE THREAD

**Issue by SylvainVerdy** [coqui-ai/TTS#1690]
### Describe the bug

I can't use tts command on terminal after installing TTS repos.

### To Reproduce

pip install TTS

tts --list_models

### Logs

```shell
Traceback (most recent call last):
  File "/home/nxf77184/miniconda3/envs/baptiste_env/bin/tts-server", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts-server')())
  File "/home/nxf77184/miniconda3/envs/baptiste_env/bin/tts-server", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nxf77184/Desktop/thesis/generate_text_from_picovoice/TTS-0.7.0_models/TTS/server/server.py", line 14, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/nxf77184/Desktop/thesis/generate_text_from_picovoice/TTS-0.7.0_models/TTS/utils/synthesizer.py", line 14, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/nxf77184/Desktop/thesis/generate_text_from_picovoice/TTS-0.7.0_models/TTS/utils/audio.py", line 5, in <module>
    import pyworld as pw
  File "/home/nxf77184/.local/lib/python3.8/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.1+cu113",
        "TTS": "0.6.2",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022"
    }
}
```

**Comment by p0p4k** [comment]
Try and report back.
```
pip uninstall numpy
pip install numpy
```

**Comment by SylvainVerdy** [comment]
[output_log.txt](https://github.com/coqui-ai/TTS/files/8976919/output_log.txt)
`(baptiste_env) nxf77184@sopdpuml10:~/Desktop/thesis/generate_text_from_picovoice/TTS-0.7.0_models/TTS$ pip uninstall numpy
Found existing installation: numpy 1.21.6
Uninstalling numpy-1.21.6:
  Would remove:
    /home/nxf77184/miniconda3/envs/baptiste_env/bin/f2py
    /home/nxf77184/miniconda3/envs/baptiste_env/bin/f2py3
    /home/nxf77184/miniconda3/envs/baptiste_env/bin/f2py3.8
    /home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/site-packages/numpy-1.21.6.dist-info/*
    /home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/site-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0
    /home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/site-packages/numpy.libs/libopenblasp-r0-2d23e62b.3.17.so
    /home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/site-packages/numpy.libs/libquadmath-2d0c479f.so.0.0.0
    /home/nxf77184/miniconda3/envs/baptiste_env/lib/python3.8/site-packages/numpy/*
Proceed (Y/n)? Y
  Successfully uninstalled numpy-1.21.6
(baptiste_env) nxf77184@sopdpuml10:~/Desktop/thesis/generate_text_from_picovoice/TTS-0.7.0_models/TTS$ pip install numpy
Collecting numpy
  Using cached numpy-1.23.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.23.0 which is incompatible.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.0 which is incompatible.
tts 0.6.2 requires numpy==1.21.6, but you have numpy 1.23.0 which is incompatible.
`

**That's the output from my terminal.**

**Comment by p0p4k** [comment]
Yes, that was going to be my next suggestion as well. Good luck!
