### ISSUE TITLE
VITS + multiband-melgan or univnet Inference Error "Mean-Var stats does not match the given feature dimensions"

### ISSUE THREAD

**Issue by iprovalo** [coqui-ai/TTS#1699]
### Describe the bug

When running vits + multiband-melgan or univnet inference on pre-trained released models, I get this error:

`Mean-Var stats does not match the given feature dimensions`

### To Reproduce

1. Install:
```
git clone https://github.com/coqui-ai/TTS
cd TTS/
python3 -m pip install -r requirements.txt
python3 setup.py develop
```
2. Run:
```python3 TTS/bin/synthesize.py --model_name tts_models/en/ljspeech/vits --vocoder_name vocoder_models/en/ljspeech/univnet --text "This is a test sentence for English model"```

### Logs

```shell
['This is a test sentence for English model']
Traceback (most recent call last):
  File "TTS/bin/synthesize.py", line 367, in <module>
    main()
  File "TTS/bin/synthesize.py", line 358, in main
    reference_speaker_name=args.reference_speaker_idx,
  File "/apps/tts/TTS/TTS/utils/synthesizer.py", line 290, in tts
    vocoder_input = self.vocoder_ap.normalize(mel_postnet_spec.T)
  File "/apps/tts/TTS/TTS/utils/audio.py", line 452, in normalize
    raise RuntimeError(" [!] Mean-Var stats does not match the given feature dimensions.")
RuntimeError:  [!] Mean-Var stats does not match the given feature dimensions.
```

### Environment

```shell
{
"CUDA": {
"GPU": [
"NVIDIA A100-SXM4-40GB"
],
"available": true,
"version": "11.5"
},
"Packages": {
"PyTorch_debug": false,
"PyTorch_version": "1.11.0+cu115",
"TTS": "0.7.0",
"numpy": "1.21.6"
},
"System": {
"OS": "Linux",
"architecture": [
"64bit",
"ELF"
],
"processor": "x86_64",
"python": "3.7.13",
"version": "#61~18.04.3-Ubuntu SMP Fri Oct 1 14:04:01 UTC 2021"
}
}
```

**Comment by iprovalo** [comment]
@lexkoro thank you, for the comments in https://github.com/coqui-ai/TTS/issues/1700 

Works as expected!
