### ISSUE TITLE
[WinError 32] The process cannot access the file because it is being used by another process:

### ISSUE THREAD

**Issue by q8ing** [coqui-ai/TTS#1711]
### Describe the bug

I tried to use one of TTS recipes in Windows 10 Pro 21H2 19044.1766 using Python 3.8, but I got this error:

(.tts) C:\Users\root\Desktop\TTS\recipes\thorsten_DE>cd tacotron2-DDC

(.tts) C:\Users\root\Desktop\TTS\recipes\thorsten_DE\tacotron2-DDC>python train_tacotron_ddc.py
C:\Users\root\Desktop\TTS\.tts\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 22668 files in C:\Users\root\Desktop\TTS\recipes\thorsten_DE\thorsten
 > Using CUDA: True
 > Number of GPUs: 1

 > Model has 47669492 parameters

 > Number of output frames: 6

 > EPOCH: 0/1000
 --> C:\Users\root\Desktop\TTS\recipes\thorsten_DE\tacotron2-DDC\run-July-03-2022_12+29PM-5c821d9f
[*] Pre-computing phonemes...
  0%|                                                                                        | 0/22442 [00:00<?, ?it/s]C:\Users\root\Desktop\TTS\.tts\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > Found 22668 files in C:\Users\root\Desktop\TTS\recipes\thorsten_DE\thorsten
 > Using CUDA: True
 > Number of GPUs: 1

 > Model has 47669492 parameters

 > Number of output frames: 6

 > EPOCH: 0/1000
 --> C:\Users\root\Desktop\TTS\recipes\thorsten_DE\tacotron2-DDC\run-July-03-2022_12+29PM-5c821d9f

> DataLoader initialization
| > Tokenizer:
        | > add_blank: False
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: de
                | > phoneme backend: espeak
| > Number of instances : 22442
 | > Preprocessing samples
 | > Max text length: 181
 | > Min text length: 3
 | > Avg text length: 51.10043309778892
 |
 | > Max audio length: 220282.0
 | > Min audio length: 5515.0
 | > Avg audio length: 76939.2241622977
 | > Num. instances discarded samples: 507
 | > Batch group size: 0.

 > TRAINING (2022-07-03 12:29:42)
Traceback (most recent call last):
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\trainer\trainer.py", line 1492, in fit
    self._fit()
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\trainer\trainer.py", line 1476, in _fit
    self.train_epoch()
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\trainer\trainer.py", line 1254, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\root\Desktop\TTS\recipes\thorsten_DE\tacotron2-DDC\train_tacotron_ddc.py", line 108, in <module>
    trainer.fit()
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\trainer\trainer.py", line 1511, in fit
    remove_experiment_folder(self.output_path)
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\trainer\generic_utils.py", line 64, in remove_experiment_folder
    fs.rm(experiment_path, recursive=True)
  File "C:\Users\root\Desktop\TTS\.tts\lib\site-packages\fsspec\implementations\local.py", line 151, in rm
    shutil.rmtree(p)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 730, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 608, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\root\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 606, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Users/root/Desktop/TTS/recipes/thorsten_DE/tacotron2-DDC/run-July-03-2022_12+29PM-5c821d9f\\events.out.tfevents.1656840570.DESKTOP-985JVKU'

### To Reproduce

1- Open CMD.
2- Change the path to TTS/recipes/thorsten_DE/tacotron2-DDC using cd command.
3- Run python train_tacotron_ddc.py.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1060 6GB"
        ],
        "available": true,
        "version": "10.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.8.0+cu101",
        "TTS": "0.7.1",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel",
        "python": "3.8.0",
        "version": "10.0.19041"
    }
}
```

**Comment by erogol** [comment]
We don't support Windows currently.

**Comment by Aqirito** [comment]
> Modifi you script to this variant: [train.txt](https://github.com/coqui-ai/TTS/files/10716159/train.txt)
Hello @tarasfrompir, what line did you modify?.
