### ISSUE TITLE
[Bug] save_best_model does not save the best model in distributed training

### ISSUE THREAD

**Issue by yurtmete** [coqui-ai/TTS#1751]
### Describe the bug

I started VITS model training with single GPU, and then decided to continue with distributed training. However, in the case of distributed training, the best model is not saved. 

### To Reproduce

Start a training using VITS recipe on VCTK dataset:
0-  $ CUDA_VISIBLE_DEVICES=4 python recipes/vctk/vits/train_vits.py 

and then continue with --continue_path argument as below:
1- $ CUDA_VISIBLE_DEVICES=4 python recipes/vctk/vits/train_vits.py --continue_path
 /scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/vits_vctk-July-14-2022_09+36PM-5cef6fa

and then continue the training in distributed setting with two GPUs:
2- $ CUDA_VISIBLE_DEVICES=4,5 python -m trainer.distribute --script /scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/train_vits.py --continue_path /scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/vits_vctk-July-14-2022_09+36PM-5cef6fa --coqpit.distributed_url tcp://localhost:54322

and observe the following error log:
3- The error log:
> BEST MODEL : /scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/vits_vctk-July-14-2022_09+36PM-5cef6fa/best_model_160007.pth
 ! Run is kept in /scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/vits_vctk-July-14-2022_09+36PM-5cef6fa
Traceback (most recent call last):
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/trainer/trainer.py", line 1533, in fit
    self._fit()
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/trainer/trainer.py", line 1527, in _fit
    self.save_best_model()
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/trainer/trainer.py", line 1607, in save_best_model
    self.best_loss = save_best_model(
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/trainer/io.py", line 188, in save_best_model
    fs.copy(checkpoint_path, shortcut_path)
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/fsspec/spec.py", line 884, in copy
    self.cp_file(p1, p2, **kwargs)
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/fsspec/implementations/local.py", line 121, in cp_file    **raise FileNotFoundErrorFileNotFoundError**^CTraceback (most recent call last):
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/trainer/distribute.py", line 73, in <module>
    distribute()
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/site-packages/trainer/distribute.py", line 59, in distribute
    p.wait()
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/mete/miniconda3/envs/coqui_VITS/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

### Expected behavior

Save best model does indeed saves the best model in the case of single GPU training. After that if we continue the session with multi GPU training, the save_best_model method does not save the best model. 

### Environment

```shell
- TTS version 0.7.1
- PyTorch version 1.12.0
- Python version 3.8.13
- OS linux
```

### Additional context

Here is my config.json:

```JSON
{
    "output_path": "/scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits",
    "logger_uri": null,
    "run_name": "vits_vctk",
    "project_name": null,
    "run_description": "\ud83d\udc38Coqui trainer run.",
    "print_step": 25,
    "plot_step": 100,
    "model_param_stats": false,
    "wandb_entity": null,
    "dashboard_logger": "tensorboard",
    "log_model_step": 10000,
    "save_step": 10000,
    "save_n_checkpoints": 5,
    "save_checkpoints": true,
    "save_all_best": false,
    "save_best_after": 10000,
    "target_loss": null,
    "print_eval": false,
    "test_delay_epochs": -1,
    "run_eval": true,
    "run_eval_steps": null,
    "distributed_backend": "nccl",
    "distributed_url": "tcp://localhost:54322",
    "mixed_precision": true,
    "epochs": 1000,
    "batch_size": 64,
    "eval_batch_size": 16,
    "grad_clip": [
        1000.0,
        1000.0
    ],
    "scheduler_after_epoch": true,
    "lr": 0.001,
    "optimizer": "AdamW",
    "optimizer_params": {
        "betas": [
            0.8,
            0.99
        ],
        "eps": 1e-09,
        "weight_decay": 0.01
    },
    "lr_scheduler": "",
    "lr_scheduler_params": null,
    "use_grad_scaler": false,
    "cudnn_enable": true,
    "cudnn_deterministic": false,
    "cudnn_benchmark": false,
    "training_seed": 54321,
    "model": "vits",
    "num_loader_workers": 4,
    "num_eval_loader_workers": 4,
    "use_noise_augment": false,
    "audio": {
        "fft_size": 1024,
        "win_length": 1024,
        "hop_length": 256,
        "frame_shift_ms": null,
        "frame_length_ms": null,
        "stft_pad_mode": "reflect",
        "sample_rate": 22050,
        "resample": false,
        "preemphasis": 0.0,
        "ref_level_db": 20,
        "do_sound_norm": false,
        "log_func": "np.log",
        "do_trim_silence": false,
        "trim_db": 23,
        "do_rms_norm": false,
        "db_level": null,
        "power": 1.5,
        "griffin_lim_iters": 60,
        "num_mels": 80,
        "mel_fmin": 0.0,
        "mel_fmax": null,
        "spec_gain": 1,
        "do_amp_to_db_linear": false,
        "do_amp_to_db_mel": true,
        "pitch_fmax": 640.0,
        "pitch_fmin": 0.0,
        "signal_norm": false,
        "min_level_db": -100,
        "symmetric_norm": true,
        "max_norm": 4.0,
        "clip_norm": true,
        "stats_path": null
    },
    "use_phonemes": true,
    "phonemizer": "espeak",
    "phoneme_language": "en",
    "compute_input_seq_cache": true,
    "text_cleaner": "english_cleaners",
    "enable_eos_bos_chars": false,
    "test_sentences_file": "",
    "phoneme_cache_path": "/scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/phoneme_cache",
    "characters": {
        "characters_class": "TTS.tts.utils.text.characters.IPAPhonemes",
        "vocab_dict": null,
        "pad": "<PAD>",
        "eos": "<EOS>",
        "bos": "<BOS>",
        "blank": "<BLNK>",
        "characters": "iy\u0268\u0289\u026fu\u026a\u028f\u028ae\u00f8\u0258\u0259\u0275\u0264o\u025b\u0153\u025c\u025e\u028c\u0254\u00e6\u0250a\u0276\u0251\u0252\u1d7b\u0298\u0253\u01c0\u0257\u01c3\u0284\u01c2\u0260\u01c1\u029bpbtd\u0288\u0256c\u025fk\u0261q\u0262\u0294\u0274\u014b\u0272\u0273n\u0271m\u0299r\u0280\u2c71\u027e\u027d\u0278\u03b2fv\u03b8\u00f0sz\u0283\u0292\u0282\u0290\u00e7\u029dx\u0263\u03c7\u0281\u0127\u0295h\u0266\u026c\u026e\u028b\u0279\u027bj\u0270l\u026d\u028e\u029f\u02c8\u02cc\u02d0\u02d1\u028dw\u0265\u029c\u02a2\u02a1\u0255\u0291\u027a\u0267\u02b2\u025a\u02de\u026b",
        "punctuations": "!'(),-.:;? ",
        "phonemes": null,
        "is_unique": false,
        "is_sorted": true
    },
    "add_blank": true,
    "batch_group_size": 5,
    "loss_masking": null,
    "sort_by_audio_len": false,
    "min_audio_len": 1,
    "max_audio_len": Infinity,
    "min_text_len": 1,
    "max_text_len": 630,
    "compute_f0": false,
    "compute_linear_spec": true,
    "precompute_num_workers": 0,
    "start_by_longest": false,
    "datasets": [
        {
            "name": "vctk",
            "path": "/scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/VCTK",
            "meta_file_train": "",
            "ignored_speakers": null,
            "language": "en-us",
            "meta_file_val": "",
            "meta_file_attn_mask": ""
        }
    ],
    "test_sentences": [
        [
            "It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."
        ],
        [
            "Be a voice, not an echo."
        ],
        [
            "I'm sorry Dave. I'm afraid I can't do that."
        ],
        [
            "This cake is great. It's so delicious and moist."
        ],
        [
            "Prior to November 22, 1963."
        ]
    ],
    "eval_split_max_size": null,
    "eval_split_size": 0.01,
    "use_speaker_weighted_sampler": false,
    "speaker_weighted_sampler_alpha": 1.0,
    "use_language_weighted_sampler": false,
    "language_weighted_sampler_alpha": 1.0,
    "use_length_weighted_sampler": false,
    "length_weighted_sampler_alpha": 1.0,
    "model_args": {
        "num_chars": 131,
        "out_channels": 513,
        "spec_segment_size": 32,
        "hidden_channels": 192,
        "hidden_channels_ffn_text_encoder": 768,
        "num_heads_text_encoder": 2,
        "num_layers_text_encoder": 6,
        "kernel_size_text_encoder": 3,
        "dropout_p_text_encoder": 0.1,
        "dropout_p_duration_predictor": 0.5,
        "kernel_size_posterior_encoder": 5,
        "dilation_rate_posterior_encoder": 1,
        "num_layers_posterior_encoder": 16,
        "kernel_size_flow": 5,
        "dilation_rate_flow": 1,
        "num_layers_flow": 4,
        "resblock_type_decoder": "1",
        "resblock_kernel_sizes_decoder": [
            3,
            7,
            11
        ],
        "resblock_dilation_sizes_decoder": [
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ]
        ],
        "upsample_rates_decoder": [
            8,
            8,
            2,
            2
        ],
        "upsample_initial_channel_decoder": 512,
        "upsample_kernel_sizes_decoder": [
            16,
            16,
            4,
            4
        ],
        "periods_multi_period_discriminator": [
            2,
            3,
            5,
            7,
            11
        ],
        "use_sdp": true,
        "noise_scale": 1.0,
        "inference_noise_scale": 0.667,
        "length_scale": 1.0,
        "noise_scale_dp": 1.0,
        "inference_noise_scale_dp": 1.0,
        "max_inference_len": null,
        "init_discriminator": true,
        "use_spectral_norm_disriminator": false,
        "use_speaker_embedding": true,
        "num_speakers": 109,
        "speakers_file": "/scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/vits_vctk-July-14-2022_09+36PM-5cef6fa/speakers.pth",
        "d_vector_file": null,
        "speaker_embedding_channels": 256,
        "use_d_vector_file": false,
        "d_vector_dim": 0,
        "detach_dp_input": true,
        "use_language_embedding": false,
        "embedded_language_dim": 4,
        "num_languages": 0,
        "language_ids_file": null,
        "use_speaker_encoder_as_loss": false,
        "speaker_encoder_config_path": "",
        "speaker_encoder_model_path": "",
        "condition_dp_on_speaker": true,
        "freeze_encoder": false,
        "freeze_DP": false,
        "freeze_PE": false,
        "freeze_flow_decoder": false,
        "freeze_waveform_decoder": false,
        "encoder_sample_rate": null,
        "interpolate_z": true,
        "reinit_DP": false,
        "reinit_text_encoder": false
    },
    "lr_gen": 0.0002,
    "lr_disc": 0.0002,
    "lr_scheduler_gen": "ExponentialLR",
    "lr_scheduler_gen_params": {
        "gamma": 0.999875,
        "last_epoch": -1
    },
    "lr_scheduler_disc": "ExponentialLR",
    "lr_scheduler_disc_params": {
        "gamma": 0.999875,
        "last_epoch": -1
    },
    "kl_loss_alpha": 1.0,
    "disc_loss_alpha": 1.0,
    "gen_loss_alpha": 1.0,
    "feat_loss_alpha": 1.0,
    "mel_loss_alpha": 45.0,
    "dur_loss_alpha": 1.0,
    "speaker_encoder_loss_alpha": 1.0,
    "return_wav": true,
    "r": 1,
    "num_speakers": 0,
    "use_speaker_embedding": true,
    "speakers_file": "/scratch1/users/mete/coqui_TTS_VITS/recipes/vctk/vits/vits_vctk-July-14-2022_09+36PM-5cef6fa/speakers.pth",
    "speaker_embedding_channels": 256,
    "language_ids_file": null,
    "use_language_embedding": false,
    "use_d_vector_file": false,
    "d_vector_file": null,
    "d_vector_dim": 0
}
```

**Comment by erogol** [comment]
I am not sure if I understand what the issue is exactly. What do you mean by not saving the best model in multi-gpu training?
Does it try to save but raise an error or print saving but never save or something else?

**Comment by yurtmete** [comment]
Today I tried to replicate the issue, however I could not. Sorry for spamming :( Closing the issue.
