### ISSUE TITLE
[Bug] Error when set Characters in Tacotron2

### ISSUE THREAD

**Issue by blackmamba1122** [coqui-ai/TTS#1887]
### Describe the bug

I got error when set characters in tacoron 2, here's my train.py

```
import os

from trainer import Trainer, TrainerArgs

from TTS.config.shared_configs import BaseAudioConfig
from TTS.tts.configs.tacotron2_config import Tacotron2Config
from TTS.tts.configs.shared_configs import CharactersConfig, BaseDatasetConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.tacotron2 import Tacotron2
from TTS.tts.utils.speakers import SpeakerManager
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

# set experiment paths
output_path = os.path.dirname(os.path.abspath(__file__))
dataset_config = BaseDatasetConfig(name="my_data", meta_file_train="", path=os.path.join(output_path, "/my_data/"))


# define audio config
# ❗ resample the dataset externally using `TTS/bin/resample.py` and set `resample=False` for faster training
audio_config = BaseAudioConfig(
    sample_rate=22050,
    resample=True,  # Resample to 22050 Hz. It slows down training. Use `TTS/bin/resample.py` to pre-resample and set this False for faster training.
    do_trim_silence=True,
    trim_db=23.0,
    signal_norm=False,
    mel_fmin=0.0,
    mel_fmax=8000,
    spec_gain=1.0,
    log_func="np.log",
    preemphasis=0.0,
)

# define model config


config = Tacotron2Config(  # This is the config that is saved for the future use
    audio=audio_config,
    run_name="My_Run",
    num_speakers=4,
    batch_size=16,
    eval_batch_size=8,
    num_loader_workers=4,
    num_eval_loader_workers=4,
    run_eval=True,
    test_delay_epochs=-1,
    r=6, 
    gradual_training=[[0, 6, 16], [10000, 4, 16], [50000, 3, 16], [100000, 2, 16]],
    double_decoder_consistency=True,
    epochs=1000,
    text_cleaner="basic_cleaners",
    use_phonemes=False,
    phoneme_language="en-us",
    phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
    precompute_num_workers=8,
    print_step=10,
    print_eval=True,
    mixed_precision=False,
    output_path=output_path,
    datasets=[dataset_config],
    use_speaker_embedding=True,  # set this to enable multi-sepeaker training
    lr=0.0001,
    characters=CharactersConfig(
        pad = "_",
        eos="&",
        bos="*",
        blank="<BLNK>",
        characters="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
        phonemes=None,
        ),
)


# INITIALIZE THE AUDIO PROCESSOR
# Audio processor is used for feature extraction and audio I/O.
# It mainly serves to the dataloader and the training loggers.
ap = AudioProcessor.init_from_config(config)

# INITIALIZE THE TOKENIZER
# Tokenizer is used to convert text to sequences of token IDs.
# If characters are not defined in the config, default characters are passed to the config
tokenizer, config = TTSTokenizer.init_from_config(config)

# LOAD DATA SAMPLES
# Each sample is a list of ```[text, audio_file_path, speaker_name]```
# You can define your custom sample loader returning the list of samples.
# Or define your custom formatter and pass it to the `load_tts_samples`.
# Check `TTS.tts.datasets.load_tts_samples` for more details.
train_samples, eval_samples = load_tts_samples(
    dataset_config,
    eval_split=True,
    eval_split_max_size=config.eval_split_max_size,
    eval_split_size=config.eval_split_size,
)

# init speaker manager for multi-speaker training
# it maps speaker-id to speaker-name in the model and data-loader
speaker_manager = SpeakerManager()
speaker_manager.set_ids_from_data(train_samples + eval_samples, parse_key="speaker_name")
config.num_speakers = speaker_manager.num_speakers

# init model
model = GlowTTS(config, ap, tokenizer, speaker_manager=speaker_manager)

# INITIALIZE THE TRAINER
# Trainer provides a generic API to train all the 🐸TTS models with all its perks like mixed-precision training,
# distributed training, etc.
trainer = Trainer(
    TrainerArgs(), config, output_path, model=model, train_samples=train_samples, eval_samples=eval_samples
)

# AND... 3,2,1... 🚀
trainer.fit()
```

I've already added my dataset formatters in formatters.py

### Expected behavior

No error when training

### Logs

```shell
> Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:True
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:23.0
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
Traceback (most recent call last):
  File "train.py", line 83, in <module>
    tokenizer, config = TTSTokenizer.init_from_config(config)
  File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/TTS/TTS/tts/utils/text/tokenizer.py", line 174, in init_from_config
    characters, new_config = Graphemes().init_from_config(config)
  File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/TTS/TTS/tts/utils/text/characters.py", line 454, in init_from_config
    is_sorted=config.characters["is_sorted"],
  File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/TTS/TTS/tts/utils/text/characters.py", line 433, in __init__
    super().__init__(characters, punctuations, pad, eos, bos, blank, is_unique, is_sorted)
  File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/TTS/TTS/tts/utils/text/characters.py", line 167, in __init__
    self._create_vocab()
  File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/TTS/TTS/tts/utils/text/characters.py", line 258, in _create_vocab
    self.vocab = _vocab + list(self._punctuations)
TypeError: 'NoneType' object is not iterable

```

### Environment

```shell
{
"CUDA": {
"GPU": [
"NVIDIA GeForce GTX 1660 Ti"
],
"available": true,
"version": "10.2"
},
"Packages": {
"PyTorch_debug": false,
"PyTorch_version": "1.11.0+cu102",
"TTS": "0.6.1",
"numpy": "1.19.5"
},
"System": {
"OS": "Linux",
"architecture": [
"64bit",
"ELF"
],
"processor": "x86_64",
"python": "3.8.0",
"version": "#118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022"
}
}
```

**Comment by erogol** [comment]
You need punctuations set here 

```
characters=CharactersConfig(
        pad = "_",
        eos="&",
        bos="*",
        blank="<BLNK>",
        characters="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
        phonemes=None,
        ),
```

**Comment by blackmamba1122** [comment]
> You need punctuations set here
> 
> ```
> characters=CharactersConfig(
>         pad = "_",
>         eos="&",
>         bos="*",
>         blank="<BLNK>",
>         characters="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
>         phonemes=None,
>         ),
> ```

As you can see, I've set my punctuation in my train.py, but still error.
```
    characters=CharactersConfig(
        pad = "_",
        eos="&",
        bos="*",
        blank="<BLNK>",
        characters="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!'(),-.:;? ",
        phonemes=None,
        ),
)
```
