### ISSUE TITLE
[Bug] Error when training VITS multispeaker

### ISSUE THREAD

**Issue by blackmamba1122** [coqui-ai/TTS#1941]
### Describe the bug

I want to try VITS multispeaker and running using:

```
CUDA_VISIBLE_DEVICES=0 python train.py 
```
It's my train.py

```
import os

from trainer import Trainer, TrainerArgs

from TTS.config.shared_configs import BaseAudioConfig
from TTS.tts.configs.shared_configs import BaseDatasetConfig
from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.vits import Vits, VitsArgs, CharactersConfig
from TTS.tts.utils.speakers import SpeakerManager
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

output_path = os.path.dirname(os.path.abspath(file))
dataset_config = BaseDatasetConfig(name="mailab", meta_file_train="", path=os.path.join(output_path, ".../MAILAB/"))

audio_config = BaseAudioConfig(
sample_rate=22050,
win_length=1024,
hop_length=256,
num_mels=80,
preemphasis=0.0,
ref_level_db=20,
log_func="np.log",
do_trim_silence=True,
trim_db=23.0,
mel_fmin=0,
mel_fmax=None,
spec_gain=1.0,
signal_norm=False,
do_amp_to_db_linear=False,
resample=True,
)

vitsArgs = VitsArgs(
use_speaker_embedding=True,
)

config = VitsConfig(
model_args=vitsArgs,
audio=audio_config,
run_name="Vits_MAILAB",
num_speakers=4,
batch_size=8,
eval_batch_size=4,
batch_group_size=5,
num_loader_workers=4,
num_eval_loader_workers=4,
run_eval=True,
test_delay_epochs=-1,
epochs=2000,
text_cleaner="phoneme_cleaners",
use_phonemes=True,
phoneme_language="en-us",
phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
compute_input_seq_cache=True,
print_step=10,
print_eval=True,
mixed_precision=False,
output_path=output_path,
datasets=[dataset_config],
lr=0.0001,
test_sentences=["Aku lagi males.", "Males banget untuk kerja.", "Apa yang kamu lakukan jika kamu memiliki banyak uang?"],
)

ap = AudioProcessor.init_from_config(config)

tokenizer, config = TTSTokenizer.init_from_config(config)

train_samples, eval_samples = load_tts_samples(
dataset_config,
eval_split=True,
eval_split_max_size=config.eval_split_max_size,
eval_split_size=config.eval_split_size,
)

speaker_manager = SpeakerManager()
speaker_manager.set_ids_from_data(train_samples + eval_samples, parse_key="speaker_name")
config.model_args.num_speakers = speaker_manager.num_speakers

model = Vits(config, ap, tokenizer, speaker_manager)

trainer = Trainer(
TrainerArgs(),
config,
output_path,
model=model,
train_samples=train_samples,
eval_samples=eval_samples,
)
trainer.fit()
```

### To Reproduce

and I got error like this:

```
--> STEP: 170/495 -- GLOBAL_STEP: 170
| > loss_disc: 2.56896 (2.49092)
| > loss_disc_real_0: 0.29256 (0.19180)
| > loss_disc_real_1: 0.21851 (0.25452)
| > loss_disc_real_2: 0.24393 (0.25421)
| > loss_disc_real_3: 0.27644 (0.25253)
| > loss_disc_real_4: 0.16534 (0.25395)
| > loss_disc_real_5: 0.19653 (0.23969)
| > loss_0: 2.56896 (2.49092)
| > grad_norm_0: 11.30908 (7.44597)
| > loss_gen: 2.27789 (2.37348)
| > loss_kl: 2.34740 (7.49759)
| > loss_feat: 3.50568 (3.26735)
| > loss_mel: 44.98423 (52.07333)
| > loss_duration: 2.61673 (2.72957)
| > loss_1: 55.73194 (67.94135)
| > grad_norm_1: 97.12949 (221.20049)
| > current_lr_0: 0.00020
| > current_lr_1: 0.00020
| > step_time: 0.75400 (0.63732)
| > loader_time: 0.00350 (0.00343)

! Run is kept in /media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/CoquiTTS/TTS/Vits-August-23-2022_02+00PM-68cef28a
Traceback (most recent call last):
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/trainer/trainer.py", line 1492, in fit
self._fit()
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/trainer/trainer.py", line 1476, in _fit
self.train_epoch()
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/trainer/trainer.py", line 1254, in train_epoch
for cur_step, batch in enumerate(self.train_loader):
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in next
data = self._next_data()
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
return self._process_data(data)
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
data.reraise()
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
data = fetcher.fetch(index)
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/coqui_env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
return self.collate_fn(data)
File "/media/48e7e847-4b76-4839-a9bc-6f2511e980d3/riset_tts/Coqui_TTS/TTS/TTS/tts/models/vits.py", line 293, in collate_fn
wav_padded[i, :, : wav.size(1)] = torch.FloatTensor(wav)
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0. Target sizes: [1, 90736]. Tensor sizes: [2, 90736]
```

### Expected behavior

Not error during training

### Environment

```shell
{
"CUDA": {
"GPU": [
"NVIDIA GeForce GTX 1660 Ti"
],
"available": true,
"version": "10.2"
},
"Packages": {
"PyTorch_debug": false,
"PyTorch_version": "1.11.0+cu102",
"TTS": "0.6.1",
"numpy": "1.19.5"
},
"System": {
"OS": "Linux",
"architecture": [
"64bit",
"ELF"
],
"processor": "x86_64",
"python": "3.8.0",
"version": "#118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022"
}
```

**Comment by erogol** [comment]
I think you audio files are 2 channels. You need to convert them to 1 channel audio before training.

**Comment by blackmamba1122** [comment]
Yup, that's true. One of my speakers use 2 channel(stereo), after change to 1 channel (mono) it's working fine.
