### ISSUE TITLE
[Bug] AttributeError: 'Vits' object has no attribute 'disc'

### ISSUE THREAD

**Issue by NK990** [coqui-ai/TTS#2101]
### Describe the bug

I got strange error while I'm trying to use pretrained VITS model with its configuration.

### To Reproduce

Running this command:
```
!CUDA_VISIBLE_DEVICES="0" python /content/drive/MyDrive/TTS/vits/train_tts.py \
    --config_path /content/drive/MyDrive/TTS/vits/config.json \
    --restore_path /content/drive/MyDrive/TTS/vits/model_file.pth 
```

I tried also to set lr_disc via coqpit :

```
!CUDA_VISIBLE_DEVICES="0" python /content/drive/MyDrive/TTS/vits/train_tts.py \
    --config_path /content/drive/MyDrive/TTS/vits/config.json \
    --restore_path /content/drive/MyDrive/TTS/vits/model_file.pth \
     ---coqpit.lr_disc 0.0002
```
It returns this error:

```
 > Training Environment:
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 4
 | > Num. of Torch Threads: 2
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
Traceback (most recent call last):
  File "/content/drive/MyDrive/TTS/vits/train_tts.py", line 71, in <module>
    main()
  File "/content/drive/MyDrive/TTS/vits/train_tts.py", line 65, in main
    parse_command_line_args=False,
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 481, in __init__
    self.optimizer = self.get_optimizer(self.model, self.config)
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1646, in get_optimizer
    optimizer = model.get_optimizer()
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/models/vits.py", line 1643, in get_optimizer
    optimizer0 = get_optimizer(self.config.optimizer, self.config.optimizer_params, self.config.lr_disc, self.disc)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'Vits' object has no attribute 'disc'
```

 

### Logs

```shell
It returns this error:
 > Training Environment:
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 4
 | > Num. of Torch Threads: 2
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
Traceback (most recent call last):
  File "/content/drive/MyDrive/TTS/vits/train_tts.py", line 71, in <module>
    main()
  File "/content/drive/MyDrive/TTS/vits/train_tts.py", line 65, in main
    parse_command_line_args=False,
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 481, in __init__
    self.optimizer = self.get_optimizer(self.model, self.config)
  File "/usr/local/lib/python3.7/dist-packages/trainer/trainer.py", line 1646, in get_optimizer
    optimizer = model.get_optimizer()
  File "/usr/local/lib/python3.7/dist-packages/TTS/tts/models/vits.py", line 1643, in get_optimizer
    optimizer0 = get_optimizer(self.config.optimizer, self.config.optimizer_params, self.config.lr_disc, self.disc)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'Vits' object has no attribute 'disc'
```

### Environment

```shell
I'm using latest version of CoquiTTS
```

**Comment by erogol** [comment]
Unfortunately, the released model has no discriminator provided. Either you need to manually only restore the generator part of the model or you need to start from scratch.

**Comment by ADD-eNavarro** [comment]
Could have been a more rounded answer if it had provided the steps to restore the generator.

**Comment by tubali12345** [comment]
@erogol Can you provide the steps to restore only the generator part of the model?
