### ISSUE TITLE
[Bug] Doing a `pip install TTS` on a clean aarch64 Raspian devices yields a numpy version error

### ISSUE THREAD

**Issue by iamsrp** [coqui-ai/TTS#2117]
### Describe the bug

[ This is from memory since I am away-from-desk but, if further details are needed, I can likely dig them out at some point. It's a simple reproducer, provided that you have an RPi4 to hand. ]

Hi,

If you do a `pip install TTS` on a newly built, and `apt update`'d, Raspberry Pi 4 device, using the 64bit version of the OS, it yields a version compatibility error with numpy when you invoke the TTS system. (A grumble from Numba(?) which is something like "Built against 0xf but have Numpy version 0xe.") Forcibly upgrading numpy doesn't help since TTS looks to require the older version.

I also tried `make install`'ng the `git clone`'d tree and got the same results.

That being said, it all seems to work on Ubuntu x64. I am rather taken with the `tts_models/en/blizzard2013/capacitron-t2-c50` model at this point.

Thanks for making TTS public. It seems to be the best one of the bunch as far as I can tell.

srp

### To Reproduce

Install a fresh Raspbian 64bit OS on a Raspberry Pi 4. Do `pip install TTS`. Invoke the system.

### Expected behavior

It should work. Instead it grumbles about numpy versions.

### Logs

```shell
[Available upon request]
```

### Environment

```shell
Effectively covered above, I believe.
```

**Comment by iamsrp** [comment]
That would explain it, thanks @Vuizur. Basically the default Python version has moved on but some of the dependencies haven't caught up yet. Downgrading probably is probably an interim solution but likely not viable long term.

This isn't urgent for me since I have other options until it rattles itself out. If the issue is in one of the dependencies then it's likely not something which the Coqui crew can easily fix.

**Comment by sylsau** [comment]
On an up-to-date Arch Linux x64, I got the same problem.
I read somewhere else that downgrading `numpy`'s version would fix the problem. It did not.
Not knowing how to downgrade Python, I tried a simpler thing: I used `pipx` instead of `pip` and it indeed worked right away. Make sure you uninstall `pip`'s version before using installing the other one so it can effectively replace the binaries.

```
pip uninstall tts
# ...
pipx install tts
```

**Comment by ludwikbukowski** [comment]
The same issue, tried to instal TTS on raspberrypi 4B 64x.
Installing by `pipx install tts` didnt help:
```
Traceback (most recent call last):
  File "/home/ludwik/.local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/home/ludwik/.local/pipx/venvs/tts/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 357, in main
    wav = synthesizer.tts(
  File "/home/ludwik/.local/pipx/venvs/tts/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 278, in tts
    outputs = synthesis(
  File "/home/ludwik/.local/pipx/venvs/tts/lib/python3.9/site-packages/TTS/tts/utils/synthesis.py", line 185, in synthesis
    speaker_id = id_to_torch(speaker_id, cuda=use_cuda)
  File "/home/ludwik/.local/pipx/venvs/tts/lib/python3.9/site-packages/TTS/tts/utils/synthesis.py", line 79, in id_to_torch
    aux_id = torch.from_numpy(aux_id)
RuntimeError: Numpy is not available
```

**Comment by robindegen** [comment]
Automatically closed an issue that is still an obvious issue on multiple platforms for multiple people? Okay..
