### ISSUE TITLE
[Bug] Out of memory when training VITS

### ISSUE THREAD

**Issue by jingzhaoou** [coqui-ai/TTS#2159]
### Describe the bug

Things used to work fine but not any more with the latest code. I ran `CUDA_VISIBLE_DEVICES=0 python recipes/vctk/vits/train_vits.py` on a V100 card with 32GB memory. I encountered the following errors:

```
 File "/home/jou2019/workspace/TTS/TTS/tts/layers/losses.py", line 643, in feature_loss
    loss += torch.mean(torch.abs(rl - gl))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 13.57 GiB already allocated; 4.75 MiB free; 14.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I am puzzled with the latest code needs more GPU memory. Is it due to memory leak somewhere? I appreciate your help! 

### To Reproduce

1. Download the VCTK data using `sh recipes/vctk/download_vctk.sh`
2. Run the training with `CUDA_VISIBLE_DEVICES=6 python recipes/vctk/vits/train_vits.py` or `CUDA_VISIBLE_DEVICES=7 python recipes/multilingual/vits_tts/train_vits_tts.py`. 
3. After a while, encountered the following errors
```
 --> STEP: 1335/1371 -- GLOBAL_STEP: 21900                                                                                                      
     | > loss_disc: 2.54605  (2.63893)                                                                                                            
     | > loss_disc_real_0: 0.09713  (0.18666)                                                                                                     
     | > loss_disc_real_1: 0.24667  (0.22746)                                                                                                     
     | > loss_disc_real_2: 0.25251  (0.23864)                                                                                                     
     | > loss_disc_real_3: 0.24055  (0.23719)                                                                                                     
     | > loss_disc_real_4: 0.21703  (0.23438)
     | > loss_disc_real_5: 0.21695  (0.22689)
     | > loss_0: 2.54605  (2.63893)
     | > grad_norm_0: 32.07741  (18.41952)
     | > loss_gen: 2.18676  (2.05279)
     | > loss_kl: 1.11700  (1.04184) 
     | > loss_feat: 5.08621  (4.08387)
     | > loss_mel: 19.44244  (17.22504)
     | > loss_duration: 2.31844  (2.43404)
     | > amp_scaler: 256.00000  (256.00000)
     | > loss_1: 30.15086  (26.83759)
     | > grad_norm_1: 389.50940  (204.48013)
     | > current_lr_0: 0.00020 
     | > current_lr_1: 0.00020 
     | > step_time: 2.57010  (1.06903)
     | > loader_time: 0.22560  (0.01884)

 ! Run is kept in /home/jou2019/workspace/TTS/recipes/vctk/vits/vits_vctk-November-18-2022_04+47AM-bc6120c3
Traceback (most recent call last):
  File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1538, in fit
    self._fit()
  File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1522, in _fit
    self.train_epoch()
File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1287, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1140, in train_step
    outputs, loss_dict_new, step_time = self._optimize(
  File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 1001, in _optimize
    outputs, loss_dict = self._model_train_step(batch, model, criterion, optimizer_idx=optimizer_idx)
  File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/trainer/trainer.py", line 959, in _model_train_step
    return model.train_step(*input_args)
  File "/home/jou2019/workspace/TTS/TTS/tts/models/vits.py", line 1311, in train_step
    loss_dict = criterion[optimizer_idx](
  File "/home/jou2019/local/miniconda3/envs/coqui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jou2019/workspace/TTS/TTS/tts/layers/losses.py", line 719, in forward
    self.feature_loss(feats_real=feats_disc_real, feats_generated=feats_disc_fake) * self.feat_loss_alpha
  File "/home/jou2019/workspace/TTS/TTS/tts/layers/losses.py", line 643, in feature_loss
    loss += torch.mean(torch.abs(rl - gl))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 13.57 GiB already allocated; 4.75 MiB free; 14.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB",
            "NVIDIA Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.13.0+cu117",
        "TTS": "0.9.0",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.8",
        "version": "#118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020"
    }
}
```

**Comment by jingzhaoou** [comment]
I found where the root cause was. The GPUs were in default mode, meaning that other processes like GUI may use some GPU memory. I set my GPUs to exclusive process mode and things run fine afterward.

**Comment by WeberJulian** [comment]
Thanks for explaining what was wrong, hopefully it can help someone with the same issue!

**Comment by Omer-ler** [comment]
@jingzhaoou  - 
How did you allocated the GPU to the training only? 
I encounter the same problem. 

Thanks!

**Comment by siddas27** [comment]
Getting the same error, without GUI.
