### ISSUE TITLE
[Bug] TacotronCapacitronTrainTest fails

### ISSUE THREAD

**Issue by slegroux** [coqui-ai/TTS#2184]
### Describe the bug

Looking at Capacitron tests to understand behavior and noticed the unit test fails with 
"tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

Checked that all input tensors to criterion are on  same cuda device. need to dig deeper to see where discrepancy arises.

### To Reproduce

nose2 -F -v -B tests.tts_tests.test_tacotron2_model.TacotronCapacitronTrainTest 

### Expected behavior

test should pass

### Logs

```shell
ERROR: test_train_step (tests.tts_tests.test_tacotron2_model.TacotronCapacitronTrainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/syl20/Src/ass/Coqui/tests/tts_tests/test_tacotron2_model.py", line 314, in test_train_step
    _, loss_dict = model.train_step(batch, criterion)
  File "/home/syl20/Src/ass/Coqui/TTS/tts/models/tacotron2.py", line 338, in train_step
    loss_dict = criterion(
  File "/home/syl20/anaconda3/envs/coqui/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/syl20/Src/ass/Coqui/TTS/tts/layers/losses.py", line 440, in forward
    self.criterion_st(stopnet_output, stopnet_target, stop_target_length)
  File "/home/syl20/anaconda3/envs/coqui/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/syl20/Src/ass/Coqui/TTS/tts/layers/losses.py", line 193, in forward
    loss = functional.binary_cross_entropy_with_logits(
  File "/home/syl20/anaconda3/envs/coqui/lib/python3.8/site-packages/torch/nn/functional.py", line 3150, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.12.1+cu102",
        "TTS": "0.9.0",
        "numpy": "1.21.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.15",
        "version": "#180-Ubuntu SMP Wed Mar 2 17:25:05 UTC 2022"
    }
}
```

**Comment by erogol** [comment]
@WeberJulian 👀

**Comment by WeberJulian** [comment]
Should be fixed with this PR https://github.com/coqui-ai/TTS/pull/2189
Wasn't catched by the CI because it runs on CPU.
