### ISSUE TITLE
[Bug] Won't install - importlib.metadata.PackageNotFoundError: TTS

### ISSUE THREAD

**Issue by chrisbward** [coqui-ai/TTS#2240]
### Describe the bug

Followed the readme, Ubuntu 20.04

```
pip install -e .
WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)
Obtaining file:///home/user/Tools/TTS/TTS
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)
Requirement already satisfied: pysbd in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.3.4)
Requirement already satisfied: numba==0.55.1 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.55.1)
Requirement already satisfied: pandas in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (1.3.3)
Requirement already satisfied: torch>=1.7 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (1.10.0+cu111)
Requirement already satisfied: unidic-lite==1.0.8 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (1.0.8)
Requirement already satisfied: scipy>=1.4.0 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (1.9.3)
Requirement already satisfied: fsspec>=2021.04.0 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (2022.10.0)
Requirement already satisfied: torchaudio in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.10.0+cu111)
Requirement already satisfied: gruut[de]==2.2.3 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (2.2.3)
Requirement already satisfied: flask in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (2.2.2)
Requirement already satisfied: pyyaml in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (5.4.1)
Requirement already satisfied: trainer in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.0.20)
Requirement already satisfied: librosa==0.8.0 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.8.0)
Requirement already satisfied: inflect==5.6.0 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (5.6.0)
Requirement already satisfied: tqdm in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (4.64.1)
Requirement already satisfied: nltk in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (3.7)
Requirement already satisfied: mecab-python3==1.0.5 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (1.0.5)
Requirement already satisfied: numpy==1.21.6 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (1.21.6)
Requirement already satisfied: umap-learn==0.5.1 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.5.1)
Requirement already satisfied: jamo in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.4.1)
Requirement already satisfied: g2pkk>=0.1.1 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.1.2)
Requirement already satisfied: anyascii in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.3.1)
Requirement already satisfied: matplotlib in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (3.4.2)
Requirement already satisfied: soundfile in /home/user/miniconda3/lib/python3.9/site-packages/SoundFile-0.10.3.post1-py3.9.egg (from TTS==0.10.0) (0.10.3.post1)
Requirement already satisfied: jieba in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.42.1)
Requirement already satisfied: coqpit>=0.0.16 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.0.17)
Requirement already satisfied: pypinyin in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.47.1)
Requirement already satisfied: cython==0.29.28 in /home/user/miniconda3/lib/python3.9/site-packages (from TTS==0.10.0) (0.29.28)
Requirement already satisfied: jsonlines~=1.2.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (1.2.0)
Requirement already satisfied: gruut-lang-en~=2.0.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (2.0.0)
Requirement already satisfied: Babel<3.0.0,>=2.8.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (2.11.0)
Requirement already satisfied: dateparser~=1.1.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (1.1.4)
Requirement already satisfied: python-crfsuite~=0.9.7 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (0.9.8)
Requirement already satisfied: num2words<1.0.0,>=0.5.10 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (0.5.12)
Requirement already satisfied: gruut-ipa<1.0,>=0.12.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (0.13.0)
Requirement already satisfied: networkx<3.0.0,>=2.5.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (2.6.3)
Requirement already satisfied: gruut-lang-de~=2.0.0 in /home/user/miniconda3/lib/python3.9/site-packages (from gruut[de]==2.2.3->TTS==0.10.0) (2.0.0)
Requirement already satisfied: pooch>=1.0 in /home/user/miniconda3/lib/python3.9/site-packages/pooch-1.6.0-py3.9.egg (from librosa==0.8.0->TTS==0.10.0) (1.6.0)
Requirement already satisfied: audioread>=2.0.0 in /home/user/miniconda3/lib/python3.9/site-packages/audioread-3.0.0-py3.9.egg (from librosa==0.8.0->TTS==0.10.0) (3.0.0)
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /home/user/miniconda3/lib/python3.9/site-packages (from librosa==0.8.0->TTS==0.10.0) (0.23.2)
Requirement already satisfied: resampy>=0.2.2 in /home/user/miniconda3/lib/python3.9/site-packages (from librosa==0.8.0->TTS==0.10.0) (0.3.1)
Requirement already satisfied: joblib>=0.14 in /home/user/miniconda3/lib/python3.9/site-packages/joblib-1.2.0-py3.9.egg (from librosa==0.8.0->TTS==0.10.0) (1.2.0)
Requirement already satisfied: decorator>=3.0.0 in /home/user/miniconda3/lib/python3.9/site-packages (from librosa==0.8.0->TTS==0.10.0) (5.1.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /home/user/miniconda3/lib/python3.9/site-packages (from numba==0.55.1->TTS==0.10.0) (0.38.1)
Requirement already satisfied: setuptools in /home/user/miniconda3/lib/python3.9/site-packages (from numba==0.55.1->TTS==0.10.0) (59.5.0)
Requirement already satisfied: pynndescent>=0.5 in /home/user/miniconda3/lib/python3.9/site-packages (from umap-learn==0.5.1->TTS==0.10.0) (0.5.8)
Requirement already satisfied: cffi>=1.0 in /home/user/miniconda3/lib/python3.9/site-packages (from soundfile->TTS==0.10.0) (1.14.6)
Requirement already satisfied: typing-extensions in /home/user/.local/lib/python3.9/site-packages (from torch>=1.7->TTS==0.10.0) (4.3.0)
Requirement already satisfied: importlib-metadata>=3.6.0 in /home/user/.local/lib/python3.9/site-packages (from flask->TTS==0.10.0) (4.12.0)
Requirement already satisfied: Jinja2>=3.0 in /home/user/miniconda3/lib/python3.9/site-packages (from flask->TTS==0.10.0) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /home/user/miniconda3/lib/python3.9/site-packages (from flask->TTS==0.10.0) (2.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in /home/user/.local/lib/python3.9/site-packages (from flask->TTS==0.10.0) (2.2.2)
Requirement already satisfied: click>=8.0 in /home/user/miniconda3/lib/python3.9/site-packages (from flask->TTS==0.10.0) (8.1.3)
Requirement already satisfied: pyparsing>=2.2.1 in /home/user/miniconda3/lib/python3.9/site-packages (from matplotlib->TTS==0.10.0) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/user/miniconda3/lib/python3.9/site-packages (from matplotlib->TTS==0.10.0) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/user/miniconda3/lib/python3.9/site-packages (from matplotlib->TTS==0.10.0) (1.3.2)
Requirement already satisfied: pillow>=6.2.0 in /home/user/miniconda3/lib/python3.9/site-packages (from matplotlib->TTS==0.10.0) (9.2.0)
Requirement already satisfied: cycler>=0.10 in /home/user/miniconda3/lib/python3.9/site-packages (from matplotlib->TTS==0.10.0) (0.10.0)
Requirement already satisfied: regex>=2021.8.3 in /home/user/miniconda3/lib/python3.9/site-packages/regex-2022.9.13-py3.9-linux-x86_64.egg (from nltk->TTS==0.10.0) (2022.9.13)
Requirement already satisfied: pytz>=2017.3 in /home/user/miniconda3/lib/python3.9/site-packages (from pandas->TTS==0.10.0) (2021.1)
Requirement already satisfied: psutil in /home/user/miniconda3/lib/python3.9/site-packages (from trainer->TTS==0.10.0) (5.9.3)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /home/user/miniconda3/lib/python3.9/site-packages (from trainer->TTS==0.10.0) (3.19.6)
Requirement already satisfied: tensorboardX in /home/user/miniconda3/lib/python3.9/site-packages (from trainer->TTS==0.10.0) (2.5.1)
Requirement already satisfied: pycparser in /home/user/miniconda3/lib/python3.9/site-packages (from cffi>=1.0->soundfile->TTS==0.10.0) (2.20)
Requirement already satisfied: six in /home/user/miniconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->TTS==0.10.0) (1.16.0)
Requirement already satisfied: tzlocal in /home/user/miniconda3/lib/python3.9/site-packages (from dateparser~=1.1.0->gruut[de]==2.2.3->TTS==0.10.0) (4.2)
Requirement already satisfied: zipp>=0.5 in /home/user/miniconda3/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask->TTS==0.10.0) (3.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/user/.local/lib/python3.9/site-packages (from Jinja2>=3.0->flask->TTS==0.10.0) (2.1.1)
Requirement already satisfied: docopt>=0.6.2 in /home/user/.local/lib/python3.9/site-packages (from num2words<1.0.0,>=0.5.10->gruut[de]==2.2.3->TTS==0.10.0) (0.6.2)
Requirement already satisfied: appdirs>=1.3.0 in /home/user/miniconda3/lib/python3.9/site-packages/appdirs-1.4.4-py3.9.egg (from pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/user/.local/lib/python3.9/site-packages (from pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (21.3)
Requirement already satisfied: requests>=2.19.0 in /home/user/miniconda3/lib/python3.9/site-packages (from pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (2.25.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/user/miniconda3/lib/python3.9/site-packages/threadpoolctl-3.1.0-py3.9.egg (from scikit-learn!=0.19.0,>=0.14.0->librosa==0.8.0->TTS==0.10.0) (3.1.0)
Requirement already satisfied: idna<3,>=2.5 in /home/user/miniconda3/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/user/miniconda3/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/user/miniconda3/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user/miniconda3/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.0->TTS==0.10.0) (1.26.6)
Requirement already satisfied: pytz-deprecation-shim in /home/user/miniconda3/lib/python3.9/site-packages (from tzlocal->dateparser~=1.1.0->gruut[de]==2.2.3->TTS==0.10.0) (0.1.0.post0)
Requirement already satisfied: tzdata in /home/user/miniconda3/lib/python3.9/site-packages (from pytz-deprecation-shim->tzlocal->dateparser~=1.1.0->gruut[de]==2.2.3->TTS==0.10.0) (2022.7)
Building wheels for collected packages: TTS
  Building editable for TTS (pyproject.toml) ... done
  Created wheel for TTS: filename=TTS-0.10.0-0.editable-cp39-cp39-linux_x86_64.whl size=13551 sha256=351fa072955af8cfdb612bee9b689de7b231c416cd0a11645f128e37923576e5
  Stored in directory: /tmp/pip-ephem-wheel-cache-6q5svnxd/wheels/1c/98/00/a2375981907b77205d6febef2943821eab1160bb31b564d5be
Successfully built TTS
WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)
Installing collected packages: TTS
  Attempting uninstall: TTS
    WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)
    Found existing installation: TTS 0.10.0
    Uninstalling TTS-0.10.0:
      Successfully uninstalled TTS-0.10.0
WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)
Successfully installed TTS-0.10.0
WARNING: Ignoring invalid distribution -orch (/home/user/miniconda3/lib/python3.9/site-packages)

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
(base) ➜  TTS git:(dev) tts --list_models
Traceback (most recent call last):
  File "/usr/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/usr/bin/tts", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: TTS
```

### To Reproduce

Tried from pip, tried the make targets, tried installing from git repo. No dice.

### Environment

```shell
Ubuntu 20.04
```

**Comment by chrisbward** [comment]
Okay so, I noticed the script in /usr/bin/tts was using 3.8 and not my miniconda python install.

I updated the first line of this, the shebang and it seems to be working now.

Thanks
