### ISSUE TITLE
[Feature request] Upgrade the numpy version 

### ISSUE THREAD

**Issue by TharukaCkasthuri** [coqui-ai/TTS#2315]
**🚀 Feature Description**

We are frustrated when working with Coqui TTS as it downgrades the Numpy version in my python environment. Coqui TTS only supports Numpy version 1.22.4, which is an old version. We need newer version of Numpy in python 3.10.

**Comment by p0p4k** [comment]
Hi, have you tried manually updating Numpy? What is the latest version that works well with 🐸 TTS?

**Comment by TharukaCkasthuri** [comment]
Yeah. Updating manually works. But appreciate if you can change the requirement file . The latest version works with coqui TTS is numpy==1.23.0.

**Comment by marsninja** [comment]
Thanks @p0p4k !! We Jaseci contributors appreciates it and admires the work by you folks!

**Comment by erogol** [comment]
done in dev

**Comment by mweinelt** [comment]
Numpy is now indeed relaxed, but the librosa version pinned is incompatible with latest numpy(==1.24.2) version.

Importing librosa on that environment leads to the following traceback for me:

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/hqwqi97ayil2bijhxdlnpy4a1ch1cj3h-python3.10-librosa-0.8.1/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/nix/store/hqwqi97ayil2bijhxdlnpy4a1ch1cj3h-python3.10-librosa-0.8.1/lib/python3.10/site-packages/librosa/core/__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "/nix/store/hqwqi97ayil2bijhxdlnpy4a1ch1cj3h-python3.10-librosa-0.8.1/lib/python3.10/site-packages/librosa/core/constantq.py", line 1059, in <module>
    dtype=np.complex,
  File "/nix/store/0xhlg0vi0y8m5lxsm8khcqqma8rmy2jr-python3.10-numpy-1.24.2/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
```

https://github.com/librosa/librosa/blame/0.8.0/librosa/core/constantq.py#L1058
