### ISSUE TITLE
[Bug] unable to run tts-server on windows using miniconda

### ISSUE THREAD

**Issue by king-dahmanus** [coqui-ai/TTS#2378]
### Describe the bug

Hello. So I created a new conda env called coquitts using:
conda create -n coquitts python=3.10
then, I activated it
conda activate coquitts
pip install tts
after it was done, I tried tts-server --model_name d:\downloads\best_model_1000865.pth
But I got this error.
Traceback (most recent call last):
  File "D:\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python3\Scripts\tts-server.exe\__main__.py", line 4, in <module>
  File "D:\python3\lib\site-packages\TTS\server\server.py", line 103, in <module>
    synthesizer = Synthesizer(
  File "D:\python3\lib\site-packages\TTS\utils\synthesizer.py", line 75, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "D:\python3\lib\site-packages\TTS\utils\synthesizer.py", line 108, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "D:\python3\lib\site-packages\TTS\config\__init__.py", line 79, in load_config
    ext = os.path.splitext(config_path)[1]
  File "D:\python3\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### To Reproduce

in the describtion

### Expected behavior

It should have run the tts server and told me what port it's listening on like usual

### Environment

```shell
tts 0.11.1, miniconda.python 3.10, no GPU, automatic torch installation that happened automatically when I did pip install tts, windows 10x64
```

**Comment by king-dahmanus** [comment]
Can You Please help guys? When I updated the tts installation in my normal python environment, which worked well before update, it too gave me the same error. I'm not sure, maybe it could be an error with the model itself since it's 952 megabites and only at step 6000

**Comment by king-dahmanus** [comment]
and the pretrained vits model from tts 0.8.0 is only 138mb. Why is that the case? The dataset used to train the model is a subset of mailabs.
