### ISSUE TITLE
[Bug] RuntimeError: stft requires the return_complex parameter be given for real inputs

### ISSUE THREAD

**Issue by thoraxe** [coqui-ai/TTS#2449]
### Describe the bug

When trying to fine-tune YourTTS with an LJSpeech formatted dataset after computing the encodings, this error appears.

### To Reproduce

Run the your_tts recipe:
https://gist.github.com/thoraxe/d75d47990b5a07b2201ddeaebdb71362

### Expected behavior

Training should occur.

### Logs

```shell
Traceback (most recent call last):
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/trainer/trainer.py", line 1591, in fit
    self._fit()
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/trainer/trainer.py", line 1544, in _fit
    self.train_epoch()
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/trainer/trainer.py", line 1309, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/trainer/trainer.py", line 1126, in train_step
    batch = self.format_batch(batch)
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/trainer/trainer.py", line 926, in format_batch
    batch = self.model.format_batch_on_device(batch)
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/TTS/tts/models/vits.py", line 1503, in format_batch_on_device
    batch["spec"] = wav_to_spec(wav, ac.fft_size, ac.hop_length, ac.win_length, center=False)
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/TTS/tts/models/vits.py", line 123, in wav_to_spec
    spec = torch.stft(
  File "/home/thoraxe/.pyenv/versions/tts-310/lib/python3.10/site-packages/torch/functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3080"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu118",
        "TTS": "0.12.0",
        "numpy": "1.22.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.9",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

**Comment by pivolan** [comment]
one bad variant to fix by hardcode in local env:

nano /opt/conda/lib/python3.10/site-packages/torch/functional.py:

at line 641:

insert this before return statement:

```
    if not return_complex:
        return torch.view_as_real(_VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
                                           normalized, onesided, return_complex=True))

```

![image](https://user-images.githubusercontent.com/903550/227371868-6b50736d-bfa1-4a41-a4d1-5a1e72670297.png)

**Comment by samuel-larsson** [comment]
I am on the dev branch but I still get the error.  I'm running this on Colab so I'm not sure how to change the code as @pivolan  suggests above. The strange thing is that this started occuring between runs using the exact same dataset and parameters. The only difference is that I had a new runtime in Colab.


Error trace:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1591, in fit
    self._fit()
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1544, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1309, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1126, in train_step
    batch = self.format_batch(batch)
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 926, in format_batch
    batch = self.model.format_batch_on_device(batch)
  File "/usr/local/lib/python3.9/dist-packages/TTS/tts/models/vits.py", line 1503, in format_batch_on_device
    batch["spec"] = wav_to_spec(wav, ac.fft_size, ac.hop_length, ac.win_length, center=False)
  File "/usr/local/lib/python3.9/dist-packages/TTS/tts/models/vits.py", line 123, in wav_to_spec
    spec = torch.stft(
  File "/usr/local/lib/python3.9/dist-packages/torch/functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1591, in fit
    self._fit()
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1544, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1309, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1126, in train_step
    batch = self.format_batch(batch)
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 926, in format_batch
    batch = self.model.format_batch_on_device(batch)
  File "/usr/local/lib/python3.9/dist-packages/TTS/tts/models/vits.py", line 1503, in format_batch_on_device
    batch["spec"] = wav_to_spec(wav, ac.fft_size, ac.hop_length, ac.win_length, center=False)
  File "/usr/local/lib/python3.9/dist-packages/TTS/tts/models/vits.py", line 123, in wav_to_spec
    spec = torch.stft(
  File "/usr/local/lib/python3.9/dist-packages/torch/functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-b6cd7ba69c0e>", line 1, in <cell line: 1>
    trainer.fit()
  File "/usr/local/lib/python3.9/dist-packages/trainer/trainer.py", line 1612, in fit
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.9/inspect.py", line 1543, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/trainer/trainer.py](https://localhost:8080/#) in fit(self)
   1590         try:
-> 1591             self._fit()
   1592             if self.args.rank == 0:

16 frames
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

[/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py](https://localhost:8080/#) in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

**Comment by leenajenniferedwin** [comment]
Hi,

I have come across this same problem when trying to run the NVidiaQuartzNetMic.ipynb, tried fixing it by inserting this statement in my /usr/local/lib/python3.9/dist-packages/torch/functional.py at line 641, but it still gives the same error. Could you please help me.

[/usr/local/lib/python3.9/dist-packages/torch/functional.py](https://localhost:8080/#) in stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided, return_complex)
    639         input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
    640         input = input.view(input.shape[-signal_dim:])
--> 641     if not return_complex:
    642       return torch.view_as_real(_VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
    643                                            normalized, onesided, return_complex=True))

RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.

**Comment by offside609** [comment]
I have same issue in VITS model. But it comes as warning not a bug. But it leads to losses becoming Nan later and training interrupts.
https://github.com/coqui-ai/TTS/issues/2555

**Comment by QinHsiu** [comment]
I have the same problem, can anyone help me fix this problem?

**Comment by pivolan** [comment]
> I have the same problem, can anyone help me fix this problem?

as I tried some time ago, in the last version of coqui, this problem is already solved. But if you still have it, and use old version of coqui tts, try my method with changes in sources of torch library.

**Comment by Jasmijn888** [comment]
> one bad variant to fix by hardcode in local env:
> 
> nano /opt/conda/lib/python3.10/site-packages/torch/functional.py:
> 
> at line 641:
> 
> insert this before return statement:
> 
> ```
>     if not return_complex:
>         return torch.view_as_real(_VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
>                                            normalized, onesided, return_complex=True))
> ```
> 
> ![image](https://user-images.githubusercontent.com/903550/227371868-6b50736d-bfa1-4a41-a4d1-5a1e72670297.png)

it works for me. Thanks!

**Comment by eginhard** [comment]
This has also been fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by Snailgoo** [comment]
> one bad variant to fix by hardcode in local env:
> 
> nano /opt/conda/lib/python3.10/site-packages/torch/functional.py:
> 
> at line 641:
> 
> insert this before return statement:
> 
> ```
>     if not return_complex:
>         return torch.view_as_real(_VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
>                                            normalized, onesided, return_complex=True))
> ```
> 
> ![image](https://user-images.githubusercontent.com/903550/227371868-6b50736d-bfa1-4a41-a4d1-5a1e72670297.png)

**Traceback (most recent call last):
File "/D2Former/evaluation.py", line 102, in
evaluation(args.model_path, noisy_dir, clean_dir, args.save_tracks, args.save_dir, out_file)
File "/D2Former/evaluation.py", line 72, in evaluation
est_audio, length = enhance_one_track(model, noisy_path, saved_dir, 16000*8, n_fft, n_fft//4, save_tracks)
File "/py310_audio/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/D2Former/evaluation.py", line 42, in enhance_one_track
est_audio = torch.istft(est_spec_uncompress, n_fft, hop, window=torch.hamming_window(n_fft).cuda(),
RuntimeError: istft requires a complex-valued input tensor matching the output from stft with return_complex=True.**
