### ISSUE TITLE
[Bug] Voice conversion converting speaker of the `source_wav` to the speaker of the `target_wav`

### ISSUE THREAD

**Issue by ziyaad30** [coqui-ai/TTS#2493]
### Describe the bug

```
tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=False, gpu=True)
tts.voice_conversion_to_file(source_wav="my/source.wav", target_wav="my/target.wav", file_path="output.wav")

```

```
(coqui) C:\Users\User\Desktop\coqui\TTS>python test.py
 > voice_conversion_models/multilingual/vctk/freevc24 is already downloaded.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=False, gpu=True)
  File "C:\Users\User\Desktop\coqui\TTS\TTS\api.py", line 277, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "C:\Users\User\Desktop\coqui\TTS\TTS\api.py", line 368, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "C:\Users\User\Desktop\coqui\TTS\TTS\utils\synthesizer.py", line 86, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "C:\Users\User\Desktop\coqui\TTS\TTS\utils\synthesizer.py", line 145, in _load_tts
    if self.tts_config["use_phonemes"] and self.tts_config["phonemizer"] is None:
  File "C:\Users\User\anaconda3\envs\coqui\lib\site-packages\coqpit\coqpit.py", line 614, in __getitem__
    return self.__dict__[arg]
KeyError: 'use_phonemes'
```

### Environment

```shell
TTS Version 0.13.0
```

**Comment by erogol** [comment]
https://github.com/coqui-ai/TTS/pull/2495 fixes it

**Comment by nateraw** [comment]
Hey @erogol that PR doesn't fix this issue

**Comment by erogol** [comment]
@nateraw the same code above works on my side with the PR
