### ISSUE TITLE
[Bug] Missing Logic for Trained Model Prediction

### ISSUE THREAD

**Issue by VArdulov** [coqui-ai/TTS#2501]
### Describe the bug

I discovered this bug, that exists when you try to use a custom trained model that since `self.model_name` is None in those cases this will raise an error when you call `tts_model.tt

some code to recreate the bug:
```
from TTS.api import TTS
custom_model = TTS(
     model_path="/home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC/model_file.pth",
     config_path="/home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC/config.json"
)
custom_model.tts("This is a test!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/TTS/TTS/api.py", line 507, in tts
    self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, emotion=emotion, speed=speed)
  File "/home/ubuntu/TTS/TTS/api.py", line 414, in _check_arguments
    if not self.is_coqui_studio:
  File "/home/ubuntu/TTS/TTS/api.py", line 296, in is_coqui_studio
    return "coqui_studio" in self.model_name
TypeError: argument of type 'NoneType' is not iterable
```

Since the initialization logic would fail if I passed an intermediate model name in the `TTS` constructor, a intermediate solution is to use add:
```
custom_model.model_name = "custom-model"
``` 

but I recommend adding some logic to the `is_coqui_studio` function to:
```
@property
def is_coqui_studio(self):
    if self.model_name:
        return "coqui_studio" in self.model_name
    return False
```

### To Reproduce

```
from TTS.api import TTS
custom_model = TTS(
     model_path="/home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC/model_file.pth",
     config_path="/home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC/config.json"
)
custom_model.tts("This is a test!")
```

### Environment

```shell
- Python3.9
- Ubuntu 20.04 
-
```

**Comment by VArdulov** [comment]
In retrospect perhaps more concise solution to this logic would be to add:
```
@property
def is_coqui_studio(self):
        return self.model_name and "coqui_studio" in self.model_name
```

This will return evaluated as False is `self.model_name` is None and won't raise the Error described. If this is in line with the Coqui-TTS functionality, I'd be happy to author the commit.

**Comment by erogol** [comment]
This should already be fixed
