### ISSUE TITLE
[Bug] SSL error when training is supposed to be resumed. EDIT: It effects whole training, even when starting a fresh one (not resuming)

### ISSUE THREAD

**Issue by Alienpups** [coqui-ai/TTS#2567]
### Describe the bug

Whenever I try to resume training my language model (VITs), I encounter an SSL or Requests error. Training ran smoothly for several weeks using the same command without any modifications, but now I am encountering an SSL or Requests error. It seems like something might not be running correctly with the Coqui TTS Gateway.

Error:
(TTS-Training) C:\TTS-Training>python train_vits.py --continue_path "vits_luise-voice-April-21-2023_05+38PM-0000000"
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 13644 files in C:\TTS-Training\luise_dataset
fatal: not a git repository (or any of the parent directories): .git
 > Training Environment:
 | > Num. of CPUs: 20
 | > Num. of Torch Threads: 12
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 > Start Tensorboard: tensorboard --logdir=vits_luise-voice-April-21-2023_05+38PM-0000000
 > Restoring from best_model_14843.pth ...
 > Restoring Model...
 > Restoring Optimizer...
 > Model restored from step 14843
C:\TTS-Training\lib\site-packages\torch\cuda\amp\grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")

 > Model has 83059180 parameters
Traceback (most recent call last):
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\TTS-Training\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\TTS-Training\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\TTS-Training\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TTS-Training\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\TTS-Training\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /trainer/training_run (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TTS-Training\train_vits.py", line 94, in <module>
    main()
  File "C:\TTS-Training\train_vits.py", line 80, in main
    trainer = Trainer(
  File "C:\TTS-Training\lib\site-packages\trainer\trainer.py", line 528, in __init__
    ping_training_run()
  File "C:\TTS-Training\lib\site-packages\trainer\analytics.py", line 12, in ping_training_run
    _ = requests.get(URL)
  File "C:\TTS-Training\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\adapters.py", line 518, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /trainer/training_run (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)')))

(TTS-Training) C:\TTS-Training>

### To Reproduce

1. Start cmd, activate virtual python environment
2. Resume training by using "python train_vits.py --continue_path "vits_luise-voice-April-21-2023_05+38PM-0000000"" in main directory
3. Training seems to be starting but will then throw an error

### Expected behavior

Resume training like in the past.

### Logs

```shell
(TTS-Training) C:\TTS-Training>python train_vits.py --continue_path "vits_luise-voice-April-21-2023_05+38PM-0000000"
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 13644 files in C:\TTS-Training\luise_dataset
fatal: not a git repository (or any of the parent directories): .git
 > Training Environment:
 | > Num. of CPUs: 20
 | > Num. of Torch Threads: 12
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 > Start Tensorboard: tensorboard --logdir=vits_luise-voice-April-21-2023_05+38PM-0000000
 > Restoring from best_model_14843.pth ...
 > Restoring Model...
 > Restoring Optimizer...
 > Model restored from step 14843
C:\TTS-Training\lib\site-packages\torch\cuda\amp\grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")

 > Model has 83059180 parameters
Traceback (most recent call last):
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\TTS-Training\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\TTS-Training\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\TTS-Training\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TTS-Training\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "C:\TTS-Training\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\TTS-Training\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /trainer/training_run (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TTS-Training\train_vits.py", line 94, in <module>
    main()
  File "C:\TTS-Training\train_vits.py", line 80, in main
    trainer = Trainer(
  File "C:\TTS-Training\lib\site-packages\trainer\trainer.py", line 528, in __init__
    ping_training_run()
  File "C:\TTS-Training\lib\site-packages\trainer\analytics.py", line 12, in ping_training_run
    _ = requests.get(URL)
  File "C:\TTS-Training\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\TTS-Training\lib\site-packages\requests\adapters.py", line 518, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /trainer/training_run (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1007)')))

(TTS-Training) C:\TTS-Training>
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cpu",
        "TTS": "0.13.3",
        "numpy": "1.23.5"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 151 Stepping 2, GenuineIntel",
        "python": "3.10.11",
        "version": "10.0.22624"
    }
}
```

**Comment by FrischJulien** [comment]
Add the following environment variable TRAINER_TELEMETRY=0
https://github.com/coqui-ai/Trainer#anonymized-telemetry

**Comment by erogol** [comment]
Fixed by now

**Comment by Alienpups** [comment]
> Add the following environment variable TRAINER_TELEMETRY=0 https://github.com/coqui-ai/Trainer#anonymized-telemetry

Can you elaborate on that? Where exactly do I have to paste this? In my train_vits.py?

**Comment by FrischJulien** [comment]
Sure, it is an environment variable that should be used when calling the script. Something like :
TRAINER_TELEMETRY=0 training_script.py

**Comment by FrischJulien** [comment]
In your case, try : 
python TRAINER_TELEMETRY=0 train_vits.py --continue_path "vits_luise-voice-April-21-2023_05+38PM-0000000"

**Comment by Alienpups** [comment]
Thank you for the quick help. It now works fine without using "TRAINER_TELEMETRY=0". Looks like it was something on their end only. But now I know how to handle that issue in the future, thanks again :)
