### ISSUE TITLE
[Bug] SSL Errors and Python Traceback Errors

### ISSUE THREAD

**Issue by alkaris2** [coqui-ai/TTS#2581]
### Describe the bug

When downloading a TTS model I'm receiving SSL Certificate errors, along with Python error traceback errors.

```PYTHON
$ tts --text "Text for TTS"

 > Downloading model to /home/xxxxxx/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /v0.6.1_models/tts_models--en--ljspeech--tacotron2-DDC.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxxxx/.local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/home/xxxxx/.local/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 337, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/TTS/utils/manage.py", line 275, in download_model
    self._download_zip_file(model_item["github_rls_url"], output_path, self.progress_bar)
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/TTS/utils/manage.py", line 390, in _download_zip_file
    r = requests.get(file_url, stream=True)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /v0.6.1_models/tts_models--en--ljspeech--tacotron2-DDC.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:997)')))
```

Attempting to run same command again then just returns the following;

```BASH
$ tts --text "Text for TTS"

 > tts_models/en/ljspeech/tacotron2-DDC is already downloaded.
Traceback (most recent call last):
  File "/home/xxxxxx/.local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 337, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/TTS/utils/manage.py", line 278, in download_model
    output_model_path, output_config_path = self._find_files(output_path)
  File "/home/xxxxxx/.local/lib/python3.10/site-packages/TTS/utils/manage.py", line 301, in _find_files
    raise ValueError(" [!] Model file not found in the output path")
ValueError:  [!] Model file not found in the output path
```

Even though it throws this other error stating model file not found in the output path, it created folders for the TTS voice models, but obviously because of the SSL Certificate Errors it doesn't actually download the voice models you requested. If there's actual URL where these voice models are downloaded from I could just manually download and place them in the directory and should work, but since it doesn't state where it's downloading from, can't do just that to get around the SSL Certificate Error.

### To Reproduce

n/a

### Logs

```shell
n/a
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3070"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu117",
        "TTS": "0.13.3",
        "numpy": "1.23.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.10.9",
        "version": "#1 SMP PREEMPT Mon Mar 13 11:02:38 UTC 2023"
    }
}
```

### Additional context

If attempting to download a different voice model and vocoder, it also fails with same errors as above.

**Comment by erogol** [comment]
fixed by now. reopen if not

**Comment by Amith5970** [comment]
How this error got fixed? I too getting the same error
