### ISSUE TITLE
[Bug] TTS loads a corrupted model instead of redownloading 

### ISSUE THREAD

**Issue by adrianboguszewski** [coqui-ai/TTS#2590]
### Describe the bug

If I interrupt model downloading and rerun the code, the corrupted model will be loaded instead of re-downloading. In that case, I need to find the cached file on the disk myself and delete it.

### To Reproduce

1. Run `tts = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", progress_bar=True, gpu=False)`
2. Interrupt when downloading
3. Rerun above code
4. See the error

### Expected behavior

The correct behavior would be re-downloading the model if a hash is different than expected for that model.

### Logs

```shell
Traceback (most recent call last):
  File "/home/adrian/PycharmProjects/pythonProject/tts.py", line 6, in <module>
    tts = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", progress_bar=False, gpu=False)
  File "/home/adrian/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/TTS/api.py", line 54, in __init__
    self.load_model_by_name(model_name, gpu)
  File "/home/adrian/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/TTS/api.py", line 114, in load_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path = self.download_model_by_name(model_name)
  File "/home/adrian/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/TTS/api.py", line 98, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "/home/adrian/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/TTS/utils/manage.py", line 248, in download_model
    output_model_path, output_config_path = self._find_files(output_path)
  File "/home/adrian/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/TTS/utils/manage.py", line 271, in _find_files
    raise ValueError(" [!] Model file not found in the output path")
ValueError:  [!] Model file not found in the output path
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060 Laptop GPU"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu117",
        "TTS": "0.12.0",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.16",
        "version": "#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2"
    }
}
```

**Comment by adrianboguszewski** [comment]
@erogol, I know that the cache folder should be deleted. I'm just suggesting that it would be nice to redownload it automatically if hashes don't equal each other.

**Comment by erogol** [comment]
that makes sense. I'll take a look

**Comment by trientran** [comment]
Can you please clarify where the cache folder is located?. Thanks
