### ISSUE TITLE
[Bug] loading a self trained multi-speaker vits model with server.py doesnt seems to work

### ISSUE THREAD

**Issue by KukumavMozolo** [coqui-ai/TTS#2645]
### Describe the bug

After training a model using `recipes/multilingual/vits_tts/train_vits_tts.py`
i tried starting a server wit the following command:
```
--model_path .../vits_vctk-May-30-2023_11+17PM-23a7a9a3/checkpoint_130000.pth --config_path .../vits_tts/test.json --speakers_file_path .../vits_vctk-May-30-2023_11+17PM-23a7a9a3/speakers.pth
```

The server starts and I can access the interface at `http://localhost:5002/`
However when I try to get a translation the following error is thrown:

```

 > Model input: It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.
 > Speaker Idx: 0
 > Language Idx: 
 > Text splitted to sentences.
["It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."]
ERROR:server:Exception on /api/tts [GET]
Traceback (most recent call last):
  File ".../TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File ".../TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../virtualenvs/TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File ".../TTS/TTS/server/server.py", line 199, in tts
    wavs = synthesizer.tts(text, speaker_name=speaker_idx, language_name=language_idx, style_wav=style_wav)
  File ".../TTS/TTS/utils/synthesizer.py", line 280, in tts
    if len(self.tts_model.speaker_manager.name_to_id) == 1:
AttributeError: 'NoneType' object has no attribute 'name_to_id'
INFO:werkzeug:::ffff:127.0.0.1 - - [31/May/2023 18:12:50] "GET /api/tts?text=It%20took%20me%20quite%20a%20long%20time%20to%20develop%20a%20voice,%20and%20now%20that%20I%20have%20it%20I'm%20not%20going%20to%20be%20silent.&speaker_id=0&style_wav=&language_id= HTTP/1.1" 500 -


```

Looking at the server script `TTS/server/server.py:`

```

synthesizer = Synthesizer(
    tts_checkpoint=model_path,
    tts_config_path=config_path,
    tts_speakers_file=speakers_file_path,
    tts_languages_file=None,
    vocoder_checkpoint=vocoder_path,
    vocoder_config=vocoder_config_path,
    encoder_checkpoint="",
    encoder_config="",
    use_cuda=args.use_cuda,
)

use_multi_speaker = hasattr(synthesizer.tts_model, "num_speakers") and (
    synthesizer.tts_model.num_speakers > 1 or synthesizer.tts_speakers_file is not None
)
speaker_manager = getattr(synthesizer.tts_model, "speaker_manager", None)

```

The encoder_checkpoint is left empty, also `recipes/multilingual/vits_tts/train_vits_tts.py` doesnt seem to create any files SpeakerManager related files except `speakers.pth`, how is that supposed to work?

### To Reproduce

Train a model using  `recipes/multilingual/vits_tts/train_vits_tts.py`
Try to start a sever as described above

### Expected behavior

The server allows to translate text2speech on http://localhost:5002/

### Logs

```shell
> Model input: It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.
 > Speaker Idx: 0
 > Language Idx: 
 > Text splitted to sentences.
["It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent."]
ERROR:server:Exception on /api/tts [GET]
Traceback (most recent call last):
  File ".../TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File ".../TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../virtualenvs/TTS-69Acq6UT/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File ".../TTS/TTS/server/server.py", line 199, in tts
    wavs = synthesizer.tts(text, speaker_name=speaker_idx, language_name=language_idx, style_wav=style_wav)
  File ".../TTS/TTS/utils/synthesizer.py", line 280, in tts
    if len(self.tts_model.speaker_manager.name_to_id) == 1:
AttributeError: 'NoneType' object has no attribute 'name_to_id'
INFO:werkzeug:::ffff:127.0.0.1 - - [31/May/2023 18:12:50] "GET /api/tts?text=It%20took%20me%20quite%20a%20long%20time%20to%20develop%20a%20voice,%20and%20now%20that%20I%20have%20it%20I'm%20not%20going%20to%20be%20silent.&speaker_id=0&style_wav=&language_id= HTTP/1.1" 500 -


```
```


### Environment

```shell
TTS Version, dev-branch
```

**Comment by KukumavMozolo** [comment]
I think i get the same or related problem when using 

```

model_path = "...vits_vctk-May-30-2023_11+17PM-23a7a9a3/checkpoint_130000.pth"
config_path = "...vits_vctk-May-30-2023_11+17PM-23a7a9a3/config.json"
tts = TTS(model_path=model_path, config_path=config_path, progress_bar=False, gpu=False)

tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.", speaker=tts.speakers[0], language=tts.languages[0], file_path="output.wav")

```

Since `tts.speakers` is not initialized

**Comment by KukumavMozolo** [comment]
I changed server.py as follows to get around this problem(hacky):

```

# speaker_manager = getattr(synthesizer.tts_model, "speaker_manager", None)
speaker_manager = SpeakerManager()
speaker_manager.load_ids_from_file(speakers_file_path)
synthesizer.speaker_manager = speaker_manager
synthesizer.tts_model.speaker_manager = speaker_manager

```

**Comment by erogol** [comment]
we haven't touched the server for a while. I am actually surprised that it still works :). I plan to deprecate the current implementation and use Gradio based on the TTS API. For now, it is open for help.

**Comment by MaxIakovliev** [comment]
It should work.
Here is how I'm doing it:

`
python3 TTS/bin/synthesize.py --text "Are we still connected? I cant hear you" \
    --model_path "/root/tts_volume/male_001_ad/male_001_ad-June-04-2023_11+10PM-0000000/checkpoint_1130000/checkpoint_1130000.pth" \
    --config_path "/root/tts_volume/male_001_ad/male_001_ad-June-04-2023_11+10PM-0000000/checkpoint_1130000/config.json" \
    --target_wav /root/tts_volume/male_001_ad_checkpoint_1130000_003.wav > /root/tts_volume/male_001_ad_checkpoint_1130000_003.log
`

**Comment by Muhammad-Ali-Saqib** [comment]
I was doing
```
script  = 'hello this is the test audio.'
wav, alignment, _, _ = synthesis(model, script, C, "cuda" in str(next(model.parameters()).device), speaker_id=None, d_vector=target_emb, language_id=0).values()
```
and the error was 
```
AttributeError: 'NoneType' object has no attribute 'name_to_id'
```
I have resolved that by setting `language_id=None` the show command will be 
```
wav, alignment, _, _ = synthesis(model, script, C, "cuda" in str(next(model.parameters()).device), speaker_id=None, d_vector=target_emb, language_id=None).values()
```

you can get the generated audio by 
```
file_name = "inference/generative_audio.wav"
ap.save_wav(wav, file_name)
```
