### ISSUE TITLE
[Bug] Tokenizer decode and ids_to_text KeyError resulted from improper handling of <BOS> and <EOS>

### ISSUE THREAD

**Issue by 46319943** [coqui-ai/TTS#2670]
### Describe the bug

While calling `text_to_ids` function in tokenizer, the tokenizer will add `<BOS>` and `<EOS>` to the head and tail of the text if `use_eos_bos` enabled.
```python
# line 114 in tokenizer.py
...
if self.use_eos_bos:
    text = self.pad_with_bos_eos(text)
...
```

If `bos` and `eos` are not provided in the `characters`, the `characters` will map `bos_id` and `eos_id` to the length of `vocab`
```python
# line 71 in characters.py
@property
def bos_id(self) -> int:
    """Return the index of the bos character. If the bos character is not specified, return the length of the
    vocabulary."""
    return self.char_to_id(self.bos) if self.bos else len(self.vocab)
```

However, while decoing and making call to the `ids_to_text` function, the id of bos and eos will not be recognized as they are out of the `vocab`.

```python
>>> tokenizer.text_to_ids('test')
[192, 111, 79, 141, 111, 192]

>>> tokenizer.ids_to_text([192, 111, 79, 141, 111, 192])
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Document\Maperson\TTS\TTS\tts\utils\text\tokenizer.py", line 120, in ids_to_text
    return self.decode(id_sequence)
  File "C:\Document\Maperson\TTS\TTS\tts\utils\text\tokenizer.py", line 84, in decode
    text += self.characters.id_to_char(token_id)
  File "C:\Document\Maperson\TTS\TTS\tts\utils\text\characters.py", line 305, in id_to_char
    try:
KeyError: 192
```

Maybe additional process involving the bos and eos shoule be added to the `id_to_char` function in the `characters.py`

### To Reproduce

```python
# with `enable_eos_bos_chars` set true and eos=None, bos=None
>>> tokenizer.text_to_ids('test')
[192, 111, 79, 141, 111, 192]

>>> tokenizer.ids_to_text([192, 111, 79, 141, 111, 192])
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Document\Maperson\TTS\TTS\tts\utils\text\tokenizer.py", line 120, in ids_to_text
    return self.decode(id_sequence)
  File "C:\Document\Maperson\TTS\TTS\tts\utils\text\tokenizer.py", line 84, in decode
    text += self.characters.id_to_char(token_id)
  File "C:\Document\Maperson\TTS\TTS\tts\utils\text\characters.py", line 305, in id_to_char
    try:
KeyError: 192
```

### Environment

```shell
- TTS Version: commit d658194
```

**Comment by erogol** [comment]
Thanks for flagging it. It is definitely a bug. Can you send a PR with you proposed solution?

**Comment by 46319943** [comment]
> Thanks for flagging it. It is definitely a bug. Can you send a PR with you proposed solution?

Of course. Actually, the solution has already been submitted in https://github.com/coqui-ai/TTS/pull/2671

**Comment by erogol** [comment]
Ok I'll follow up there...
