### ISSUE TITLE
[Bug] RuntimeError: The following operation failed in the TorchScript interpreter.

### ISSUE THREAD

**Issue by siddas27** [coqui-ai/TTS#2684]
### Describe the bug

Getting runtime errors while trying to train VITS model on a custom dataset of size more than 200 data points. Surprisingly, if dataset size is less than 200, training runs fine.  

I tried setting max_split_size_mb and decreasing the batch size but nothing solves the issue.

### To Reproduce

```
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:1024"
# Trainer: Where the ✨️ happens.
# TrainingArgs: Defines the set of arguments of the Trainer.
from trainer import Trainer, TrainerArgs

from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.models.vits import Vits, VitsAudioConfig
# BaseDatasetConfig: defines name, formatter and path of the dataset.


from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

from TTS.tts.configs.shared_configs import BaseDatasetConfig,BaseAudioConfig,CharactersConfig
#from TTS.configs import BaseDatasetConfig,BaseAudioConfig,CharactersConfig#GlowTTSConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.utils.speakers import SpeakerManager

from TTS.config import load_config

pretrained = False
pretrained_path = ''

meta_file = 'all_dataset.csv' #'narir_neeti.csv'
root_path = 'data/all_dataset'


dataset_config = BaseDatasetConfig(
     meta_file_train=meta_file, path=os.path.join(root_path, "")
)

train_samples, eval_samples = load_tts_samples(dataset_config,formatter=formatter, eval_split=True, eval_split_size=0.1)

output_path = 'output'


audio_config = VitsAudioConfig(
    sample_rate=22050, win_length=1024, hop_length=256, num_mels=80, mel_fmin=0, mel_fmax=None
)


characters_config = CharactersConfig(
  pad = '<PAD>',
  eos = '<EOS>',
  bos = '<BOS>',# None,
  blank = '<BLNK>',
  phonemes = None,
  characters =  "ঀঁংঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ঽৎৗড়ঢ়য়ৠৡৢৣ০১২৩৪৫৬৭৮৯ৰৱ৲৳৴৵৶৷৸৹৺৻\u200c",
  punctuations = "—-–,।|!¡'().:;¿? ‘’",
)

config = VitsConfig(
    audio=audio_config,
    run_name="own_model",
    batch_size=8,
    batch_group_size=0,
    num_loader_workers=4,
    run_eval=False,
    test_delay_epochs=-1,
    epochs=15000,
    text_cleaner=None, #"collapse_whitespace"
    use_phonemes=False,
    compute_input_seq_cache=True,
    print_step=50,
    print_eval=False,
    mixed_precision=True,
    output_path=output_path,
    datasets=[dataset_config],
    characters = characters_config,
    save_step=1000,
    cudnn_benchmark=True,
)

ap = AudioProcessor.init_from_config(config)
ap.resample

tokenizer, config = TTSTokenizer.init_from_config(config)
model = Vits(config, ap, tokenizer, speaker_manager=None)
trainer = Trainer(
    TrainerArgs(continue_path = pretrained_path), config, output_path, model=model, train_samples=train_samples, eval_samples=eval_samples
)

trainer.fit()

```

### Logs

```shell
> Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 > Training Environment:
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 4
 | > Num. of Torch Threads: 4
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: True
 > Start Tensorboard: tensorboard --logdir=output/own_model-June-18-2023_02+27PM-0000000

 > Model has 83056492 parameters

 > EPOCH: 0/15000
 --> output/own_model-June-18-2023_02+27PM-0000000


> DataLoader initialization
| > Tokenizer:
        | > add_blank: True
        | > use_eos_bos: False
        | > use_phonemes: False
| > Number of instances : 564
 | > Preprocessing samples
 | > Max text length: 210
 | > Min text length: 15
 | > Avg text length: 69.81028368794327
 | 
 | > Max audio length: 28177650.0
 | > Min audio length: 34641.0
 | > Avg audio length: 213723.24822695035
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.

 > TRAINING (2023-06-18 14:27:30) 
/home/user/venv/lib/python3.10/site-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/user/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py:309: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv1d(input, weight, bias, self.stride,

   --> STEP: 0/71 -- GLOBAL_STEP: 0
     | > loss_disc: 5.91148  (5.91148)
     | > loss_disc_real_0: 0.98131  (0.98131)
     | > loss_disc_real_1: 0.97515  (0.97515)
     | > loss_disc_real_2: 0.97682  (0.97682)
     | > loss_disc_real_3: 0.96805  (0.96805)
     | > loss_disc_real_4: 1.02368  (1.02368)
     | > loss_disc_real_5: 0.98561  (0.98561)
     | > loss_0: 5.91148  (5.91148)
     | > grad_norm_0: 0.00000  (0.00000)
     | > loss_gen: 5.90853  (5.90853)
     | > loss_kl: 164.97803  (164.97803)
     | > loss_feat: 0.37497  (0.37497)
     | > loss_mel: 91.95757  (91.95757)
     | > loss_duration: 1.87205  (1.87205)
     | > amp_scaler: 32768.00000  (32768.00000)
     | > loss_1: 265.09116  (265.09116)
     | > grad_norm_1: 0.00000  (0.00000)
     | > current_lr_0: 0.00020 
     | > current_lr_1: 0.00020 
     | > step_time: 5.45690  (5.45693)
     | > loader_time: 1.62180  (1.62178)


   --> STEP: 50/71 -- GLOBAL_STEP: 50
     | > loss_disc: 2.77858  (3.08638)
     | > loss_disc_real_0: 0.24604  (0.29116)
     | > loss_disc_real_1: 0.28361  (0.29299)
     | > loss_disc_real_2: 0.29806  (0.29477)
     | > loss_disc_real_3: 0.33682  (0.29522)
     | > loss_disc_real_4: 0.26197  (0.30612)
     | > loss_disc_real_5: 0.29136  (0.30274)
     | > loss_0: 2.77858  (3.08638)
     | > grad_norm_0: 4.91631  (7.73643)
     | > loss_gen: 1.64691  (1.93434)
     | > loss_kl: 3.31923  (28.07552)
     | > loss_feat: 1.34948  (1.09513)
     | > loss_mel: 44.38672  (61.37371)
     | > loss_duration: 2.24268  (2.13923)
     | > amp_scaler: 256.00000  (1203.20000)
     | > loss_1: 52.94501  (94.61792)
     | > grad_norm_1: 229.76118  (179.64922)
     | > current_lr_0: 0.00020 
     | > current_lr_1: 0.00020 
     | > step_time: 0.92490  (0.82931)
     | > loader_time: 0.00570  (0.00590)

/home/user/venv/lib/python3.10/site-packages/TTS/tts/layers/generic/wavenet.py:107: UserWarning: FALLBACK path has been taken inside: runCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
 (Triggered internally at ../third_party/nvfuser/csrc/manager.cpp:335.)
  acts = fused_add_tanh_sigmoid_multiply(x_in, g_l, n_channels_tensor)
 ! Run is removed from output/own_model-June-18-2023_02+27PM-0000000
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.10/site-packages/trainer/trainer.py", line 1591, in fit
    self._fit()
  File "/home/user/venv/lib/python3.10/site-packages/trainer/trainer.py", line 1544, in _fit
    self.train_epoch()
  File "/home/user/venv/lib/python3.10/site-packages/trainer/trainer.py", line 1309, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/home/user/venv/lib/python3.10/site-packages/trainer/trainer.py", line 1162, in train_step
    outputs, loss_dict_new, step_time = self._optimize(
  File "/home/user/venv/lib/python3.10/site-packages/trainer/trainer.py", line 1023, in _optimize
    outputs, loss_dict = self._model_train_step(batch, model, criterion, optimizer_idx=optimizer_idx)
  File "/home/user/venv/lib/python3.10/site-packages/trainer/trainer.py", line 970, in _model_train_step
    return model.train_step(*input_args)
  File "/home/user/venv/lib/python3.10/site-packages/TTS/tts/models/vits.py", line 1255, in train_step
    outputs = self.forward(
  File "/home/user/venv/lib/python3.10/site-packages/TTS/tts/models/vits.py", line 1021, in forward
    z, m_q, logs_q, y_mask = self.posterior_encoder(y, y_lengths, g=g)
  File "/home/user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/TTS/tts/layers/vits/networks.py", line 284, in forward
    x = self.enc(x, x_mask, g=g)
  File "/home/user/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/TTS/tts/layers/generic/wavenet.py", line 107, in forward
    acts = fused_add_tanh_sigmoid_multiply(x_in, g_l, n_channels_tensor)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA out of memory. Tried to allocate 646.00 MiB (GPU 0; 15.73 GiB total capacity; 11.41 GiB already allocated; 27.12 MiB free; 14.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Environment

```shell
- 🐸TTS Version: 0.14.3
- PyTorch Version:2.0.1+cu118
- Python version:3.10
- OS (e.g., Linux): Ubuntu 22.04
- CUDA/cuDNN version:12.0
- GPU models and configuration: NVIDIA RTX A4000 16GB
- Installed PyTorch: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by erogol** [comment]
It is not a bug. You just need more VRAM or smaller batch size to train the model
