### ISSUE TITLE
[Bug]  Clone the vocie from prompt to speech by YourTTS is unavailable 

### ISSUE THREAD

**Issue by ggbangyes** [coqui-ai/TTS#2691]
### Describe the bug

Fail to clone the voice from a prompt .wav file to the speech .wav file. 
Because the model is unavailable anymore. When I enter the link of model ( > Error: Bad zip file - **https://coqui.gateway.scarf.sh/v0.10.1_models/tts_models--multilingual--multi-dataset--your_tts.zip** )
It displays nothing. 

### To Reproduce

from TTS.api import TTS

# Example voice cloning with YourTTS in English, French and Portuguese

tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=True, gpu=True)
tts.tts_to_file("This is voice cloning.", speaker_wav="prompts/prompt_Raymond_6s.wav", language="en", file_path="output.wav")

### Expected behavior

to generate a .wav file 

### Logs

```shell
> Downloading model to /home/hb/.local/share/tts/tts_models--multilingual--multi-dataset--your_tts
  0%|                                               | 0.00/29.0 [00:00<?, ?iB/s] > Error: Bad zip file - https://coqui.gateway.scarf.sh/v0.10.1_models/tts_models--multilingual--multi-dataset--your_tts.zip
Traceback (most recent call last):
  File "/hdd/haoran_project/YourTTS/TTS/utils/manage.py", line 434, in _download_zip_file
    with zipfile.ZipFile(temp_zip_name) as z:
  File "/home/qw/anaconda3/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/home/qw/anaconda3/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hdd/haoran_project/YourTTS/generate_voice.py", line 9, in <module>
    tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=True, gpu=True)
  File "/hdd/haoran_project/YourTTS/TTS/api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/hdd/haoran_project/YourTTS/TTS/api.py", line 385, in load_tts_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(
  File "/hdd/haoran_project/YourTTS/TTS/api.py", line 348, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "/hdd/haoran_project/YourTTS/TTS/utils/manage.py", line 303, in download_model
    self._download_zip_file(model_item["github_rls_url"], output_path, self.progress_bar)
  File "/hdd/haoran_project/YourTTS/TTS/utils/manage.py", line 439, in _download_zip_file
    raise zipfile.BadZipFile  # pylint: disable=raise-missing-from
zipfile.BadZipFile
100%|█████████████████████████████████████████| 29.0/29.0 [00:00<00:00, 114iB/s]

****** when I run same code again ****

 > tts_models/multilingual/multi-dataset/your_tts is already downloaded.
Traceback (most recent call last):
  File "/hdd/haoran_project/YourTTS/generate_voice.py", line 9, in <module>
    tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=True, gpu=True)
  File "/hdd/haoran_project/YourTTS/TTS/api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/hdd/haoran_project/YourTTS/TTS/api.py", line 385, in load_tts_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(
  File "/hdd/haoran_project/YourTTS/TTS/api.py", line 348, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "/hdd/haoran_project/YourTTS/TTS/utils/manage.py", line 309, in download_model
    output_model_path, output_config_path = self._find_files(output_path)
  File "/hdd/haoran_project/YourTTS/TTS/utils/manage.py", line 332, in _find_files
    raise ValueError(" [!] Model file not found in the output path")
ValueError:  [!] Model file not found in the output path
```

### Environment

```shell
"CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.14.3",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.13",
        "version": "#161~18.04.1-Ubuntu SMP Fri Feb 10 15:55:22 UTC 2023"
    }
}
```

**Comment by Edresson** [comment]
Hi, could you please try again? I think we have some issues with our servers. Now for me, it is working.

**Comment by ggbangyes** [comment]
> Hi, could you please try again? I think we have some issues with our servers. Now for me, it is working.

Thank you! I just try on it, the model is available now!
