### ISSUE TITLE
[Bug] the latest docker images cannot handle "tts_models/multilingual/multi-dataset/your_tts" model.

### ISSUE THREAD

**Issue by taesuklee** [coqui-ai/TTS#2704]
### Describe the bug

Both CPU version and GPU version docker images cannot handle the "tts_models/multilingual/multi-dataset/your_tts" model while voice cloning operation.

### To Reproduce

1. Run the following command `sudo docker run --rm --gpus all -v ~/tts-output:/root/tts-output ghcr.io/coqui-ai/tts --model_name "tts_models/multilingual/multi-dataset/your_tts" --language_idx en  --speaker_wav "voices/ex.wav"  --text "Hello hello hi hi." --out_path /root/tts-output/hello.wav --use_cuda true`
2. see error 
```
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/root/TTS/bin/synthesize.py", line 359, in main
 > Model's license - CC BY-NC-ND 4.0
 > Check https://creativecommons.org/licenses/by-nc-nd/4.0/ for more info.
    if model_item["author"] == "fairseq" or isinstance(model_item["github_rls_url"], list):
KeyError: 'author'
```

### Expected behavior

The voice cloning operation goes through.

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3070 Ti"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.14.3",
        "numpy": "1.23.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.10",
        "version": "#46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20"
    }
}
```

**Comment by erogol** [comment]
fixed by now
