### ISSUE TITLE
[Bug] Model download error

### ISSUE THREAD

**Issue by yingshaoxo** [coqui-ai/TTS#2709]
### Describe the bug

If you cut off the network when download the second model, it will always print out error.

```bash
 > Downloading model to /home/yingshaoxo/.local/share/tts/tts_models--en--ljspeech--fast_pitch
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 458M/458M [04:24<00:00, 1.73MiB/s]
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
 > Downloading model to /home/yingshaoxo/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2
Traceback (most recent call last):
  File "/home/yingshaoxo/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yingshaoxo/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/yingshaoxo/anaconda3/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

```bash
Exception has occurred: ValueError
 [!] Model file not found in the output path
  File "/home/yingshaoxo/CS/ML/17.text_to_speech/main.py", line 11, in <module>
    tts = TTS("tts_models/en/ljspeech/fast_pitch")
ValueError:  [!] Model file not found in the output path
```

### To Reproduce

```python
#pip install TTS
#pip install pydub
from TTS.api import TTS
from pprint import pprint

from pydub import AudioSegment
from pydub.playback import play

tts = TTS("tts_models/en/ljspeech/fast_pitch")

wav = tts.tts("Hello, yingshaoxo! This is a test!", speaker=tts.speakers[0], language=tts.languages[0])
tts.tts_to_file(text="Hello world!", speaker=tts.speakers[0], language=tts.languages[0], file_path="output.wav")

audio = AudioSegment.from_wav("output.wav")
play(audio)
```

> Cut off network when download the second model, then restart the program.

### Environment

```shell
(base) yingshaoxo@pop-os:~/CS/ML$ pip show TTS
Name: TTS
Version: 0.14.3
```

```
(base) yingshaoxo@pop-os:~/CS/ML$ python --version
Python 3.10.9
```

```
(base) yingshaoxo@pop-os:~/CS/ML$ uname -a
Linux pop-os 6.2.6-76060206-generic #202303130630~1679424972~22.04~4a8cde1 SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux
```
```


### Additional context

_No response_

**Comment by erogol** [comment]
Looks like a temporary hiccup. Models downloads correctly now. However, Fastpicthc is not a multi speaker model. So you will have an error calling ```tts.speakers```
