### ISSUE TITLE
[Bug] Config for bark cannot be found

### ISSUE THREAD

**Issue by JLPiper** [coqui-ai/TTS#2744]
### Describe the bug

Attempting to use Bark through TTS API [Using tts = TTS("tts_models/multilingual/multi-dataset/bark"] throws the following error.
```
Traceback (most recent call last):
  File "c:\Users\timeb\Desktop\BarkAI\Clone and Product TTS.py", line 7, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/bark")
  File "C:\Users\timeb\AppData\Local\Programs\Python\Python39\lib\site-packages\TTS\api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "C:\Users\timeb\AppData\Local\Programs\Python\Python39\lib\site-packages\TTS\api.py", line 391, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "C:\Users\timeb\AppData\Local\Programs\Python\Python39\lib\site-packages\TTS\utils\synthesizer.py", line 107, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "C:\Users\timeb\AppData\Local\Programs\Python\Python39\lib\site-packages\TTS\utils\synthesizer.py", line 159, in _load_tts_from_dir
    config = load_config(os.path.join(model_dir, "config.json"))
  File "C:\Users\timeb\AppData\Local\Programs\Python\Python39\lib\site-packages\TTS\config\__init__.py", line 94, in load_config
    config_class = register_config(model_name.lower())
  File "C:\Users\timeb\AppData\Local\Programs\Python\Python39\lib\site-packages\TTS\config\__init__.py", line 47, in register_config
    raise ModuleNotFoundError(f" [!] Config for {model_name} cannot be found.")
ModuleNotFoundError:  [!] Config for bark cannot be found.
```
I know of one other bug report on the issue #2722. However that was supposedly fixed in 0.15.2.

### To Reproduce

Run the following example code:

```
from TTS.api import TTS

# Load the model to GPU
# Bark is really slow on CPU, so we recommend using GPU.
tts = TTS("tts_models/multilingual/multi-dataset/bark")

# Cloning a new speaker
# This expects to find a mp3 or wav file like `bark_voices/new_speaker/speaker.wav`
# It computes the cloning values and stores in `bark_voices/new_speaker/speaker.npz`
tts.tts_to_file(text="Hello, how are you?",
                file_path="output.wav",
                voice_dir="bark_voices/",
                speaker="anna")


# When you run it again it uses the stored values to generate the voice.
tts.tts_to_file(text="Hello, how are you?",
                file_path="output.wav",
                voice_dir="bark_voices/",
                speaker="anna")
```

### Expected behavior

Produce output.wav using Bark.

### Environment

```shell
-OS: Windows
-Python Version: 3.9.13
-TTS Version: 0.15.5
-Using CPU Only
```

**Comment by erogol** [comment]
Can't replicate. Sample code works fine with 0.15.5

**Comment by Rentetier** [comment]
I have the same issue, I'm getting the error:
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/<myusername>/Library/Application Support/tts/tts_models--multilingual--multi-dataset--bark/config.json'

**Comment by erogol** [comment]
remove the folder try again.

**Comment by Rentetier** [comment]
Yes, now it's working. I believe the issue occurs when the download was aborted / failed, and then the we try to use the model at a later time. Then TTS assumes the model is there, because the folder is and some files are there, but the model file is incomplete and other files like the config are missing. I don't know if it would somehow be possible to check if the model is downloaded correctly and otherwise remove the folder and re-download.

**Comment by JLPiper** [comment]
> Yes, now it's working. I believe the issue occurs when the download was aborted / failed, and then the we try to use the model at a later time. Then TTS assumes the model is there, because the folder is and some files are there, but the model file is incomplete and other files like the config are missing. I don't know if it would somehow be possible to check if the model is downloaded correctly and otherwise remove the folder and re-download.

FYI: For those looking for a solution in the future, this turned out to be my issue as well. If you get this error, reinstalling the package entirely is the best option. Even if it seems like your download was stable and you see the correct files, something might have failed to download and you may not know.
