### ISSUE TITLE
[Bug] KeyError with Tortoise and custom speaker directory

### ISSUE THREAD

**Issue by tazz4843** [coqui-ai/TTS#2745]
### Describe the bug

The docs do not have proper documentation on how to run Tortoise. 

### To Reproduce

1. Download the following file and unzip it somewhere (contains sample files): 
[jfk.zip](https://github.com/coqui-ai/TTS/files/11974023/jfk.zip)

2. Run the following command or execute the following code (both exhibit the same result), replacing your voice directory as required.
```
tts --model_name  tts_models/en/multi-dataset/tortoise-v2 \
  --text "This is an example." \
  --out_path "output.wav" \
  --voice_dir /home/zero/data/audio-samples/ \
  --speaker_idx "jfk" \
  --progress_bar True
```
```py
from TTS.api import TTS

# Load the model
tortoise = TTS("tts_models/en/multi-dataset/tortoise-v2")
print(" - Loaded `tortoise`")

speaker = "jfk"
src_dir = "/home/zero/data/audio-samples/"
output_base = "/home/zero/data/audio-samples/{}/quick-brown-fox-{}.wav"
text_sample = "The quick brown fox jumps over the lazy dog."

tortoise.tts_to_file(text=text_sample,
                     file_path=output_base.format(speaker, "tortoise-ultra_fast"),
                     voice_dir=src_dir,
                     speaker=speaker,
                     preset="ultra_fast")
```

### Expected behavior

No KeyError exception.

### Logs

```shell
zero@zero-desktop ~/PycharmProjects/scripty-tts-server > tts --model_name  tts_models/en/multi-dataset/tortoise-v2 \
                                                             --text "This is an example." \
                                                             --out_path "output.wav" \
                                                             --voice_dir /home/zero/data/audio-samples/ \
                                                             --speaker_idx "jfk" \
                                                             --progress_bar True
 > tts_models/en/multi-dataset/tortoise-v2 is already downloaded.
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
 > Using model: tortoise
 > Text: This is an example.
 > Text splitted to sentences.
['This is an example.']
Traceback (most recent call last):
  File "/home/zero/PycharmProjects/scripty-tts-server/venv/bin/tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zero/PycharmProjects/scripty-tts-server/venv/lib/python3.11/site-packages/TTS/bin/synthesize.py", line 447, in main
    wav = synthesizer.tts(args.text, speaker_name=args.speaker_idx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/PycharmProjects/scripty-tts-server/venv/lib/python3.11/site-packages/TTS/utils/synthesizer.py", line 365, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/PycharmProjects/scripty-tts-server/venv/lib/python3.11/site-packages/TTS/tts/models/tortoise.py", line 520, in synthesize
    voice_samples, conditioning_latents = load_voice(speaker_id)
                                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/PycharmProjects/scripty-tts-server/venv/lib/python3.11/site-packages/TTS/tts/layers/tortoise/audio_utils.py", line 122, in load_voice
    paths = voices[voice]
            ~~~~~~^^^^^^^
KeyError: 'jfk'
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cpu",
        "TTS": "0.15.5",
        "numpy": "1.24.1"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.11.3",
        "version": "#1 SMP PREEMPT_DYNAMIC Sat, 01 Jul 2023 16:17:21 +0000"
    }
}
```

**Comment by manmay-nakhashi** [comment]
@tazz4843 does your voice dir have a folder called jfk ?

**Comment by tazz4843** [comment]
It does

**Comment by erogol** [comment]
@tazz4843 can you try https://github.com/coqui-ai/TTS/pull/2748

**Comment by tazz4843** [comment]
Seems to solve this issue, but I get a different, unrelated error now. I'll open a new issue for it.

**Comment by fyunusa** [comment]
hi, please i've been trying to locate the fix but i cant seem to figure out what you have as the proposed solution.
Can you please point me to it. Also having same issues here.
@erogol
