### ISSUE TITLE
[Bug] IndexError while training on Custom dataset with vctk_old format

### ISSUE THREAD

**Issue by wetdog** [coqui-ai/TTS#2784]
### Describe the bug

Training crashed after ~20k step.

```
Traceback (most recent call last):
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/trainer/trainer.py", line 1593, in fit
    self._fit()
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/trainer/trainer.py", line 1546, in _fit
    self.train_epoch()
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/trainer/trainer.py", line 1311, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/trainer/trainer.py", line 1164, in train_step
    outputs, loss_dict_new, step_time = self._optimize(
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/trainer/trainer.py", line 1025, in _optimize
    outputs, loss_dict = self._model_train_step(batch, model, criterion, optimizer_idx=optimizer_idx)
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/trainer/trainer.py", line 970, in _model_train_step
    return model.train_step(*input_args)
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/TTS/tts/models/vits.py", line 1255, in train_step
    outputs = self.forward(
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/TTS/tts/models/vits.py", line 1027, in forward
    outputs, attn = self.forward_mas(outputs, z_p, m_p, logs_p, x, x_mask, y_mask, g=g, lang_emb=lang_emb)
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/TTS/tts/models/vits.py", line 919, in forward_mas
    attn = maximum_path(logp, attn_mask.squeeze(1)).unsqueeze(1).detach()  # [b, 1, t, t']
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/TTS/tts/utils/helpers.py", line 174, in maximum_path
    return maximum_path_numpy(value, mask)
  File "/gpfs/projects/bsc88/speech/environments/tts_0.14.3_espeak/lib/python3.8/site-packages/TTS/tts/utils/helpers.py", line 231, in maximum_path_numpy
    path[index_range, index, j] = 1
IndexError: index -142 is out of bounds for axis 1 with size 141
srun: error: p9r3n12: task 0: Exited with exit code 1
```

We found the same issue in [#1371](https://github.com/coqui-ai/TTS/issues/1371) However we already set the mixed precisión to `False` and we also have not nan values on our losses:

```
[1m   --> STEP: 22150/77101 -- GLOBAL_STEP: 22150[0m
     | > loss_disc: 2.35753  (2.45034)
     | > loss_disc_real_0: 0.10628  (0.14345)
     | > loss_disc_real_1: 0.18547  (0.23286)
     | > loss_disc_real_2: 0.28896  (0.24459)
     | > loss_disc_real_3: 0.23501  (0.22150)
     | > loss_disc_real_4: 0.26701  (0.24012)
     | > loss_disc_real_5: 0.21822  (0.24326)
     | > loss_0: 2.35753  (2.45034)
     | > grad_norm_0: 53.88837  (43.83282)
     | > loss_gen: 2.46746  (2.35341)
     | > loss_kl: 1.24726  (1.46966)
     | > loss_feat: 5.29864  (4.32032)
     | > loss_mel: 21.64699  (25.13474)
     | > loss_duration: 2.30667  (2.19097)
     | > loss_1: 32.96701  (35.46910)
     | > grad_norm_1: 1201.41138  (434.57941)
     | > current_lr_0: 0.00020 
     | > current_lr_1: 0.00020 
     | > step_time: 0.78940  (0.75441)
     | > loader_time: 0.00360  (0.02091)
```

### To Reproduce

the config.json file
```

{
    "output_path": "/gpfs/projects/bsc88/speech/tts/training_output/0.14.3",
    "logger_uri": null,
    "run_name": "cat",
    "project_name": null,
    "run_description": "",
    "print_step": 25,
    "plot_step": 100,
    "model_param_stats": false,
    "wandb_entity": null,
    "dashboard_logger": "tensorboard",
    "save_on_interrupt": true,
    "log_model_step": null,
    "save_step": 10000,
    "save_n_checkpoints": 5,
    "save_checkpoints": true,
    "save_all_best": false,
    "save_best_after": 10000,
    "target_loss": null,
    "print_eval": false,
    "test_delay_epochs": 0,
    "run_eval": true,
    "run_eval_steps": null,
    "distributed_backend": "nccl",
    "distributed_url": "tcp://localhost:54321",
    "mixed_precision": false,
    "precision": "fp16",
    "epochs": 10000,
    "batch_size": 10,
    "eval_batch_size": 10,
    "grad_clip": [
        5.0,
        5.0
    ],
    "scheduler_after_epoch": true,
    "lr": 0.001,
    "optimizer": "AdamW",
    "optimizer_params": {
        "betas": [
            0.8,
            0.99
        ],
        "eps": 1e-09,
        "weight_decay": 0.01
    },
    "lr_scheduler": "",
    "lr_scheduler_params": {},
    "use_grad_scaler": false,
    "cudnn_enable": true,
    "cudnn_deterministic": false,
    "cudnn_benchmark": true,
    "training_seed": 54321,
    "model": "vits",
    "num_loader_workers": 4,
    "num_eval_loader_workers": 0,
    "use_noise_augment": false,
    "audio": {
        "fft_size": 1024,
        "sample_rate": 16000,
        "win_length": 1024,
        "hop_length": 256,
        "num_mels": 80,
        "mel_fmin": 60,
        "mel_fmax": null
    },
    "use_phonemes": true,
    "phonemizer": "espeak",
    "phoneme_language": "ca",
    "compute_input_seq_cache": false,
    "text_cleaner": "phoneme_cleaners",
    "enable_eos_bos_chars": false,
    "test_sentences_file": "",
    "phoneme_cache_path": "/gpfs/projects/bsc88/speech/tts/training_output/definitive_phoneme_cache_ca",
    "characters": {
        "characters_class": "TTS.tts.models.vits.VitsCharacters",
        "vocab_dict": null,
        "pad": "_",
        "eos": "",
        "bos": "",
        "blank": null,
        "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
        "punctuations": ";:,.!?\u00a1\u00bf\u2014\u2026\"\u00ab\u00bb\u201c\u201d ",
        "phonemes": "\u0251\u0250\u0252\u00e6\u0253\u0299\u03b2\u0254\u0255\u00e7\u0257\u0256\u00f0\u02a4\u0259\u0258\u025a\u025b\u025c\u025d\u025e\u025f\u0284\u0261\u0260\u0262\u029b\u0266\u0267\u0127\u0265\u029c\u0268\u026a\u029d\u026d\u026c\u026b\u026e\u029f\u0271\u026f\u0270\u014b\u0273\u0272\u0274\u00f8\u0275\u0278\u03b8\u0153\u0276\u0298\u0279\u027a\u027e\u027b\u0280\u0281\u027d\u0282\u0283\u0288\u02a7\u0289\u028a\u028b\u2c71\u028c\u0263\u0264\u028d\u03c7\u028e\u028f\u0291\u0290\u0292\u0294\u02a1\u0295\u02a2\u01c0\u01c1\u01c2\u01c3\u02c8\u02cc\u02d0\u02d1\u02bc\u02b4\u02b0\u02b1\u02b2\u02b7\u02e0\u02e4\u02de\u2193\u2191\u2192\u2197\u2198'\u0329'\u1d7b",
        "is_unique": true,
        "is_sorted": true
    },
    "add_blank": true,
    "batch_group_size": 0,
    "loss_masking": null,
    "min_audio_len": 1,
    "max_audio_len": Infinity,
    "min_text_len": 1,
    "max_text_len": Infinity,
    "compute_f0": false,
    "compute_energy": false,
    "compute_linear_spec": true,
    "precompute_num_workers": 0,
    "start_by_longest": false,
    "shuffle": false,
    "drop_last": false,
    "datasets": [
        {
            "formatter": "vctk_old",
            "dataset_name": "vctk_old",
            "path": "/gpfs/projects/bsc88/speech/data/multispeaker_ca_data",
            "meta_file_train": "",
            "ignored_speakers": ["0021fa05994fff2526e68ee711aecc26380750e316e7113fe13a111ae493373f296944ba737076a9466e0596cded6a223a9b80736ea1ce00b1d7e3aa7e46924d",
            "00512989213a06cccee0659efa8df02e1d0662aaf265f85420f6f3ccb8c5ae78236aa522c91443a34f59726ae5cd90a13892505cd9caa9afc1619d5866ef04c8",
            "01067663db08dbdd404245317a8caf0a077a62ae3cf1e836c8f17cc93efe9a13a9c96fce7f955a3082a983fcdefa761a5644330a212a3618330c1442c90f59cd",
            "01334eca08791ab04e8e58b569b41278f64d2e8a762a32ba8c5eeeb3d68caa517f09a1708a8fc4ba91540e00c47369cb228224225991efe0967485499dc15026"],
            "language": "ca",
            "meta_file_val": "",
            "meta_file_attn_mask": ""
        }
    ],
    "test_sentences": [
        [
            "Per exemple, dels nostres bancs que inverteixen en armament de les nostres empreses."
        ],
        [
            "Preguntin-se si aix\u00f2 era necessari."
        ],
        [
            "La suposada ocultaci\u00f3 dels informes que advertien de risc s\u00edsmic."
        ],
        [
            "\u00c9s de 633 milions d'euros quan es far\u00e0 la publicaci\u00f3 detallada."
        ]
    ],
    "eval_split_max_size": null,
    "eval_split_size": 0.01,
    "use_speaker_weighted_sampler": false,
    "speaker_weighted_sampler_alpha": 1.0,
    "use_language_weighted_sampler": false,
    "language_weighted_sampler_alpha": 1.0,
    "use_length_weighted_sampler": false,
    "length_weighted_sampler_alpha": 1.0,
    "model_args": {
        "num_chars": 179,
        "out_channels": 513,
        "spec_segment_size": 32,
        "hidden_channels": 192,
        "hidden_channels_ffn_text_encoder": 768,
        "num_heads_text_encoder": 2,
        "num_layers_text_encoder": 6,
        "kernel_size_text_encoder": 3,
        "dropout_p_text_encoder": 0.1,
        "dropout_p_duration_predictor": 0.5,
        "kernel_size_posterior_encoder": 5,
        "dilation_rate_posterior_encoder": 1,
        "num_layers_posterior_encoder": 16,
        "kernel_size_flow": 5,
        "dilation_rate_flow": 1,
        "num_layers_flow": 4,
        "resblock_type_decoder": "1",
        "resblock_kernel_sizes_decoder": [
            3,
            7,
            11
        ],
        "resblock_dilation_sizes_decoder": [
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ]
        ],
        "upsample_rates_decoder": [
            8,
            8,
            2,
            2
        ],
        "upsample_initial_channel_decoder": 512,
        "upsample_kernel_sizes_decoder": [
            16,
            16,
            4,
            4
        ],
        "periods_multi_period_discriminator": [
            2,
            3,
            5,
            7,
            11
        ],
        "use_sdp": true,
        "noise_scale": 1.0,
        "inference_noise_scale": 0.667,
        "length_scale": 1.0,
        "noise_scale_dp": 1.0,
        "inference_noise_scale_dp": 0.8,
        "max_inference_len": null,
        "init_discriminator": true,
        "use_spectral_norm_disriminator": false,
        "use_speaker_embedding": true,
        "num_speakers": 840,
        "speakers_file": "/gpfs/projects/bsc88/speech/tts/TTS_28_06_23/recipes/vctk/vits/vits_vctk_ca-July-14-2023_06+43PM-a035b25/speakers.pth",
        "d_vector_file": null,
        "speaker_embedding_channels": 256,
        "use_d_vector_file": false,
        "d_vector_dim": 0,
        "detach_dp_input": true,
        "use_language_embedding": false,
        "embedded_language_dim": 4,
        "num_languages": 0,
        "language_ids_file": null,
        "use_speaker_encoder_as_loss": false,
        "speaker_encoder_config_path": "",
        "speaker_encoder_model_path": "",
        "condition_dp_on_speaker": true,
        "freeze_encoder": false,
        "freeze_DP": false,
        "freeze_PE": false,
        "freeze_flow_decoder": false,
        "freeze_waveform_decoder": false,
        "encoder_sample_rate": null,
        "interpolate_z": true,
        "reinit_DP": false,
        "reinit_text_encoder": false
    },
    "lr_gen": 0.0002,
    "lr_disc": 0.0002,
    "lr_scheduler_gen": "ExponentialLR",
    "lr_scheduler_gen_params": {
        "gamma": 0.999875,
        "last_epoch": -1
    },
    "lr_scheduler_disc": "ExponentialLR",
    "lr_scheduler_disc_params": {
        "gamma": 0.999875,
        "last_epoch": -1
    },
    "kl_loss_alpha": 1.0,
    "disc_loss_alpha": 1.0,
    "gen_loss_alpha": 1.0,
    "feat_loss_alpha": 1.0,
    "mel_loss_alpha": 45.0,
    "dur_loss_alpha": 1.0,
    "speaker_encoder_loss_alpha": 1.0,
    "return_wav": true,
    "use_weighted_sampler": false,
    "weighted_sampler_attrs": {},
    "weighted_sampler_multipliers": {},
    "r": 1,
    "num_speakers": 0,
    "use_speaker_embedding": false,
    "speakers_file": "/gpfs/projects/bsc88/speech/tts/TTS_28_06_23/recipes/vctk/vits/vits_vctk_ca-July-14-2023_06+43PM-a035b25/speakers.pth",
    "speaker_embedding_channels": 256,
    "language_ids_file": null,
    "use_language_embedding": false,
    "use_d_vector_file": false,
    "d_vector_file": null,
    "d_vector_dim": 0
}
```

### Expected behavior

Train without errors, Assert the index is on the range of the path dimensions

### Environment

```shell
{
    "CUDA": {
        "GPU": ["Tesla V100-SXM2-16GB"],
        "available": true,
        "version": "10.2"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.9.0a0+gitdfbd030",
        "TTS": "0.14.3",
        "numpy": "1.21.6"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "ppc64le",
        "python": "3.8.1",
        "version": "#1 SMP Tue Sep 25 12:28:39 EDT 2018"
    }
}
```

### Additional context

We're a using a processed version of commonvoice 12 on catalan language.

**Comment by pivolan** [comment]
on what epoch it was fallen?

**Comment by wetdog** [comment]
We were training Vits, for our dataset it was on the first epoch. We also print the tensors value and mask that are the inputs for the maximum_path_numpy function. We think that it fails because the value tensor is full of nans

**Comment by pivolan** [comment]
thanks, I just done with some experiments with config, and this error gone away

lr_gen=4e-1,
    lr=4e-1,
    lr_disc=4e-1,
    max_text_len=130,

I removed this lines, and set max_text_length to 110

and also tried with this paramemer:
steps_to_start_discriminator=10000,

this is my current config, may be it will helpful, anyway I don't know the reason of this error
```
delightful_tts_config = DelightfulTTSConfig(
    run_name=RUN_NAME,
    run_description="Train delightful tts for funke from the scratch, full dataset usage.",
    model_args=model_args,
    audio=audio_config,
    vocoder=vocoder_config,
    batch_size=24,
    eval_batch_size=12,
    num_loader_workers=10,
    num_eval_loader_workers=10,
    precompute_num_workers=10,
    batch_group_size=1,
    compute_input_seq_cache=True,
    compute_f0=True,
    f0_cache_path=os.path.join(output_path, RUN_NAME + "f0_cache"),
    run_eval=False,
    test_delay_epochs=-1,
    epochs=1000,
    text_cleaner="phoneme_cleaners",
    use_phonemes=True,
    phoneme_language="de",
    phonemizer='espeak',
    phoneme_cache_path=os.path.join(output_path, RUN_NAME + "phoneme_cache"),
    print_step=50,
    log_model_step=1000,
    save_step=100,
    save_n_checkpoints=4,
    save_checkpoints=True,
    print_eval=False,
    mixed_precision=True,
    output_path=output_path,
    datasets=[dataset_config],
    start_by_longest=True,
    eval_split_size=0.1,
    binary_align_loss_alpha=0.0,
    use_attn_priors=False,
    max_text_len=110,
    steps_to_start_discriminator=10000,
    test_sentences=[ "Ich gehe gerne spazieren, besonders im Frühling.",

```
And I disable `run_eval`
I found before in the issues that setting     `mixed_precision=True,` can affect on this behaviour, but for me it has no any affects.

Also I tries to increase or decrease counts of files, no affects.

**Comment by erogol** [comment]
I close this one as the main issue seems solved.
