### ISSUE TITLE
delightfulTTS training errors[Bug] 

### ISSUE THREAD

**Issue by stlohrey** [coqui-ai/TTS#2798]
### Describe the bug

I tried to train a delightfulTTS model, following the recipe for ljspeech. In the evaluation step, i run into the following error:

``[!] `eval_step()` retuned `None` outputs. Skipping evaluation step.``
`UnboundLocalError: local variable 'outputs' referenced before assignment`

### To Reproduce

See 'recipes/ljspeech/delightful_tts/train_delightful_tts.py'

### Expected behavior

Normal training

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.15.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2"
    }
}
```

**Comment by kelseyjd** [comment]
I have the same problem.

> DataLoader initialization
| > Tokenizer:
	| > add_blank: False
	| > use_eos_bos: False
	| > use_phonemes: True
	| > phonemizer:
		| > phoneme language: en-us
		| > phoneme backend: gruut
| > Number of instances : 1310
 | > Preprocessing samples
 | > Max text length: 130
 | > Min text length: 14
 | > Avg text length: 88.46477495107632
 | 
 | > Max audio length: 221363.0
 | > Min audio length: 25011.0
 | > Avg audio length: 128514.9060665362
 | > Num. instances discarded samples: 288
 | > Batch group size: 0.

 > EVALUATION 

 [!] `eval_step()` retuned `None` outputs. Skipping evaluation step.
 [!] `eval_step()` retuned `None` outputs. Skipping evaluation step.
 [!] `eval_step()` retuned `None` outputs. Skipping evaluation step.
 [!] `eval_step()` retuned `None` outputs. Skipping evaluation step.
[!] `eval_step()` retuned `None` outputs. Skipping evaluation step.
Traceback (most recent call last):
  File "/home/kel/anaconda3/envs/coqui/lib/python3.9/site-packages/trainer/trainer.py", line 1666, in fit
    self._fit()
  File "/home/kel/anaconda3/envs/coqui/lib/python3.9/site-packages/trainer/trainer.py", line 1620, in _fit
    self.eval_epoch()
  File "/home/kel/anaconda3/envs/coqui/lib/python3.9/site-packages/trainer/trainer.py", line 1495, in eval_epoch
    if self.args.rank == 0 and outputs is not None:
UnboundLocalError: local variable 'outputs' referenced before assignment

**Comment by ppisljar** [comment]
did any of you experience very slow f0 precomputation ? its taking 15s/step for me

**Comment by pivolan** [comment]
I have the same problem, and with enabled eval train does not work.

**Comment by ppisljar** [comment]
it took around 3 days for f0 calculation to be completed on ljspeech, 
now training is running, but its very slow, uses very little gpu resources, is stuck on cpu most of the time.
![Screenshot from 2023-07-31 07-34-55](https://github.com/coqui-ai/TTS/assets/13629809/c274bdc8-39de-4692-9d75-0c461c0edb61)

**Comment by ppisljar** [comment]
also those NaN seem wrong

**Comment by ppisljar** [comment]
cc @loganhart420

**Comment by ppisljar** [comment]
i think this should be reopened as the merged PR doesn't full solve this:
- there is still an issue with eval step as it does not seem to return value
- there is still an issue with slowness of delightufullTTS

**Comment by catselectro** [comment]
Any updates on this? I also tried with the branch called "fix_delightfultts" but I'm still getting:
 [!] `eval_step()` retuned `None` outputs.

And then of course:
    return d_vector.cuda()
AttributeError: 'NoneType' object has no attribute 'cuda'

**Comment by erogol** [comment]
@catselectro try updating the trainer 

`pip install -U trainer`

**Comment by catselectro** [comment]
> @catselectro try updating the trainer
> 
> `pip install -U trainer`

Thanks, but it said I already have the latest version. In case of this helps, I'm using Python 3.10 and this is my train file:

`    data_path = "tests\data\ljspeech"
    output_path = os.path.dirname(os.path.abspath(__file__))

    dataset_config = BaseDatasetConfig(
        dataset_name="ljspeech", formatter="ljspeech", meta_file_train="metadata.csv", path=data_path
    )

    audio_config = DelightfulTtsAudioConfig()
    model_args = DelightfulTtsArgs()

    vocoder_config = VocoderConfig()

    delightful_tts_config = DelightfulTTSConfig(
        run_name="new",
        run_description="Train like in delightful tts paper.",
        model_args=model_args,
        audio=audio_config,
        vocoder=vocoder_config,
        batch_size=6,
        eval_batch_size=6,
        num_loader_workers=10,
        num_eval_loader_workers=10,
        precompute_num_workers=10,
        batch_group_size=20,
        compute_input_seq_cache=True,
        compute_f0=True,
        f0_cache_path=os.path.join(data_path, "f0_cache"),
        run_eval=False,
        test_delay_epochs=-1,
        epochs=1000,
        text_cleaner="english_cleaners",
        use_phonemes=True,
        phoneme_language="en-us",
        phoneme_cache_path=os.path.join(data_path, "phoneme_cache"),
        print_step=50,
        print_eval=False,
        mixed_precision=True,
        output_path=output_path,
        datasets=[dataset_config],
        start_by_longest=False,
        eval_split_size=0.3,
        binary_align_loss_alpha=0.0,
        use_attn_priors=False,
        lr_gen=4e-1,
        lr=4e-1,
        lr_disc=4e-1,
        max_text_len=130,
    )


    tokenizer, config = TTSTokenizer.init_from_config(delightful_tts_config)

    ap = AudioProcessor.init_from_config(config)


    train_samples, eval_samples = load_tts_samples(
        dataset_config,
        eval_split=True,
        eval_split_max_size=config.eval_split_max_size,
        eval_split_size=config.eval_split_size,
    )

    model = DelightfulTTS(ap=ap, config=config, tokenizer=tokenizer, speaker_manager=None)

    trainer = Trainer(
        TrainerArgs(),
        config,
        output_path,
        model=model,
        train_samples=train_samples,
        eval_samples=eval_samples,
    )

    trainer.fit()`

**Comment by loganhart420** [comment]
> > @catselectro try updating the trainer
> > `pip install -U trainer`
> 
> Thanks, but it said I already have the latest version. In case of this helps, I'm using Python 3.10 and this is my train file:
> 
> ` data_path = "tests\data\ljspeech" output_path = os.path.dirname(os.path.abspath(**file**))
> 
> ```
> dataset_config = BaseDatasetConfig(
>     dataset_name="ljspeech", formatter="ljspeech", meta_file_train="metadata.csv", path=data_path
> )
> 
> audio_config = DelightfulTtsAudioConfig()
> model_args = DelightfulTtsArgs()
> 
> vocoder_config = VocoderConfig()
> 
> delightful_tts_config = DelightfulTTSConfig(
>     run_name="new",
>     run_description="Train like in delightful tts paper.",
>     model_args=model_args,
>     audio=audio_config,
>     vocoder=vocoder_config,
>     batch_size=6,
>     eval_batch_size=6,
>     num_loader_workers=10,
>     num_eval_loader_workers=10,
>     precompute_num_workers=10,
>     batch_group_size=20,
>     compute_input_seq_cache=True,
>     compute_f0=True,
>     f0_cache_path=os.path.join(data_path, "f0_cache"),
>     run_eval=False,
>     test_delay_epochs=-1,
>     epochs=1000,
>     text_cleaner="english_cleaners",
>     use_phonemes=True,
>     phoneme_language="en-us",
>     phoneme_cache_path=os.path.join(data_path, "phoneme_cache"),
>     print_step=50,
>     print_eval=False,
>     mixed_precision=True,
>     output_path=output_path,
>     datasets=[dataset_config],
>     start_by_longest=False,
>     eval_split_size=0.3,
>     binary_align_loss_alpha=0.0,
>     use_attn_priors=False,
>     lr_gen=4e-1,
>     lr=4e-1,
>     lr_disc=4e-1,
>     max_text_len=130,
> )
> 
> 
> tokenizer, config = TTSTokenizer.init_from_config(delightful_tts_config)
> 
> ap = AudioProcessor.init_from_config(config)
> 
> 
> train_samples, eval_samples = load_tts_samples(
>     dataset_config,
>     eval_split=True,
>     eval_split_max_size=config.eval_split_max_size,
>     eval_split_size=config.eval_split_size,
> )
> 
> model = DelightfulTTS(ap=ap, config=config, tokenizer=tokenizer, speaker_manager=None)
> 
> trainer = Trainer(
>     TrainerArgs(),
>     config,
>     output_path,
>     model=model,
>     train_samples=train_samples,
>     eval_samples=eval_samples,
> )
> 
> trainer.fit()
> ```
> 
> `

I'm going to try and reproduce this today.

**Comment by AWAS666** [comment]
> 

running into the same issues even with the newest trainer.
