### ISSUE TITLE
[Bug] FastSpeech2 Expanding Tensor RunTimeError

### ISSUE THREAD

**Issue by zohaib-khan5040** [coqui-ai/TTS#2800]
### Describe the bug

I'm trying to train with Fastspeech2 on a custom dataset with the LJSpeech format and am running into this error (please note that I have done a clean install as directed by the repo):

The error message I got:
```
> EPOCH: 0/10000
 --> /workspace/fastspeech2_ljspeech-July-25-2023_02+13PM-0000000
[*] Pre-computing energys...
 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 1412/1849 [00:25<00:04, 105.44it/s]/opt/conda/lib/python3.10/site-packages/librosa/core/spectrum.py:256: UserWarning: n_fft=1024 is too large for input signal of length=2
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/librosa/core/spectrum.py:256: UserWarning: n_fft=1024 is too large for input signal of length=2
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/librosa/core/spectrum.py:256: UserWarning: n_fft=1024 is too large for input signal of length=2
  warnings.warn(
 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 1412/1849 [00:36<00:11, 38.71it/s]
 ! Run is removed from /workspace/fastspeech2_ljspeech-July-25-2023_02+13PM-0000000
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/trainer/trainer.py", line 1805, in fit
    self._fit()
  File "/opt/conda/lib/python3.10/site-packages/trainer/trainer.py", line 1757, in _fit
    self.train_epoch()
  File "/opt/conda/lib/python3.10/site-packages/trainer/trainer.py", line 1467, in train_epoch
    self.train_loader = self.get_train_dataloader(
  File "/opt/conda/lib/python3.10/site-packages/trainer/trainer.py", line 931, in get_train_dataloader
    return self._get_loader(
  File "/opt/conda/lib/python3.10/site-packages/trainer/trainer.py", line 895, in _get_loader
    loader = model.get_data_loader(
  File "/workspace/TTS/TTS/tts/models/base_tts.py", line 315, in get_data_loader
    dataset = TTSDataset(
  File "/workspace/TTS/TTS/tts/datasets/dataset.py", line 168, in __init__
    self.energy_dataset = EnergyDataset(
  File "/workspace/TTS/TTS/tts/datasets/dataset.py", line 855, in __init__
    self.precompute(precompute_num_workers)
  File "/workspace/TTS/TTS/tts/datasets/dataset.py", line 881, in precompute
    for batch in dataloder:
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/workspace/TTS/TTS/tts/datasets/dataset.py", line 954, in collate_fn
    energys_torch[i, :energy_len] = torch.LongTensor(energys[i])
RuntimeError: expand(torch.LongTensor{[513, 1]}, size=[513]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
```

### To Reproduce

I found some place that mentioned changing `r=1` to `r=7` but this error persisted across both changes.
This is the script I ran for training the model:

```python
import os

from trainer import Trainer, TrainerArgs
from TTS.config.shared_configs import BaseAudioConfig, BaseDatasetConfig
from TTS.tts.configs.fastspeech2_config import Fastspeech2Config
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.forward_tts import ForwardTTS
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor
from TTS.utils.manage import ModelManager
from TTS.tts.configs.shared_configs import CharactersConfig

output_path = os.path.dirname(os.path.abspath(__file__))
dataset = "./dataset"
assert os.path.exists(dataset), "Dataset path specified does not exist!"
# init configs
dataset_config = BaseDatasetConfig(
    formatter="ljspeech",
    meta_file_train="metadata.csv",
    path=os.path.join(output_path, dataset)
)

audio_config = BaseAudioConfig(
    sample_rate=44100,
    do_trim_silence=True,
    trim_db=60.0,
    signal_norm=False,
    mel_fmin=0.0,
    mel_fmax=8000,
    spec_gain=1.0,
    log_func="np.log",
    ref_level_db=20,
    preemphasis=0.0,
)

config = Fastspeech2Config(
    run_name="fastspeech2_ljspeech",
    audio=audio_config,
    batch_size=4,
    eval_batch_size=16,
    num_loader_workers=8,
    num_eval_loader_workers=4,
    compute_input_seq_cache=True,
    compute_f0=False,
    f0_cache_path=os.path.join(output_path, "f0_cache"),
    compute_energy=True,
    energy_cache_path=os.path.join(output_path, "energy_cache"),
    run_eval=False,
    test_delay_epochs=-1,
    epochs=10000,
    text_cleaner="english_cleaners",
    use_phonemes=False,
    phoneme_language="en-us",
    phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
    precompute_num_workers=4,
    print_step=50,
    print_eval=False,
    mixed_precision=False,
    max_seq_len=500000,
    output_path=output_path,
    datasets=[dataset_config],
    r=1,
    characters=CharactersConfig(
        pad="<PAD>",
        eos="<EOS>",
        bos="<BOS>",
        blank="<BLNK>",
        characters="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ۵ٹثۃگںف۲۱ظچئژذ۳لیڈن۸ۓزم۹بھۂےطغ۰ہأؤسواتصعدء۴۶شخضڑپآحک۷رجق",
        punctuations=" ,.'٫؟،۔؛٪",
        is_unique=False,
        is_sorted=True
    ),
    test_sentences=[
    ]
)

# compute alignments
if not config.model_args.use_aligner:
    manager = ModelManager()
    model_path, config_path, _ = manager.download_model("tts_models/en/ljspeech/tacotron2-DCA")
    # TODO: make compute_attention python callable
    os.system(
        f"python TTS/bin/compute_attention_masks.py --model_path {model_path} --config_path {config_path} --dataset ljspeech --dataset_metafile metadata.csv --data_path ./recipes/ljspeech/LJSpeech-1.1/  --use_cuda true"
    )

# INITIALIZE THE AUDIO PROCESSOR
# Audio processor is used for feature extraction and audio I/O.
# It mainly serves to the dataloader and the training loggers.
ap = AudioProcessor.init_from_config(config)

# INITIALIZE THE TOKENIZER
# Tokenizer is used to convert text to sequences of token IDs.
# If characters are not defined in the config, default characters are passed to the config
tokenizer, config = TTSTokenizer.init_from_config(config)

# LOAD DATA SAMPLES
# Each sample is a list of ```[text, audio_file_path, speaker_name]```
# You can define your custom sample loader returning the list of samples.
# Or define your custom formatter and pass it to the `load_tts_samples`.
# Check `TTS.tts.datasets.load_tts_samples` for more details.
train_samples, eval_samples = load_tts_samples(
    dataset_config,
    eval_split=False,
    eval_split_max_size=config.eval_split_max_size,
    eval_split_size=config.eval_split_size,
)

# init the model
model = ForwardTTS(config, ap, tokenizer, speaker_manager=None)

# init the trainer and 🚀
trainer = Trainer(
    TrainerArgs(), config, output_path, model=model, train_samples=train_samples, eval_samples=eval_samples
)
trainer.fit()
```

### Environment

```shell
- TTS: 0.15.6 (from `conda list` since the `collect_env_info.py` script gave the error `TTS has no attribute '__version__'`)
- PyTorch: 2.0.1
- OS: Ubuntu 16.04
```

**Comment by erogol** [comment]
You might have multi-channel audio files in your dataset.

**Comment by zohaib-khan5040** [comment]
Yep, this issue only popped up after adding a new subset of data to the original that was already working. Thank you!
