### ISSUE TITLE
[Bug] Uncomment code in tts\configs\__init__.py for PyInstaller to find configs

### ISSUE THREAD

**Issue by Sharrnah** [coqui-ai/TTS#2802]
### Describe the bug

I tried to build a standalone project using coqui-ai but did hit a wall of it not finding most tts configs for bark or tortoise models (and maybe others).

Code to fix this is already included but commented out in the file `tts\configs\__init__.py`.

### To Reproduce

create a standalone build using pyinstaller.
(this is might be too much or some missing dependencies, but thats what i have so far)

```bat
pyinstaller main.py -y ^
            --onedir --clean --distpath=dist ^
            --name=coqui-tts ^
            --python-option=u ^
            --hidden-import=pytorch --collect-data=torch --copy-metadata=torch ^
            --hidden-import=torchaudio.lib.libtorchaudio ^
            --hidden-import=gruut ^
            --hidden-import=gruut_lang_de ^
            --hidden-import=gruut_lang_en ^
            --hidden-import=gruut_lang_es ^
            --hidden-import=gruut_lang_fr ^
            --hidden-import=pycrfsuite._dumpparser ^
            --hidden-import=pycrfsuite._logparser ^
            --hidden-import=mecab-python3 ^
            --hidden-import=unidic-lite ^
            --hidden-import=sentencepiece ^
            --copy-metadata=tqdm ^
            --copy-metadata=regex ^
            --copy-metadata=numpy ^
            --copy-metadata=tokenizers ^
            --copy-metadata=sentencepiece ^
            --copy-metadata=transformers ^
            --copy-metadata=requests ^
            --copy-metadata=aiohttp ^
            --copy-metadata=packaging ^
            --copy-metadata=filelock ^
            --collect-all=TTS ^
            --collect-all=torchaudio ^
            --collect-all=scipy ^
            --collect-all=librosa ^
            --collect-all=torchlibrosa ^
            --collect-all=transformers ^
            --collect-all=sentencepiece ^
            --collect-all=trainer ^
            --collect-all=unidic_lite ^
            --collect-all=gruut ^
            --collect-all=gruut_lang_de ^
            --collect-all=gruut_lang_en ^
            --collect-all=gruut_lang_es ^
            --collect-all=gruut_lang_fr ^
            --collect-all=jamo ^
            --collect-all=nltk ^
            --collect-all=g2pkk ^
            --collect-all=bangla ^
            --collect-all=bnnumerizer ^
            --collect-all=bnunicodenormalizer ^
            --collect-all=k_diffusion ^
            --collect-all=einops ^
            --collect-all=encodec ^
            --collect-all=fsspec ^
            --collect-all=pysbd ^
            --collect-all=anyascii ^
            --collect-all=coqpit ^
            --collect-all=jieba ^
            --collect-all=jsonschema_specifications ^
            --collect-all=clip
```

run it with bark or tortoise model using the generated pyinstaller build.

### Expected behavior

Load models without error

### Logs

```shell
for tortoise-v2 (but for Bark it is similar)


Traceback (most recent call last):
  File "main.py", line 267, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "click\decorators.py", line 33, in new_func
  File "main.py", line 260, in main
  File "main.py", line 244, in load_model
  File "TTS\api.py", line 289, in __init__
  File "TTS\api.py", line 391, in load_tts_model_by_name
  File "TTS\utils\synthesizer.py", line 107, in __init__
  File "TTS\utils\synthesizer.py", line 159, in _load_tts_from_dir
  File "TTS\config\__init__.py", line 94, in load_config
  File "TTS\config\__init__.py", line 47, in register_config
ModuleNotFoundError:  [!] Config for tortoise cannot be found.
```
```


### Environment

```shell
- 🐸TTS Version: v0.16.0:
- PyTorch Version: 2.0.1+cu117
- Python Version: 3.10
- OS: Windows 11
- GPU models and configuration: Geforce RTX 3090
- How you installed PyTorch: pip using `--extra-index-url https://download.pytorch.org/whl/cu117`
- PyInstaller version: 5.13.0
```

### Additional context

The code to load the configs is already there, but commented out for some reason.

uncommenting it does not seem to have any other negative effects i noticed, so i suggest uncommenting it again.

**Comment by erogol** [comment]
What does a` standalone project` in this context? Like installing with a legit installer?

**Comment by erogol** [comment]
Ok, thanks. It is not something I am interested in ATM. But if you have a fix feel free to send a PR, if it is not a deal-breaker we can discuss it there.

**Comment by Sharrnah** [comment]
well. the fix would be to just uncomment that code i mentioned. I am not sure why it is commented out in the first place though.
A similar code that is not commented out is in another place though, so... no idea why it is like it is.

**Comment by erogol** [comment]
It causes recursive imports and breaks the runtime.

**Comment by Sharrnah** [comment]
why is it not commented out here then?
https://github.com/coqui-ai/TTS/blob/dev/TTS/vocoder/configs/__init__.py
(just curious. if its not something fixable, i can just uncomment it myself when i need it)

**Comment by erogol** [comment]
it doesn't cause the same issue there.

**Comment by Sharrnah** [comment]
okay. would it be acceptable then to execute the code only when its bundled?
according to PyInstaller, it should work like this.
```py
import sys
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    print('running in a PyInstaller bundle')
```

see: https://pyinstaller.org/en/stable/runtime-information.html#run-time-information

**Comment by Sharrnah** [comment]
would still love this being changed, so it does not require patching when bundling.

**Comment by daryltucker** [comment]
Yeah, also seeing issues with it trying to load a VERSION file from the cwd.  [TTS/__init__.py](https://github.com/coqui-ai/TTS/blob/dbf1a08a0d4e47fdad6172e433eeb34bc6b13b4e/TTS/__init__.py#L4)

*Edit:* Actually `--collect-all "TTS"` solves this particular issue.  Sorry for the noise.
