### ISSUE TITLE
[Bug] Logging error while continue training using --continue_path

### ISSUE THREAD

**Issue by kin0303** [coqui-ai/TTS#2880]
### Describe the bug

I got this error when tried to continue training using --continue_path:

```
TypeError: '<' not supported between instances of 'float' and 'dict'
```
This error appears when saving the model. And there is also an error when restoring the best loss from checkpoint:
```
--- Logging errors ---
Traceback (most recently last call):
   File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
     msg = self. format(record)
   File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
     return fmt. format(record)
   File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
     record.message = record.getMessage()
   File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
     msg = msg % self.args
TypeError: must be real number, not dict
Call stacks:
   File "/Your_TTS/TTS/Your_TTS.py", line 213, in <module>
     trainer.fit()
   File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1808, in fit
     self._fit()
   File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1746, in _fit
     self._restore_best_loss()
   File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1710, in _restore_best_loss
     logger.info(" > Starting with last loaded best loss %f", self.best_loss)
Message: ' > Starting with last loaded best loss %f'
Arguments: {'train_loss': 46.055439511812644, 'eval_loss': None}
--- Logging errors ---
Traceback (most recently last call):
   File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
     msg = self. format(record)
   File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
     return fmt. format(record)
   File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
     record.message = record.getMessage()
   File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
     msg = msg % self.args
TypeError: must be real number, not dict
Call stacks:
   File "/Your_TTS/TTS/Your_TTS.py", line 213, in <module>
     trainer.fit()
   File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1808, in fit
     self._fit()
   File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1746, in _fit
     self._restore_best_loss()
   File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1710, in _restore_best_loss
     logger.info(" > Starting with last loaded best loss %f", self.best_loss)
Message: ' > Starting with last loaded best loss %f'
Arguments: {'train_loss': 46.055439511812644, 'eval_loss': None}
```

### To Reproduce

```
CUDA_VISIBLE_DEVICES=0 python Your_TTS.py --continue_path /Your_TTS/TTS/YourTTS-August-21-2023_10+58AM-c87377b7
```
And the full error:
```
 ! Run is kept in /Your_TTS/TTS/YourTTS-August-21-2023_10+58AM-c87377b7
Traceback (most recent call last):
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1771, in _fit
    self.save_best_model()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/utils/distributed.py", line 35, in wrapped_fn
    return fn(*args, **kwargs)
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1893, in save_best_model
    self.best_loss = save_best_model(
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/io.py", line 183, in save_best_model
    if current_loss < best_loss:
TypeError: '<' not supported between instances of 'float' and 'dict'
```

### Logs

```shell
| > /Your_TTS/TTS/data/id/Female/Karin/metadata.csv
 | > /Your_TTS/TTS/data/id/Male/Faisal/metadata.csv
 | > Found 2142 files in /Your_TTS/TTS/data
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Model fully restored. 
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 6
 | > Num. of Torch Threads: 24
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=/Your_TTS/TTS/YourTTS-August-21-2023_10+58AM-c87377b7
 > `speakers.pth` is saved to /Your_TTS/TTS/YourTTS-August-21-2023_10+58AM-c87377b7/speakers.pth.
 > `speakers_file` is updated in the config.json.
 > Restoring from checkpoint_327.pth ...
 > Restoring Model...
 > Restoring Optimizer...
 > Model restored from step 327

 > Model has 86565676 parameters
 > Restoring best loss from checkpoint_327.pth ...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: must be real number, not dict
Call stack:
  File "/Your_TTS/TTS/Your_TTS.py", line 213, in <module>
    trainer.fit()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1746, in _fit
    self._restore_best_loss()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1710, in _restore_best_loss
    logger.info(" > Starting with loaded last best loss %f", self.best_loss)
Message: ' > Starting with loaded last best loss %f'
Arguments: {'train_loss': 46.055439511812644, 'eval_loss': None}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: must be real number, not dict
Call stack:
  File "/Your_TTS/TTS/Your_TTS.py", line 213, in <module>
    trainer.fit()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1746, in _fit
    self._restore_best_loss()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1710, in _restore_best_loss
    logger.info(" > Starting with loaded last best loss %f", self.best_loss)
Message: ' > Starting with loaded last best loss %f'
Arguments: {'train_loss': 46.055439511812644, 'eval_loss': None}

 > EPOCH: 0/1000
...

 ! Run is kept in /Your_TTS/TTS/YourTTS-August-21-2023_10+58AM-c87377b7
Traceback (most recent call last):
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1771, in _fit
    self.save_best_model()
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/utils/distributed.py", line 35, in wrapped_fn
    return fn(*args, **kwargs)
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/trainer.py", line 1893, in save_best_model
    self.best_loss = save_best_model(
  File "/Your_TTS/tts_env/lib/python3.9/site-packages/trainer/io.py", line 183, in save_best_model
    if current_loss < best_loss:
TypeError: '<' not supported between instances of 'float' and 'dict'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1660 Ti"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.16.2",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.17",
        "version": "#86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023"
    }
}
```

**Comment by lsauter014** [comment]
Same problem for me ! I have been trying to deal with it for a week. Crash at the end of the epoch.

**Comment by kin0303** [comment]
> Same problem for me ! I have been trying to deal with it for a week. Crash at the end of the epoch.

Have you got the solution?

**Comment by lsauter014** [comment]
> Have you got the solution?

Nop, I got the same problem when I downgrade the tts version (I tried with the v0.15.1). I still stuck

**Comment by lsauter014** [comment]
> Have you got the solution?

I don't know if you still stuck but instead using the ```--continue_path``` arg you can use the ```--restore_path```  arg
you put the folder with the last checkoint/best_model.pth in the argument.

```restore_path='tts_train_dir/{last exec folder}/checkpoint_#######.pth' ```

Is less efficient as the  ```--continue_path```  but is a quick fix until a update/fix from TTS

if you use in a script: 
```
trainer = Trainer( TrainerArgs(restore_path),config, output_path, model=model, train_samples=train_samples, eval_samples=eval_samples)
```

**Comment by kin0303** [comment]
> > Have you got the solution?
> 
> I don't know if you still stuck but instead using the `--continue_path` arg you can use the `--restore_path` arg you put the folder with the last checkoint/best_model.pth in the argument.
> 
> `restore_path='tts_train_dir/{last exec folder}/checkpoint_#######.pth' `
> 
> Is less efficient as the `--continue_path` but is a quick fix until a update/fix from TTS
> 
> if you use in a script:
> 
> ```
> trainer = Trainer( TrainerArgs(restore_path),config, output_path, model=model, train_samples=train_samples, eval_samples=eval_samples)
> ```

Where is the ```trainer=...```? is it on the ```python3.9/site-packages/trainer/trainer.py```?

**Comment by koloric** [comment]
Yeah, I'm facing the same problem. The last time **--continue path** worked for me was on the **14th of August**. Since then, I've been encountering the same error as mentioned above and haven't been able to resume the training. I'm hesitant to use the --restore_path option since my model isn't adequately trained, and I'm concerned about the risk of overfitting.

**Comment by Kit-Bower-Morris** [comment]
Ran up against this same issue. 
I think I solved it by editing the trainer.py at line 1702.  Adding in self.best_loss = self.best_loss['train_loss'] in this function. It looks like normally self.best_loss = ch["model_loss"] should  just give train_loss but in my case it was giving {"train_loss" = x, "eval_loss" = 0}

`    def _restore_best_loss(self):
        """Restore the best loss from the args.best_path if provided else
        from the model (`args.continue_path`) used for resuming the training"""
        if self.args.continue_path and (self.restore_step != 0 or self.args.best_path):
            logger.info(" > Restoring best loss from %s ...", os.path.basename(self.args.best_path))
            ch = load_fsspec(self.args.restore_path, map_location="cpu")
            if "model_loss" in ch:
                self.best_loss = ch["model_loss"]
                self.best_loss = self.best_loss['train_loss']
            logger.info(" > Starting with loaded last best loss %f", self.best_loss)`

**Comment by koloric** [comment]
> Ran up against this same issue. I think I solved it by editing the trainer.py at line 1702. Adding in self.best_loss = self.best_loss['train_loss'] in this function. It looks like normally self.best_loss = ch["model_loss"] should just give train_loss but in my case it was giving {"train_loss" = x, "eval_loss" = 0}
> 
> def _restore_best_loss(self): """Restore the best loss from the args.best_path if provided else from the model (`args.continue_path`) used for resuming the training""" if self.args.continue_path and (self.restore_step != 0 or self.args.best_path): logger.info(" > Restoring best loss from %s ...", os.path.basename(self.args.best_path)) ch = load_fsspec(self.args.restore_path, map_location="cpu") if "model_loss" in ch: self.best_loss = ch["model_loss"] self.best_loss = self.best_loss['train_loss'] logger.info(" > Starting with loaded last best loss %f", self.best_loss)

Thank you! It works now!

**Comment by relitrix** [comment]
> Ran up against this same issue. I think I solved it by editing the trainer.py at line 1702. Adding in self.best_loss = self.best_loss['train_loss'] in this function. It looks like normally self.best_loss = ch["model_loss"] should just give train_loss but in my case it was giving {"train_loss" = x, "eval_loss" = 0}
> 
> def _restore_best_loss(self): """Restore the best loss from the args.best_path if provided else from the model (`args.continue_path`) used for resuming the training""" if self.args.continue_path and (self.restore_step != 0 or self.args.best_path): logger.info(" > Restoring best loss from %s ...", os.path.basename(self.args.best_path)) ch = load_fsspec(self.args.restore_path, map_location="cpu") if "model_loss" in ch: self.best_loss = ch["model_loss"] self.best_loss = self.best_loss['train_loss'] logger.info(" > Starting with loaded last best loss %f", self.best_loss)

After 2nd continue not working. Is it just me?

**Comment by erogol** [comment]
Looks like a bug in the Trainer. Feel free to send a PR. I won't be fixing it until I encounter it.
