### ISSUE TITLE
[Bug] Multispeaker inference using --speaker_idx

### ISSUE THREAD

**Issue by kin0303** [coqui-ai/TTS#2902]
### Describe the bug

I'm training yourtts using vctk formatter and I can't inference using --speaker idx. config.json:
```
{
    "output_path": "/Your_TTS/TTS",
    "logger_uri": null,
    "run_name": "YourTTS",
    "project_name": "YourTTS",
    "run_description": "\n            - YourTTS trained using  dataset\n        ",
    "print_step": 50,
    "plot_step": 100,
    "model_param_stats": false,
    "wandb_entity": null,
    "dashboard_logger": "tensorboard",
    "save_on_interrupt": true,
    "log_model_step": 1000,
    "save_step": 5000,
    "save_n_checkpoints": 5,
    "save_checkpoints": true,
    "save_all_best": false,
    "save_best_after": 10000,
    "target_loss": "loss_1",
    "print_eval": false,
    "test_delay_epochs": 0,
    "run_eval": true,
    "run_eval_steps": null,
    "distributed_backend": "nccl",
    "distributed_url": "tcp://localhost:54321",
    "mixed_precision": false,
    "precision": "fp16",
    "epochs": 1000,
    "batch_size": 4,
    "eval_batch_size": 4,
    "grad_clip": [
        1000.0,
        1000.0
    ],
    "scheduler_after_epoch": true,
    "lr": 0.001,
    "optimizer": "AdamW",
    "optimizer_params": {
        "betas": [
            0.8,
            0.99
        ],
        "eps": 1e-09,
        "weight_decay": 0.01
    },
    "lr_scheduler": null,
    "lr_scheduler_params": {},
    "use_grad_scaler": false,
    "allow_tf32": false,
    "cudnn_enable": true,
    "cudnn_deterministic": false,
    "cudnn_benchmark": false,
    "training_seed": 54321,
    "model": "vits",
    "num_loader_workers": 8,
    "num_eval_loader_workers": 0,
    "use_noise_augment": false,
    "audio": {
        "fft_size": 1024,
        "sample_rate": 22050,
        "win_length": 1024,
        "hop_length": 256,
        "num_mels": 80,
        "mel_fmin": 0,
        "mel_fmax": null
    },
    "use_phonemes": false,
    "phonemizer": "espeak",
    "phoneme_language": "id",
    "compute_input_seq_cache": true,
    "text_cleaner": "multilingual_cleaners",
    "enable_eos_bos_chars": false,
    "test_sentences_file": "",
    "phoneme_cache_path": null,
    "characters": {
        "characters_class": "TTS.tts.models.vits.VitsCharacters",
        "vocab_dict": null,
        "pad": "_",
        "eos": "&",
        "bos": "*",
        "blank": null,
        "characters": "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\u00af\u00b7\u00df\u00e0\u00e1\u00e2\u00e3\u00e4\u00e6\u00e7\u00e8\u00e9\u00ea\u00eb\u00ec\u00ed\u00ee\u00ef\u00f1\u00f2\u00f3\u00f4\u00f5\u00f6\u00f9\u00fa\u00fb\u00fc\u00ff\u0101\u0105\u0107\u0113\u0119\u011b\u012b\u0131\u0142\u0144\u014d\u0151\u0153\u015b\u016b\u0171\u017a\u017c\u01ce\u01d0\u01d2\u01d4\u0430\u0431\u0432\u0433\u0434\u0435\u0436\u0437\u0438\u0439\u043a\u043b\u043c\u043d\u043e\u043f\u0440\u0441\u0442\u0443\u0444\u0445\u0446\u0447\u0448\u0449\u044a\u044b\u044c\u044d\u044e\u044f\u0451\u0454\u0456\u0457\u0491\u2013!'(),-.:;? ",
        "punctuations": "!'(),-.:;? ",
        "phonemes": "",
        "is_unique": true,
        "is_sorted": true
    },
    "add_blank": true,
    "batch_group_size": 4,
    "loss_masking": null,
    "min_audio_len": 1,
    "max_audio_len": 286650,
    "min_text_len": 1,
    "max_text_len": Infinity,
    "compute_f0": false,
    "compute_energy": false,
    "compute_linear_spec": true,
    "precompute_num_workers": 12,
    "start_by_longest": true,
    "shuffle": false,
    "drop_last": false,
    "datasets": [
        {
            "formatter": "_multi",
            "dataset_name": "_multi",
            "path": "/Your_TTS/TTS/",
            "meta_file_train": "",
            "ignored_speakers": null,
            "language": "id",
            "phonemizer": "",
            "meta_file_val": "",
            "meta_file_attn_mask": ""
        }
    ],
    "test_sentences": [
        [
            "Awan adalah massa yang dapat dilihat dari tetesan air atau kristal beku yang menggantung di atmosfer yang berada di atas permukaan bumi atau permukaan planet lain.",
            "Karin",
            null,
            "id"
        ],
        [
            "Awan juga merupakan massa terlihat yang tertarik oleh gravitasi, seperti massa materi dalam ruang yang disebut awan antarbintang dan nebula.",
            "Faisal",
            null,
            "id"
        ]
    ],
    "eval_split_max_size": 256,
    "eval_split_size": 0.01,
    "use_speaker_weighted_sampler": false,
    "speaker_weighted_sampler_alpha": 1.0,
    "use_language_weighted_sampler": false,
    "language_weighted_sampler_alpha": 1.0,
    "use_length_weighted_sampler": false,
    "length_weighted_sampler_alpha": 1.0,
    "model_args": {
        "num_chars": 165,
        "out_channels": 513,
        "spec_segment_size": 32,
        "hidden_channels": 192,
        "hidden_channels_ffn_text_encoder": 768,
        "num_heads_text_encoder": 2,
        "num_layers_text_encoder": 10,
        "kernel_size_text_encoder": 3,
        "dropout_p_text_encoder": 0.1,
        "dropout_p_duration_predictor": 0.5,
        "kernel_size_posterior_encoder": 5,
        "dilation_rate_posterior_encoder": 1,
        "num_layers_posterior_encoder": 16,
        "kernel_size_flow": 5,
        "dilation_rate_flow": 1,
        "num_layers_flow": 4,
        "resblock_type_decoder": "2",
        "resblock_kernel_sizes_decoder": [
            3,
            7,
            11
        ],
        "resblock_dilation_sizes_decoder": [
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ]
        ],
        "upsample_rates_decoder": [
            8,
            8,
            2,
            2
        ],
        "upsample_initial_channel_decoder": 512,
        "upsample_kernel_sizes_decoder": [
            16,
            16,
            4,
            4
        ],
        "periods_multi_period_discriminator": [
            2,
            3,
            5,
            7,
            11
        ],
        "use_sdp": true,
        "noise_scale": 1.0,
        "inference_noise_scale": 0.667,
        "length_scale": 1.0,
        "noise_scale_dp": 1.0,
        "inference_noise_scale_dp": 1.0,
        "max_inference_len": null,
        "init_discriminator": true,
        "use_spectral_norm_disriminator": false,
        "use_speaker_embedding": false,
        "num_speakers": 0,
        "speakers_file": "/Your_TTS/TTS/YourTTS--August-15-2023_03+14PM-c87377b7/speakers.pth",
        "d_vector_file": [
            "/Your_TTS/TTS/Data/speakers.pth"
        ],
        "speaker_embedding_channels": 256,
        "use_d_vector_file": true,
        "d_vector_dim": 512,
        "detach_dp_input": true,
        "use_language_embedding": false,
        "embedded_language_dim": 4,
        "num_languages": 0,
        "language_ids_file": null,
        "use_speaker_encoder_as_loss": false,
        "speaker_encoder_config_path": "https://github.com/coqui-ai/TTS/releases/download/speaker_encoder_model/config_se.json",
        "speaker_encoder_model_path": "https://github.com/coqui-ai/TTS/releases/download/speaker_encoder_model/model_se.pth.tar",
        "condition_dp_on_speaker": true,
        "freeze_encoder": false,
        "freeze_DP": false,
        "freeze_PE": false,
        "freeze_flow_decoder": false,
        "freeze_waveform_decoder": false,
        "encoder_sample_rate": null,
        "interpolate_z": true,
        "reinit_DP": false,
        "reinit_text_encoder": false
    },
    "lr_gen": 0.0002,
    "lr_disc": 0.0002,
    "lr_scheduler_gen": "ExponentialLR",
    "lr_scheduler_gen_params": {
        "gamma": 0.999875,
        "last_epoch": -1
    },
    "lr_scheduler_disc": "ExponentialLR",
    "lr_scheduler_disc_params": {
        "gamma": 0.999875,
        "last_epoch": -1
    },
    "kl_loss_alpha": 1.0,
    "disc_loss_alpha": 1.0,
    "gen_loss_alpha": 1.0,
    "feat_loss_alpha": 1.0,
    "mel_loss_alpha": 45.0,
    "dur_loss_alpha": 1.0,
    "speaker_encoder_loss_alpha": 9.0,
    "return_wav": true,
    "use_weighted_sampler": true,
    "weighted_sampler_attrs": {
        "speaker_name": 1.0
    },
    "weighted_sampler_multipliers": {},
    "r": 1,
    "num_speakers": 0,
    "use_speaker_embedding": false,
    "speakers_file": "/Your_TTS/TTS/YourTTS--August-15-2023_03+14PM-c87377b7/speakers.pth",
    "speaker_embedding_channels": 256,
    "language_ids_file": null,
    "use_language_embedding": false,
    "use_d_vector_file": true,
    "d_vector_file": [
        "/Your_TTS/TTS/Data/speakers.pth"
    ],
    "d_vector_dim": 512
}
```

and when I running :
```tts --text "Calo atau makelar menurut Kamus Besar Bahasa Indonesia (KBBI) adalah orang yang menjadi perantara dan memberikan jasanya untuk menguruskan sesuatu berdasarkan upah." --out_path /Your_TTS/TTS/Output/speech_376019.wav --model_path /Your_TTS/TTS/YourTTS-Botika-August-15-2023_03+14PM-c87377b7/best_model_376019.pth --config_path /Your_TTS/TTS/YourTTS-Botika-August-15-2023_03+14PM-c87377b7/config.json --list_speaker_idx```

I got this error:
```
 > Using model: vits
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Available speaker ids: (Set --speaker_idx flag to one of these values to use the multi-speaker model.
{}
```

### To Reproduce

```
tts --text "Text for TTS" --out_path output/path/speech.wav --model_path /Your_TTS/TTS/YourTTS-Botika-August-15-2023_03+14PM-c87377b7/best_model_376019.pth --config_path /Your_TTS/TTS/YourTTS-Botika-August-15-2023_03+14PM-c87377b7/config.json --speakers_file_path p/Your_TTS/TTS/YourTTS-Botika-August-15-2023_03+14PM-c87377b7/speakers.pth --speaker_idx Karin
```

### Expected behavior

Can do the inference using --speaker_idx

### Logs

```shell
> Using model: vits
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Text: Text for TTS
 > Text splitted to sentences.
['Text for TTS']
Traceback (most recent call last):
  File ".local/bin/tts", line 8, in <module>
    sys.exit(main())
  File ".local/lib/python3.8/site-packages/TTS/bin/synthesize.py", line 350, in main
    wav = synthesizer.tts(
  File ".local/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 219, in tts
    speaker_embedding = self.tts_model.speaker_manager.get_mean_embedding(
  File ".local/lib/python3.8/site-packages/TTS/tts/utils/managers.py", line 214, in get_mean_embedding
    embeddings = self.get_embeddings_by_name(idx)
  File ".local/lib/python3.8/site-packages/TTS/tts/utils/managers.py", line 187, in get_embeddings_by_name
    return self.embeddings_by_names[idx]
KeyError: 'Karin'
```

### Environment

```
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce GTX 1660 Ti"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.16.2",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.9.17",
        "version": "#86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023"
    }
}
```

**Comment by Zeon8985Army** [comment]
Is YourTTS support Indonesian ?

**Comment by kin0303** [comment]
> Is YourTTS support Indonesian ? or you find a pretrained model or maybe you have created it from scratch ?

I think it's support all language. They use Espeak for phonemes and It supports Indonesian language

**Comment by Nanayeb34** [comment]
hey @kin0303 
I don't have a solution but I am facing a similar situation. I can't run inference when I pass in the speaker_idx. I get the ff error

```
! tts --text "I am a boy"\
 --config_path "/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/config.json"\
--model_path "/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/checkpoint_1054000.pth"\
 --out_path "/content/quantized_audio.wav"\
 --speakers_file_path "/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/speaker_ids.json"\
 --speaker_idx VCTK_elsie
```

```
> Using model: vits
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Model fully restored. 
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > External Speaker Encoder Loaded !!
 > Model fully restored. 
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Text: I am a boy
 > Text splitted to sentences.
['I am a boy']
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/TTS/bin/synthesize.py", line 446, in main
    wav = synthesizer.tts(
  File "/usr/local/lib/python3.10/dist-packages/TTS/utils/synthesizer.py", line 387, in tts
    outputs = synthesis(
  File "/usr/local/lib/python3.10/dist-packages/TTS/tts/utils/synthesis.py", line 221, in synthesis
    outputs = run_model_torch(
  File "/usr/local/lib/python3.10/dist-packages/TTS/tts/utils/synthesis.py", line 53, in run_model_torch
    outputs = _func(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/TTS/tts/models/vits.py", line 1161, in inference
    o = self.waveform_decoder((z * y_mask)[:, :, : self.max_inference_len], g=g)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/TTS/vocoder/models/hifigan_generator.py", line 250, in forward
    o = o + self.cond_layer(g)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
TypeError: conv1d() received an invalid combination of arguments - got (NoneType, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple of (int,), tuple of (int,), tuple of (int,), int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple of (int,), tuple of (int,), tuple of (int,), int)
```
When I however pass a speaker_wav file, it works fine. The Vits doc however states Vits should be able to run without having to pass in a speaker_wav

**Comment by osoman2** [comment]
> hey @kin0303 I don't have a solution but I am facing a similar situation. I can't run inference when I pass in the speaker_idx. I get the ff error
> 
> ```
> ! tts --text "I am a boy"\
>  --config_path "/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/config.json"\
> --model_path "/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/checkpoint_1054000.pth"\
>  --out_path "/content/quantized_audio.wav"\
>  --speakers_file_path "/content/drive/MyDrive/NSMQ AI Project/Technical/TTS/Prof Elsie Kauffmann/VITS model/vits-elsie/traineroutput/vits_vctk-May-24-2023_11+05PM-23a7a9a3/speaker_ids.json"\
>  --speaker_idx VCTK_elsie
> ```
> 
> ```
> > Using model: vits
>  > Setting up Audio Processor...
>  | > sample_rate:22050
>  | > resample:False
>  | > num_mels:80
>  | > log_func:np.log10
>  | > min_level_db:0
>  | > frame_shift_ms:None
>  | > frame_length_ms:None
>  | > ref_level_db:None
>  | > fft_size:1024
>  | > power:None
>  | > preemphasis:0.0
>  | > griffin_lim_iters:None
>  | > signal_norm:None
>  | > symmetric_norm:None
>  | > mel_fmin:0
>  | > mel_fmax:None
>  | > pitch_fmin:None
>  | > pitch_fmax:None
>  | > spec_gain:20.0
>  | > stft_pad_mode:reflect
>  | > max_norm:1.0
>  | > clip_norm:True
>  | > do_trim_silence:False
>  | > trim_db:60
>  | > do_sound_norm:False
>  | > do_amp_to_db_linear:True
>  | > do_amp_to_db_mel:True
>  | > do_rms_norm:False
>  | > db_level:None
>  | > stats_path:None
>  | > base:10
>  | > hop_length:256
>  | > win_length:1024
>  > Model fully restored. 
>  > Setting up Audio Processor...
>  | > sample_rate:16000
>  | > resample:False
>  | > num_mels:64
>  | > log_func:np.log10
>  | > min_level_db:-100
>  | > frame_shift_ms:None
>  | > frame_length_ms:None
>  | > ref_level_db:20
>  | > fft_size:512
>  | > power:1.5
>  | > preemphasis:0.97
>  | > griffin_lim_iters:60
>  | > signal_norm:False
>  | > symmetric_norm:False
>  | > mel_fmin:0
>  | > mel_fmax:8000.0
>  | > pitch_fmin:1.0
>  | > pitch_fmax:640.0
>  | > spec_gain:20.0
>  | > stft_pad_mode:reflect
>  | > max_norm:4.0
>  | > clip_norm:False
>  | > do_trim_silence:False
>  | > trim_db:60
>  | > do_sound_norm:False
>  | > do_amp_to_db_linear:True
>  | > do_amp_to_db_mel:True
>  | > do_rms_norm:True
>  | > db_level:-27.0
>  | > stats_path:None
>  | > base:10
>  | > hop_length:160
>  | > win_length:400
>  > External Speaker Encoder Loaded !!
>  > Model fully restored. 
>  > Setting up Audio Processor...
>  | > sample_rate:16000
>  | > resample:False
>  | > num_mels:64
>  | > log_func:np.log10
>  | > min_level_db:-100
>  | > frame_shift_ms:None
>  | > frame_length_ms:None
>  | > ref_level_db:20
>  | > fft_size:512
>  | > power:1.5
>  | > preemphasis:0.97
>  | > griffin_lim_iters:60
>  | > signal_norm:False
>  | > symmetric_norm:False
>  | > mel_fmin:0
>  | > mel_fmax:8000.0
>  | > pitch_fmin:1.0
>  | > pitch_fmax:640.0
>  | > spec_gain:20.0
>  | > stft_pad_mode:reflect
>  | > max_norm:4.0
>  | > clip_norm:False
>  | > do_trim_silence:False
>  | > trim_db:60
>  | > do_sound_norm:False
>  | > do_amp_to_db_linear:True
>  | > do_amp_to_db_mel:True
>  | > do_rms_norm:True
>  | > db_level:-27.0
>  | > stats_path:None
>  | > base:10
>  | > hop_length:160
>  | > win_length:400
>  > Text: I am a boy
>  > Text splitted to sentences.
> ['I am a boy']
> Traceback (most recent call last):
>   File "/usr/local/bin/tts", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/TTS/bin/synthesize.py", line 446, in main
>     wav = synthesizer.tts(
>   File "/usr/local/lib/python3.10/dist-packages/TTS/utils/synthesizer.py", line 387, in tts
>     outputs = synthesis(
>   File "/usr/local/lib/python3.10/dist-packages/TTS/tts/utils/synthesis.py", line 221, in synthesis
>     outputs = run_model_torch(
>   File "/usr/local/lib/python3.10/dist-packages/TTS/tts/utils/synthesis.py", line 53, in run_model_torch
>     outputs = _func(
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/TTS/tts/models/vits.py", line 1161, in inference
>     o = self.waveform_decoder((z * y_mask)[:, :, : self.max_inference_len], g=g)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/TTS/vocoder/models/hifigan_generator.py", line 250, in forward
>     o = o + self.cond_layer(g)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 313, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
>     return F.conv1d(input, weight, bias, self.stride,
> TypeError: conv1d() received an invalid combination of arguments - got (NoneType, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
>  * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
>       didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple of (int,), tuple of (int,), tuple of (int,), int)
>  * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
>       didn't match because some of the arguments have invalid types: (NoneType, Parameter, Parameter, tuple of (int,), tuple of (int,), tuple of (int,), int)
> ```
> 
> When I however pass a speaker_wav file, it works fine. The Vits doc however states Vits should be able to run without having to pass in a speaker_wav

Following this issue. I've been having the same issue. Do you have the solution @Nanayeb34 ?
