### ISSUE TITLE
[Bug] Unable to train "No training samples found"

### ISSUE THREAD

**Issue by RinLovesYou** [coqui-ai/TTS#2931]
### Describe the bug

I am trying to train a model, looking through the documentation i have prepared some wav files and a metadata.txt, yet when i run the delightful recipe for instance, it claims it can't find any training samples.

### To Reproduce

![image](https://github.com/coqui-ai/TTS/assets/29461788/efdbb610-0b8f-4e78-afe0-7ba80251985b)

Metadata.txt contains text formatted like
```
001|some sentence.
002|some sentence.
etc..
```

I am well aware 3 files isn't nearly enough, i am just trying to get a grasp on the pipeline before properly training it. I can not understand why it says there are no training samples. Perhaps this is not a bug and i missed something, if so i apologize and ask you to point me in the right direction ❤️

```python
data_path = "/home/sarah/Documents/github/TTS/delightfultest/dataset"
output_path = os.path.dirname(os.path.abspath(__file__))


dataset_config = BaseDatasetConfig(
    formatter="vctk", meta_file_train="metadata.txt", path=data_path, language="en-us"
)
```

```
[sarah@archbtw delightfultest]$  CUDA_VISIBLE_DEVICES="0" python test.py 
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:100
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:8000
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
Traceback (most recent call last):
  File "/home/sarah/Documents/github/TTS/delightfultest/test.py", line 65, in <module>
    train_samples, eval_samples = load_tts_samples(
  File "/home/sarah/Documents/github/TTS/TTS/tts/datasets/__init__.py", line 121, in load_tts_samples
    assert len(meta_data_train) > 0, f" [!] No training samples found in {root_path}/{meta_file_train}"
AssertionError:  [!] No training samples found in /home/sarah/Documents/github/TTS/delightfultest/dataset/metadata.txt
```

### Expected behavior

It would find the audio files and the transcription and start training

### Logs

```shell
already included all errors
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 2070 SUPER"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu117",
        "TTS": "0.16.6",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.10.11",
        "version": "#1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000"
    }
}
```

### Additional context

Do note that i am installing and pulling directly from source `dev` branch

**Comment by RinLovesYou** [comment]
I had to use the custom formatter, didn't catch that
