### ISSUE TITLE
[Bug] `pip install TTS` failing, related to NumPy

### ISSUE THREAD

**Issue by jro-cambria** [coqui-ai/TTS#2932]
### Describe the bug

Hello - I'm trying to install TTS for the first time on a Mac, so that I can have a local text-to-speech generator, and I'm getting an error upon installation, using `pip3`.

## System Details
Computer: MacBook Pro, 2021 Apple M1 Max
OS: MacOS Ventura 13.5.1
Python version: 3.11.5

From install instructions: "TTS is tested on Ubuntu 18.04 with python >= 3.7, < 3.11.."

From logs: " NumPy 1.22.0 may not yet support Python 3.11."

"Custom 'build_py' does not implement 'get_data_files_without_manifest'.
                    Please extend command classes from setuptools instead of distutils."

### To Reproduce

pip3 install TTS 

### Expected behavior

Installation of TTS

### Logs

```shell
jro@JRO-Laptop Text-to-speech % pip3 install TTS
Collecting TTS
  Using cached TTS-0.16.6.tar.gz (1.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/82/3b/0715493246eb08e93506f4da0efe1d05a3c9d9ac3b76e97cc362890e6adf/setuptools-68.2.0-py3-none-any.whl.metadata
        Using cached setuptools-68.2.0-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting cython==0.29.30
        Using cached Cython-0.29.30-py2.py3-none-any.whl (985 kB)
      Collecting numpy==1.22.0
        Using cached numpy-1.22.0.zip (11.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [94 lines of output]
            <string>:66: RuntimeWarning: NumPy 1.22.0 may not yet support Python 3.11.
            Running from numpy source directory.
            running egg_info
            running build_src
            INFO: build_src
            creating numpy.egg-info
            writing numpy.egg-info/PKG-INFO
            writing dependency_links to numpy.egg-info/dependency_links.txt
            writing entry points to numpy.egg-info/entry_points.txt
            writing top-level names to numpy.egg-info/top_level.txt
            writing manifest file 'numpy.egg-info/SOURCES.txt'
            /opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py:126: SetuptoolsDeprecationWarning: `build_py` command does not inherit from setuptools' `build_py`.
            !!
      
                    ********************************************************************************
                    Custom 'build_py' does not implement 'get_data_files_without_manifest'.
                    Please extend command classes from setuptools instead of distutils.
      
                    See https://peps.python.org/pep-0632/ for details.
                    ********************************************************************************
      
            !!
              self._add_data_files(self._safe_data_files(build_py))
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            Traceback (most recent call last):
              File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
                return hook(config_settings)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
                return self._get_build_requires(config_settings, requirements=['wheel'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
                self.run_setup()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
                super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
                exec(code, locals())
              File "<string>", line 450, in <module>
              File "<string>", line 442, in setup_package
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
                       ^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
                super().run_command(command)
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/9n/trgty1s93c3070xl9r5383p00000gn/T/pip-install-qe5q5j6t/numpy_0b9879d093ad42079f0929cd18edd218/numpy/distutils/command/egg_info.py", line 25, in run
                _egg_info.run(self)
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 319, in run
                self.find_sources()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
                mm.run()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 549, in run
                self.add_defaults()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
                sdist.add_defaults(self)
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 114, in add_defaults
                self._add_defaults_build_sub_commands()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 134, in _add_defaults_build_sub_commands
                self.filelist.extend(chain.from_iterable(files))
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 492, in extend
                self.files.extend(filter(self._safe_path, paths))
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 133, in <genexpr>
                files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 132, in <genexpr>
                cmds = (self.get_finalized_command(c) for c in missing_cmds)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
                cmd_obj.ensure_finalized()
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
                self.finalize_options()
              File "/private/var/folders/9n/trgty1s93c3070xl9r5383p00000gn/T/pip-install-qe5q5j6t/numpy_0b9879d093ad42079f0929cd18edd218/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
                v = getattr(c, a)
                    ^^^^^^^^^^^^^
              File "/private/var/folders/9n/trgty1s93c3070xl9r5383p00000gn/T/pip-build-env-4q4rxfej/overlay/lib/python3.11/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
                return _build_ext.build_ext.__getattr__(self, name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
                raise AttributeError(attr)
            AttributeError: fcompiler. Did you mean: 'compiler'?
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1",
        "numpy": "1.25.2"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "arm",
        "python": "3.11.5",
        "version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000"
    }
}
```

**Comment by jro-cambria** [comment]
Update:
I noticed that that NumPy mentioned it was not compatible with Python 3.11, so was able to install using

`python3.10 -m pip install TTS`

**Comment by jkobject** [comment]
yes or `python3 -m` on my end

**Comment by erogol** [comment]
I think this is a duplicate for #2986

**Comment by sorgfresser** [comment]
Not 100% sure if it's a dupe. I was able to produce #2986 with python 3.9 too

**Comment by erogol** [comment]
Should be fixed by the latest release
