### ISSUE TITLE
[Bug] variable type 

### ISSUE THREAD

**Issue by qwdh** [coqui-ai/TTS#2965]
### Describe the bug

NoneType variable is an object thus none iterable.

### To Reproduce

 > Using model: tortoise
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 385, in main
    synthesizer = Synthesizer(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 107, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 162, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/tts/models/tortoise.py", line 879, in load_checkpoint
    for pat in keys_to_ignore:
TypeError: 'NoneType' object is not iterable
FAIL

======================================================================
FAIL: tests.zoo_tests.test_models.test_models_offset_1_step_3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/TTS/TTS/tests/zoo_tests/test_models.py", line 75, in test_models_offset_1_step_3
    run_models(offset=1, step=3)
  File "/home/runner/work/TTS/TTS/tests/zoo_tests/test_models.py", line 47, in run_models
    run_cli(
  File "/home/runner/work/TTS/TTS/tests/__init__.py", line 43, in run_cli
    assert exit_status == 0, f" [!] command `{command}` failed."
AssertionError:  [!] command `tts --model_name  tts_models/en/multi-dataset/tortoise-v2 --text "This is an example." --out_path "/home/runner/work/TTS/TTS/tests/outputs/output.wav" --progress_bar False` failed.

### Logs

```shell
> Using model: tortoise
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 385, in main
    synthesizer = Synthesizer(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 107, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 162, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/TTS/tts/models/tortoise.py", line 879, in load_checkpoint
    for pat in keys_to_ignore:
TypeError: 'NoneType' object is not iterable
FAIL

======================================================================
FAIL: tests.zoo_tests.test_models.test_models_offset_1_step_3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/TTS/TTS/tests/zoo_tests/test_models.py", line 75, in test_models_offset_1_step_3
    run_models(offset=1, step=3)
  File "/home/runner/work/TTS/TTS/tests/zoo_tests/test_models.py", line 47, in run_models
    run_cli(
  File "/home/runner/work/TTS/TTS/tests/__init__.py", line 43, in run_cli
    assert exit_status == 0, f" [!] command `{command}` failed."
AssertionError:  [!] command `tts --model_name  tts_models/en/multi-dataset/tortoise-v2 --text "This is an example." --out_path "/home/runner/work/TTS/TTS/tests/outputs/output.wav" --progress_bar False` failed.
```

### Environment

```shell
Python 3.9, 3.10, 3.11
```

### Additional context

Will work on figuring out a fix

**Comment by WeberJulian** [comment]
Could you try `pip install transformers==4.33.0` ?
