### ISSUE TITLE
Speaker encoder model fails.

### ISSUE THREAD

**Issue by Arunes007** [coqui-ai/TTS#3020]
### Describe the bug

While using [this](https://github.com/coqui-ai/TTS/releases/tag/speaker_encoder_model) speaker encoder model. I am getting error. I am using FastPitch model for generating Hindi audio by running this command:

tts --text "बहुत समय पहले की बात है" --model_path $model_path --config_path $config_path  --speakers_file_path $speakers_file_path --out_path $out_path --vocoder_path $vocoder_path --vocoder_config_path $vocoder_config --speaker_wav $speaker_wav  --encoder_path $encoding_path --encoder_config_path $encoder_config --device cpu

### To Reproduce

Run the following command by giving model
tts --text "बहुत समय पहले की बात है" --model_path <> --config_path <>  --speakers_file_path $speakers_file_path --out_path $out_path --vocoder_path $vocoder_path --vocoder_config_path $vocoder_config --speaker_wav $speaker_wav  --encoder_path $encoding_path --encoder_config_path $encoder_config --device cpu

### Logs

```shell
> Using model: fast_pitch
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Init speaker_embedding layer.
 > Model fully restored. 
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:64
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:512
 | > power:1.5
 | > preemphasis:0.97
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:False
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:True
 | > db_level:-27.0
 | > stats_path:None
 | > base:10
 | > hop_length:160
 | > win_length:400
 > Vocoder Model: hifigan
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 > Text: बहुत समय पहले की बात है
 > Text splitted to sentences.
['बहुत समय पहले की बात है']
Traceback (most recent call last):
  File "/Users/M/miniforge3/envs/tts/bin/tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/TTS/bin/synthesize.py", line 476, in main
    wav = synthesizer.tts(
          ^^^^^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/TTS/utils/synthesizer.py", line 387, in tts
    outputs = synthesis(
              ^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/TTS/tts/utils/synthesis.py", line 221, in synthesis
    outputs = run_model_torch(
              ^^^^^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/TTS/tts/utils/synthesis.py", line 53, in run_model_torch
    outputs = _func(
              ^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/TTS/tts/models/forward_tts.py", line 684, in inference
    o_en, x_mask, g, _ = self._forward_encoder(x, x_mask, g)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/TTS/tts/models/forward_tts.py", line 399, in _forward_encoder
    g = self.emb_g(g)  # [B, C, 1]
        ^^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/Users/M/miniforge3/envs/tts/lib/python3.11/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1",
        "TTS": "0.17.6",
        "numpy": "1.24.3"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "arm",
        "python": "3.11.0",
        "version": "Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000"
    }
}
```

**Comment by erogol** [comment]
@Aya-AlJafari can you check this?

**Comment by Aya-AlJafari** [comment]
@Arunes007 Hi, can you specify the exact environment variables you passed to the command arguments?

`tts --text "बहुत समय पहले की बात है" --model_path <> --config_path <> --speakers_file_path $speakers_file_path --out_path $out_path --vocoder_path $vocoder_path --vocoder_config_path $vocoder_config --speaker_wav $speaker_wav --encoder_path $encoding_path --encoder_config_path $encoder_config --device cpu`
