### ISSUE TITLE
[Bug] tts_to_file gives TypeError: Invalid file: None

### ISSUE THREAD

**Issue by perrylets** [coqui-ai/TTS#3067]
### Describe the bug

When using the xtts-1 model on windows (python 3.11.6), every time I run the `tts_to_file` function, it gives the error `TypeError: Invalid file: None`

### To Reproduce

On windows with python 3.11.6, with torch, torchaudio (not sure if needed, but just to be sure) and TTS installed, run this snippet
```python
import torch
from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1").to("cuda" if toch.cuda.is_available() else "cpu")
# any combination of parameters gives the same error.
tts.tts_to_file("Hello, world!", language="en") # Expected error: "TypeError: Invalid file: None"
```

### Expected behavior

The audio output should be written to output.wav, or the specified file name.

### Environment

```shell
- 🐸TTS Version: 0.17.8
- PyTorch Version: 2.1.0+cpu
- Python Version: 3.11.6
- OS: Windows 11
- CUDA/cuDNN version: null
- GPU models and configuration: AMD Ryzen 7 5700G with Radeon Graphics
- How you installed PyTorch: pip on a virtual environment
```

**Comment by erogol** [comment]
@Aya-AlJafari can you check this ?

**Comment by taha9881** [comment]
speaker_wav="cloning/audio.wav"
file_path="output.wav"

Try adding this two argument, Make the respective directory for speaker_wav and add sample audio file in .wav format.

**Comment by perrylets** [comment]
I already did that before making the issue.

**Comment by Aya-AlJafari** [comment]
Hi @perrylets, can you please post the full log after executing this command: 

`tts.tts_to_file("Hello, world!",file_path="output.wav", speaker_wav="path/to/wavefile", language="en")`

because the missing `speaker_wav` in `tts.tts_to_file("Hello, world!", language="en")` is the source of the `None` error, and the alternative above should fix it. I'm curious to see the log if it's still not working on your side.

**Comment by perrylets** [comment]
Where are the logs? Is it just the console output?

**Comment by Aya-AlJafari** [comment]
@perrylets yes the full output.

**Comment by Mikerhinos** [comment]
I'm having the same error while using the tts.tts_with_vc_to_file() method even after adding the speaker_wav path, using xtts_v1 or xtts_v1.1

**Comment by gorip1** [comment]
Hi, same error for me using `xtts_v1.1` & `tts.tts_with_vc_to_file()`

**main.py :** 
``` python
from TTS.api import TTS
tts = TTS(model_name="tts_models/multilingual/multi-dataset/xtts_v1.1", progress_bar=True).to("cpu")
tts.tts_with_vc_to_file(
    text="Hi guys how are you ?",
    speaker_wav="TTS/real_audio_sample/me_speaking.wav",
    file_path="output.wav",
    language="en"
```


**Full output :** 
``` python
 > tts_models/multilingual/multi-dataset/xtts_v1.1 is already downloaded.
 > Using model: xtts
/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/Users/XXX/PycharmProjects/coquiTTS/main.py", line 9, in <module>
    tts.tts_with_vc_to_file(
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/api.py", line 488, in tts_with_vc_to_file
    wav = self.tts_with_vc(text=text, language=language, speaker_wav=speaker_wav)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/api.py", line 463, in tts_with_vc
    self.tts_to_file(text=text, speaker=None, language=language, file_path=fp.name)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/api.py", line 403, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/api.py", line 341, in tts
    wav = self.synthesizer.tts(
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 374, in tts
    outputs = self.tts_model.synthesize(
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 462, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 484, in inference_with_config
    return self.full_inference(text, ref_audio_path, language, **settings)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 570, in full_inference
    ) = self.get_conditioning_latents(audio_path=ref_audio_path, gpt_cond_len=gpt_cond_len)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 435, in get_conditioning_latents
    speaker_embedding = self.get_speaker_embedding(audio_path)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 421, in get_speaker_embedding
    audio = load_audio(audio_path, self.hifigan_decoder.speaker_encoder_audio_config["sample_rate"])
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/TTS/tts/models/xtts.py", line 34, in load_audio
    audio, sampling_rate = torchaudio.load(audiopath)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/torchaudio/_backend/utils.py", line 203, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/torchaudio/_backend/soundfile.py", line 26, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/torchaudio/_backend/soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/Users/XXX/PycharmProjects/coquiTTS/venv/lib/python3.9/site-packages/soundfile.py", line 1212, in _open
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: None
```

Hope it'll help 🤞

**Comment by lucasjinreal** [comment]
Hi, how to load model from local path?

    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
