### ISSUE TITLE
[Bug] Error when continuing training with vctk vits

### ISSUE THREAD

**Issue by pearbender** [coqui-ai/TTS#3069]
### Describe the bug

Starting a training session from a previous one like
```
C:\Users\user\code\TTS\recipes\vctk\vits>train_vits.py --continue_path "vits_vctk-October-14-2023_10+28AM-99635193"
```
results in an error after the first epoch.

```
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\io.py", line 183, in save_best_model
    if current_loss < best_loss:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'dict'
```

### To Reproduce

1. Train using the vctk vits recipie.
2. End training
3. Resume training with `--continue_path`

### Expected behavior

Training continues successfully

### Logs

```shell
(env) C:\Users\user\code\TTS\recipes\vctk\vits>train_vits.py --continue_path "vits_vctk-October-14-2023_10+28AM-99635193"
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 531 files in C:\Users\user\code\TTS\recipes\vctk\vits\pero
 > initialization of speaker-embedding layers.
C:\Users\user\code\TTS\env\Lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: True
 | > Precision: fp16
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 20
 | > Num. of Torch Threads: 14
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=vits_vctk-October-14-2023_10+28AM-99635193
 > `speakers.pth` is saved to vits_vctk-October-14-2023_10+28AM-99635193\speakers.pth.
 > `speakers_file` is updated in the config.json.
 > Restoring from checkpoint_1010000.pth ...
 > Restoring Model...
 > Restoring Optimizer...
 > Restoring Scaler...
 > Model restored from step 1010000

 > Model has 86410668 parameters
 > Restoring best loss from best_model_1001752.pth ...
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not dict
Call stack:
  File "C:\Users\user\code\TTS\recipes\vctk\vits\train_vits.py", line 105, in <module>
    main()
  File "C:\Users\user\code\TTS\recipes\vctk\vits\train_vits.py", line 100, in main
    trainer.fit()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1808, in fit
    self._fit()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1746, in _fit
    self._restore_best_loss()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1710, in _restore_best_loss
    logger.info(" > Starting with loaded last best loss %f", self.best_loss)
Message: ' > Starting with loaded last best loss %f'
Arguments: {'train_loss': 11.944393793741861, 'eval_loss': None}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: must be real number, not dict
Call stack:
  File "C:\Users\user\code\TTS\recipes\vctk\vits\train_vits.py", line 105, in <module>
    main()
  File "C:\Users\user\code\TTS\recipes\vctk\vits\train_vits.py", line 100, in main
    trainer.fit()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1808, in fit
    self._fit()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1746, in _fit
    self._restore_best_loss()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1710, in _restore_best_loss
    logger.info(" > Starting with loaded last best loss %f", self.best_loss)
Message: ' > Starting with loaded last best loss %f'
Arguments: {'train_loss': 11.944393793741861, 'eval_loss': None}

 > EPOCH: 0/1000
 --> vits_vctk-October-14-2023_10+28AM-99635193


> DataLoader initialization
| > Tokenizer:
        | > add_blank: True
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: espeak
| > Number of instances : 526
 | > Preprocessing samples
 | > Max text length: 143
 | > Min text length: 11
 | > Avg text length: 43.29467680608365
 |
 | > Max audio length: 277852.0
 | > Min audio length: 35302.0
 | > Avg audio length: 67769.15779467681
 | > Num. instances discarded samples: 0
 | > Batch group size: 160.

 > TRAINING (2023-10-16 18:46:39)
C:\Users\user\code\TTS\env\Lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ..\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]


> DataLoader initialization
| > Tokenizer:
        | > add_blank: True
        | > use_eos_bos: False
        | > use_phonemes: True
        | > phonemizer:
                | > phoneme language: en-us
                | > phoneme backend: espeak
| > Number of instances : 5
 | > Preprocessing samples
 | > Max text length: 103
 | > Min text length: 23
 | > Avg text length: 49.8
 |
 | > Max audio length: 141142.0
 | > Min audio length: 35302.0
 | > Avg audio length: 71464.0
 | > Num. instances discarded samples: 0
 | > Batch group size: 0.

 > EVALUATION

 | > Synthesizing test sentences.
C:\Users\user\code\TTS\TTS\tts\models\vits.py:1455: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3618.)
  test_figures["{}-alignment".format(idx)] = plot_alignment(alignment.T, output_fig=False)

  --> EVAL PERFORMANCE
     | > avg_loader_time: 3.5880024433135986 (+0)
     | > avg_loss_disc: 2.8253118991851807 (+0)
     | > avg_loss_disc_real_0: 0.29010456800460815 (+0)
     | > avg_loss_disc_real_1: 0.34353992342948914 (+0)
     | > avg_loss_disc_real_2: 0.2349240928888321 (+0)
     | > avg_loss_disc_real_3: 0.23307518661022186 (+0)
     | > avg_loss_disc_real_4: 0.2128710299730301 (+0)
     | > avg_loss_disc_real_5: 0.21233540773391724 (+0)
     | > avg_loss_0: 2.8253118991851807 (+0)
     | > avg_loss_gen: 1.8743318319320679 (+0)
     | > avg_loss_kl: 6.808666706085205 (+0)
     | > avg_loss_feat: 1.9743752479553223 (+0)
     | > avg_loss_mel: 15.583901405334473 (+0)
     | > avg_loss_duration: 1.7729015350341797 (+0)
     | > avg_loss_1: 28.014177322387695 (+0)

 ! Run is kept in vits_vctk-October-14-2023_10+28AM-99635193
Traceback (most recent call last):
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1808, in fit
    self._fit()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1771, in _fit
    self.save_best_model()
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\utils\distributed.py", line 35, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\trainer.py", line 1893, in save_best_model
    self.best_loss = save_best_model(
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\user\code\TTS\env\Lib\site-packages\trainer\io.py", line 183, in save_best_model
    if current_loss < best_loss:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'dict'

(env) C:\Users\user\code\TTS\recipes\vctk\vits>
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu118",
        "TTS": "0.17.8",
        "numpy": "1.24.3"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
        "python": "3.11.5",
        "version": "10.0.19045"
    }
}
```

**Comment by erogol** [comment]
probably bug in the trainer

**Comment by WeberJulian** [comment]
For now, maybe you can try `--restore_path` to your best checkpoint instead.

**Comment by nahue-passano** [comment]
> For now, maybe you can try `--restore_path` to your best checkpoint instead.

This works fine, thanks!
