### ISSUE TITLE
[Bug]  ı cant get downloads weight and cant create config files

### ISSUE THREAD

**Issue by nto4** [coqui-ai/TTS#3088]
### Describe the bug

I think so that links dosnt work and more propably

                        "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v1/model.pth",
                        "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v1/config.json",
                        "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v1/vocab.json"
                        
                        

### To Reproduce

just delete all weight and try  reinstall 

rm -rf /root/.local/share/tts

tts --model_name tts_models/multilingual/multi-dataset/xtts_v1      --text "It took me."      --speaker_wav /coquio_ttsx_vish_coqui/code/voices/michael/Michael_2.wav      --language_idx en      --out_path /coquio_ttsx_vish_coqui/code/sil2222.wav

### Expected behavior

download weight and configs

### Logs

```shell
leancoquio_xtts_venv) root@DESKTOP-RUI9N9R:/coquio_ttsx_vish_coqui/code# tts --model_name tts_models/multilingual/multi-dataset/xtts_v1      --text "It took me."      --speaker_wav /coquio_ttsx_vish_coqui/code/voices/michael/Michael_2.wav      --language_idx en      --out_path /coquio_ttsx_vish_coqui/code/sil2222.wav
 > You must agree to the terms of service to use this model.
 | > Please see the terms of service at https://coqui.ai/cpml.txt
 | > "I have read, understood and agreed the Terms and Conditions." - [y/n]
 | | > y
 > Downloading model to /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v1
0.00iB [00:01, ?iB/s]
 > Model's license - CPML
 > Check https://coqui.ai/cpml.txt for more info.
Traceback (most recent call last):
  File "/coquio_ttsx_vish_coqui/cleancoquio_xtts_venv/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/coquio_ttsx_vish_coqui/cleancoquio_xtts_venv/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 401, in main
    synthesizer = Synthesizer(
  File "/coquio_ttsx_vish_coqui/cleancoquio_xtts_venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/coquio_ttsx_vish_coqui/cleancoquio_xtts_venv/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 161, in _load_tts_from_dir
    config = load_config(os.path.join(model_dir, "config.json"))
  File "/coquio_ttsx_vish_coqui/cleancoquio_xtts_venv/lib/python3.10/site-packages/TTS/config/__init__.py", line 95, in load_config
    data = read_json_with_comments(config_path)
  File "/coquio_ttsx_vish_coqui/cleancoquio_xtts_venv/lib/python3.10/site-packages/TTS/config/__init__.py", line 22, in read_json_with_comments
    data = json.loads(input_str)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 4070"
        ],
        "available": true,
        "version": "11.7"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu117",
        "TTS": "0.17.5",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
    }
}
```

**Comment by WeberJulian** [comment]
Yeah you'll need to update TTS to `0.17.7` or `0.17.10`.

**Comment by nto4** [comment]
why i want to use 0.17.5 its voice quality much better than other versions ?
why u removin that weights ?
