### ISSUE TITLE
[Bug] Japanese not working from CLI

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/TTS#3098]
### Describe the bug

```
% TTS --model_name tts_models/multilingual/multi-dataset/xtts_v1.1 --text "こんにちは私の良き友人！" --language_idx ja --out_path "foo.wav" --speaker_wav "/Users/josh/Downloads/female-hispanola.wav"
 > tts_models/multilingual/multi-dataset/xtts_v1.1 is already downloaded.
 > Using model: xtts
 > Text: こんにちは私の良き友人！
 > Text splitted to sentences.
['こんにちは私の良き友人！']
Traceback (most recent call last):
  File "/opt/homebrew/bin/TTS", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/TTS/bin/synthesize.py", line 529, in main
    wav = synthesizer.tts(
          ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/TTS/utils/synthesizer.py", line 374, in tts
    outputs = self.tts_model.synthesize(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/TTS/tts/models/xtts.py", line 462, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/TTS/tts/models/xtts.py", line 469, in inference_with_config
    language in self.config.languages
AssertionError:  ❗ Language ja is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn']
```

### To Reproduce

```
$ pip list | grep TTS
TTS                       0.18.2
```

current version

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1",
        "TTS": "0.18.2",
        "numpy": "1.24.3"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "arm",
        "python": "3.11.4",
        "version": "Darwin Kernel Version 21.6.0: Thu Jul  6 22:20:00 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_ARM64_T6000"
    }
}
```

**Comment by akshathmangudi** [comment]
Have you looked into pykakasi? I would like this to be assigned to me, this looks interesting.

**Comment by erogol** [comment]
@Edresson can you deal with this?
