### ISSUE TITLE
KeyError: 'xtts_v1'

### ISSUE THREAD

**Issue by a-3isa** [coqui-ai/TTS#3099]
Hey, when i run the following python api i encounter KeyError :'xtts_v1'

```
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1").to(device)

# Run TTS
# ❗ Since this model is multi-lingual voice cloning model, we must set the target speaker_wav and language
# Text to speech list of amplitude values as output
wav = tts.tts(text="Hello world!", speaker_wav="my/cloning/audio.wav", language="en")
# Text to speech to a file
tts.tts_to_file(text="Hello world!", speaker_wav="my/cloning/audio.wav", language="en", file_path="output.wav")
```

### The Error

```
No API token found for 🐸Coqui Studio voices - https://coqui.ai 
Visit 🔗https://app.coqui.ai/account to get one.
Set it as an environment variable `export COQUI_STUDIO_TOKEN=<token>`

['tts_models/multilingual/multi-dataset/your_tts', 'tts_models/bg/cv/vits', 'tts_models/cs/cv/vits', 'tts_models/da/cv/vits', 'tts_models/et/cv/vits', 'tts_models/ga/cv/vits', 'tts_models/en/ek1/tacotron2', 'tts_models/en/ljspeech/tacotron2-DDC', 'tts_models/en/ljspeech/tacotron2-DDC_ph', 'tts_models/en/ljspeech/glow-tts', 'tts_models/en/ljspeech/speedy-speech', 'tts_models/en/ljspeech/tacotron2-DCA', 'tts_models/en/ljspeech/vits', 'tts_models/en/ljspeech/vits--neon', 'tts_models/en/ljspeech/fast_pitch', 'tts_models/en/ljspeech/overflow', 'tts_models/en/ljspeech/neural_hmm', 'tts_models/en/vctk/vits', 'tts_models/en/vctk/fast_pitch', 'tts_models/en/sam/tacotron-DDC', 'tts_models/en/blizzard2013/capacitron-t2-c50', 'tts_models/en/blizzard2013/capacitron-t2-c150_v2', 'tts_models/en/multi-dataset/tortoise-v2', 'tts_models/en/jenny/jenny', 'tts_models/es/mai/tacotron2-DDC', 'tts_models/es/css10/vits', 'tts_models/fr/mai/tacotron2-DDC', 'tts_models/fr/css10/vits', 'tts_models/uk/mai/glow-tts', 'tts_models/uk/mai/vits', 'tts_models/zh-CN/baker/tacotron2-DDC-GST', 'tts_models/nl/mai/tacotron2-DDC', 'tts_models/nl/css10/vits', 'tts_models/de/thorsten/tacotron2-DCA', 'tts_models/de/thorsten/vits', 'tts_models/de/thorsten/tacotron2-DDC', 'tts_models/de/css10/vits-neon', 'tts_models/ja/kokoro/tacotron2-DDC', 'tts_models/tr/common-voice/glow-tts', 'tts_models/it/mai_female/glow-tts', 'tts_models/it/mai_female/vits', 'tts_models/it/mai_male/glow-tts', 'tts_models/it/mai_male/vits', 'tts_models/ewe/openbible/vits', 'tts_models/hau/openbible/vits', 'tts_models/lin/openbible/vits', 'tts_models/tw_akuapem/openbible/vits', 'tts_models/tw_asante/openbible/vits', 'tts_models/yor/openbible/vits', 'tts_models/hu/css10/vits', 'tts_models/el/cv/vits', 'tts_models/fi/css10/vits', 'tts_models/hr/cv/vits', 'tts_models/lt/cv/vits', 'tts_models/lv/cv/vits', 'tts_models/mt/cv/vits', 'tts_models/pl/mai_female/vits', 'tts_models/pt/cv/vits', 'tts_models/ro/cv/vits', 'tts_models/sk/cv/vits', 'tts_models/sl/cv/vits', 'tts_models/sv/cv/vits', 'tts_models/ca/custom/vits', 'tts_models/fa/custom/glow-tts', 'tts_models/bn/custom/vits-male', 'tts_models/bn/custom/vits-female']
Traceback (most recent call last):
  File "d:/liveManga/work.py", line 11, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1").to(device)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\TTS\api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\TTS\api.py", line 386, in load_tts_model_by_name
    model_name
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\TTS\api.py", line 348, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\TTS\utils\manage.py", line 287, in download_model
    model_item, model_full_name, model = self._set_model_item(model_name)
  File "C:\Users\smart\AppData\Local\Programs\Python\Python37\lib\site-packages\TTS\utils\manage.py", line 269, in _set_model_item
    model_item = self.models_dict[model_type][lang][dataset][model]
KeyError: 'xtts_v1'
```

### Environment

```shell
TTS version 0.14.3
python 3.7
cuda 12
windows 11
```

**Comment by lexkoro** [comment]
Upgrade your TTS version. 
XTTS came with [v0.17.0](https://github.com/coqui-ai/TTS/releases/tag/v0.17.0)
