### ISSUE TITLE
MAX token limit for XTTS

### ISSUE THREAD

**Issue by haiderasad** [coqui-ai/TTS#3111]
### Describe the bug

I would like to know what is the max token limit for XTTS as while i was passing text of 130 tokens it said that it has a limit of 400 tokens for a single input prompt, kindly explain how you guys calculate tokens

### To Reproduce

Just give it a long text

### Expected behavior

AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.

### Logs

```shell
INFO: 2023-10-27 06:03:52,381: app.main  model loaded in 133.42864871025085 seconds
INFO: 2023-10-27 06:03:53,914: app.main  I: Generating new audio...
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 374, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 465, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/app/main.py", line 181, in clone_voice
    out = model.inference(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 620, in inference
    text_tokens.shape[-1] < self.args.gpt_max_text_tokens
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 374, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 465, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/app/main.py", line 226, in process_clone_job
    clone_voice.remote(
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
  File "/pkg/synchronicity/combined_types.py", line 26, in __call__
    raise uc_exc.exc from None
  File "<ta-x9hXLFyDMwQoOVUWS36QVU>:/root/app/main.py", line 181, in clone_voice
  File "<ta-x9hXLFyDMwQoOVUWS36QVU>:/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
  File "<ta-x9hXLFyDMwQoOVUWS36QVU>:/opt/conda/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 620, in inference
AssertionError:  ❗ XTTS can only generate text with a maximum of 400 tokens.
```

### Environment

```shell
no
```

### Additional context

no

**Comment by tsycstang** [comment]
I tried this and maybe I can provide you some insight from other languages. I used xTTS to generate Japanese text-to-speech, though the quality is not that good. The way it preprocess the text before feeding into NN is to convert Japanese text (Kanji or Chinese character) into kana so the NN knows how to pronounce it. This process significantly increases the number of characters. E.g. "pepper" in Kanji is 胡椒 while in kana is こしょう, the number of characters is doubled. I think it explained something indirectly though (before tokenization).

**Comment by m000lie** [comment]
> what you enter is not the exact character count. Tokenizer converts the input text to different units and the limit applies to these tokens. Currently, the model is architecturally limited so cannot provide long text output in one shot. You need to split them into sentences or just use the python API that does this automatically. 

Can you explain how it is "architecturally limited so cannot provide long text output in one shot."?
