### ISSUE TITLE
[Bug] Loading fine-tuned XTTSv1.1 model will get an error

### ISSUE THREAD

**Issue by bensonbs** [coqui-ai/TTS#3155]
### Describe the bug

I use `TTS/recipes/ljspeech/xtts_v1/train_gpt_xtts.py` to fine-tune XTTSv1.1.2 model 

Loading fine-tuned XTTS model will get an error

### To Reproduce
I use `train_gpt_xtts.py` to tuning and get error
```
 > EVALUATION 

 | > Synthesizing test sentences.
 ! Run is removed from /home/ubuntu/TTS/recipes/ljspeech/xtts_v1/run/training/GPT_XTTS_LJSpeech_FT-November-07-2023_10+39PM-5e992d87
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/trainer/trainer.py", line 1764, in _fit
    self.test_run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/trainer/trainer.py", line 1680, in test_run
    test_outputs = self.model.test_run(self.training_assets)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/TTS/tts/layers/xtts/trainer/gpt_trainer.py", line 235, in test_run
    wav = self.xtts.synthesize(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 485, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 510, in inference_with_config
    return self.full_inference(text, ref_audio_path, language, **settings)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 602, in full_inference
    return self.inference(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 714, in inference
    assert hasattr(
AssertionError: You must enable ne_hifigan decoder to use it by setting config `use_ne_hifigan: true`
```
And I add `use_ne_hifigan=True` in  `train_gpt_xtts.py` 
```
    model_args = GPTArgs(
        max_conditioning_length=132300,  # 6 secs
        min_conditioning_length=66150,  # 3 secs
        debug_loading_failures=False,
        max_wav_length=255995,  # ~11.6 seconds
        max_text_length=200,
        mel_norm_file=MEL_NORM_FILE,
        dvae_checkpoint=DVAE_CHECKPOINT,
        # tokenizer_file="/raid/datasets/xtts_models/vocab.json", # vocab path of the model that you want to fine-tune
        # xtts_checkpoint="https://huggingface.co/coqui/XTTS-v1/resolve/hifigan/model.pth",
        xtts_checkpoint=XTTS_CHECKPOINT,  # checkpoint path of the model that you want to fine-tune
        tokenizer_file=TOKENIZER_FILE,
        gpt_num_audio_tokens=8194,
        gpt_start_audio_token=8192,
        gpt_stop_audio_token=8193,
        # use_ne_hifigan=True,
```

After tuning use this code to infer  model
```
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

CONFIG_PATH = "recipes/ljspeech/xtts_v1/run/training/GPT_XTTS_LJSpeech_FT-November-07-2023_08+18PM-5e992d87/config.json"
TOKENIZER_PATH = "recipes/ljspeech/xtts_v1/run/training/XTTS_v1.1_original_model_files/vocab.json"

config = XttsConfig()
config.load_json(CONFIG_PATH)
model = Xtts.init_from_config(config)
```

base model can be load
```
XTTS_CHECKPOINT = "recipes/ljspeech/xtts_v1/run/training/XTTS_v1.1_original_model_files/model.pth"
model.load_checkpoint(config, checkpoint_path=XTTS_CHECKPOINT, vocab_path=TOKENIZER_PATH, use_deepspeed=False)
```

but model after tinetune get error
```
XTTS_CHECKPOINT = "recipes/ljspeech/xtts_v1/run/training/GPT_XTTS_LJSpeech_FT-November-07-2023_08+18PM-5e992d87/best_model.pth"
model.load_checkpoint(config, checkpoint_path=XTTS_CHECKPOINT, vocab_path=TOKENIZER_PATH, use_deepspeed=False)
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/TTS/TTS/tts/models/xtts.py:752, in Xtts.load_checkpoint(self, config, checkpoint_dir, checkpoint_path, vocab_path, eval, strict, use_deepspeed)
    751 try:
--> 752     self.load_state_dict(checkpoint, strict=strict)
    753 except:

File ~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2152, in Module.load_state_dict(self, state_dict, strict, assign)
   2151 if len(error_msgs) > 0:
-> 2152     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2153                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2154 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for Xtts:
    Unexpected key(s) in state_dict: "ne_hifigan_decoder.waveform_decoder.conv_pre.bias", "ne_hifigan_decoder.waveform_decoder.conv_pre.weight", "ne_hifigan
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.20.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.12",
        "version": "#93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023"
    }
}
```

**Comment by bensonbs** [comment]
Upgrade TTS to `0.20.1`  will not trigger `You must enable ne_hifigan decoder to use it by setting config use_ne_hifigan: true`  and everything runs smoothly.
