### ISSUE TITLE
[Bug] CS_API self.list_voices() raising error

### ISSUE THREAD

**Issue by RichardH64** [coqui-ai/TTS#3161]
### Describe the bug

Unable to use CS_API as when functions such as when self.list_voices() is called, the code gives an error.

### To Reproduce

import os
from TTS.api import CS_API

os.environ["COQUI_STUDIO_TOKEN"] = "TOKEN_HERE"

engine = CS_API(model="XTTS")
engine.ping_api()
engine._check_token()
print(engine.list_voices())

engine.tts_to_file(text="My name is Gilberto Mathias", speaker_name="Gilberto Mathias", file_path="output.wav")

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Tinker\PycharmProjects\trialModel\main.py", line 12, in <module>
    print(engine.list_voices())
  File "C:\Users\Tinker\PycharmProjects\trialModel\venv\lib\site-packages\TTS\cs_api.py", line 154, in list_voices
    return [Speaker(s, True) for s in json.loads(data)["result"]]
  File "C:\Users\Tinker\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Tinker\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Tinker\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cpu",
        "TTS": "0.20.1",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 158 Stepping 13, GenuineIntel",
        "python": "3.9.10",
        "version": "10.0.19044"
    }
}
```

**Comment by erogol** [comment]
I am looking at it

**Comment by erogol** [comment]
@RichardH64 can you try dev. Should be fixed.

**Comment by RichardH64** [comment]
Yep it works now, thank you
