### ISSUE TITLE
[Bug] XTTS ValueError: Model is not multi-lingual but `language` is provided.

### ISSUE THREAD

**Issue by LSXAxeller** [coqui-ai/TTS#3171]
### Describe the bug

I am trying to load XTTS-v1 locally but whenever I try to provide language="en" i get ```ValueError: Model is not multi-lingual but `language` is provided.``` and if I didn't, I get ```AssertionError:  ❗ Language None is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn']```

### To Reproduce

```
from TTS.TTS.api import TTS

class State():
    current_language = "EN"
    current_voice_suffix = "wav"
    
class TTSControl():
    tts = TTS(model_path="C:/External/Models/XTTS-v1", config_path="C:/External/Models/XTTS-v1/config_v1.json").to("cuda")
    clone_text: str = "Secret side, I wanna know it, so mysterious, Even that elusive side, part of her controlled area, Complete and perfect "

    def clone_voice(self):
        self.tts.tts_to_file(text=self.clone_text, speaker_wav="Temp/voice_temp." + State.current_voice_suffix, language='en', file_path="Output/output.wav")

if __name__ == "__main__":
    control = TTSControl()
    control.clone_voice()
    
```

### Expected behavior

it should clone the voice and save it to output.wav

### Logs

```shell
(venv) E:\Others\Native\VoiceGeneration>python n.py
 > Using model: xtts
Cloning Started
Traceback (most recent call last):
  File "E:\Others\Native\VoiceGeneration\n.py", line 28, in <module>
    control.clone_voice()
  File "E:\Others\Native\VoiceGeneration\n.py", line 17, in clone_voice
    self.tts.tts_to_file(text=self.clone_text,
  File "E:\Others\Native\VoiceGeneration\venv\lib\site-packages\TTS\TTS\api.py", line 391, in tts_to_file
    self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "E:\Others\Native\VoiceGeneration\venv\lib\site-packages\TTS\TTS\api.py", line 242, in _check_arguments
    raise ValueError("Model is not multi-lingual but `language` is provided.")
ValueError: Model is not multi-lingual but `language` is provided.
```

```
  File "E:\Others\Native\VoiceGeneration\VoiceGenerationWebUI\VoiceGenerationWebUI\VoiceGenerationWebUI.py", line 53, in clone_voice
    self.tts.tts_to_file(text=self.clone_text, speaker_wav="Temp/voice_temp." + State.current_voice_suffix, file_path="Output/output.wav")
  File "E:\Others\Native\VoiceGeneration\venv\lib\site-packages\TTS\TTS\api.py", line 403, in tts_to_file
    wav = self.tts(text=text, speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "E:\Others\Native\VoiceGeneration\venv\lib\site-packages\TTS\TTS\api.py", line 341, in tts
    wav = self.synthesizer.tts(
  File "E:\Others\Native\VoiceGeneration\venv\Lib\site-packages\TTS\TTS\utils\synthesizer.py", line 374, in tts
    outputs = self.tts_model.synthesize(
  File "E:\Others\Native\VoiceGeneration\venv\Lib\site-packages\TTS\TTS\tts\models\xtts.py", line 442, in synthesize
    return self.inference_with_config(text, config, ref_audio_path=speaker_wav, language=language, **kwargs)
  File "E:\Others\Native\VoiceGeneration\venv\Lib\site-packages\TTS\TTS\tts\models\xtts.py", line 448, in inference_with_config
    assert (
AssertionError:  ❗ Language None is not supported. Supported languages are ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar', 'zh-cn']
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3060"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.1+cu118",
        "TTS": "0.19.1",
        "numpy": "1.23.5"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 167 Stepping 1, GenuineIntel",
        "python": "3.10.6",
        "version": "10.0.22631"
    }
}
```

**Comment by WeberJulian** [comment]
V1 is no longer supported, use either v1.1 or v2 and update TTS.

```python
import torch
from TTS.api import TTS
device = "cuda" if torch.cuda.is_available() else "cpu"
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1.1").to(device)
wav = tts.tts(text="Hello world!", speaker_wav="my/cloning/audio.wav", language="en")
```
This code works fine on my env
