### ISSUE TITLE
[Bug] doesn't xtts V2 model finetuning surpport Chinese or mutil-language yet?

### ISSUE THREAD

**Issue by AIFSH** [coqui-ai/TTS#3206]
### Describe the bug

when i fine-tuning  xtts V2 with Chinese speaker, but same script with english speaker is working! What's wrong!
```
>> DVAE weights restored from: /root/autodl-tmp/xtts_ft/finetuning/XTTS_v2.0_original_model_files/dvae.pth
 | > Found 1029 files in /root/autodl-tmp/xtts_ft/luoxiang/ft_dataset
 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 128
 | > Num. of Torch Threads: 1
 | > Torch seed: 1
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=/root/autodl-tmp/xtts_ft/finetuning/luoxiang_GPT_XTTS_v2.0_LJSpeech_FT-November-13-2023_03+06PM-8b2f4c0

 > Model has 517360175 parameters

 > EPOCH: 0/1000
 --> /root/autodl-tmp/xtts_ft/finetuning/luoxiang_GPT_XTTS_v2.0_LJSpeech_FT-November-13-2023_03+06PM-8b2f4c0
 > Filtering invalid eval samples!!
 > Total eval samples after filtering: 0
 ! Run is removed from /root/autodl-tmp/xtts_ft/finetuning/luoxiang_GPT_XTTS_v2.0_LJSpeech_FT-November-13-2023_03+06PM-8b2f4c0
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/root/miniconda3/lib/python3.10/site-packages/trainer/trainer.py", line 1762, in _fit
    self.eval_epoch()
  File "/root/miniconda3/lib/python3.10/site-packages/trainer/trainer.py", line 1610, in eval_epoch
    self.get_eval_dataloader(
  File "/root/miniconda3/lib/python3.10/site-packages/trainer/trainer.py", line 976, in get_eval_dataloader
    return self._get_loader(
  File "/root/miniconda3/lib/python3.10/site-packages/trainer/trainer.py", line 900, in _get_loader
    len(loader) > 0
AssertionError:  ❗ len(DataLoader) returns 0. Make sure your dataset is not empty or len(dataset) > 0. 
```

### To Reproduce

finetuning with Chinese dataset

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA RTX A5000"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0+cu121",
        "TTS": "0.20.2",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.8",
        "version": "#121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022"
    }
}
```
```


### Additional context

_No response_

**Comment by erogol** [comment]
XTTS and TTS support all the languages. It is not clear to me what the problem is from the info you provide.

**Comment by ehsanrs2** [comment]
I faced the same problem with Persian language.

**Comment by hdmjdp** [comment]
> meta_file_val
How do you fix it? I just add a line " meta_file_val ="/FG/metadata_val.csv",", there is still a error.

**Comment by hdmjdp** [comment]
@AIFSH Can you share your config_dataset ?

**Comment by lpscr** [comment]
hi same problem in greek languase please can someone give solution on this ? 

on **vits**,**glow** etc working just fine with not any problem and i have success complete train 

the problem it's when try non-English , in  **xttsV1**,**xtts2V2**
format i use it's ljspeech

**audio|text|text** << this  like vits2,glow

also i try

**audio.wav|text|text**

and the full path file audio 

**path/audio.wav|text|text**

i try also to add the value **meta_file_val** in config and same error
because look like can find the eval files but same problem 


i get error in **xttsv1** , **xtsv2** 

i try everything just now spend hours to test and nothing working 

can some one please give solution and tell what wrong here this mean it's not support other language 

here what i get 
also i try make fresh install in colab to make sure it's not something wrong and same again 

**AssertionError:  ❗ len(DataLoader) returns 0. Make sure your dataset is not empty or len(dataset) > 0.** 

i try in colab and also in wls 

```
>> DVAE weights restored from: /content/XTTS_v1.1_original_model_files/dvae.pth

 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Num. of CPUs: 2
 | > Num. of Torch Threads: 1
 | > Torch seed: 1
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=/content/GPT_XTTS_LJSpeech_FT_new-November-15-2023_02+08PM-0000000

 > Model has 514458563 parameters

 | > Found 9338 files in /content/lora


 > EPOCH: 0/1000
 --> /content/GPT_XTTS_LJSpeech_FT_new-November-15-2023_02+08PM-0000000
 ! Run is removed from /content/GPT_XTTS_LJSpeech_FT_new-November-15-2023_02+08PM-0000000

 > Filtering invalid eval samples!!
 > Total eval samples after filtering: 0
Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1808, in fit
    self._fit()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1762, in _fit
    self.eval_epoch()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1610, in eval_epoch
    self.get_eval_dataloader(
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 976, in get_eval_dataloader
    return self._get_loader(
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 900, in _get_loader
    len(loader) > 0
AssertionError:  ❗ len(DataLoader) returns 0. Make sure your dataset is not empty or len(dataset) > 0. 
```

**Comment by thanhnew2001** [comment]
Is this approach working?
