### ISSUE TITLE
AttributeError: 'XttsConfig' object has no attribute 'use_d_vector_file'

### ISSUE THREAD

**Issue by robin977** [coqui-ai/TTS#3325]
### Describe the bug

The tts_models/multilingual/multi - the dataset/xtts_v2 model, after the server starts, call, an error
AttributeError: 'XttsConfig' object has no attribute 'use_d_vector_file'

### To Reproduce

[2023-11-28 11:48:32,803] ERROR in app: Exception on /api/tts [POST]
Traceback (most recent call last):
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/venv/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/venv/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/venv/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/venv/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/TTS/server/server.py", line 203, in tts
    wavs = synthesizer.tts(text, speaker_name=speaker_idx, language_name=language_idx, style_wav=style_wav)
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/TTS/utils/synthesizer.py", line 304, in tts
    if self.tts_config.use_d_vector_file:
  File "/Users/robinpeng/PycharmProjects/TTS-0.21.1/venv/lib/python3.9/site-packages/coqpit/coqpit.py", line 626, in __getattribute__
    value = super().__getattribute__(arg)
AttributeError: 'XttsConfig' object has no attribute 'use_d_vector_file'
::1 - - [28/Nov/2023 11:48:32] "POST /api/tts HTTP/1.1" 500 -

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1",
        "TTS": "0.20.6",
        "numpy": "1.26.2"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "i386",
        "python": "3.9.13",
        "version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020"
    }
}
```

**Comment by erogol** [comment]
server does not support XTTS

**Comment by robin977** [comment]
> server does not support XTTS
Thank you. Is there any plan to support xtts？

**Comment by robin977** [comment]
Thank you. Is there any plan to support xtts？
