### ISSUE TITLE
FINETUNING IN JAPANESE DATASET ERROR:

### ISSUE THREAD

**Issue by gjin10969** [coqui-ai/TTS#3410]
###when i generate the fine-tuning XTTS ENCODER NOT CONTINUE THE TRAINING:
it show errors in below

![image](https://github.com/coqui-ai/TTS/assets/113190973/4c0c5f18-8619-445b-b223-9c19bb2a0220)

Running on local URL:  http://0.0.0.0:5003
Running on public URL: https://8b545f7571a2b8566d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Loading Whisper Model!
2023-12-12 07:01:09,257 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:09,735 [INFO] Processing audio with duration 00:12.980
2023-12-12 07:01:13,116 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:13,486 [INFO] Processing audio with duration 00:05.430
2023-12-12 07:01:14,252 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:14,619 [INFO] Processing audio with duration 00:05.640
2023-12-12 07:01:15,472 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:15,843 [INFO] Processing audio with duration 00:08.040
2023-12-12 07:01:17,030 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:17,489 [INFO] Processing audio with duration 00:08.980
2023-12-12 07:01:18,783 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:19,254 [INFO] Processing audio with duration 00:07.790
2023-12-12 07:01:20,331 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:20,706 [INFO] Processing audio with duration 00:07.680
2023-12-12 07:01:21,864 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:22,370 [INFO] Processing audio with duration 00:07.670
2023-12-12 07:01:23,385 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:23,771 [INFO] Processing audio with duration 00:12.540
2023-12-12 07:01:25,232 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:25,597 [INFO] Processing audio with duration 00:05.760
2023-12-12 07:01:26,553 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:26,920 [INFO] Processing audio with duration 00:07.320
2023-12-12 07:01:27,944 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:28,318 [INFO] Processing audio with duration 00:07.400
2023-12-12 07:01:29,406 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:29,778 [INFO] Processing audio with duration 00:10.780
2023-12-12 07:01:31,140 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:31,619 [INFO] Processing audio with duration 00:15.010
2023-12-12 07:01:33,462 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:33,928 [INFO] Processing audio with duration 00:09.690
2023-12-12 07:01:35,170 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:35,548 [INFO] Processing audio with duration 00:13.050
2023-12-12 07:01:37,073 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:37,432 [INFO] Processing audio with duration 00:02.890
2023-12-12 07:01:38,080 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:38,454 [INFO] Processing audio with duration 00:15.540
2023-12-12 07:01:40,179 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:40,540 [INFO] Processing audio with duration 00:03.660
2023-12-12 07:01:41,324 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:41,717 [INFO] Processing audio with duration 00:05.440
2023-12-12 07:01:42,645 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:43,027 [INFO] Processing audio with duration 00:04.390
2023-12-12 07:01:43,723 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:44,097 [INFO] Processing audio with duration 00:06.010
2023-12-12 07:01:45,137 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:45,599 [INFO] Processing audio with duration 00:04.790
2023-12-12 07:01:46,488 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:46,957 [INFO] Processing audio with duration 00:04.010
2023-12-12 07:01:47,808 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:48,266 [INFO] Processing audio with duration 00:04.160
2023-12-12 07:01:49,026 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:49,393 [INFO] Processing audio with duration 00:10.200
2023-12-12 07:01:50,743 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:51,108 [INFO] Processing audio with duration 00:03.510
2023-12-12 07:01:51,895 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:52,268 [INFO] Processing audio with duration 00:04.180
2023-12-12 07:01:53,011 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:53,385 [INFO] Processing audio with duration 00:05.100
2023-12-12 07:01:54,185 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:54,556 [INFO] Processing audio with duration 00:03.230
2023-12-12 07:01:55,222 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:55,599 [INFO] Processing audio with duration 00:07.420
2023-12-12 07:01:56,736 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:57,100 [INFO] Processing audio with duration 00:09.650
2023-12-12 07:01:58,380 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:01:58,853 [INFO] Processing audio with duration 00:08.470
2023-12-12 07:02:00,116 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:00,584 [INFO] Processing audio with duration 00:08.290
2023-12-12 07:02:01,837 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:02,280 [INFO] Processing audio with duration 00:06.960
2023-12-12 07:02:03,302 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:03,670 [INFO] Processing audio with duration 00:07.160
2023-12-12 07:02:04,631 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:05,000 [INFO] Processing audio with duration 00:07.230
2023-12-12 07:02:06,035 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:06,417 [INFO] Processing audio with duration 00:05.770
2023-12-12 07:02:07,198 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:07,582 [INFO] Processing audio with duration 00:04.000
2023-12-12 07:02:08,389 [WARNING] Discarding ID3 tags because more suitable tags were found.
2023-12-12 07:02:08,761 [INFO] Processing audio with duration 00:08.140
Dataset Processed!
>> DVAE weights restored from: /tmp/xtts_ft/run/training/XTTS_v2.0_original_model_files/dvae.pth
 | > Found 2 files in /tmp/xtts_ft/dataset
 > Sampling by language: dict_keys(['ja'])
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1826, in fit
    self._fit()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1778, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1503, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
RecursionError: Caught RecursionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 180, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 180, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  [Previous line repeated 964 more times]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 146, in __getitem__
    index = random.randint(0, len(self.samples[lang]) - 1)
  File "/usr/lib/python3.10/random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.10/random.py", line 352, in randrange
    return istart + self._randbelow(width)
  File "/usr/lib/python3.10/random.py", line 245, in _randbelow_with_getrandbits
    k = n.bit_length()  # don't use (n-1) here because n can be 1
RecursionError: maximum recursion depth exceeded while calling a Python object

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1826, in fit
    self._fit()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1778, in _fit
    self.train_epoch()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1503, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
RecursionError: Caught RecursionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 180, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 180, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 156, in __getitem__
    return self[1]
  [Previous line repeated 964 more times]
  File "/content/TTS/TTS/tts/layers/xtts/trainer/dataset.py", line 146, in __getitem__
    index = random.randint(0, len(self.samples[lang]) - 1)
  File "/usr/lib/python3.10/random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.10/random.py", line 352, in randrange
    return istart + self._randbelow(width)
  File "/usr/lib/python3.10/random.py", line 245, in _randbelow_with_getrandbits
    k = n.bit_length()  # don't use (n-1) here because n can be 1
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/TTS/TTS/demos/xtts_ft_demo/xtts_demo.py", line 284, in train_model
    config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "/content/TTS/TTS/demos/xtts_ft_demo/utils/gpt_train.py", line 159, in train_gpt
    trainer.fit()
  File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1855, in fit
    sys.exit(1)
SystemExit: 1

### To Reproduce

Run the following command '...'
...
See error
Comment

### Expected behavior

Run the following command '...'
...
See error
Comment

### Logs

```shell
Run the following command '...'
...
See error
Comment
```

### Environment

```shell
SAME ON THE INSTRUCTION
```

### Additional context

Run the following command '...'
...
See error
Comment

**Comment by Edresson** [comment]
Hi @gjin10969,

Looks like the formatter only divided your WAV file into two files:
```
Found 2 files in /tmp/xtts_ft/dataset
```

 It is not right, make sure that your audio is long enough (and that you have proper speech on it not only long silences).
You can debug the samples by checking the metadata files.

**Comment by foreverhell** [comment]
The same issue when finetuning in Chinese dataset
