### ISSUE TITLE
[Bug] Can't "pip install" on Ubuntu 20.04

### ISSUE THREAD

**Issue by MaximeLeFloch** [coqui-ai/TTS#3473]
### Describe the bug

I can't make the installation on Ubuntu 20.04,
Would be glad if anyone can help!

### To Reproduce

$ git clone https://github.com/coqui-ai/TTS
$ pip install -e .[all,dev,notebooks]  # Select the relevant extras

If you are on Ubuntu (Debian), you can also run following commands for installation.
$ make system-deps  # intended to be used on Ubuntu (Debian). Let us know if you have a different OS.
$ make install

### Logs

```shell
pip install -e .[all]
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Obtaining file:///home/mlf/perso/TTS
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp5g1zi7mi get_requires_for_build_wheel /tmp/tmp279ws_6x
       cwd: /home/mlf/perso/TTS
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/tmp/tmp5g1zi7mi", line 280, in <module>
      main()
    File "/tmp/tmp5g1zi7mi", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp5g1zi7mi", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-oikn0_5d/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-oikn0_5d/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-oikn0_5d/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-oikn0_5d/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 36, in <module>
  RuntimeError: TTS requires python >= 3.9 and < 3.12 but your Python version is 3.8.10 (default, Nov 22 2023, 10:22:35)
  [GCC 9.4.0]
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp5g1zi7mi get_requires_for_build_wheel /tmp/tmp279ws_6x Check the logs for full command output.
make: *** [Makefile:75: install] Error 1
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2+cu121",
        "TTS": "0.22.0",
        "numpy": "1.24.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.8.10",
        "version": "#101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023"
    }
}
```

**Comment by lexkoro** [comment]
Did you read the error message?

**Comment by ralyodio** [comment]
doens't work on arch either.

**Comment by cagrikumas** [comment]
I also encountered the same problem.

**Comment by MaximeLeFloch** [comment]
> Did you read the error message?

Hi, I did read the message, I'm quite new to Linux, please enlighten me if the answer is obvious for more experienced users.

**Comment by eginhard** [comment]
> > Did you read the error message?
> 
> Hi, I did read the message, I'm quite new to Linux, please enlighten me if the answer is obvious for more experienced users.

The message says `TTS requires python >= 3.9 and < 3.12 but your Python version is 3.8.10`, as also stated in the [readme](https://github.com/coqui-ai/TTS#installation). So you need to install TTS into a virtual environment with Python version 3.9 or higher.
