### ISSUE TITLE
Failed to resolve 'coqui.gateway.scarf.sh'

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [coqui-ai/TTS#3485]
I have set the system environment variable as discussed [here ](https://github.com/coqui-ai/TTS/discussions/2586)and restarted Windows.
However, the error does not go away:

(base) tts@DESKTOP-D3RQAKA:/mnt/c/WINDOWS/system32$ conda activate TTS_env
(TTS_env) tts@DESKTOP-D3RQAKA:/mnt/c/WINDOWS/system32$ python3 /mnt/c/Train.py
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:45
 | > do_sound_norm:False
 | > do_amp_to_db_linear:False
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 | > /mnt/c/Dataset_ge/by_book/male/myvoice/metadata.csv
> File /mnt/c/Dataset_ge/by_book/male/myvoice/wavs/﻿audio_30303_L.wav does not exist!
 | > Found 200 files in /mnt/c/Dataset_ge/by_book
/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 20
 | > Num. of Torch Threads: 10
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=/mnt/c/output/VITS_german-January-02-2024_02+52AM-0000000
 > Restoring from model_file.pth ...
 > Restoring Model...
 > Restoring Optimizer...
 > Optimizer is not compatible with the restored model.
 > Model restored from step 543000

 > Model has 83059180 parameters
Traceback (most recent call last):
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fd3a330ac80>: Failed to resolve 'coqui.gateway.scarf.sh' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /trainer/training_run (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd3a330ac80>: Failed to resolve 'coqui.gateway.scarf.sh' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Train.py", line 82, in <module>
    trainer = Trainer(
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/trainer/trainer.py", line 569, in __init__
    ping_training_run()
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/trainer/analytics.py", line 12, in ping_training_run
    _ = requests.get(URL, timeout=5)
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tts/miniconda3/envs/TTS_env/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /trainer/training_run (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fd3a330ac80>: Failed to resolve 'coqui.gateway.scarf.sh' ([Errno -3] Temporary failure in name resolution)"))
(TTS_env) tts@DESKTOP-D3RQAKA:/mnt/c/WINDOWS/system32$

**Comment by NoteToSelfFindGoodNickname** [comment]
Also, "c/Dataset_ge/by_book/male/myvoice/wavs/﻿audio_30303_L.wav" exists. 
I don't know why this error is thrown.

**Comment by pablodz** [comment]
https://github.com/coqui-ai/TTS/issues/3488

**Comment by NoteToSelfFindGoodNickname** [comment]
> #3488

Yes, I know, but I don't know why it still trys to connect even though I disabled Telemetry.

**Comment by NoteToSelfFindGoodNickname** [comment]
It's scary to see that even though the variable is set, it still tries to spy on you.
