### ISSUE TITLE
[Bug] `fsspec.exceptions.FSTimeoutError` and `asyncio.exceptions.TimeoutError` after `> Loading pretrained speaker encoder model ...` when using `freevc` in voice conversion

### ISSUE THREAD

**Issue by snakeninny** [coqui-ai/TTS#3495]
### Describe the bug

I'm testing the voice conversion and I've followed the official demo in readme. The full source code is:
```
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=True).to("cuda")

# Text to speech to a file
tts.voice_conversion_to_file(source_wav="./任正非.wav", target_wav="./雷军.wav", file_path="./output.wav")
```
After running it, the output was:
```
<TTS.utils.manage.ModelManager object at 0x7fc4500eff40>
 > voice_conversion_models/multilingual/vctk/freevc24 is already downloaded.
 > Using model: freevc
 > Loading pretrained speaker encoder model ...
```
Then after a few minutes, an error occurred:
```
Traceback (most recent call last):
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/http.py", line 260, in _get_file
    chunk = await r.content.read(chunk_size)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/aiohttp/streams.py", line 383, in read
    await self._wait("read")
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/aiohttp/streams.py", line 301, in _wait
    with self._timer:
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyl/TTS/test.py", line 42, in <module>
    tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=True).to("cuda")
  File "/home/zyl/TTS/TTS/api.py", line 76, in __init__
    self.load_vc_model_by_name(model_name, gpu)
  File "/home/zyl/TTS/TTS/api.py", line 157, in load_vc_model_by_name
    self.voice_converter = Synthesizer(vc_checkpoint=model_path, vc_config=config_path, use_cuda=gpu)
  File "/home/zyl/TTS/TTS/utils/synthesizer.py", line 101, in __init__
    self._load_vc(vc_checkpoint, vc_config, use_cuda)
  File "/home/zyl/TTS/TTS/utils/synthesizer.py", line 139, in _load_vc
    self.vc_model = setup_vc_model(config=self.vc_config)
  File "/home/zyl/TTS/TTS/vc/models/__init__.py", line 16, in setup_model
    model = MyModel.init_from_config(config, samples)
  File "/home/zyl/TTS/TTS/vc/models/freevc.py", line 552, in init_from_config
    model = FreeVC(config)
  File "/home/zyl/TTS/TTS/vc/models/freevc.py", line 370, in __init__
    self.load_pretrained_speaker_encoder()
  File "/home/zyl/TTS/TTS/vc/models/freevc.py", line 381, in load_pretrained_speaker_encoder
    self.enc_spk_ex = SpeakerEncoderEx(
  File "/home/zyl/TTS/TTS/vc/modules/freevc/speaker_encoder/speaker_encoder.py", line 42, in __init__
    checkpoint = load_fsspec(weights_fpath, map_location="cpu")
  File "/home/zyl/TTS/TTS/utils/io.py", line 46, in load_fsspec
    with fsspec.open(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/core.py", line 103, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 436, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/spec.py", line 1295, in open
    f = self._open(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 436, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 697, in _open
    self.fs.get_file(path, fn)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/asyn.py", line 101, in sync
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
```
At first I was thinking about a proxy issue because I'm in China mainland and need a VPN to get access to huggingface and github. But `freevc` was downloaded already and the next step was to load the pretrained speaker encoder model, not downloading it. So I'm not quite sure if it's a proxy issue.
Any ideas? Thank you!

### To Reproduce

```
import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=True).to("cuda")

# Text to speech to a file
tts.voice_conversion_to_file(source_wav="./任正非.wav", target_wav="./雷军.wav", file_path="./output.wav")
```

That's it. Maybe you need a Chinese server to test?

### Expected behavior

You know what's the expectation

### Logs

```shell
<TTS.utils.manage.ModelManager object at 0x7f536fd87f40>
 > voice_conversion_models/multilingual/vctk/freevc24 is already downloaded.
 > Using model: freevc
 > Loading pretrained speaker encoder model ...
Traceback (most recent call last):
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/http.py", line 260, in _get_file
    chunk = await r.content.read(chunk_size)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/aiohttp/streams.py", line 383, in read
    await self._wait("read")
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/aiohttp/streams.py", line 301, in _wait
    with self._timer:
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyl/TTS/test.py", line 42, in <module>
    tts = TTS(model_name="voice_conversion_models/multilingual/vctk/freevc24", progress_bar=True).to("cuda")
  File "/home/zyl/TTS/TTS/api.py", line 76, in __init__
    self.load_vc_model_by_name(model_name, gpu)
  File "/home/zyl/TTS/TTS/api.py", line 157, in load_vc_model_by_name
    self.voice_converter = Synthesizer(vc_checkpoint=model_path, vc_config=config_path, use_cuda=gpu)
  File "/home/zyl/TTS/TTS/utils/synthesizer.py", line 101, in __init__
    self._load_vc(vc_checkpoint, vc_config, use_cuda)
  File "/home/zyl/TTS/TTS/utils/synthesizer.py", line 139, in _load_vc
    self.vc_model = setup_vc_model(config=self.vc_config)
  File "/home/zyl/TTS/TTS/vc/models/__init__.py", line 16, in setup_model
    model = MyModel.init_from_config(config, samples)
  File "/home/zyl/TTS/TTS/vc/models/freevc.py", line 552, in init_from_config
    model = FreeVC(config)
  File "/home/zyl/TTS/TTS/vc/models/freevc.py", line 370, in __init__
    self.load_pretrained_speaker_encoder()
  File "/home/zyl/TTS/TTS/vc/models/freevc.py", line 381, in load_pretrained_speaker_encoder
    self.enc_spk_ex = SpeakerEncoderEx(
  File "/home/zyl/TTS/TTS/vc/modules/freevc/speaker_encoder/speaker_encoder.py", line 42, in __init__
    checkpoint = load_fsspec(weights_fpath, map_location="cpu")
  File "/home/zyl/TTS/TTS/utils/io.py", line 46, in load_fsspec
    with fsspec.open(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/core.py", line 103, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 436, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/spec.py", line 1295, in open
    f = self._open(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 436, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 697, in _open
    self.fs.get_file(path, fn)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/zyl/miniconda3/envs/coqui/lib/python3.10/site-packages/fsspec/asyn.py", line 101, in sync
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
```
```


### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.2+cu121",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.13",
        "version": "#98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023"
    }
}
```
```


### Additional context

_No response_

**Comment by snakeninny** [comment]
It was because of this:
```
    def load_pretrained_speaker_encoder(self):
        """Load pretrained speaker encoder model as mentioned in the paper."""
        print(" > Loading pretrained speaker encoder model ...")
        self.enc_spk_ex = SpeakerEncoderEx(
            "https://github.com/coqui-ai/TTS/releases/download/v0.13.0_models/speaker_encoder.pt"
        )
```
`github.com` was blocked in China mainland, change it to another mirror like `hub.fgit.cf`

**Comment by treya-lin** [comment]
> It was because of this:
> 
> ```
>     def load_pretrained_speaker_encoder(self):
>         """Load pretrained speaker encoder model as mentioned in the paper."""
>         print(" > Loading pretrained speaker encoder model ...")
>         self.enc_spk_ex = SpeakerEncoderEx(
>             "https://github.com/coqui-ai/TTS/releases/download/v0.13.0_models/speaker_encoder.pt"
>         )
> ```
> 
> `github.com` was blocked in China mainland, change it to another mirror like `hub.fgit.cf`

I met the same issue, can we just download it by ourselves and save it to some local directory instead of having to load it each time we run it？
