### ISSUE TITLE
Cuda on windows [Bug] 

### ISSUE THREAD

**Issue by RASPIAUDIO** [coqui-ai/TTS#3499]
### Describe the bug

CPU working on windows but no GPU just like if CUDA wahs not installed  when it is.

Has anyone made the GPU acceleration worked on Windows?

### To Reproduce

normal install  with pip

### Expected behavior

"CUDA is not availabe on this machine."

### Logs

```shell
C:\holobot\prod\mytts>python testmytts2.py
<TTS.utils.manage.ModelManager object at 0x0000016C6C79A990>
C:\Users\olivi\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\api.py:70: UserWarning: `gpu` will be deprecated. Please use `tts.to(device)` instead.
  warnings.warn("`gpu` will be deprecated. Please use `tts.to(device)` instead.")
 > tts_models/multilingual/multi-dataset/your_tts is already downloaded.
Traceback (most recent call last):
  File "C:\holobot\prod\mytts\testmytts2.py", line 12, in <module>
    tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=False, gpu=True).to(device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\api.py", line 74, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\api.py", line 177, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
                       ^^^^^^^^^^^^
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\utils\synthesizer.py", line 90, in __init__
    assert torch.cuda.is_available(), "CUDA is not availabe on this machine."
AssertionError: CUDA is not availabe on this machine.
```

### Environment

```shell
Windows11

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by RASPIAUDIO** [comment]
ok found the solution here:


https://github.com/coqui-ai/TTS/discussions/2373
