### ISSUE TITLE
[Bug] Error Dataloader when using distributed training vtck vits

### ISSUE THREAD

**Issue by phamkhactu** [coqui-ai/TTS#3596]
### Describe the bug

I want to train vtck vits. First of all, I set up in vitsconfig
```
{

    # Enable the weighted sampler
    use_weighted_sampler=True,
    # Ensures that all speakers are seen in the training batch equally no matter how many samples each speaker has
    weighted_sampler_attrs={"speaker_name": 1.0},
    weighted_sampler_multipliers={},
    # It defines the Speaker Consistency Loss (SCL) α to 9 like the paper
    speaker_encoder_loss_alpha=9.0,
}
```

I don't get error when running  **train_vits.py**  with 1 gpu. However with multi gpus:
```
CUDA_VISIBLE_DEVICES="0, 1" python -m trainer.distribute --script recipes/vctk/vits/train_vits.py
```
I get error about dataloader 

### To Reproduce

With same config
1. Test runs with 1 gpu --> no error
```
CUDA_VISIBLE_DEVICES="0" python -m trainer.distribute --script recipes/vctk/vits/train_vits.py
```
2. Test runs with multi gpu --> get error
```
CUDA_VISIBLE_DEVICES="0, 1" python -m trainer.distribute --script recipes/vctk/vits/train_vits.py
```

If I comment  config:

```
    weighted_sampler_attrs={"speaker_name": 1.0},

```
Both commands above  don't get error.

### Expected behavior

Can run it well

### Logs

```shell
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tupk/tupk/nlp/custom/TTS/TTS/tts/models/vits.py", line 263, in __getitem__
    item = self.samples[idx]
TypeError: list indices must be integers or slices, not list

 ! Run is kept in /home/tupk/tupk/nlp/custom/TTS/recipes/vctk/vits/vits_vctk-February-20-2024_09+49AM-b1b4fd31
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/trainer/trainer.py", line 1826, in fit
    self._fit()
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/trainer/trainer.py", line 1778, in _fit
    self.train_epoch()
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/trainer/trainer.py", line 1503, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tupk/anaconda3/envs/dl/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tupk/tupk/nlp/custom/TTS/TTS/tts/models/vits.py", line 263, in __getitem__
    item = self.samples[idx]
TypeError: list indices must be integers or slices, not list

```
```


### Environment

```shell
TTS: Version: 0.21.1
Torch: Version: 2.1.1
```

**Comment by khaidoan25** [comment]
@phamkhactu there is another issue stating that distributed training is not compatible with weighted_sampler and they don't have plan to fix that bug.

**Comment by phamkhactu** [comment]
> @phamkhactu there is another issue stating that distributed training is not compatible with weighted_sampler and they don't have plan to fix that bug.

Hi @khaidoan25 
Thanks for your reply. It means that I only train model with one gpu if I want to add weighted_sampler with new speaker?

**Comment by khaidoan25** [comment]
> > @phamkhactu there is another issue stating that distributed training is not compatible with weighted_sampler and they don't have plan to fix that bug.
> 
> 
> 
> Hi @khaidoan25 
> 
> Thanks for your reply. It means that I only train model with one gpu if I want to add weighted_sampler with new speaker?
> 
> 

yes, that's what I mean.
