### ISSUE TITLE
[Bug] Bark fails in non-root environment

### ISSUE THREAD

**Issue by egdels** [coqui-ai/TTS#3608]
### Describe the bug

On Debian 12 with python 3.11 and tts 0.22.0 running command 

tts --model_name tts_models/multilingual/multi-dataset/bark --list_speaker_idxs

as non-root fails with error:

PermissionError: [Errno 13] Permission denied: '/root/.local'

Screenshot:

![grafik](https://github.com/coqui-ai/TTS/assets/27009458/0f444530-53d4-4512-bb5c-738184e4182a)

### To Reproduce

1. python3 -m venv path/to/venv
2. source path/to/venv/bin/activate
3. pip install tts
4. tts --model_name tts_models/multilingual/multi-dataset/bark --list_speaker_idxs
5. model is downloaded, but when model should be loaded see error.

### Expected behavior

tts should download model and then list available speakers

### Logs

```shell
> Downloading model to /home/christian/.local/share/tts/tts_models--multilingual--multi-dataset--bark
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.93G/3.93G [09:24<00:00, 6.97MiB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.74G/3.74G [08:56<00:00, 6.97MiB/s]
 31%|█████████████████████████████████████████████████████                                                                                                                      | 9.00/29.0 [00:00<00:00, 27.8iB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.11k/6.11k [00:00<00:00, 13.1kiB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.14G/1.14G [02:43<00:00, 6.97MiB/s]
  0%|                                                                                                                                                                                  | 0.00/104M [00:00<?, ?iB/s > Model's license - MIT███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 104M/104M [00:14<00:00, 7.11MiB/s]
 > Check https://choosealicense.com/licenses/mit/ for more info.
 > Using model: bark
/home/christian/git/path/to/venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
WARNING:TTS.tts.layers.bark.load_model:found outdated text model, removing...
Traceback (most recent call last):
  File "/home/christian/git/path/to/venv/bin/tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/bin/synthesize.py", line 423, in main
    synthesizer = Synthesizer(
                  ^^^^^^^^^^^^
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/utils/synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/utils/synthesizer.py", line 164, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/tts/models/bark.py", line 281, in load_checkpoint
    self.load_bark_models()
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/tts/models/bark.py", line 50, in load_bark_models
    self.semantic_model, self.config = load_model(
                                       ^^^^^^^^^^^
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/tts/layers/bark/load_model.py", line 119, in load_model
    _download(config.REMOTE_MODEL_PATHS[model_type]["path"], ckpt_path, config.CACHE_DIR)
  File "/home/christian/git/path/to/venv/lib/python3.11/site-packages/TTS/tts/layers/bark/load_model.py", line 49, in _download
    os.makedirs(CACHE_DIR, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/root/.local'
```

### Environment

```shell
python collect_env_info.py
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.1+cu121",
        "TTS": "0.22.0",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "",
        "python": "3.11.2",
        "version": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30)"
    }
}
```

**Comment by yoller** [comment]
Hi, I have a practically similar problem but on macOS, any solutions?

EDIT
I found this: https://github.com/coqui-ai/TTS/issues/2781#issuecomment-1694174629

**Comment by carlosmatthews** [comment]
same issue  on terminal ubuntu on wsl windows, non-root fails with error:

PermissionError: [Errno 13] Permission denied: '/root/.local'

**Comment by hykilpikonna** [comment]
You can edit these in `~/.local/share/tts/tts_models--multilingual--multi-dataset--bark/config.json`

![image](https://github.com/user-attachments/assets/ba433782-561a-4904-8f75-fa7cc95d650b)

**Comment by hykilpikonna** [comment]
I'm honestly 🤯 by how /root is hardcoded in the config 🤦🏼‍♀️

**Comment by eginhard** [comment]
This is now fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), available via `pip install coqui-tts`

**Comment by Rick-Hard89** [comment]
> You can edit these in `~/.local/share/tts/tts_models--multilingual--multi-dataset--bark/config.json`
> 
> ![image](https://github.com/user-attachments/assets/ba433782-561a-4904-8f75-fa7cc95d650b)

thank you so much!

also had to change "CACHE_DIR" at the bottom of config
