### ISSUE TITLE
[Bug] compute_statistics.py isn't working.

### ISSUE THREAD

**Issue by MistakingManx** [coqui-ai/TTS#3692]
### Describe the bug

I haven't seen another issue, so this might just be a me problem, but I lack the ability to fix it myself.

When running `python compute_statistics.py --config_path D:/AI/Testing/TTS/dataset/dataset/LJSpeech-1.1/config.json --output_path D:/AI/Testing/TTS/dataset/dataset/LJSpeech-1.1/stats.npy` I'm greeted with this error after it starts processing;

```
Traceback (most recent call last):
  File "D:\AI\Testing\TTS\TTS\bin\compute_statistics.py", line 96, in <module>
    main()
  File "D:\AI\Testing\TTS\TTS\bin\compute_statistics.py", line 61, in main
    linear_sum += linear.sum(1)
ValueError: operands could not be broadcast together with shapes (47188,1) (51157,1) (47188,1)
```

### To Reproduce

1. Run `python compute_statistics.py (config path) (output path)`
2. See error for some reason.

### Logs

```shell
(TTS) D:\AI\Testing\TTS\TTS\bin>python compute_statistics.py --config_path D:/AI/Testing/TTS/dataset/dataset/LJSpeech-1.1/config.json --output_path D:/AI/Testing/TTS/dataset/dataset/LJSpeech-1.1/stats.npy
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 15425 files in D:\AI\Testing\TTS\dataset\dataset\LJSpeech-1.1
 > There are 15425 files.
  0%|                                                                                                                                                                                   | 0/15425 [00:00<?, ?it/s]D:\anaconda3\envs\TTS\lib\site-packages\librosa\core\spectrum.py:256: UserWarning: n_fft=1024 is too large for input signal of length=2
  warnings.warn(
  0%|                                                                                                                                                                        | 1/15425 [00:11<47:45:51, 11.15s/it]
Traceback (most recent call last):
  File "D:\AI\Testing\TTS\TTS\bin\compute_statistics.py", line 96, in <module>
    main()
  File "D:\AI\Testing\TTS\TTS\bin\compute_statistics.py", line 61, in main
    linear_sum += linear.sum(1)
ValueError: operands could not be broadcast together with shapes (47188,1) (51157,1) (47188,1)
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 4060 Ti"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.2+cu121",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
        "python": "3.10.14",
        "version": "10.0.19045"
    }
}
```

**Comment by MistakingManx** [comment]
Un-stale it please I still haven't gotten a solution.
