### ISSUE TITLE
[Bug] XTTS Finetuning - xtts_demo.py - Collab

### ISSUE THREAD

**Issue by kabelklaus** [coqui-ai/TTS#3738]
### Describe the bug

starting the process of train with a .wav file

### To Reproduce

1. Start xtts_demo.py 
2. klick on the link for gradio
3. move a .wav to the file section
4. start the first step of the process

### Expected behavior

When I upload a .wav file and start the process in gradio, I would like to come to the next step (step 2) in the finetune training.

### Logs

```shell
The data processing was interrupted due an error !! Please check the console to verify the full error message! Error summary: Traceback (most recent call last): File "/content/TTS/TTS/demos/xtts_ft_demo/xtts_demo.py", line 215, in preprocess_dataset train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, target_language=language, out_path=out_path, gradio_progress=progress) File "/content/TTS/TTS/demos/xtts_ft_demo/utils/formatter.py", line 75, in format_audio_list segments = list(segments) File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 426, in generate_segments encoder_output = self.encode(segment) File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 610, in encode return self.model.encode(features, to_cpu=to_cpu) RuntimeError: Library libcublas.so.11 is not found or cannot be loaded
```

### Environment

```shell
# Installiere die benötigten CUDA-Bibliotheken
!apt-get update
!apt-get install -y wget
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
!mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
!wget https://developer.download.nvidia.com/compute/cuda/12.2.0/local_installers/cuda-repo-ubuntu2004-12-2-local_12.2.0-1_amd64.deb
!dpkg -i cuda-repo-ubuntu2004-12-2-local_12.2.0-1_amd64.deb
!apt-key add /var/cuda-repo-ubuntu2004-12-2-local/7fa2af80.pub
!apt-get update
!apt-get -y install cuda

# Setze die Umgebungsvariablen für CUDA
import os
cuda_path = "/usr/local/cuda-12.2/targets/x86_64-linux/lib"
os.environ["PATH"] = "/usr/local/cuda-12.2/bin:" + os.environ.get("PATH", "")
os.environ["LD_LIBRARY_PATH"] = f"{cuda_path}:{os.environ.get('LD_LIBRARY_PATH', '')}"

# Überprüfe, ob libcublas installiert ist
!ls /usr/local/cuda-12.2/targets/x86_64-linux/lib/libcublas.so.12

# Aktualisiere Gradio
!pip install --upgrade gradio

# Starte dein Skript
!python /content/TTS/TTS/demos/xtts_ft_demo/xtts_demo.py
```

**Comment by jcgarciaca** [comment]
I did `!apt install libcublas11` and it worked
