### ISSUE TITLE
[Bug] Official linked XTTS_v2 Google Colab throws: ibcublas.so.11 is not found

### ISSUE THREAD

**Issue by flocked** [coqui-ai/TTS#3779]
### Describe the bug

When using the [Google Colab](https://colab.research.google.com/drive/1GiI4_X724M8q2W-zZ-jXo7cWTV7RfaH-?usp=sharing) for XTTS_v2 that is linked in the [official tutorial](https://docs.coqui.ai/en/stable/models/xtts.html) it throws an error after running the first two steps, opening the gradio UI via the public URL, uploading audio files and creating the dataset:

`Library libcublas.so.11 is not found or cannot be loaded`

### To Reproduce

1. Run the first two steps of the Google Colab
2. Open the gradio UI via the public URL
3. Upload audio files
4. Create the dataset. It will throw the error listed in the log.

### Logs

Loading Whisper Model!
2024-06-06 02:52:48,192 [INFO] Processing audio with duration 15:04.526
Traceback (most recent call last):
  File "/content/TTS/TTS/demos/xtts_ft_demo/xtts_demo.py", line 215, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, target_language=language, out_path=out_path, gradio_progress=progress)
  File "/content/TTS/TTS/demos/xtts_ft_demo/utils/formatter.py", line 75, in format_audio_list
    segments = list(segments)
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 426, in generate_segments
    encoder_output = self.encode(segment)
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 610, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library libcublas.so.11 is not found or cannot be loaded

### Environment

```shell
Google Colab: https://colab.research.google.com/drive/1GiI4_X724M8q2W-zZ-jXo7cWTV7RfaH-?usp=sharing
From official tutorial: https://docs.coqui.ai/en/stable/models/xtts.html
```

**Comment by flocked** [comment]
Adding the code `!apt install libcublas11` solves the problem.
`pip install transformers -U` has also be added to run the right version of it.

**Comment by saifulislam79** [comment]
This is CUDA Driver issue, please check the driver 12.2 or other version. Make sure cuda version and this "libcublas.so.11" for cuda 12.2 and it CUDNN is 8.x.x.
