### ISSUE TITLE
[Bug] XTTS v2 using Docker image not launching

### ISSUE THREAD

**Issue by mariussdl** [coqui-ai/TTS#3805]
### Describe the bug

Hey, I'm using the Docker image provided, but when I try to use the XTTS v2 model I get this error:
```python
Traceback (most recent call last):
  File "/root/TTS/server/server.py", line 104, in <module>
    synthesizer = Synthesizer(
  File "/root/TTS/utils/synthesizer.py", line 93, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/root/TTS/utils/synthesizer.py", line 183, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "/root/TTS/config/__init__.py", line 82, in load_config
    ext = os.path.splitext(config_path)[1]
  File "/usr/local/lib/python3.10/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
The model downloaded fine. I agreed to the Terms and Conditions.

### To Reproduce

1. Launch the Docker image
2. Run `python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/xtts_v2`

### Logs

```shell
root@6eab1efd81d8:~# python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/xtts_v2
 > You must confirm the following:
 | > "I have purchased a commercial license from Coqui: licensing@coqui.ai"
 | > "Otherwise, I agree to the terms of the non-commercial CPML: https://coqui.ai/cpml" - [y/n]
 | | > y
 > Downloading model to /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2
 > Model's license - CPML
 > Check https://coqui.ai/cpml.txt for more info.
Traceback (most recent call last):
  File "/root/TTS/server/server.py", line 104, in <module>
    synthesizer = Synthesizer(
  File "/root/TTS/utils/synthesizer.py", line 93, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/root/TTS/utils/synthesizer.py", line 183, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "/root/TTS/config/__init__.py", line 82, in load_config
    ext = os.path.splitext(config_path)[1]
  File "/usr/local/lib/python3.10/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.1+cu118",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "",
        "python": "3.10.8",
        "version": "#1 SMP PREEMPT_DYNAMIC Wed Jun  5 07:37:32 UTC 2024"
    }
}
```

**Comment by eginhard** [comment]
The server doesn't support XTTS, you'll have to run it manually.

**Comment by mariussdl** [comment]
Okay, and how am I suppose to do that ? Can I still run it through Docker ?

**Comment by eginhard** [comment]
Yes: https://coqui-tts.readthedocs.io/en/latest/models/xtts.html#inference

**Comment by acosme** [comment]
> Okay, and how am I suppose to do that ? Can I still run it through Docker ?

Maybe updating some params, look at this comment:

https://github.com/coqui-ai/TTS/issues/3454#issuecomment-2135886750
[](https://github.com/coqui-ai/TTS/issues/3454#issuecomment-2135886750)
