### ISSUE TITLE
[Bug] list_speaker_idx issue for bark model

### ISSUE THREAD

**Issue by madey83** [coqui-ai/TTS#3823]
### Describe the bug

tts --model_name tts_models/multilingual/multi-dataset/bark --list_speaker_idx
 > tts_models/multilingual/multi-dataset/bark is already downloaded.
 > Using model: bark
/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
found outdated text model, removing...
100%|███████████████████████████████████████████████████████████████████████████████████████| 17.2k/17.2k [00:00<00:00, 34.6MiB/s]
Traceback (most recent call last):
  File "/CoquiTTS/CoquiTTS/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 423, in main
    synthesizer = Synthesizer(
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 164, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 281, in load_checkpoint
    self.load_bark_models()
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/TTS/tts/models/bark.py", line 50, in load_bark_models
    self.semantic_model, self.config = load_model(
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/TTS/tts/layers/bark/load_model.py", line 121, in load_model
    checkpoint = torch.load(ckpt_path, map_location=device)
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/CoquiTTS/CoquiTTS/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

### To Reproduce

tts --model_name tts_models/multilingual/multi-dataset/bark --list_speaker_idx

### Expected behavior

i would like to see available  speaker idx

### Environment

```shell
pip list
Package                  Version
------------------------ -----------
absl-py                  2.1.0
aiohttp                  3.9.5
aiosignal                1.3.1
annotated-types          0.7.0
anyascii                 0.3.2
async-timeout            4.0.3
attrs                    23.2.0
audioread                3.0.1
Babel                    2.15.0
bangla                   0.0.2
blinker                  1.8.2
blis                     0.7.11
bnnumerizer              0.0.2
bnunicodenormalizer      0.1.7
catalogue                2.0.10
certifi                  2024.7.4
cffi                     1.16.0
chardet                  5.2.0
charset-normalizer       3.3.2
click                    8.1.7
cloudpathlib             0.18.1
confection               0.1.5
contourpy                1.2.1
coqpit                   0.0.17
cycler                   0.12.1
cymem                    2.0.8
Cython                   3.0.10
dateparser               1.1.8
decorator                5.1.1
docopt                   0.6.2
einops                   0.8.0
encodec                  0.1.1
filelock                 3.15.4
Flask                    3.0.3
fonttools                4.53.1
frozenlist               1.4.1
fsspec                   2024.6.1
g2pkk                    0.1.2
grpcio                   1.64.1
gruut                    2.2.3
gruut-ipa                0.13.0
gruut-lang-de            2.0.1
gruut-lang-en            2.0.1
gruut-lang-es            2.0.1
gruut-lang-fr            2.0.2
hangul-romanize          0.1.0
huggingface-hub          0.23.4
idna                     3.7
inflect                  7.3.1
itsdangerous             2.2.0
jamo                     0.4.1
jieba                    0.42.1
Jinja2                   3.1.4
joblib                   1.4.2
jsonlines                1.2.0
kiwisolver               1.4.5
langcodes                3.4.0
language_data            1.2.0
lazy_loader              0.4
librosa                  0.10.0
llvmlite                 0.43.0
marisa-trie              1.2.0
Markdown                 3.6
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.8.4
mdurl                    0.1.2
more-itertools           10.3.0
mpmath                   1.3.0
msgpack                  1.0.8
multidict                6.0.5
murmurhash               1.0.10
networkx                 2.8.8
nltk                     3.8.1
num2words                0.5.13
numba                    0.60.0
numpy                    1.22.0
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
packaging                24.1
pandas                   1.5.3
pillow                   10.4.0
pip                      22.0.2
platformdirs             4.2.2
pooch                    1.8.2
preshed                  3.0.9
protobuf                 4.25.3
psutil                   6.0.0
pycparser                2.22
pydantic                 2.8.2
pydantic_core            2.20.1
pydub                    0.25.1
Pygments                 2.18.0
pynndescent              0.5.13
pyparsing                3.1.2
pypinyin                 0.51.0
pysbd                    0.3.4
pysrt                    1.1.2
python-crfsuite          0.9.10
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.1
regex                    2024.5.15
requests                 2.32.3
rich                     13.7.1
safetensors              0.4.3
scikit-learn             1.5.1
scipy                    1.11.4
setuptools               70.3.0
shellingham              1.5.4
six                      1.16.0
smart-open               7.0.4
soundfile                0.12.1
soxr                     0.3.7
spacy                    3.7.5
spacy-legacy             3.0.12
spacy-loggers            1.0.5
srsly                    2.4.8
SudachiDict-core         20240409
SudachiPy                0.6.8
sympy                    1.13.0
tensorboard              2.17.0
tensorboard-data-server  0.7.2
thinc                    8.2.5
threadpoolctl            3.5.0
tokenizers               0.19.1
torch                    2.3.1
torchaudio               2.3.1
torchvision              0.18.1
tqdm                     4.66.4
trainer                  0.0.36
transformers             4.42.3
triton                   2.3.1
TTS                      0.22.0
typeguard                4.3.0
typer                    0.12.3
typing_extensions        4.12.2
tzlocal                  5.2
umap-learn               0.5.6
Unidecode                1.3.8
urllib3                  2.2.2
wasabi                   1.1.3
weasel                   0.4.1
Werkzeug                 3.0.3
wheel                    0.43.0
wrapt                    1.16.0
yarl                     1.9.4
```

**Comment by eginhard** [comment]
This bug is fixed in [our fork](https://github.com/idiap/coqui-ai-TTS), you can install it with `pip install coqui-tts`

**Comment by thebitanpaul** [comment]
reffer to the ipynb files in the repo, and you can clone the voice using those ipynb codes. As of now, Bark and TTS are not communicating with each other properly.
