### ISSUE TITLE
[Bug] Failed building wheel

### ISSUE THREAD

**Issue by siddas27** [coqui-ai/TTS#3828]
### Describe the bug

  ERROR: Failed building wheel for TTS when building/installing TTS

### To Reproduce

Clone repo and pip install -e .

### Logs

```shell
Building wheels for collected packages: TTS
  Building editable for TTS (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for TTS (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [111 lines of output]
      running editable_wheel
      creating /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info
      writing /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/entry_points.txt
      writing requirements to /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/requires.txt
      writing top-level names to /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/top_level.txt
      writing manifest file '/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'tests*'
      adding license file 'LICENSE.txt'
      writing manifest file '/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS.egg-info/SOURCES.txt'
      creating '/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS-0.16.0.dist-info'
      creating /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-wheel-a7urs515/.tmp-w0nz8sfw/TTS-0.16.0.dist-info/WHEEL
      running build_py
      running build_ext
      building 'TTS.tts.utils.monotonic_align.core' extension
      creating /var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/tmp42gpisnb.build-temp/TTS
      creating /var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/tmp42gpisnb.build-temp/TTS/tts
      creating /var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/tmp42gpisnb.build-temp/TTS/tts/utils
      creating /var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/tmp42gpisnb.build-temp/TTS/tts/utils/monotonic_align
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/siddharthdas/miniconda3/envs/pytorch_env/include -arch arm64 -fPIC -O2 -isystem /Users/siddharthdas/miniconda3/envs/pytorch_env/include -arch arm64 -I/opt/homebrew/opt/portaudio/include/ -I/Users/siddharthdas/miniconda3/envs/pytorch_env/include/python3.11 -c TTS/tts/utils/monotonic_align/core.c -o /var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/tmp42gpisnb.build-temp/TTS/tts/utils/monotonic_align/core.o
      TTS/tts/utils/monotonic_align/core.c:711:10: fatal error: 'numpy/arrayobject.h' file not found
      #include "numpy/arrayobject.h"
               ^~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      Traceback (most recent call last):
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 71, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
        File "/Users/siddharthdas/miniconda3/envs/pytorch_env/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/clang', '-DNDEBUG', '-fwrapv', '-O2', '-Wall', '-fPIC', '-O2', '-isystem', '/Users/siddharthdas/miniconda3/envs/pytorch_env/include', '-arch', 'arm64', '-fPIC', '-O2', '-isystem', '/Users/siddharthdas/miniconda3/envs/pytorch_env/include', '-arch', 'arm64', '-I/opt/homebrew/opt/portaudio/include/', '-I/Users/siddharthdas/miniconda3/envs/pytorch_env/include/python3.11', '-c', 'TTS/tts/utils/monotonic_align/core.c', '-o', '/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/tmp42gpisnb.build-temp/TTS/tts/utils/monotonic_align/core.o']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 191, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1044, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 77, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 153, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 605, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 193, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      /private/var/folders/p4/l9n1n8dn11j15bpqytqc34d80000gn/T/pip-build-env-dyaojq_7/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:989: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `TTS` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for TTS
Failed to build TTS
ERROR: Could not build wheels for TTS, which is required to install pyproject.toml-based projects
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.1.0",
        "TTS": "0.16.0",
        "numpy": "1.24.3"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "arm",
        "python": "3.11.4",
        "version": "Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112"
    }
}
```

**Comment by rodyherrera** [comment]
Hello, I currently have the same problem..., were you able to solve it? I'm on Ubuntu 22.04, the documentation shows that it has only been tested up to version 20.10. 
![Screenshot from 2024-07-21 23-10-37](https://github.com/user-attachments/assets/5b78f075-44e2-4464-b8ee-7e986fb7c8f9)

**Comment by eginhard** [comment]
You'll need to first install Numpy, then it probably works. But you're trying to install an old version of the package for some reason and recent ones should take care of this automatically. You could also install [our fork](https://github.com/idiap/coqui-ai-TTS) instead, which is maintained and definitely supports recent Python/Ubuntu versions.

**Comment by 240db** [comment]
Hey so I just the heads up... TTS has always been a breeze to install but lately, i wasn't able to install it using python 3.1.x, 3.7.x or 3.8.x 

It worked with **3.9.17**! 🎉

Just make sure you use pyenv (set it up first),then install a later version of python like 3.9.17:

```bash
pyenv install 3.9.17
pyenv local 3.9.17
```

 Create a venv environment if applicable, and will be able to clone the repo, and install it from source to train and etc. 

```bash
git clone https://github.com/coqui-ai/TTS
pip install -e .[all,dev,notebooks]  # Select the relevant extras
```

I was stuck for two days on this, tried many things, at last, changing python version with pyenv is what solved it. I am not sure that exact version is necessary, but you will see that when using 3.7 or 3.8, pip will fail with a clear message stating TTS needs something below 3.1 or above 3.9 so I tried to get a later version. I was using Linux (Debian). Hopefully this will be helpful to others facing issues while installing.

**Comment by eginhard** [comment]
3.7 and 3.8 aren't supported anymore for a long time already, these Python versions have reached end-of-life and won't receive security updates anymore. Otherwise I also recommend to install [our fork](https://github.com/idiap/coqui-ai-TTS) with `pip install coqui-tts` which is still maintained and more compatible with recent Python and dependency versions.
