### ISSUE TITLE
[Bug] can not load the checkpoints when do fine-tune with XTTS_v2

### ISSUE THREAD

**Issue by kaen2891** [coqui-ai/TTS#3840]
### Describe the bug

Hello, community and @eginhard, 

For the XTTS fine-tuning, I manually downloaded `dvae.pth, mel_stats.pth, model.pth` and `vocab.json` in `train_gpt_xtts.py`.
Further, below is the command line for fine-tuning XTTS_v2.

```
CUDA_VISIBLE_DEVICES="0" python recipes/mshop/xtts_v2/train_gpt_xtts.py \
    --restore_path /home/ec2-user/SageMaker/workspace/TTS/XTTS/xtts_v2/model.pth
```

where the model.pth is derived from `tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)`

I got the error as below:

```
| > Layer missing in the checkpoint: dvae.decoder.3.net.4.weight
 | > Layer missing in the checkpoint: dvae.decoder.3.net.4.bias
 | > Layer missing in the checkpoint: dvae.decoder.4.0.conv.weight
 | > Layer missing in the checkpoint: dvae.decoder.4.0.conv.bias
 | > Layer missing in the checkpoint: dvae.decoder.5.0.conv.weight
 | > Layer missing in the checkpoint: dvae.decoder.5.0.conv.bias
 | > Layer missing in the checkpoint: dvae.decoder.6.weight
 | > Layer missing in the checkpoint: dvae.decoder.6.bias
 | > Layer missing in the checkpoint: dvae.codebook.embed
 | > Layer missing in the checkpoint: dvae.codebook.cluster_size
 | > Layer missing in the checkpoint: dvae.codebook.embed_avg
 | > Layer missing in the checkpoint: torch_mel_spectrogram_dvae.mel_stft.spectrogram.window
 | > Layer missing in the checkpoint: torch_mel_spectrogram_dvae.mel_stft.mel_scale.fb
 | > 0 / 1023 layers are restored.
 > Model restored from step 10000000
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/workspace/TTS/XTTS/recipes/mshop/xtts_v2/train_gpt_xtts.py", line 202, in <module>
    main()
  File "/home/ec2-user/SageMaker/workspace/TTS/XTTS/recipes/mshop/xtts_v2/train_gpt_xtts.py", line 186, in main
    trainer = Trainer(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/trainer/trainer.py", line 558, in __init__
    (self.model, self.optimizer, self.scaler, self.restore_step, self.restore_epoch) = self.restore_model(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/trainer/trainer.py", line 862, in restore_model
    restore_epoch = checkpoint["epoch"]
KeyError: 'epoch'
```

As a result,

1) I put the pretrained weights of dvae, hifigan (mel_stats.pth), model.pth in DVAE_CHECKPOINT, MEL_NORM_FILE, TOKENIZER_FILE, and XTTS_CHECKPOINT, but it seems like not working
2) When I check the XTTS_v2 checkpoints with torch.load() and do find 'epoch', there is no epoch in checkpoints.

### To Reproduce

```
CUDA_VISIBLE_DEVICES="0" python recipes/mshop/xtts_v2/train_gpt_xtts.py \
    --restore_path /home/ec2-user/SageMaker/workspace/TTS/XTTS/xtts_v2/model.pth
```

### Expected behavior

fine-tuning with own dataset

### Logs

```shell
| > Layer missing in the checkpoint: xtts.gpt.gpt.h.28.ln_2.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.28.mlp.c_fc.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.28.mlp.c_fc.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.28.mlp.c_proj.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.28.mlp.c_proj.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.ln_1.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.ln_1.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.attn.c_attn.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.attn.c_attn.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.attn.c_proj.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.attn.c_proj.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.ln_2.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.ln_2.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.mlp.c_fc.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.mlp.c_fc.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.mlp.c_proj.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.h.29.mlp.c_proj.bias
 | > Layer missing in the checkpoint: xtts.gpt.gpt.ln_f.weight
 | > Layer missing in the checkpoint: xtts.gpt.gpt.ln_f.bias
 | > Layer missing in the checkpoint: xtts.gpt.mel_pos_embedding.emb.weight
 | > Layer missing in the checkpoint: xtts.gpt.text_pos_embedding.emb.weight
 | > Layer missing in the checkpoint: xtts.gpt.final_norm.weight
 | > Layer missing in the checkpoint: xtts.gpt.final_norm.bias
 | > Layer missing in the checkpoint: xtts.gpt.text_head.weight
 | > Layer missing in the checkpoint: xtts.gpt.text_head.bias
 | > Layer missing in the checkpoint: xtts.gpt.mel_head.weight
 | > Layer missing in the checkpoint: xtts.gpt.mel_head.bias
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.latents
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.0.to_q.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.0.to_kv.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.0.to_out.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.1.0.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.1.0.bias
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.1.2.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.0.1.2.bias
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.0.to_q.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.0.to_kv.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.0.to_out.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.1.0.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.1.0.bias
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.1.2.weight
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.layers.1.1.2.bias
 | > Layer missing in the checkpoint: xtts.gpt.conditioning_perceiver.norm.gamma
 | > Layer missing in the checkpoint: torch_mel_spectrogram_style_encoder.mel_stft.spectrogram.window
 | > Layer missing in the checkpoint: torch_mel_spectrogram_style_encoder.mel_stft.mel_scale.fb
 | > Layer missing in the checkpoint: dvae.discrete_loss.accumulator_index
 | > Layer missing in the checkpoint: dvae.discrete_loss.accumulator_filled
 | > Layer missing in the checkpoint: dvae.discrete_loss.accumulator
 | > Layer missing in the checkpoint: dvae.encoder.0.0.weight
 | > Layer missing in the checkpoint: dvae.encoder.0.0.bias
 | > Layer missing in the checkpoint: dvae.encoder.1.0.weight
 | > Layer missing in the checkpoint: dvae.encoder.1.0.bias
 | > Layer missing in the checkpoint: dvae.encoder.2.net.0.weight
 | > Layer missing in the checkpoint: dvae.encoder.2.net.0.bias
 | > Layer missing in the checkpoint: dvae.encoder.2.net.2.weight
 | > Layer missing in the checkpoint: dvae.encoder.2.net.2.bias
 | > Layer missing in the checkpoint: dvae.encoder.2.net.4.weight
 | > Layer missing in the checkpoint: dvae.encoder.2.net.4.bias
 | > Layer missing in the checkpoint: dvae.encoder.3.net.0.weight
 | > Layer missing in the checkpoint: dvae.encoder.3.net.0.bias
 | > Layer missing in the checkpoint: dvae.encoder.3.net.2.weight
 | > Layer missing in the checkpoint: dvae.encoder.3.net.2.bias
 | > Layer missing in the checkpoint: dvae.encoder.3.net.4.weight
 | > Layer missing in the checkpoint: dvae.encoder.3.net.4.bias
 | > Layer missing in the checkpoint: dvae.encoder.4.net.0.weight
 | > Layer missing in the checkpoint: dvae.encoder.4.net.0.bias
 | > Layer missing in the checkpoint: dvae.encoder.4.net.2.weight
 | > Layer missing in the checkpoint: dvae.encoder.4.net.2.bias
 | > Layer missing in the checkpoint: dvae.encoder.4.net.4.weight
 | > Layer missing in the checkpoint: dvae.encoder.4.net.4.bias
 | > Layer missing in the checkpoint: dvae.encoder.5.weight
 | > Layer missing in the checkpoint: dvae.encoder.5.bias
 | > Layer missing in the checkpoint: dvae.decoder.0.weight
 | > Layer missing in the checkpoint: dvae.decoder.0.bias
 | > Layer missing in the checkpoint: dvae.decoder.1.net.0.weight
 | > Layer missing in the checkpoint: dvae.decoder.1.net.0.bias
 | > Layer missing in the checkpoint: dvae.decoder.1.net.2.weight
 | > Layer missing in the checkpoint: dvae.decoder.1.net.2.bias
 | > Layer missing in the checkpoint: dvae.decoder.1.net.4.weight
 | > Layer missing in the checkpoint: dvae.decoder.1.net.4.bias
 | > Layer missing in the checkpoint: dvae.decoder.2.net.0.weight
 | > Layer missing in the checkpoint: dvae.decoder.2.net.0.bias
 | > Layer missing in the checkpoint: dvae.decoder.2.net.2.weight
 | > Layer missing in the checkpoint: dvae.decoder.2.net.2.bias
 | > Layer missing in the checkpoint: dvae.decoder.2.net.4.weight
 | > Layer missing in the checkpoint: dvae.decoder.2.net.4.bias
 | > Layer missing in the checkpoint: dvae.decoder.3.net.0.weight
 | > Layer missing in the checkpoint: dvae.decoder.3.net.0.bias
 | > Layer missing in the checkpoint: dvae.decoder.3.net.2.weight
 | > Layer missing in the checkpoint: dvae.decoder.3.net.2.bias
 | > Layer missing in the checkpoint: dvae.decoder.3.net.4.weight
 | > Layer missing in the checkpoint: dvae.decoder.3.net.4.bias
 | > Layer missing in the checkpoint: dvae.decoder.4.0.conv.weight
 | > Layer missing in the checkpoint: dvae.decoder.4.0.conv.bias
 | > Layer missing in the checkpoint: dvae.decoder.5.0.conv.weight
 | > Layer missing in the checkpoint: dvae.decoder.5.0.conv.bias
 | > Layer missing in the checkpoint: dvae.decoder.6.weight
 | > Layer missing in the checkpoint: dvae.decoder.6.bias
 | > Layer missing in the checkpoint: dvae.codebook.embed
 | > Layer missing in the checkpoint: dvae.codebook.cluster_size
 | > Layer missing in the checkpoint: dvae.codebook.embed_avg
 | > Layer missing in the checkpoint: torch_mel_spectrogram_dvae.mel_stft.spectrogram.window
 | > Layer missing in the checkpoint: torch_mel_spectrogram_dvae.mel_stft.mel_scale.fb
 | > 0 / 1023 layers are restored.
 > Model restored from step 10000000
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/workspace/TTS/XTTS/recipes/mshop/xtts_v2/train_gpt_xtts.py", line 202, in <module>
    main()
  File "/home/ec2-user/SageMaker/workspace/TTS/XTTS/recipes/mshop/xtts_v2/train_gpt_xtts.py", line 186, in main
    trainer = Trainer(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/trainer/trainer.py", line 558, in __init__
    (self.model, self.optimizer, self.scaler, self.restore_step, self.restore_epoch) = self.restore_model(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/trainer/trainer.py", line 862, in restore_model
    restore_epoch = checkpoint["epoch"]
KeyError: 'epoch'
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB",
            "Tesla V100-SXM2-32GB"
        ],
        "available": true,
        "version": "12.1"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.3.1+cu121",
        "TTS": "0.22.0",
        "numpy": "1.22.0"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            "ELF"
        ],
        "processor": "x86_64",
        "python": "3.10.8",
        "version": "#1 SMP Tue May 21 16:52:24 UTC 2024"
    }
}
```

### Additional context

...

**Comment by eginhard** [comment]
Just run `CUDA_VISIBLE_DEVICES="0" python recipes/mshop/xtts_v2/train_gpt_xtts.py` without the `--restore_path`

**Comment by kaen2891** [comment]
Thanks for reply. However, what should I do if the work environment does not have an internet connection?

Does XTTS automatically loads the pretrained weigths from `XTTS_CHECKPOINT` if we do not give any `restore_path`?

**Comment by kaen2891** [comment]
It looks like `YourTTS` supports `restore_path` but `XTTS_v2` doesn't support though, right?

**Comment by kaen2891** [comment]
Ah, it automatically loads the XTTS checkpoints in [here](https://github.com/coqui-ai/TTS/blob/dev/TTS/tts/layers/xtts/trainer/gpt_trainer.py#L84).

Thanks
