### ISSUE TITLE
Crash while saving checkpoint : "Audio buffer is not finite everywhere"

### ISSUE THREAD

**Issue by astricks** [coqui-ai/TTS#387]
Hi,

First of all, thanks for all this great code!

Now, I'm training a new Tacotron2 using a Hindi dataset - 25 hours, 12,000 audio files, single speaker, not noisey, trimmed silences.

At 10000 global steps, when the model tries to save the checkpoint, it crashes with the message "Audio buffer is not finite everywhere". I've been trying to tweak the config parameters, but to no avail.

> Traceback (most recent call last):                                                                                                                                                           
  File "TTS/bin/train_tacotron.py", line 664, in <module>                                                                                                                                    
    main(args)                                                                                                                                                                               
  File "TTS/bin/train_tacotron.py", line 634, in main                                                                                                                                        
    scaler_st)                                                                                                                                                                               
  File "TTS/bin/train_tacotron.py", line 312, in train                                                                                                                                       
    train_audio = ap.inv_melspectrogram(const_spec.T)                                                                                                                                        
  File "/home/ubuntu/TTS/TTS/utils/audio.py", line 286, in inv_melspectrogram                                                                                                                
    return self._griffin_lim(S**self.power)                                                                                                                                                  
  File "/home/ubuntu/TTS/TTS/utils/audio.py", line 315, in _griffin_lim                                                                                                                      
    angles = np.exp(1j * np.angle(self._stft(y)))                                                                                                                                            
  File "/home/ubuntu/TTS/TTS/utils/audio.py", line 303, in _stft                                                                                                                             
    pad_mode=self.stft_pad_mode,                                                                                                                                                             
  File "/home/ubuntu/.local/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft                                                                                         
    util.valid_audio(y)                                                                                                                                                                      
  File "/home/ubuntu/.local/lib/python3.6/site-packages/librosa/util/utils.py", line 275, in valid_audio                                                                                     
    raise ParameterError('Audio buffer is not finite everywhere')                                                                                                                            
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere 

I'd really appreciate any hints to what might be causing this.

**Comment by astricks** [comment]
I'll dig a little deeper, closing for now. I had a misconfigured parameter. Still hitting issues, but will reopen another issue if i can't resolve it myself.

**Comment by Sadam1195** [comment]
Hi @astricks  I fixed same issue with my dataset by changing following lines in `usr/local/lib/python3.7/site-packages/librosa/util/utils.py`

From

    if not np.isfinite(y).all():
        raise ParameterError('Audio buffer is not finite everywhere')

 to
 
     if not np.isfinite(y).all():
        y = np.nan_to_num(y)
        pass

Not sure, if that was the right thing to do but it solved my issue.
