### ISSUE TITLE
[Bug] Install on clean Ubuntu 22.04 fails in SudachiPy build....

### ISSUE THREAD

**Issue by pwayner** [coqui-ai/TTS#3989]
### Describe the bug

I'm trying to install TTS on an ARM server with a clean version of Ubuntu 22.04 after "apt install python3-pip". 

Here's the bug in the log section. 

TIA

### To Reproduce

Start with a clean version of 22.04 on an arm server. 
Run "apt install python3-pip"
Run "pip install TTS"

### Logs

```shell
pip install TTS
Collecting TTS
  Using cached TTS-0.22.0.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting unidecode>=1.3.2
  Using cached Unidecode-1.3.8-py3-none-any.whl (235 kB)
Collecting umap-learn>=0.5.1
  Using cached umap_learn-0.5.6-py3-none-any.whl (85 kB)
Collecting coqpit>=0.0.16
  Using cached coqpit-0.0.17-py3-none-any.whl (13 kB)
Collecting torch>=2.1
  Using cached torch-2.4.1-cp310-cp310-manylinux2014_aarch64.whl (89.7 MB)
Collecting bangla
  Using cached bangla-0.0.2-py2.py3-none-any.whl (6.2 kB)
Collecting spacy[ja]>=3
  Using cached spacy-3.7.6.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bnnumerizer
  Using cached bnnumerizer-0.0.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... done
Collecting einops>=0.6.0
  Using cached einops-0.8.0-py3-none-any.whl (43 kB)
Collecting inflect>=5.6.0
  Using cached inflect-7.3.1-py3-none-any.whl (34 kB)
Collecting trainer>=0.0.32
  Using cached trainer-0.0.36-py3-none-any.whl (51 kB)
Collecting flask>=2.0.1
  Using cached flask-3.0.3-py3-none-any.whl (101 kB)
Collecting scipy>=1.11.2
  Using cached scipy-1.14.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (35.6 MB)
Collecting packaging>=23.1
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
Collecting fsspec>=2023.6.0
  Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)
Collecting nltk
  Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Collecting gruut[de,es,fr]==2.2.3
  Using cached gruut-2.2.3.tar.gz (73 kB)
  Preparing metadata (setup.py) ... done
Collecting anyascii>=0.3.0
  Using cached anyascii-0.3.2-py3-none-any.whl (289 kB)
Collecting tqdm>=4.64.1
  Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)
Collecting cython>=0.29.30
  Using cached Cython-3.0.11-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.5 MB)
Collecting transformers>=4.33.0
  Using cached transformers-4.44.2-py3-none-any.whl (9.5 MB)
Collecting numba>=0.57.0
  Using cached numba-0.60.0-cp310-cp310-manylinux2014_aarch64.manylinux_2_17_aarch64.whl (3.4 MB)
Collecting g2pkk>=0.1.1
  Using cached g2pkk-0.1.2-py3-none-any.whl (25 kB)
Collecting encodec>=0.1.1
  Using cached encodec-0.1.1.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... done
Collecting pyyaml>=6.0
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (718 kB)
Collecting scikit-learn>=1.3.0
  Using cached scikit_learn-1.5.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (12.5 MB)
Collecting aiohttp>=3.8.1
  Using cached aiohttp-3.10.5-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.2 MB)
Collecting torchaudio
  Using cached torchaudio-2.4.1-cp310-cp310-manylinux2014_aarch64.whl (1.7 MB)
Collecting jamo
  Using cached jamo-0.4.1-py3-none-any.whl (9.5 kB)
Collecting jieba
  Using cached jieba-0.42.1.tar.gz (19.2 MB)
  Preparing metadata (setup.py) ... done
Collecting pandas<2.0,>=1.4
  Using cached pandas-1.5.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.4 MB)
Collecting bnunicodenormalizer
  Using cached bnunicodenormalizer-0.1.7-py3-none-any.whl (23 kB)
Collecting pypinyin
  Using cached pypinyin-0.52.0-py2.py3-none-any.whl (833 kB)
Collecting numpy==1.22.0
  Using cached numpy-1.22.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.4 MB)
Collecting soundfile>=0.12.0
  Using cached soundfile-0.12.1-py2.py3-none-any.whl (24 kB)
Collecting pysbd>=0.3.4
  Using cached pysbd-0.3.4-py3-none-any.whl (71 kB)
Collecting hangul-romanize
  Using cached hangul_romanize-0.1.0-py3-none-any.whl (4.6 kB)
Collecting librosa>=0.10.0
  Using cached librosa-0.10.2.post1-py3-none-any.whl (260 kB)
Collecting matplotlib>=3.7.0
  Using cached matplotlib-3.9.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (8.2 MB)
Collecting num2words
  Using cached num2words-0.5.13-py3-none-any.whl (143 kB)
Requirement already satisfied: Babel<3.0.0,>=2.8.0 in /usr/lib/python3/dist-packages (from gruut[de,es,fr]==2.2.3->TTS) (2.8.0)
Collecting dateparser~=1.1.0
  Using cached dateparser-1.1.8-py2.py3-none-any.whl (293 kB)
Collecting gruut-ipa<1.0,>=0.12.0
  Using cached gruut-ipa-0.13.0.tar.gz (101 kB)
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_en~=2.0.0
  Using cached gruut_lang_en-2.0.1.tar.gz (15.3 MB)
  Preparing metadata (setup.py) ... done
Collecting jsonlines~=1.2.0
  Using cached jsonlines-1.2.0-py2.py3-none-any.whl (7.6 kB)
Collecting networkx<3.0.0,>=2.5.0
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting python-crfsuite~=0.9.7
  Using cached python-crfsuite-0.9.10.tar.gz (478 kB)
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_fr~=2.0.0
  Using cached gruut_lang_fr-2.0.2.tar.gz (10.9 MB)
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_de~=2.0.0
  Using cached gruut_lang_de-2.0.1.tar.gz (18.1 MB)
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_es~=2.0.0
  Using cached gruut_lang_es-2.0.1.tar.gz (31.4 MB)
  Preparing metadata (setup.py) ... done
Collecting async-timeout<5.0,>=4.0
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.5-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (126 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (238 kB)
Collecting aiohappyeyeballs>=2.3.0
  Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl (12 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp>=3.8.1->TTS) (21.2.0)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.11-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (462 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting Jinja2>=3.1.2
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Collecting blinker>=1.6.2
  Using cached blinker-1.8.2-py3-none-any.whl (9.5 kB)
Collecting click>=8.1.3
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting itsdangerous>=2.1.2
  Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Collecting Werkzeug>=3.0.0
  Using cached werkzeug-3.0.4-py3-none-any.whl (227 kB)
Requirement already satisfied: more-itertools>=8.5.0 in /usr/lib/python3/dist-packages (from inflect>=5.6.0->TTS) (8.10.0)
Collecting typeguard>=4.0.1
  Using cached typeguard-4.3.0-py3-none-any.whl (35 kB)
Collecting pooch>=1.1
  Using cached pooch-1.8.2-py3-none-any.whl (64 kB)
Collecting typing-extensions>=4.1.1
  Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting soxr>=0.3.2
  Using cached soxr-0.5.0.post1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (221 kB)
Collecting audioread>=2.1.9
  Using cached audioread-3.0.1-py3-none-any.whl (23 kB)
Collecting lazy-loader>=0.1
  Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Collecting decorator>=4.3.0
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting librosa>=0.10.0
  Using cached librosa-0.10.2-py3-none-any.whl (260 kB)
  Using cached librosa-0.10.1-py3-none-any.whl (253 kB)
  Using cached librosa-0.10.0.post2-py3-none-any.whl (253 kB)
Collecting pooch<1.7,>=1.0
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Collecting librosa>=0.10.0
  Using cached librosa-0.10.0.post1-py3-none-any.whl (252 kB)
  Using cached librosa-0.10.0-py3-none-any.whl (252 kB)
Collecting joblib>=0.14
  Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Collecting msgpack>=1.0
  Using cached msgpack-1.0.8-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (376 kB)
Collecting matplotlib>=3.7.0
  Using cached matplotlib-3.9.1.post1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (8.2 MB)
  Using cached matplotlib-3.9.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (8.2 MB)
  Using cached matplotlib-3.8.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.4 MB)
Collecting kiwisolver>=1.3.1
  Using cached kiwisolver-1.4.7-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.4 MB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.53.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.6 MB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting pillow>=8
  Using cached pillow-10.4.0-cp310-cp310-manylinux_2_28_aarch64.whl (4.4 MB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.3.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (308 kB)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.7.0->TTS) (2.4.7)
Collecting docopt>=0.6.2
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.44,>=0.43.0dev0
  Using cached llvmlite-0.43.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (42.9 MB)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas<2.0,>=1.4->TTS) (2022.1)
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Collecting scipy>=1.11.2
  Using cached scipy-1.14.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (35.6 MB)
  Using cached scipy-1.13.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (33.7 MB)
  Using cached scipy-1.13.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (33.7 MB)
  Using cached scipy-1.12.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (34.8 MB)
  Using cached scipy-1.11.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (32.9 MB)
Collecting cffi>=1.0
  Using cached cffi-1.17.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (448 kB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.8-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (44 kB)
Collecting typer<1.0.0,>=0.3.0
  Using cached typer-0.12.5-py3-none-any.whl (47 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from spacy[ja]>=3->TTS) (59.6.0)
Collecting spacy-loggers<2.0.0,>=1.0.0
  Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Collecting wasabi<1.2.0,>=0.9.1
  Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/lib/python3/dist-packages (from spacy[ja]>=3->TTS) (2.25.1)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.10-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (29 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4
  Using cached pydantic-2.9.0-py3-none-any.whl (434 kB)
Collecting catalogue<2.1.0,>=2.0.6
  Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting langcodes<4.0.0,>=3.2.0
  Using cached langcodes-3.4.0-py3-none-any.whl (182 kB)
Collecting srsly<3.0.0,>=2.4.3
  Using cached srsly-2.4.8-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (488 kB)
Collecting thinc<8.3.0,>=8.2.2
  Using cached thinc-8.2.5-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (868 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.9-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (150 kB)
Collecting weasel<0.5.0,>=0.1.0
  Using cached weasel-0.4.1-py3-none-any.whl (50 kB)
Collecting sudachipy!=0.6.1,>=0.5.2
  Using cached SudachiPy-0.6.8.tar.gz (161 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 18, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 836, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 835, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2464, in load
          self.require(*args, **kwargs)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2487, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
          raise VersionConflict(dist, req).with_context(dependent_req)
      pkg_resources.VersionConflict: (setuptools 59.6.0 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=62.4'))
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment

```shell
Not finished.
```

**Comment by shiftbug** [comment]
same on mac m3 clean conda env python 3.9, 3.11

**Comment by mohsintariq-locai** [comment]
anyone found any fix for this?

**Comment by eginhard** [comment]
Few things to try:
- install into a virtual environment
- install [our fork](https://github.com/idiap/coqui-ai-TTS) with `pip install coqui-tts` for better compatibility with recent Python and dependency versions

**Comment by haydonryan** [comment]
I'm not seeing issues in SudachiPy, but i'm seeing them when compiling spacy..

I'm using python 3.11 and a virtual environment.  I think I need to downgrade further.  It also feels like the documentation needs to be updated.  It's clear it's not actually tested on 3.11 or whichever pyhthon you're using.  It would be good to see some known working versions, as well as what the dependicies (all, dev, notebooks) do.  It's clear notebooks are for juniper notebooks, but what is all / dev? who needs those features etc.

I did find something online saying that cyphton needs an older version as there is a problem with the version of spacy.

Python dependency hell really sucks.

```
  Using cached spacy-3.0.6.tar.gz (7.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [167 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          int length
      
      
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:28:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:29:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:30:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:32:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
          cpdef public object get_noun_chunks
                ^
      ------------------------------------------------------------
      
      spacy/vocab.pxd:33:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef float prior_prob
      
      
      cdef class KnowledgeBase:
          cdef Pool mem
          cpdef readonly Vocab vocab
                ^
      ------------------------------------------------------------
      
      spacy/kb.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      Copied /tmp/pip-install-g7sckm_1/spacy_4e0763a3f2c24cbfa363f3cca5b0cecf/setup.cfg -> /tmp/pip-install-g7sckm_1/spacy_4e0763a3f2c24cbfa363f3cca5b0cecf/spacy/tests/package
      Copied /tmp/pip-install-g7sckm_1/spacy_4e0763a3f2c24cbfa363f3cca5b0cecf/pyproject.toml -> /tmp/pip-install-g7sckm_1/spacy_4e0763a3f2c24cbfa363f3cca5b0cecf/spacy/tests/package
      Cythonizing sources
      Compiling spacy/training/example.pyx because it changed.
      Compiling spacy/parts_of_speech.pyx because it changed.
      Compiling spacy/strings.pyx because it changed.
      Compiling spacy/lexeme.pyx because it changed.
      Compiling spacy/vocab.pyx because it changed.
      Compiling spacy/attrs.pyx because it changed.
      Compiling spacy/kb.pyx because it changed.
      Compiling spacy/ml/parser_model.pyx because it changed.
      Compiling spacy/morphology.pyx because it changed.
      Compiling spacy/pipeline/dep_parser.pyx because it changed.
      Compiling spacy/pipeline/morphologizer.pyx because it changed.
      Compiling spacy/pipeline/multitask.pyx because it changed.
      Compiling spacy/pipeline/ner.pyx because it changed.
      Compiling spacy/pipeline/pipe.pyx because it changed.
      Compiling spacy/pipeline/trainable_pipe.pyx because it changed.
      Compiling spacy/pipeline/sentencizer.pyx because it changed.
      Compiling spacy/pipeline/senter.pyx because it changed.
      Compiling spacy/pipeline/tagger.pyx because it changed.
      Compiling spacy/pipeline/transition_parser.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/ner.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_state.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it changed.
      Compiling spacy/tokenizer.pyx because it changed.
      Compiling spacy/training/align.pyx because it changed.
      Compiling spacy/training/gold_io.pyx because it changed.
      Compiling spacy/tokens/doc.pyx because it changed.
      Compiling spacy/tokens/span.pyx because it changed.
      Compiling spacy/tokens/token.pyx because it changed.
      Compiling spacy/tokens/span_group.pyx because it changed.
      Compiling spacy/tokens/graph.pyx because it changed.
      Compiling spacy/tokens/morphanalysis.pyx because it changed.
      Compiling spacy/tokens/_retokenize.pyx because it changed.
      Compiling spacy/matcher/matcher.pyx because it changed.
      Compiling spacy/matcher/phrasematcher.pyx because it changed.
      Compiling spacy/matcher/dependencymatcher.pyx because it changed.
      Compiling spacy/symbols.pyx because it changed.
      Compiling spacy/vectors.pyx because it changed.
      [ 1/41] Cythonizing spacy/attrs.pyx
      [ 2/41] Cythonizing spacy/kb.pyx
      Traceback (most recent call last):
        File "/home/haydon/workspace/TTS/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/haydon/workspace/TTS/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/haydon/workspace/TTS/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-evsx3x6_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-evsx3x6_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-evsx3x6_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "/tmp/pip-build-env-evsx3x6_/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-evsx3x6_/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by eginhard** [comment]
> I'm using python 3.11 and a virtual environment. I think I need to downgrade further. It also feels like the documentation needs to be updated. It's clear it's not actually tested on 3.11 or whichever pyhthon you're using. It would be good to see some known working versions, as well as what the dependicies (all, dev, notebooks) do. It's clear notebooks are for juniper notebooks, but what is all / dev? who needs those features etc.

@haydonryan Just install the fork (with `pip install coqui-tts`), it is tested to work with Python versions 3.9 to 3.12 and the readme documents what the different extras are needed for. This repo is not maintained anymore, so breakages are expected.

**Comment by haydonryan** [comment]
@eginhard and pip install will work for Finetuning, retraining? 

I'll try your fork.  I wish they'd document in the README that the project is unmaintained...

**Comment by eginhard** [comment]
> and pip install will work for Finetuning, retraining?

@haydonryan Yes of course, you can use it just like the original package.
