### ISSUE TITLE
[Bug] 安装TTS失败

### ISSUE THREAD

**Issue by Alex-DeepL** [coqui-ai/TTS#4018]
### Describe the bug

      Traceback (most recent call last):
        File "/root/miniconda3/envs/xtts_v2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/xtts_v2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/xtts_v2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

### To Reproduce

      Traceback (most recent call last):
        File "/root/miniconda3/envs/xtts_v2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/xtts_v2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/xtts_v2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-omv17cfm/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

### Environment

```shell
python3.10 linux
```

**Comment by NeverBeLazyG** [comment]
I have same problem:

pip install TTS
...
....
...
      Compiling spacy/matcher/matcher.pyx because it changed.
      Compiling spacy/matcher/phrasematcher.pyx because it changed.
      Compiling spacy/matcher/dependencymatcher.pyx because it changed.
      Compiling spacy/symbols.pyx because it changed.
      Compiling spacy/vectors.pyx because it changed.
      [ 1/41] Cythonizing spacy/attrs.pyx
      [ 2/41] Cythonizing spacy/kb.pyx
      Traceback (most recent call last):
        File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\youba\AppData\Local\Temp\pip-build-env-tlncvz06\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\youba\AppData\Local\Temp\pip-build-env-tlncvz06\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\youba\AppData\Local\Temp\pip-build-env-tlncvz06\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "C:\Users\youba\AppData\Local\Temp\pip-build-env-tlncvz06\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\youba\AppData\Local\Temp\pip-build-env-tlncvz06\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS D:\python>

**Comment by Daewooki** [comment]
i have same issue. 

how can i solve it?
Every time I installed it with make install,
 it was fine, but suddenly it doesn't work. 

Are the cython and spacy versions updated?

**Comment by Daewooki** [comment]
I fixed the problem by fixing requirements tensorflow==4.44.2 and spacy[ja]==3.7.6 and running make install.

**Comment by NeverBeLazyG** [comment]
> I fixed the problem by fixing requirements tensorflow==4.44.2 and spacy[ja]==3.7.6 and running make install.

??? more details please

**Comment by Daewooki** [comment]
Modify requirements.txt as below and run pip install.

transformers==4.44.2
spacy[ja]==3.7.6

**Comment by NeverBeLazyG** [comment]
> Modify requirements.txt as below and run pip install.
> 
> transformers==4.44.2 spacy[ja]==3.7.6

thank you it worked

**Comment by eginhard** [comment]
You can install [our fork](https://github.com/idiap/coqui-ai-TTS) instead with `pip install coqui-tts`, which should work fine. This repo is not maintained anymore.

**Comment by NeverBeLazyG** [comment]
> You can install [our fork](https://github.com/idiap/coqui-ai-TTS) instead with `pip install coqui-tts`, which should work fine. This repo is not maintained anymore.

thank you that worked like a charm, what is the differece between coquiTTS and TTS ?

**Comment by eginhard** [comment]
Mostly a lot of bugs were fixed, you can see a more detailed summary of changes here: https://github.com/idiap/coqui-ai-TTS/releases

**Comment by NeverBeLazyG** [comment]
> Mostly a lot of bugs were fixed, you can see a more detailed summary of changes here: https://github.com/idiap/coqui-ai-TTS/releases

nice thanks. it woked good

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech
