### ISSUE TITLE
[Bug] ERROR on Install

### ISSUE THREAD

**Issue by sysmaya** [coqui-ai/TTS#4029]
### Describe the bug

The installation process generates an error. The installation ends abruptly with an error.
![Sin título](https://github.com/user-attachments/assets/eb784bc7-475f-40c9-9dac-5c9551dd7162)

### To Reproduce

In Windows:
pip install TTS

### Logs

```shell
spacy-3.0.6.tar.gz (7.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [167 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          int length


      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
                ^
      ------------------------------------------------------------

      spacy\vocab.pxd:28:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
                ^
      ------------------------------------------------------------

      spacy\vocab.pxd:29:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
                ^
      ------------------------------------------------------------

      spacy\vocab.pxd:30:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef class Vocab:
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
                ^
      ------------------------------------------------------------

      spacy\vocab.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef Pool mem
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
                ^
      ------------------------------------------------------------

      spacy\vocab.pxd:32:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cpdef readonly StringStore strings
          cpdef public Morphology morphology
          cpdef public object vectors
          cpdef public object _lookups
          cpdef public object writing_system
          cpdef public object get_noun_chunks
                ^
      ------------------------------------------------------------

      spacy\vocab.pxd:33:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef float prior_prob


      cdef class KnowledgeBase:
          cdef Pool mem
          cpdef readonly Vocab vocab
                ^
      ------------------------------------------------------------

      spacy\kb.pxd:31:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
      Copied C:\Users\Janus\AppData\Local\Temp\pip-install-kr8p7o0r\spacy_c1b1e55d6c504b0a9f9118071393bed6\setup.cfg -> C:\Users\Janus\AppData\Local\Temp\pip-install-kr8p7o0r\spacy_c1b1e55d6c504b0a9f9118071393bed6\spacy\tests\package
      Copied C:\Users\Janus\AppData\Local\Temp\pip-install-kr8p7o0r\spacy_c1b1e55d6c504b0a9f9118071393bed6\pyproject.toml -> C:\Users\Janus\AppData\Local\Temp\pip-install-kr8p7o0r\spacy_c1b1e55d6c504b0a9f9118071393bed6\spacy\tests\package
      Cythonizing sources
      Compiling spacy/training/example.pyx because it changed.
      Compiling spacy/parts_of_speech.pyx because it changed.
      Compiling spacy/strings.pyx because it changed.
      Compiling spacy/lexeme.pyx because it changed.
      Compiling spacy/vocab.pyx because it changed.
      Compiling spacy/attrs.pyx because it changed.
      Compiling spacy/kb.pyx because it changed.
      Compiling spacy/ml/parser_model.pyx because it changed.
      Compiling spacy/morphology.pyx because it changed.
      Compiling spacy/pipeline/dep_parser.pyx because it changed.
      Compiling spacy/pipeline/morphologizer.pyx because it changed.
      Compiling spacy/pipeline/multitask.pyx because it changed.
      Compiling spacy/pipeline/ner.pyx because it changed.
      Compiling spacy/pipeline/pipe.pyx because it changed.
      Compiling spacy/pipeline/trainable_pipe.pyx because it changed.
      Compiling spacy/pipeline/sentencizer.pyx because it changed.
      Compiling spacy/pipeline/senter.pyx because it changed.
      Compiling spacy/pipeline/tagger.pyx because it changed.
      Compiling spacy/pipeline/transition_parser.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/arc_eager.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/ner.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/nonproj.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_state.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/stateclass.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/transition_system.pyx because it changed.
      Compiling spacy/pipeline/_parser_internals/_beam_utils.pyx because it changed.
      Compiling spacy/tokenizer.pyx because it changed.
      Compiling spacy/training/align.pyx because it changed.
      Compiling spacy/training/gold_io.pyx because it changed.
      Compiling spacy/tokens/doc.pyx because it changed.
      Compiling spacy/tokens/span.pyx because it changed.
      Compiling spacy/tokens/token.pyx because it changed.
      Compiling spacy/tokens/span_group.pyx because it changed.
      Compiling spacy/tokens/graph.pyx because it changed.
      Compiling spacy/tokens/morphanalysis.pyx because it changed.
      Compiling spacy/tokens/_retokenize.pyx because it changed.
      Compiling spacy/matcher/matcher.pyx because it changed.
      Compiling spacy/matcher/phrasematcher.pyx because it changed.
      Compiling spacy/matcher/dependencymatcher.pyx because it changed.
      Compiling spacy/symbols.pyx because it changed.
      Compiling spacy/vectors.pyx because it changed.
      [ 1/41] Cythonizing spacy/attrs.pyx
      [ 2/41] Cythonizing spacy/kb.pyx
      Traceback (most recent call last):
        File "C:\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Janus\AppData\Local\Temp\pip-build-env-hqxk2lr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Janus\AppData\Local\Temp\pip-build-env-hqxk2lr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Janus\AppData\Local\Temp\pip-build-env-hqxk2lr3\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 211, in setup_package
        File "C:\Users\Janus\AppData\Local\Temp\pip-build-env-hqxk2lr3\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\Janus\AppData\Local\Temp\pip-build-env-hqxk2lr3\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: spacy/kb.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### Environment

```shell
TTS-0.22.0.tar.gz
Windows 11
Python 3.11.5
```

**Comment by eginhard** [comment]
Please install [our fork](https://github.com/idiap/coqui-ai-TTS) with `pip install coqui-tts` where this is fixed. This repo is not maintained anymore.

**Comment by burn0ut7** [comment]
+1

**Comment by ImranDevJourney** [comment]
you will need to downgrade python to 3.10 because currently there are problems with 3.11 particularly with dependencies like PyTorch and spaCy, which are crucial for the TTS library to function correctly.

**Comment by majiachen92** [comment]
I keep on getting the following message

(project) F:\workspace\project>pip install TTS
Collecting TTS
  Using cached TTS-0.22.0.tar.gz (1.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 3221225477
  ╰─> [53 lines of output]
      Collecting setuptools
        Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting wheel
        Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
      ERROR: Exception:
      Traceback (most recent call last):
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
          status = _inner_run()
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
          return self.run(options, args)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
          return func(self, options, args)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
          requirement_set = resolver.resolve(
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
          result = self._result = resolver.resolve(
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
          if not criterion.candidates:
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
          return bool(self._sequence)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
          return any(self)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 49, in _iter_built
          for version, func in infos:
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 307, in iter_index_candidate_infos
          result = self._finder.find_best_candidate(
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\index\package_finder.py", line 883, in find_best_candidate
          candidates = self.find_all_candidates(project_name)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\index\package_finder.py", line 824, in find_all_candidates
          page_candidates = list(page_candidates_it)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\index\sources.py", line 193, in page_candidates
          yield from self._candidates_from_page(self._link)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\index\package_finder.py", line 788, in process_project_url
          page_links = list(parse_links(index_response))
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\index\collector.py", line 218, in wrapper_wrapper
          return list(fn(page))
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\index\collector.py", line 233, in parse_links
          link = Link.from_json(file, page.url)
        File "C:\Users\USERNAME\.conda\envs\project\Lib\site-packages\pip\_internal\models\link.py", line 273, in from_json
          url = _ensure_quoted_url(urllib.parse.urljoin(page_url, file_url))
        File "C:\Users\USERNAME\.conda\envs\project\lib\urllib\parse.py", line 553, in urljoin
          return _coerce_result(urlunparse((scheme, netloc, path,
        File "C:\Users\USERNAME\.conda\envs\project\lib\urllib\parse.py", line 514, in urlunparse
          return _coerce_result(urlunsplit((scheme, netloc, url, query, fragment)))
        File "C:\Users\USERNAME\.conda\envs\project\lib\urllib\parse.py", line 528, in urlunsplit
          url = scheme + ':' + url
      TypeError: can only concatenate tuple (not "str") to tuple
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 3221225477
╰─> See above for output.

**Comment by eginhard** [comment]
@majiachen92 As written above: Please install [our fork](https://github.com/idiap/coqui-ai-TTS) with `pip install coqui-tts` where this is fixed. This repo is not maintained anymore.
