### ISSUE TITLE
Vocoder training fails on Windows versions of Python

### ISSUE THREAD

**Issue by GuyPaddock** [coqui-ai/TTS#404]
Trying to train a WaveGrad Vocoder on Python 3.8.8 for Windows 10 yields this error:
```
Traceback (most recent call last):
  File "./TTS/bin/train_vocoder_wavegrad.py", line 442, in <module>
    main(args)
  File "./TTS/bin/train_vocoder_wavegrad.py", line 417, in main
    best_loss = save_best_model(
  File "TTS\vocoder\utils\io.py", line 97, in save_best_model
    os.symlink(best_model_name, os.path.join(out_path, link_name))
OSError: [WinError 1314] A required privilege is not held by the client: 'best_model_1.pth.tar' -> 'c:/path/to/my/project/best_model.pth.tar'
 ```
This is  because Windows only lets admins create symlinks for... reasons...

**Comment by GuyPaddock** [comment]
This isn't stale..
