### ISSUE TITLE
[Bug] Dependencies in 0.0.13.1

### ISSUE THREAD

**Issue by gizmo84** [coqui-ai/TTS#466]
**Describe the bug**
With TTS==0.0.13.1

from TTS.utils.synthesizer import Synthesizer

- ModuleNotFoundError: No module named 'numba.decorators'
The error seems to come from librosa. Solution: pin dependency numba to 0.48. See https://github.com/librosa/librosa/issues/1160
- ModuleNotFoundError: No module named 'packaging'
Solution: require Dependency on packaging

**To Reproduce**
1. pip install TTS==0.0.13.1
2. from TTS.utils.synthesizer import Synthesizer
3. See error

**Expected behavior**
No Exceptions :)

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker python:3.8
- **PyTorch or TensorFlow version (use command below)**:
- **Python version**: Python 3.8.9

**Comment by erogol** [comment]
can you try the dev branch now?

**Comment by AndrewBarfield** [comment]
Same here:

```
Name: stt
Version: 0.10.0a6
Summary: A library for doing speech recognition using a Coqui STT model
Home-page: https://github.com/coqui-ai/STT
Author: Coqui GmbH
Author-email: None
License: MPL-2.0
Location: /home/drew/.local/lib/python3.8/site-packages
Requires: numpy
Required-by: 
 
Name: TTS
Version: 0.0.13.1
Summary: Deep learning for Text to Speech by Coqui.
Home-page: https://github.com/coqui-ai/TTS
Author: Eren Gölge
Author-email: egolge@coqui.ai
License: MPL-2.0
Location: /home/drew/.local/lib/python3.8/site-packages
Requires: scipy, tqdm, pysbd, cython, pyyaml, torch, tensorboardX, matplotlib, flask, librosa, unidecode, umap-learn, inflect, pandas, pypinyin, phonemizer, jieba, numpy, gdown, soundfile
Required-by: 
 

~/Repositories/coqui
$ tts --model_name "tts_models/en/ljspeech/speedy-speech-wn" --vocoder_name "vocoder_models/en/ljspeech/multiband-melgan" --text "Halcy."
Traceback (most recent call last):
  File "/home/drew/.local/bin/tts", line 5, in <module>
    from TTS.bin.synthesize import main
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 9, in <module>
    from TTS.tts.utils.speakers import SpeakerManager
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/tts/utils/speakers.py", line 10, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/utils/audio.py", line 1, in <module>
    import librosa
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'

~/Repositories/coqui
$ tts-server --model_name tts_models/en/vctk/sc-glow-tts
Traceback (most recent call last):
  File "/home/drew/.local/bin/tts-server", line 5, in <module>
    from TTS.server.server import main
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/server/server.py", line 14, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 9, in <module>
    from TTS.tts.utils.speakers import SpeakerManager
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/tts/utils/speakers.py", line 10, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/home/drew/.local/lib/python3.8/site-packages/TTS/utils/audio.py", line 1, in <module>
    import librosa
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/home/drew/.local/lib/python3.8/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

**Comment by AndrewBarfield** [comment]
Solution: **python3 -m pip install numba==0.48**

**Comment by krisgesling** [comment]
Can confirm this is fixed when installing from the dev branch :+1:

```bash
pip install https://github.com/coqui-ai/TTS/tarball/dev
```

**Comment by erogol** [comment]
I close as I merged the dev
