### ISSUE TITLE
[Bug] Cannot install on windows

### ISSUE THREAD

**Issue by avaer** [coqui-ai/TTS#504]
```C:\Users\avaer\Documents\GitHub\TTS>pip install -e .
Obtaining file:///C:/Users/avaer/Documents/GitHub/TTS
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\avaer\appdata\local\programs\python\python37\python.exe' 'c:\users\avaer\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\avaer\AppData\Local\Temp\tmpi2zn5wiz'
       cwd: C:\Users\avaer\Documents\GitHub\TTS
  Complete output (55 lines):
  Compiling TTS/tts/layers/glow_tts/monotonic_align/core.pyx because it changed.
  [1/1] Cythonizing TTS/tts/layers/glow_tts/monotonic_align/core.pyx
  running egg_info
  writing TTS.egg-info\PKG-INFO
  writing dependency_links to TTS.egg-info\dependency_links.txt
  writing entry points to TTS.egg-info\entry_points.txt
  writing requirements to TTS.egg-info\requires.txt
  writing top-level names to TTS.egg-info\top_level.txt
  reading manifest file 'TTS.egg-info\SOURCES.txt'
  C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\dist.py:694: UserWarning: Usage of dash-separated 'build-lib' will not be supported in future versions. Please use the underscore name 'build_lib' instead
    % (opt, underscore_opt))
  C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\dist.py:694: UserWarning: Usage of dash-separated 'build-dir' will not be supported in future versions. Please use the underscore name 'build_dir' instead
    % (opt, underscore_opt))
  Traceback (most recent call last):
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 125, in <module>
      zip_safe=False
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 299, in run
      self.find_sources()
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
      mm.run()
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 541, in run
      self.add_defaults()
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 585, in add_defaults
      self.read_manifest()
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\sdist.py", line 188, in read_manifest
      self.filelist.append(line)
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 485, in append
      if self._safe_path(path):
    File "C:\Users\avaer\AppData\Local\Temp\pip-build-env-br8yo9w_\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 518, in _safe_path
      if os.path.exists(u_path) or os.path.exists(utf8_path):
    File "c:\users\avaer\appdata\local\programs\python\python37\lib\genericpath.py", line 19, in exists
      os.stat(path)
  ValueError: stat: embedded null character in path
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\avaer\appdata\local\programs\python\python37\python.exe' 'c:\users\avaer\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\avaer\AppData\Local\Temp\tmpi2zn5wiz' Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\users\avaer\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command```

## Expected result

Install successful.

## Versions

```C:\Users\avaer\Documents\GitHub\TTS>python --version
Python 3.7.9

C:\Users\avaer\Documents\GitHub\TTS>pip --version
pip 20.1.1 from c:\users\avaer\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)
```

I've also tried python 3.9, 3.8 and they are all erroring with different versions of this on install.

**Comment by avaer** [comment]
I found this: https://stackoverflow.com/questions/66726331/how-can-i-run-mozilla-tts-coqui-tts-training-with-cuda-on-a-windows-system

**Comment by erogol** [comment]
did it work ?

**Comment by avaer** [comment]
Yes, it required 3 hours to get around Windows python problems but in the end I got it training.

**Comment by erogol** [comment]
Nice! Then I close this.
