### ISSUE TITLE
[Bug] glowtts - error when calling model.inference()

### ISSUE THREAD

**Issue by dsplog** [coqui-ai/TTS#531]
If you've found a bug, please provide the following information:

**Describe the bug**

**To Reproduce**
1. Run the following command '...'
>> python -i TTS/bin/train_glow_tts.py --config_path ./tests/inputs/test_glow_tts.json 

3. See error
RuntimeError: Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size
Traceback (most recent call last):
  File "TTS/bin/train_glow_tts.py", line 595, in <module>
    main(args)
  File "TTS/bin/train_glow_tts.py", line 571, in main
    eval_avg_loss_dict = evaluate(eval_loader, model, criterion, ap, global_step, epoch)
  File "/home/home/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "TTS/bin/train_glow_tts.py", line 397, in evaluate
    if hasattr(model, "module"):
  File "/home/home/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "./TTS/tts/models/glow_tts.py", line 281, in inference
    y, logdet = self.decoder(z, y_mask, g=g, reverse=True)
  File "/home/home/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./TTS/tts/layers/glow_tts/decoder.py", line 123, in forward
    x, logdet = f(x, x_mask, g=g, reverse=reverse)
  File "/home/home/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./TTS/tts/layers/glow_tts/glow.py", line 198, in forward
    x = self.start(x_0) * x_mask
  File "/home/home/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/home/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 259, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size

**Expected behavior**
evaluation has to proceed

**Environment (please complete the following information):**
Linux home-desktop 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
>>> torch.__version__
'1.7.1'
 NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |

**Additional context**

**Comment by erogol** [comment]
the config you used is intended to be used for only testing a special case and you should not train a model with it. 

The issue is that the provided input sequence is too short for the model.
