### ISSUE TITLE
Getting Error in using models other then the default model

### ISSUE THREAD

**Issue by adiwithadidas** [coqui-ai/TTS#542]
Hi,

I am getting the below mentioned error when using any model other the default model 

Traceback (most recent call last):
  File "/app/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.7/site-packages/TTS/bin/synthesize.py", line 257, in main
    wav = synthesizer.tts(args.text, args.speaker_idx, args.speaker_wav)
  File "/app/lib/python3.7/site-packages/TTS/utils/synthesizer.py", line 257, in tts
    waveform = self.vocoder_model.inference(vocoder_input.to(device_type))
  File "/app/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/lib/python3.7/site-packages/TTS/vocoder/models/wavegrad.py", line 94, in inference
    y_n = self.c1[n] * (y_n - self.c2[n] * self.forward(y_n, x, sqrt_alpha_hat[n].repeat(x.shape[0])))
  File "/app/lib/python3.7/site-packages/TTS/vocoder/models/wavegrad.py", line 73, in forward
    shift_and_scale.append(film(x, noise_scale))
  File "/app/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/app/lib/python3.7/site-packages/TTS/vocoder/layers/wavegrad.py", line 52, in forward
    o = self.input_conv(x)
  File "/app/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/app/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/app/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 260, in _conv_forward
    self.padding, self.dilation, self.groups)

**Comment by erogol** [comment]
pls use the issue template and repost.
