### ISSUE TITLE
pip3 install tts fails in setup.py VERSION file missing

### ISSUE THREAD

**Issue by ecowitness** [coqui-ai/TTS#555]
**Describe the bug**
(in the pip3 = pypi pip install tts ((referencing TTS-0.0.15.tar.gz uploaded Jun 4, 2021)) )

the setup.py program references file TTS/VERSION which does not exist. The github page for tts shows that file. The pypi file is not correct and cannot install as setup.py fails

**To Reproduce**
1. Run the following command 'pip3 install tts' in docker build
2. you can just pull the https://files....tar.gz and look at its contents

````
Collecting tts
  Downloading https://files.pythonhosted.org/packages/75/cb/9249b366603a941eb416915c0d7933a9e25bf90c45be822a2f4426bfad07/TTS-0.0.15.tar.gz (1.3MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dvfn6tnv/tts/setup.py", line 22, in <module>
        with open(os.path.join(cwd, "TTS", "VERSION")) as fin:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-dvfn6tnv/tts/TTS/VERSION'
````

note also that setup.py imports numpy and numpy needed cython, so just using "pip3 install tts" fails unless you do a few installs before that. if you use --no-install-recommends you will be doing a lot of installs before that

**Comment by erogol** [comment]
should be fixed with v0.0.15.1. Can you try?

**Comment by ecowitness** [comment]
setup.py no longer fails with missing file TTS/VERSION when using TTS-0.0.15.1.tar.gz

note that the requirements list includes cython, but the setup.py program imports cython

note that the requirements list includes numpy==1.18.5 but the setup.py program imports numpy. while I'm doing iterative docker builds, I had pip3 installed numpy at version 1.19.5, so now I've bumped into another issue and will do my build again.

the setup.py program runs for a very along time (installing pandas, numpy, matplotlib, etc.) so I'm closing this issue before the setup.py program has actually concluded.
