### ISSUE TITLE
[Bug] Training Align_TTS pred_spec = decoder_output[idx].detach().data.cpu().numpy().T TypeError: 'NoneType' object is not subscriptable 0 

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#556]
When training Align_TTS I am getting this error on evaluation, posting this here for faster resolution and isolating the specific problem for later

```
 > EVALUATION

Traceback (most recent call last):
  File "TTS/bin/train_align_tts.py", line 563, in <module>
    main(args)
  File "TTS/bin/train_align_tts.py", line 540, in main
    eval_avg_loss_dict = evaluate(eval_loader, model, criterion, ap, global_step, epoch, cur_phase)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "TTS/bin/train_align_tts.py", line 350, in evaluate
    pred_spec = decoder_output[idx].detach().data.cpu().numpy().T
TypeError: 'NoneType' object is not subscriptable
0 <class 'torch.Tensor'> <class 'NoneType'> None
 ! Run is removed from /home/ubuntu/work/TTS-0.0.13/output/align_tts-June-08-2021_05+54AM-0000000

```

**To Reproduce**
1. run the command CUDA_VISIBLE_DEVICES="0" python TTS/bin/train_align_tts.py --config_path config.json | tee training.log

**Expected behavior**
A trained model should be available

**Environment (please complete the following information):**
- **Linux Ubuntu 18.04**:
- **Tensorflow**:
- **Python 3.6**:

**Additional context**
Training [training.log](https://github.com/coqui-ai/TTS/files/6608101/training.log.txt) works fine after giving it the proper config 
[config.json](https://github.com/coqui-ai/TTS/files/6608072/config.json.txt)

**Comment by zubairahmed-ai** [comment]
Also do you need to set `"mixed_precision": true`?

**Comment by zubairahmed-ai** [comment]
Training seems to have started after I removed phase start steps by `"phase_start_steps" : null` 
closing the issue for now
