### ISSUE TITLE
[Bug] distribution training - RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. 

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#574]
I am running distributed training for 4 GPUs of 16Gb each to fine-tune on my own dataset using below command but I get the following error

```
:~/work/TTS-0.0.13$ CUDA_VISIBLE_DEVICES="0,1,2,3" python TTS/bin/distribute.py --script train_align_tts.py --config_path config.json
['/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py', '--continue_path=', '--restore_path=', '--config_path=config.json', '--group_id=group_2021_06_15-093823', '--rank=0']
['/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py', '--continue_path=', '--restore_path=', '--config_path=config.json', '--group_id=group_2021_06_15-093823', '--rank=1']
['/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py', '--continue_path=', '--restore_path=', '--config_path=config.json', '--group_id=group_2021_06_15-093823', '--rank=2']
['/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py', '--continue_path=', '--restore_path=', '--config_path=config.json', '--group_id=group_2021_06_15-093823', '--rank=3']
 > Using CUDA:  True
 > Number of GPUs:  4
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 > Git Hash: 0000000
 > Experiment folder: /home/ubuntu/work/TTS-0.0.13/output/align_tts-June-15-2021_09+38AM-0000000
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 > Setting up Audio Processor...
 | > sample_rate:48000
 | > resample:True
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:0
 | > fft_size:1024
 | > power:1.1
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 | > Found 44063 files in /home/ubuntu/work/TTS-0.0.13/VCTK-Corpus-removed-silence
 > Using model: align_tts

 > Model has 22813937 parameters
 > Starting with inf best loss.

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 43623
 | > Max length sequence: 185
 | > Min length sequence: 9
 | > Avg length sequence: 39.64715860899067
 | > Num. instances discarded by max-min (max=200, min=13) seq limits: 82
 | > Batch group size: 0.

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 440
 | > Max length sequence: 118
 | > Min length sequence: 13
 | > Avg length sequence: 38.80227272727273
 | > Num. instances discarded by max-min (max=200, min=13) seq limits: 0
 | > Batch group size: 0.

 > Current AlignTTS phase: None

 > EPOCH: 0/10000

 > TRAINING (2021-06-15 09:39:07)
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 563, in <module>
    main(args)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 538, in main
    train_loader, model, criterion, optimizer, scheduler, ap, global_step, epoch, cur_phase
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 147, in train
    text_input, text_lengths, mel_targets, mel_lengths, g=speaker_c, phase=training_phase
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 563, in <module>
    main(args)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 538, in main
    train_loader, model, criterion, optimizer, scheduler, ap, global_step, epoch, cur_phase
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 147, in train
    text_input, text_lengths, mel_targets, mel_lengths, g=speaker_c, phase=training_phase
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 563, in <module>
    main(args)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 538, in main
    train_loader, model, criterion, optimizer, scheduler, ap, global_step, epoch, cur_phase
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 147, in train
    text_input, text_lengths, mel_targets, mel_lengths, g=speaker_c, phase=training_phase
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 563, in <module>
    main(args)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 538, in main
    train_loader, model, criterion, optimizer, scheduler, ap, global_step, epoch, cur_phase
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 147, in train
    text_input, text_lengths, mel_targets, mel_lengths, g=speaker_c, phase=training_phase
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

```

**To Reproduce**
1. Run the following command `CUDA_VISIBLE_DEVICES="0,1,2,3" python TTS/bin/distribute.py --script train_align_tts.py --config_path config.json`

**Expected behavior**
Multi-GPU training should start

**Environment (please complete the following information):**
- **Linux Ubuntu 18.04**:
- **Python 3.6**:
- **4xGPU each Tesla V100**:

**Additional context**
Please note that training starts on single GPU with a lower batch-size

@erogol please help

**Comment by zubairahmed-ai** [comment]
I have set `find_unused_parameters=True` at `/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/parallel/distributed.py` to fix this issue 
Batch size is still 8 though

**Comment by erogol** [comment]
Please don't use my handle everytime you encounter  a problem. This is not a support channel. It's an open source project and we already try to help everyone who asks for help.

**Comment by zubairahmed-ai** [comment]
Sorry, should have seen this coming. You've been very helpful
