### ISSUE TITLE
[Bug] Distributed training on Tesla V100 but Batch-size only 4?

### ISSUE THREAD

**Issue by zubairahmed-ai** [coqui-ai/TTS#575]
Not a bug per se, but I am surprised that I cant set a larger batch-size of 8 or 16 let alone 32 on 4x Tesla V100 GPUs training distributed 
When I set a larger batch-size I got a CUDA out of memory error, it appears that 1 out of those 4 GPUs was giving this error because the training process had not exited yet and I have to Ctrl-C out of it.

![image](https://user-images.githubusercontent.com/1317442/122161015-60d03a80-ce8a-11eb-9b00-2df7cbe88ff4.png)

As you can imagine even on my small dataset of 100 samples (Mono, 48KHz) just like the 1st speaker p225 in the VCTK dataset, the training is taking longer than I anticipated. Would re-sampling dataset to a 22KHz speed things up without compromising output, I don't want to deviate from the VCTK dataset much?

Any clues how to speed things up here?

**To Reproduce**
1. Run the following command CUDA_VISIBLE_DEVICES="0,1,2,3" python TTS/bin/distribute.py --script train_align_tts.py --config_path config.json

**Environment (please complete the following information):**
- **Ubuntu 18.04**:
- **Python 3.6**:
- **Tesla V100 x4**:

**Comment by erogol** [comment]
what is the longest text in your dataset?

Can you post here your training log from the start to the first iteration?

**Comment by zubairahmed-ai** [comment]
Thanks @erogol for responding, I noticed that `training.log` doesn't update in distributed training, it was fine in single-GPU or is there any other place where the log is saved?

Finding the longest text and sending

**Comment by zubairahmed-ai** [comment]
Longest text `If the red of the second bow falls upon the green of the first, the result is to give a bow with an abnormally wide yellow band, since red and green light when mixed form yellow.` at 179 characters

**Comment by zubairahmed-ai** [comment]
![image](https://user-images.githubusercontent.com/1317442/122215753-07393180-cec5-11eb-8ea2-0a7823174c9e.png)
Here's the tensorboard output

**Comment by erogol** [comment]
What is your `r` value used in the model? 

You can copy the log from terminal and paste it here.

**Comment by zubairahmed-ai** [comment]
Not sure what happened to my `config.json` after training started, it's been reset and there is no dataset path in it :(
the "r" value is 1

**Comment by zubairahmed-ai** [comment]
Now after giving the right config `aligntts_transformers.json` and batch size 16 I get the following error when training starts
Like you notice the process hasn't exited yet and I have to kill these process to begin training again 

```
> DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 99
 | > Max length sequence: 179
 | > Min length sequence: 16
 | > Avg length sequence: 50.878787878787875
 | > Num. instances discarded by max-min (max=200, min=13) seq limits: 0
 | > Batch group size: 0.

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 1
 | > Max length sequence: 40
 | > Min length sequence: 40
 | > Avg length sequence: 40.0
 | > Num. instances discarded by max-min (max=200, min=13) seq limits: 0
 | > Batch group size: 0.

 > Current AlignTTS phase: None

 > EPOCH: 0/10000

 > TRAINING (2021-06-16 12:55:55)
 ! Run is removed from /home/ubuntu/work/TTS-0.0.13/output/align_tts-June-16-2021_12+55PM-0000000
Traceback (most recent call last):
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 563, in <module>
    main(args)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 538, in main
    train_loader, model, criterion, optimizer, scheduler, ap, global_step, epoch, cur_phase
  File "/home/ubuntu/work/TTS-0.0.13/TTS/bin/train_align_tts.py", line 147, in train
    text_input, text_lengths, mel_targets, mel_lengths, g=speaker_c, phase=training_phase
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/models/align_tts.py", line 247, in forward
    o_de, attn = self._forward_decoder(o_en, o_en_dp, dr_mas, x_mask, y_lengths, g=g)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/models/align_tts.py", line 200, in _forward_decoder
    o_de = self.decoder(o_en_ex, y_mask, g=g)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/layers/feed_forward/decoder.py", line 229, in forward
    o = self.decoder(x, x_mask, g)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/layers/feed_forward/decoder.py", line 122, in forward
    o = self.transformer_block(x) * x_mask
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/layers/generic/transformer.py", line 64, in forward
    x, align = layer(x, src_key_padding_mask=mask)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/work/TTS-0.0.13/TTS/tts/layers/generic/transformer.py", line 23, in forward
    src2, enc_align = self.self_attn(src, src, src, attn_mask=src_mask, key_padding_mask=src_key_padding_mask)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 987, in forward
    attn_mask=attn_mask)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/functional.py", line 4807, in multi_head_attention_forward
    attn_output_weights = softmax(attn_output_weights, dim=-1)
  File "/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/nn/functional.py", line 1583, in softmax
    ret = input.softmax(dim)
RuntimeError: CUDA out of memory. Tried to allocate 474.00 MiB (GPU 0; 15.78 GiB total capacity; 13.92 GiB already allocated; 228.00 MiB free; 14.07 GiB reserved in total by PyTorch)


```

**Comment by zubairahmed-ai** [comment]
Batch size of 8 seems to work
What does `warning: audio amplitude out of range, auto clipped.` warning means?

```
 > Current AlignTTS phase: None

 > EPOCH: 0/10000

 > TRAINING (2021-06-16 12:59:35)
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/ubuntu/anaconda3/envs/ttstf/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:144: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "

   --> TRAIN PERFORMACE -- EPOCH TIME: 7.19 sec -- GLOBAL_STEP: 4
     | > avg_loss: 7.81578
     | > avg_loss_l1: 0.92574
     | > avg_loss_ssim: 0.66657
     | > avg_loss_dur: 2.14748
     | > avg_mdn_loss: 4.14510
     | > avg_align_error: 0.29649
     | > avg_loader_time: 0.00530
     | > avg_step_time: 1.66000

 > EVALUATION

0 <class 'torch.Tensor'> <class 'torch.Tensor'> tensor([[[-2.0215e-01, -1.5648e-01, -3.5252e-01,  ..., -3.8091e-01,
          -3.4685e-01,  2.5457e-02],
         [-1.3190e+00, -1.4899e+00, -1.5471e+00,  ..., -9.2942e-01,
          -1.2478e+00, -1.3747e+00],
         [-2.0807e-04, -4.4352e-01,  7.1419e-02,  ...,  5.0860e-01,
          -5.5982e-01, -3.6097e-01],
         ...,
         [-2.1534e-01, -9.6414e-01, -8.5965e-01,  ..., -9.5999e-01,
          -6.3192e-01, -9.1443e-02],
         [-2.8783e-02,  4.1113e-01,  3.8835e-01,  ...,  4.2760e-01,
           5.7805e-01,  3.6064e-01],
         [ 4.4679e-03, -7.2156e-02, -9.9793e-02,  ...,  8.3315e-02,
           4.0813e-01, -6.6444e-01]]], device='cuda:0')
warning: audio amplitude out of range, auto clipped.
 | > Synthesizing test sentences
warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.
  --> EVAL PERFORMANCE
     | > avg_loss: 8.92843 (+0.00000)
     | > avg_loss_l1: 1.29984 (+0.00000)
     | > avg_loss_ssim: 0.99047 (+0.00000)
     | > avg_loss_dur: 1.28943 (+0.00000)
     | > avg_mdn_loss: 5.34869 (+0.00000)
     | > avg_align_error: 0.00000 (+0.00000)

 >> BEST MODEL : /home/ubuntu/work/TTS-0.0.13/output/align_tts-June-16-2021_12+59PM-0000000/best_model.pth.tar

 > Current AlignTTS phase: None

```

**Comment by erogol** [comment]
try reducing `max_seq_len` to ~140 and increase r=2 if you even need larger batches.

Memory is limited not only by the model but the longest sequence in the dataset. 

See https://github.com/coqui-ai/TTS/wiki/FAQ

**Comment by zubairahmed-ai** [comment]
Thanks so do I need to also reduce text in my dataset for setting max len 140?

**Comment by zubairahmed-ai** [comment]
I set the `"max_seq_len": 180` which is max of my dataset and r=2 but still can't set batch-size 16 so I think it's ok and I'll just leave it here

**Comment by zubairahmed-ai** [comment]
Closing this until the issue reappears. Thanks

**Comment by erogol** [comment]
"max_seq_len" should be lower. It filters out samples longer than the defined value so it helps you reduce memory requirements.

**Comment by zubairahmed-ai** [comment]
Thanks, now that training has started for couple of hours I will tweak this in next iteration

**Comment by zubair-ahmed-ai** [comment]
Is this training looking normal to you after nearly 1750 epochs out of 10K?

![image](https://user-images.githubusercontent.com/66907171/122334487-41e9ab00-cf53-11eb-9b3d-389034e7c6a7.png)

**Comment by zubairahmed-ai** [comment]
Is this training looking normal to you after nearly 1750 epochs out of 10K?

![image](https://user-images.githubusercontent.com/1317442/122334822-bb819900-cf53-11eb-932f-af0bed909bbb.png)

**Comment by erogol** [comment]
Why did you reopen the issue? Did the error reoccur?

**Comment by zubairahmed-ai** [comment]
No sorry about that but thought to get your feedback on the tensorboard output above and where better to show you this then the issue that started this in the first place, where can I discuss the output with you?

**Comment by erogol** [comment]
You can post in discussions
