### ISSUE TITLE
[Bug] Error when test tts_model "tts_models/zh-CN/baker/tacotron2-DDC-GST"

### ISSUE THREAD

**Issue by Lizh-TW** [coqui-ai/TTS#588]
**Describe the bug**
Run:
tts --text "你好我好大家好" \
	--model_name "tts_models/zh-CN/baker/tacotron2-DDC-GST" \
	--vocoder_name "vocoder_models/de/thorsten/wavegrad" \
	--out_path /dataset/output.wav
Error
 > tts_models/zh-CN/baker/tacotron2-DDC-GST is already downloaded.
 > vocoder_models/de/thorsten/wavegrad is already downloaded.
Traceback (most recent call last):
  File "/opt/conda/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/TTS/bin/synthesize.py", line 234, in main
    args.use_cuda,
  File "/opt/conda/lib/python3.7/site-packages/TTS/utils/synthesizer.py", line 72, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/opt/conda/lib/python3.7/site-packages/TTS/utils/synthesizer.py", line 117, in _load_tts
    self.tts_config = load_config(tts_config_path)
  File "/opt/conda/lib/python3.7/site-packages/TTS/utils/io.py", line 50, in load_config
    data = read_json_with_comments(config_path)
  File "/opt/conda/lib/python3.7/site-packages/TTS/utils/io.py", line 33, in read_json_with_comments
    data = json.loads(input_str)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 24 column 29 (char 783)

Please tell me how to solve this problem, thank you.

**Comment by Lizh-TW** [comment]
I solved this problem
pip install TTS >=0.0.15
