### ISSUE TITLE
[Bug] RuntimeWarning: overflow encountered in power

### ISSUE THREAD

**Issue by Megh-Thakkar** [coqui-ai/TTS#589]
I am running the command listed [here](https://gist.github.com/erogol/97516ad65b44dbddb8cd694953187c5b) to train tacotron on LJ Speech. I am using the code base from the [v0.0.10](https://github.com/coqui-ai/TTS/tree/v0.0.10) release. My config is as follows:

```json
{'model': 'Tacotron2', 'run_name': 'ljspeech-ddc', 'run_description': 'tacotron2 with DDC and differential spectral loss.', 'audio': {'fft_size': 1024, 'win_length': 1024, 'hop_length': 256, 'frame_length_ms': None, 'frame_shift_ms': None, 'sample_rate': 22050, 'preemphasis': 0.0, 'ref_level_db': 20, 'do_trim_silence': True, 'trim_db': 60, 'power': 1.5, 'griffin_lim_iters': 60, 'num_mels': 80, 'mel_fmin': 50.0, 'mel_fmax': 7600.0, 'spec_gain': 1, 'signal_norm': True, 'min_level_db': -100, 'symmetric_norm': True, 'max_norm': 4.0, 'clip_norm': True, 'stats_path': None}, 'distributed': {'backend': 'nccl', 'url': 'tcp://localhost:54321'}, 'reinit_layers': [], 'batch_size': 32, 'eval_batch_size': 16, 'r': 7, 'gradual_training': [[0, 7, 64], [1, 5, 64], [50000, 3, 32], [130000, 2, 32], [290000, 1, 32]], 'mixed_precision': True, 'loss_masking': True, 'decoder_loss_alpha': 0.5, 'postnet_loss_alpha': 0.25, 'postnet_diff_spec_alpha': 0.25, 'decoder_diff_spec_alpha': 0.25, 'decoder_ssim_alpha': 0.5, 'postnet_ssim_alpha': 0.25, 'ga_alpha': 5.0, 'stopnet_pos_weight': 15.0, 'run_eval': True, 'test_delay_epochs': 10, 'test_sentences_file': None, 'noam_schedule': False, 'grad_clip': 1.0, 'epochs': 1000, 'lr': 0.0001, 'wd': 1e-06, 'warmup_steps': 4000, 'seq_len_norm': False, 'memory_size': -1, 'prenet_type': 'original', 'prenet_dropout': False, 'attention_type': 'original', 'attention_heads': 4, 'attention_norm': 'sigmoid', 'windowing': False, 'use_forward_attn': False, 'forward_attn_mask': False, 'transition_agent': False, 'location_attn': True, 'bidirectional_decoder': False, 'double_decoder_consistency': True, 'ddc_r': 7, 'stopnet': True, 'separate_stopnet': True, 'print_step': 25, 'tb_plot_step': 100, 'print_eval': False, 'save_step': 10000, 'checkpoint': True, 'tb_model_param_stats': False, 'text_cleaner': 'phoneme_cleaners', 'enable_eos_bos_chars': False, 'num_loader_workers': 4, 'num_val_loader_workers': 4, 'batch_group_size': 4, 'min_seq_len': 6, 'max_seq_len': 153, 'compute_input_seq_cache': False, 'use_noise_augment': True, 'output_path': '/home/megh/text_to_speech/', 'phoneme_cache_path': '/home/megh/text_to_speech/Models/phoneme_cache/', 'use_phonemes': False, 'phoneme_language': 'en-us', 'use_speaker_embedding': False, 'use_gst': False, 'use_external_speaker_embedding_file': False, 'external_speaker_embedding_file': '../../speakers-vctk-en.json', 'gst': {'gst_style_input': None, 'gst_embedding_dim': 512, 'gst_num_heads': 4, 'gst_style_tokens': 10, 'gst_use_speaker_embedding': False}, 'datasets': [{'name': 'ljspeech', 'path': '/home/megh/text_to_speech/LJSpeech-1.1/', 'meta_file_train': 'metadata.csv', 'meta_file_val': None}]}
```

The error pops up after about 50 epochs.

The exact traceback is:

```
/home/megh/text_to_speech/tts-v0.0.9/TTS/TTS/utils/audio.py:234: RuntimeWarning: overflow encountered in power
  return np.power(10.0, x / self.spec_gain)
Traceback (most recent call last):
  File "TTS/bin/train_tacotron.py", line 665, in <module>
    main(args)
  File "TTS/bin/train_tacotron.py", line 635, in main
    scaler_st)
  File "TTS/bin/train_tacotron.py", line 313, in train
    train_audio = ap.inv_melspectrogram(const_spec.T)
  File "/home/megh/text_to_speech/tts-v0.0.9/TTS/TTS/utils/audio.py", line 286, in inv_melspectrogram
    return self._griffin_lim(S**self.power)
  File "/home/megh/text_to_speech/tts-v0.0.9/TTS/TTS/utils/audio.py", line 315, in _griffin_lim
    angles = np.exp(1j * np.angle(self._stft(y)))
  File "/home/megh/text_to_speech/tts-v0.0.9/TTS/TTS/utils/audio.py", line 303, in _stft
    pad_mode=self.stft_pad_mode,
  File "/home/megh/anaconda3/envs/tts_env/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/home/megh/anaconda3/envs/tts_env/lib/python3.6/site-packages/librosa/util/utils.py", line 275, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```

I am using pytorch 1.9.0 and a T4 GPU.

**Comment by erogol** [comment]
Try the latest version.

**Comment by erogol** [comment]
It in general means that there is a NaN value somewhere in your model. 

I could not replicate the error. Let me know if you have something replicable or an update. Until then I close this issue.
