### ISSUE TITLE
[Bug] pip command fails to install for v0.1.0

### ISSUE THREAD

**Issue by owahltinez** [coqui-ai/TTS#607]
**Describe the bug**
pip command fails to install for v0.1.0

**To Reproduce**
```
> python3 -m pip install TTS==0.1.0
Collecting TTS==0.1.0
  Downloading TTS-0.1.0.tar.gz (1.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmprwglwxm2 get_requires_for_build_wheel /tmp/tmpa74zbezq
       cwd: /tmp/pip-install-2gyoss3p/TTS
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/tmp/tmprwglwxm2", line 280, in <module>
      main()
    File "/tmp/tmprwglwxm2", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmprwglwxm2", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-48bp47yj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-48bp47yj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-48bp47yj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-48bp47yj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 43, in <module>
      requirements = open(os.path.join(cwd, "requirements.txt"), "r").readlines()
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2gyoss3p/TTS/requirements.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmprwglwxm2 get_requires_for_build_wheel /tmp/tmpa74zbezq Check the logs for full command output.
```

I can workaround the issue by pointing `pip` to the repo directly:
```
python -m pip install git+git://github.com/coqui-ai/TTS.git@v0.1.0
```

I can look into why the `requirements.txt` file is not being included as part of the PyPI package, but I'm not familiar with `twine` and this seems like a relatively high-priority issue that probably can't wait for me to figure this out.

**Environment:**
Using the following Dockerfile:
```
FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt update && \
    apt install -y ca-certificates && update-ca-certificates && \
    apt install -y espeak-ng git libsndfile1 python3 python3-pip
RUN python3 -m pip install TTS==0.1.0
```

**Comment by mawnir** [comment]
same thing on Mac OS 11.4

**Comment by serg06** [comment]
same thing on Ubuntu 18.04
