### ISSUE TITLE
Error when loading TTS using torch.hub.load [Bug] 

### ISSUE THREAD

**Issue by lucascassiano** [coqui-ai/TTS#618]
**Describe the bug**
I tried to run the example from `Coqui-TTS-torchhub-example.ipynb` and got this error:
```sh
# python3 test.py
Downloading: "https://github.com/coqui-ai/TTS/archive/dev.zip" to /root/.cache/torch/hub/dev.zip
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    synthesizer = torch.hub.load('coqui-ai/TTS:dev',
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 390, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "/usr/local/lib/python3.8/dist-packages/torch/hub.py", line 75, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.cache/torch/hub/coqui-ai_TTS_dev/hubconf.py", line 2
    'torch', 'gdown', 'pysbd', 'gruut', 'anyascii', 'pypinyin', 'coqpit', 'mecab-python3', 'unidic-lite`
                                                                                                       ^
SyntaxError: EOL while scanning string literal
```

**To Reproduce**
1. DockerFile
```dockerfile
FROM ubuntu

# update the system and install cron
RUN apt-get -y update && \
    apt-get -y install python3-pip && \
    apt-get -y install espeak-ng

RUN mkdir /app
ADD . /app/
WORKDIR /app

ENV PYTHONUNBUFFERED 1
RUN pip install -r requirements.txt
```
2. Requirements.txt
```
tts
# requirements on notebook example
pysbd
gruut
anyascii
gdown
pypinyin
coqpit
mecab-python3==1.0.3
unidic-lite
```

3. `test.py` (code)
```py
# use torch hub API
import torch
synthesizer = torch.hub.load('coqui-ai/TTS:dev', 
                             'tts', 
                             source='github')
wav = synthesizer.tts("This is an open-source library that generates synthetic speech!")
```

**Expected behavior**

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu:latest docker image
- **PyTorch or TensorFlow version (use command below)**:  Torch ==  1.9.0
- **Python version**: Python 3.8.10
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

**Comment by erogol** [comment]
Yeah it is the last char being ``` ` ``` and not `'`

fix will be there with the next dev branch .
