### ISSUE TITLE
[Bug] AssertionError of sample_rate when training vocoder model for HifiGAN

### ISSUE THREAD

**Issue by Sadam1195** [coqui-ai/TTS#705]
**Describe the bug**

```
assert C.audio["sample_rate"] == C.l1_spec_loss_params["sample_rate"]
AssertionError
```

**To Reproduce**
1. Run the following command '...'
`!CUDA_VISIBLE_DEVICES="0" python TTS_latest/TTS/bin/train_vocoder.py --config_path hifigan_config.json | tee hifigan_models_dir/log1.log`

**Expected behavior**
Training process should have started

**Full Trackback of Error**
```
fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "TTS_latest/TTS/bin/train_vocoder.py", line 12, in main
    trainer = Trainer(args, config, output_path, c_logger, tb_logger)
  File "/content/gdrive/My Drive/Colab Notebooks/Voice_Cloning/TTS_latest/TTS/trainer.py", line 209, in __init__
    self.criterion = self.get_criterion(self.model)
  File "/content/gdrive/My Drive/Colab Notebooks/Voice_Cloning/TTS_latest/TTS/trainer.py", line 919, in get_criterion
    criterion = model.get_criterion()
  File "/content/gdrive/My Drive/Colab Notebooks/Voice_Cloning/TTS_latest/TTS/vocoder/models/gan.py", line 349, in get_criterion
    return [GeneratorLoss(self.config), DiscriminatorLoss(self.config)]
  File "/content/gdrive/My Drive/Colab Notebooks/Voice_Cloning/TTS_latest/TTS/vocoder/layers/losses.py", line 258, in __init__
    assert C.audio["sample_rate"] == C.l1_spec_loss_params["sample_rate"]
AssertionError
 > Git Hash: 0000000
 > Experiment folder: ./hifigan_models_dir/spanish_hifigan-August-03-2021_07+31PM-0000000
 > Using CUDA:  True
 > Number of GPUs:  1
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:True
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.2
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:30.0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Using model: hifigan
 > Vocoder Model: hifigan
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
 ! Run is removed from ./hifigan_models_dir/spanish_hifigan-August-03-2021_07+31PM-0000000
```

**Additional context**
I have all files in `samplerate=16000` , despite that I also tried setting `resample : true` in `hifigan.config ` but I kept getting `AssertionError`

**HifiGAN Config for reference**
```
{
    "model": "hifigan",
    "run_name": "spanish_hifigan",
    "run_description": "hifigan mean-var scaling",
    "epochs": 1000,
    "batch_size": 16,
    "eval_batch_size": null,
    "mixed_precision": false,
    "run_eval": true,
    "test_delay_epochs": 10,
    "print_eval": false,
    "print_step": 25,
    "tb_plot_step": 100,
    "tb_model_param_stats": true,
    "save_step": 5000,
    "checkpoint": true,
    "keep_all_best": false,
    "keep_after": 10000,
    "num_loader_workers": 8,
    "num_eval_loader_workers": 0,
    "use_noise_augment": false,
    "output_path": "./hifigan_models_dir",
    "distributed_backend": "nccl",
    "distributed_url": "tcp://localhost:54321",
    "audio": {
        "fft_size": 1024,
        "win_length": 1024,
        "hop_length": 256,
        "frame_shift_ms": null,
        "frame_length_ms": null,
        "stft_pad_mode": "reflect",
        "sample_rate": 16000,
        "resample": true,
        "preemphasis": 0.20,
        "ref_level_db": 20,
        "do_sound_norm": false,
        "do_trim_silence": true,
        "trim_db": 60,
        "power": 1.5,
        "griffin_lim_iters": 60,
        "num_mels": 80,
        "mel_fmin": 30.0,
        "mel_fmax": 8000.0,
        "spec_gain": 20,
        "signal_norm": true,
        "min_level_db": -100,
        "symmetric_norm": true,
        "max_norm": 4.0,
        "clip_norm": true,
        "stats_path": null
    },
    "eval_split_size": 10,
    "data_path": "./Spanish_LJSpeech-1.1/wavs",
    "feature_path": null,
    "seq_len": 8192,
    "pad_short": 2000,
    "conv_pad": 0,
    "use_cache": true,
    "wd": 0.0,
    "optimizer": "AdamW",
    "optimizer_params": {
        "betas": [
            0.8,
            0.99
        ],
        "weight_decay": 0.0
    },
    "use_stft_loss": false,
    "use_subband_stft_loss": false,
    "use_mse_gan_loss": true,
    "use_hinge_gan_loss": false,
    "use_feat_match_loss": true,
    "use_l1_spec_loss": true,
    "stft_loss_weight": 0.0,
    "subband_stft_loss_weight": 0.0,
    "mse_G_loss_weight": 1.0,
    "hinge_G_loss_weight": 0.0,
    "feat_match_loss_weight": 200.0,
    "l1_spec_loss_weight": 45.0,
    "stft_loss_params": {
        "n_ffts": [
            1024,
            2048,
            512
        ],
        "hop_lengths": [
            120,
            240,
            50
        ],
        "win_lengths": [
            600,
            1200,
            240
        ]
    },
    "l1_spec_loss_params": {
        "use_mel": true,
        "sample_rate": 22050,
        "n_fft": 1024,
        "hop_length": 256,
        "win_length": 1024,
        "n_mels": 80,
        "mel_fmin": 50.0,
        "mel_fmax": 7600.0
    },
    "target_loss": "loss_0",
    "grad_clip": null,
    "lr_gen": 0.0002,
    "lr_disc": 0.0002,
    "lr_scheduler_gen": "ExponentialLR",
    "lr_scheduler_gen_params": {
        "gamma": 0.999,
        "last_epoch": -1
    },
    "lr_scheduler_disc": "ExponentialLR",
    "lr_scheduler_disc_params": {
        "gamma": 0.999,
        "last_epoch": -1
    },
    "use_pqmf": false,
    "diff_samples_for_G_and_D": false,
    "discriminator_model": "hifigan_discriminator",
    "generator_model": "hifigan_generator",
    "generator_model_params": {
        "upsample_factors": [
            8,
            8,
            2,
            2
        ],
        "upsample_kernel_sizes": [
            16,
            16,
            4,
            4
        ],
        "upsample_initial_channel": 128,
        "resblock_kernel_sizes": [
            3,
            7,
            11
        ],
        "resblock_dilation_sizes": [
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ],
            [
                1,
                3,
                5
            ]
        ],
        "resblock_type": "1"
    },
    "lr": 0.001
}
```

**Comment by Sadam1195** [comment]
**Update**

When I tried `"use_l1_spec_loss": false,` in my `config` training did get started but I am not sure if it would significantly effect performance.

**Comment by Sadam1195** [comment]
On a closer look I found out that my config settings were inconsistent so I had to edit the following settings and error was gone.

```
"l1_spec_loss_params": {
        "use_mel": true,
        "sample_rate": 22050,
        "n_fft": 1024,
        "hop_length": 256,
        "win_length": 1024,
        "n_mels": 80,
        "mel_fmin": 50.0,
        "mel_fmax": 7600.0
    },
```

**Comment by Sadam1195** [comment]
> @Sadam1195 I wonder if these settings have any implication on training,
> 
> > "mel_fmin": 50.
> > "mel_fmax": 7600.0
> 
> , because in my HiFiGan training config.json (generated the distribute.py) has the following setting
> 
> > "mel_fmin": 0.
> > "mel_fmax": null,

It shouldn't make much difference in my view.

**Comment by erogol** [comment]
try using the same values for the best performance
