### ISSUE TITLE
[Bug] ImportError: DLL load failed while importing _MeCab: Das angegebene Modul wurde nicht gefunden.

### ISSUE THREAD

**Issue by ygoe** [coqui-ai/TTS#711]
Is this already usable today or is it still under development and doesn't work yet? Just asking. I have no experience with this technology. I don't have the capacity to work on this project's code or train anything, I'm just an interested user here. In the long term, I'd like to build a speech command system with this technology. But I've never seen anything executable from DeepSpeech and just learned that this has now a different name. As this project page looked like it could be tried out, I did. But I didn't get very far. All the Python packages installed (apart from the warnings about the PATH). Next I understood I'm supposed to run the 'tts' application. That fails. It can't find something it thinks it needs.

**Describe the bug**
Executing "tts.exe" I get this error output and nothing else:

```
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\Scripts\tts.exe\__main__.py", line 4, in <module>
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\site-packages\TTS\bin\synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\site-packages\TTS\utils\synthesizer.py", line 9, in <module>
    from TTS.tts.models import setup_model as setup_tts_model
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\site-packages\TTS\tts\models\__init__.py", line 1, in <module>
    from TTS.tts.utils.text.symbols import make_symbols, parse_symbols
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\site-packages\TTS\tts\utils\text\__init__.py", line 12, in <module>
    from TTS.tts.utils.text.japanese.phonemizer import japanese_text_to_phonemes
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\site-packages\TTS\tts\utils\text\japanese\phonemizer.py", line 6, in <module>
    import MeCab
  File "C:\Users\Yves\AppData\Roaming\Python\Python39\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: Das angegebene Modul wurde nicht gefunden.
```

**To Reproduce**
1. Run the following command: pip3 install TTS
2. Run the following command: %AppData%\Python\Python39\Scripts\tts.exe
3. See error

**Expected behavior**
Maybe a more helpful output? Not sure what to expect, I'd just like to see what I can do with it.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10.20H2 x64
- **PyTorch or TensorFlow version (use command below)**: what is that? there's no command "below"
- **Python version**: 3.9.6 (current latest stable)
- **CUDA/cuDNN version**: unknown, probably n/a
- **GPU model and memory**: Intel Core i7-3770
- **Exact command to reproduce**: tts.exe

**Comment by erogol** [comment]
we don't support windows officially as of now. You can try running on WSL.

**Comment by nikich340** [comment]
Probably you don't need Japanese text tools, so you can simply comment out lines 11, 50-52 in `TTS\tts\utils\text\__init__.py`

**Comment by megakitten** [comment]
pip install mecab-python3 worked fine for me.
