### ISSUE TITLE
Resume training fails to restore previous best loss[Bug] 

### ISSUE THREAD

**Issue by Sadam1195** [coqui-ai/TTS#712]
**Describe the bug**
I tried to resume training using `--restore_path` path flag but it doesn't load model checkpoint properly so it returns empty `dir` location for `self.args.best_path` at line https://github.com/coqui-ai/TTS/blob/4c7e2f5359cfefb273b7cc0fe04e0756cccec3d9/TTS/trainer.py#L778 so it never returns previous best loss value hence it fails to resume the training. 

**To Reproduce**
1. Run the following command

```
!CUDA_VISIBLE_DEVICES="0" python TTS_latest/TTS/bin/train_vocoder.py 
     --restore_path ./hifigan_models_dir/spanish_hifigan-August-04-2021_07+22PM-0000000/best_model_7228.pth.tar 
     --config_path ./hifigan_config.json | tee ./hifigan_models_dir/log2.log
```

**Error traceback**
```
fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/content/gdrive/My Drive/Colab Notebooks/Voice_Cloning/TTS_latest/TTS/trainer.py", line 807, in fit
    self._fit()
  File "/content/gdrive/My Drive/Colab Notebooks/Voice_Cloning/TTS_latest/TTS/trainer.py", line 780, in _fit
    self.best_loss = torch.load(self.args.best_path, map_location="cpu")["model_loss"]
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
 > Git Hash: 0000000
 > Experiment folder: ./hifigan_models_dir/spanish_hifigan-August-07-2021_09+42PM-0000000
 > Using CUDA:  True
 > Number of GPUs:  1
 > Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:True
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.2
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:30.0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Using model: hifigan
 > Vocoder Model: hifigan
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
 > Restoring from best_model_7228.pth.tar ...
 > Restoring Model...
 > Restoring Optimizer...
 > Model restored from step 7228

 > Model has 71653105 parameters
 > Restoring best loss from  ...
 ! Run is removed from ./hifigan_models_dir/spanish_hifigan-August-07-2021_09+42PM-0000000
```

**Additional context**
I printed `self.args.best_path` to see if it path was loaded but it was always empty.

**Comment by Sadam1195** [comment]
I fixed it by changing the following lines in [trainer.py](https://github.com/coqui-ai/TTS/blob/4c7e2f5359cfefb273b7cc0fe04e0756cccec3d9/TTS/trainer.py)

From this 
```
        if self.restore_step != 0 or self.args.best_path:
            print(" > Restoring best loss from " f"{os.path.basename(self.args.best_path)} ...")
            self.best_loss = load_fsspec(self.args.best_path, map_location="cpu")["model_loss"]
```
to this

```
        if self.restore_step != 0 or self.args.restore_path:
            print(" > Restoring best loss from " f"{os.path.basename(self.args.restore_path)} ...")
            self.best_loss = load_fsspec(self.args.restore_path, map_location="cpu")["model_loss"]
```
