### ISSUE TITLE
[Bug] Problems on loading files on Windows

### ISSUE THREAD

**Issue by godspirit00** [coqui-ai/TTS#729]
**Describe the bug**
In version 0.2.0, it looks like `fsspec` is used to handle file io, but it is not working fine on Windows.
I was trying to continue training a model, but I got the error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'g:/G:/tts/Nancy/training/output/nancy-dca-August-09-2021_08+41PM-0fc9f387/checkpoint_60000.pth.tar'
```
It looks like `fsspec` is messing with the volume label, which makes it impossible to find the file/dir.
**To Reproduce**
1. Run the following command `python TTS\bin\train_tts.py --continue_path "G:\tts\Nancy\training\output\nancy-dca-August-09-2021_08+41PM-0fc9f387"`
2. See error

**Expected behavior**
The training should start.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **PyTorch or TensorFlow version (use command below)**: 
- **Python version**: 3.8
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**:
- **Exact command to reproduce**:

**Additional context**
I tried with `python TTS\bin\train_tts.py --continue_path "file:///G:\tts\Nancy\training\output\nancy-dca-August-09-2021_08+41PM-0fc9f387"` but the tensorboard will give an error:
```
Traceback (most recent call last):
  File "TTS\bin\train_tts.py", line 14, in <module>
    main()
  File "TTS\bin\train_tts.py", line 8, in main
    args, config, output_path, _, c_logger, dashboard_logger = init_training(sys.argv)
  File "d:\ttss\tts\TTS\trainer.py", line 1152, in init_training
    config, OUT_PATH, AUDIO_PATH, c_logger, dashboard_logger = process_args(args, config)
  File "d:\ttss\tts\TTS\trainer.py", line 1134, in process_args
    dashboard_logger = init_logger(config)
  File "d:\ttss\tts\TTS\utils\logging\__init__.py", line 8, in init_logger
    dashboard_logger = TensorboardLogger(config.output_log_path, model_name=config.model)
  File "d:\ttss\tts\TTS\utils\logging\tensorboard_logger.py", line 9, in __init__
    self.writer = SummaryWriter(log_dir)
  File "C:\Users\tony\Envs\reader-mix\lib\site-packages\tensorboardX\writer.py", line 293, in __init__
    self._get_file_writer()
  File "C:\Users\tony\Envs\reader-mix\lib\site-packages\tensorboardX\writer.py", line 341, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir,
  File "C:\Users\tony\Envs\reader-mix\lib\site-packages\tensorboardX\writer.py", line 103, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Users\tony\Envs\reader-mix\lib\site-packages\tensorboardX\event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "C:\Users\tony\Envs\reader-mix\lib\site-packages\tensorboardX\record_writer.py", line 51, in directory_check
    os.makedirs(path)
  File "c:\users\tony\appdata\local\programs\python\python38\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\tony\appdata\local\programs\python\python38\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "c:\users\tony\appdata\local\programs\python\python38\lib\os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 3 more times]
  File "c:\users\tony\appdata\local\programs\python\python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name or volume label syntax is incorrect: 'file:'
```

The training worked fine in previous version.

**Comment by erogol** [comment]
It is not a bug 

```
OSError: [WinError 123] The filename, directory name or volume label syntax is incorrect: 'file:'
```

**Comment by NanobotZ** [comment]
I've also run in the same problem - my setup runs on commit c3082267073ed45b69993aa83437958b1c42615f (11 Aug 2021).

This line was breaking it for me:
trainer.py:1029 `file_names = [scheme + "://" + file_name for file_name in file_names]`

I've replaced it with `file_names = [file_name for file_name in file_names]` (removed the `scheme + "://" + ` part) and now it continues and trains fine.
