### ISSUE TITLE
[Bug] tts_models/en/ljspeech/tacotron2-DCA using /home/erogol/

### ISSUE THREAD

**Issue by davidak** [coqui-ai/TTS#781]
Welcome to the 🐸TTS project! We are excited to see your interest, and appreciate your support!

This repository is governed by the Contributor Covenant Code of Conduct. For more details, see the [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md) file.

If you've found a bug, please provide the following information:

**Describe the bug**

```
[nix-shell:~/.cache/nixpkgs-review/pr-135694-1]$ tts --text "test" --model_name tts_models/en/ljspeech/tacotron2-DCA --vocoder_name vocoder_models/en/ljspeech/hifigan_v2
 > tts_models/en/ljspeech/tacotron2-DCA is already downloaded.
 > vocoder_models/en/ljspeech/hifigan_v2 is already downloaded.
Traceback (most recent call last):
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/bin/.tts-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 226, in main
    synthesizer = Synthesizer(
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 72, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 145, in _load_tts
    self.ap = AudioProcessor(verbose=False, **self.tts_config.audio)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/audio.py", line 294, in __init__
    mel_mean, mel_std, linear_mean, linear_std, _ = self.load_stats(stats_path)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/audio.py", line 421, in load_stats
    stats = np.load(stats_path, allow_pickle=True).item()  # pylint: disable=unexpected-keyword-arg
  File "/nix/store/ndg3gxxrw07782s2drpjsrw8s1a88f86-python3.9-numpy-1.20.3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/erogol/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/scale_stats.npy'
```

cc @erogol 

**To Reproduce**
1. Run the following command '...'
2. ...
3. See error

**Expected behavior**

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **PyTorch or TensorFlow version (use command below)**:
- **Python version**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

**Additional context**

**Comment by davidak** [comment]
This is also fixed by re-downloading the models.
