### ISSUE TITLE
[Bug] json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by davidak** [coqui-ai/TTS#782]
**Describe the bug**

```
[nix-shell:~/.cache/nixpkgs-review/pr-135694-1]$ tts --text "this is a t e s t" --model_name tts_models/en/sam/tacotron-DDC --vocoder_name vocoder_models/en/ljspeech/hifigan_v2
 > tts_models/en/sam/tacotron-DDC is already downloaded.
Traceback (most recent call last):
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/bin/.tts-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 205, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/manage.py", line 126, in download_model
    self._update_paths(output_path, output_config_path)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/manage.py", line 141, in _update_paths
    self._update_path("audio.stats_path", output_stats_path, config_path)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/utils/manage.py", line 155, in _update_path
    config = load_config(config_path)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/config/__init__.py", line 88, in load_config
    data = read_json_with_comments(config_path)
  File "/nix/store/1010symblq3nlwph1r6prcak7h4m8bh8-tts-0.2.1/lib/python3.9/site-packages/TTS/config/__init__.py", line 22, in read_json_with_comments
    data = json.loads(input_str)
  File "/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**

see above

**Expected behavior**
no error

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NixOS 21.11.git.762f24a4156 (from the future)
- **PyTorch or TensorFlow version (use command below)**:
- **Python version**: 3.9.6
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

**Additional context**
maybe it's related to the python version?

**Comment by erogol** [comment]
Can't reproduce it on my local machine. Maybe you should remove the pre-downloaded models and try again.

**Comment by davidak** [comment]
Yeah, that fixed it. Maybe add that to the release notes.

```
[nix-shell:~/.cache/nixpkgs-review/pr-135694-1]$ tts --text "this is a t e s t" --model_name tts_models/en/sam/tacotron-DDC --vocoder_name vocoder_models/en/ljspeech/hifigan_v2
 > Downloading model to /home/davidak/.local/share/tts/tts_models--en--sam--tacotron-DDC
 > Downloading model to /home/davidak/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2
 > Using model: Tacotron2
 > Vocoder Model: hifigan
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 > Text: this is a t e s t
 > Text splitted to sentences.
['this is a t e s t']
 > interpolating tts model output.
 > before interpolation : (80, 110)
 > after interpolation : torch.Size([1, 80, 151])
 > Processing time: 0.5791325569152832
 > Real-time factor: 0.1809223857904665
 > Saving output to tts_output.wav
```
