### ISSUE TITLE
[Bug] No such file or directory: vocoder_models--en--ljspeech--univnet/model_file.pth.tar

### ISSUE THREAD

**Issue by davidak** [coqui-ai/TTS#808]
**Describe the bug**

```
[nix-shell:~/.cache/nixpkgs-review/pr-137735]$ tts --text "This is how it is." --model_name tts_models/en/ljspeech/tacotron2-DDC_ph
 > Downloading model to /home/davidak/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC_ph
 > Downloading model to /home/davidak/.local/share/tts/vocoder_models--en--ljspeech--univnet
 > Using model: Tacotron2
 > Model's reduction rate `r` is set to: 2
 > Vocoder Model: univnet
 > Generator Model: univnet_generator
 > Discriminator Model: univnet_discriminator
Traceback (most recent call last):
  File "/nix/store/yv4v4219gzsbyj7n13vh2m68d0w1iaqb-tts-0.3.0/bin/.tts-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/yv4v4219gzsbyj7n13vh2m68d0w1iaqb-tts-0.3.0/lib/python3.9/site-packages/TTS/bin/synthesize.py", line 226, in main
    synthesizer = Synthesizer(
  File "/nix/store/yv4v4219gzsbyj7n13vh2m68d0w1iaqb-tts-0.3.0/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 75, in __init__
    self._load_vocoder(vocoder_checkpoint, vocoder_config, use_cuda)
  File "/nix/store/yv4v4219gzsbyj7n13vh2m68d0w1iaqb-tts-0.3.0/lib/python3.9/site-packages/TTS/utils/synthesizer.py", line 164, in _load_vocoder
    self.vocoder_model.load_checkpoint(self.vocoder_config, model_file, eval=True)
  File "/nix/store/yv4v4219gzsbyj7n13vh2m68d0w1iaqb-tts-0.3.0/lib/python3.9/site-packages/TTS/vocoder/models/gan.py", line 226, in load_checkpoint
    state = load_fsspec(checkpoint_path, map_location=torch.device("cpu"))
  File "/nix/store/yv4v4219gzsbyj7n13vh2m68d0w1iaqb-tts-0.3.0/lib/python3.9/site-packages/TTS/utils/io.py", line 71, in load_fsspec
    with fsspec.open(path, "rb") as f:
  File "/nix/store/3adslx9mfrfl73n2hljay7s7hs4rspjp-python3.9-fsspec-2021.07.0/lib/python3.9/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/nix/store/3adslx9mfrfl73n2hljay7s7hs4rspjp-python3.9-fsspec-2021.07.0/lib/python3.9/site-packages/fsspec/spec.py", line 976, in open
    f = self._open(
  File "/nix/store/3adslx9mfrfl73n2hljay7s7hs4rspjp-python3.9-fsspec-2021.07.0/lib/python3.9/site-packages/fsspec/implementations/local.py", line 145, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/nix/store/3adslx9mfrfl73n2hljay7s7hs4rspjp-python3.9-fsspec-2021.07.0/lib/python3.9/site-packages/fsspec/implementations/local.py", line 236, in __init__
    self._open()
  File "/nix/store/3adslx9mfrfl73n2hljay7s7hs4rspjp-python3.9-fsspec-2021.07.0/lib/python3.9/site-packages/fsspec/implementations/local.py", line 241, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/davidak/.local/share/tts/vocoder_models--en--ljspeech--univnet/model_file.pth.tar'
```

The file does actually not exist:

```
[nix-shell:~/.cache/nixpkgs-review/pr-137735]$ ll /home/davidak/.local/share/tts/vocoder_models--en--ljspeech--univnet/
total 659308
-rw-r--r-- 1 davidak users 675105017 Sep 15 18:30 checkpoint_580000.pth.tar
-rw-r--r-- 1 davidak users      4040 Sep 15 18:30 config.json
drwxr-xr-x 3 davidak users      4096 Sep 15 18:30 __MACOSX
-rw-r--r-- 1 davidak users     10700 Sep 15 18:30 scale_stats.npy
```

I completely removed `/home/davidak/.local/share/tts` before.

For reference: Found by reviewing https://github.com/NixOS/nixpkgs/pull/137735.

**To Reproduce**
1. Run the following command '...'
2. ...
3. See error

**Expected behavior**
no errors

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NixOS 21.11.git.77ca2b51e9c
- **PyTorch or TensorFlow version (use command below)**:
- **Python version**: 3.9
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

**Comment by erogol** [comment]
Pls remove the univnet folder and retry.

**Comment by davidak** [comment]
I also tried to remove `/home/davidak/.local/share/tts/vocoder_models--en--ljspeech--univnet` with the same result.

Maybe you have to rename `checkpoint_580000.pth.tar` to `model_file.pth.tar` in your source?

**Comment by erogol** [comment]
Yep you are ➡️, I updated the release. Should be 👍

**Comment by davidak** [comment]
It works now. Thank you!
