### ISSUE TITLE
[Bug] Init speaker_embedding layer get error

### ISSUE THREAD

**Issue by Lizh-TW** [coqui-ai/TTS#915]
I train a new model and when I test it get this error

100 is my speaker's amount.

[my model](https://drive.google.com/file/d/1hEsefigapnKP4AyK6ANF8_DuwMnPGo1e/view?usp=sharing)

$ tts --text "早安你好呀"    \                            
--model_path m-tts/n-tts/TacotronDDC_Chinese_multi-speaker_tts-October-30-2021_05+33AM-0000000/best_model.pth.tar    \
--config_path m-tts/n-tts/TacotronDDC_Chinese_multi-speaker_tts-October-30-2021_05+33AM-0000000/config.json    \
--speaker_idx SSB0005
 > Using model: tacotron
 > Init speaker_embedding layer.
Traceback (most recent call last):
  File "/opt/conda/bin/tts", line 33, in <module>
    sys.exit(load_entry_point('TTS', 'console_scripts', 'tts')())
  File "/workspace/TTS/TTS/bin/synthesize.py", line 234, in main
    args.use_cuda,
  File "/workspace/TTS/TTS/utils/synthesizer.py", line 72, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/workspace/TTS/TTS/utils/synthesizer.py", line 113, in _load_tts
    self.tts_model.load_checkpoint(self.tts_config, tts_checkpoint, eval=True)
  File "/workspace/TTS/TTS/tts/models/base_tacotron.py", line 90, in load_checkpoint
    self.load_state_dict(state["model"])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for speaker_embedding.weight: copying a param with shape torch.Size([100, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).

**Comment by erogol** [comment]
Should have been fixed by now on the dev branch.
