### ISSUE TITLE
[Bug]Multi-speaker Glow TTS (vctk DB) error at inference

### ISSUE THREAD

**Issue by Jaehyoun** [coqui-ai/TTS#919]
When I try to implement glow-tts model that I trained with VCTK DB,
I got this error and I don't know why.

$ ./TTS/bin/synthesize.py --text "Text for TTS" --out_path /workspace/Multi-speaker_TTS/outputs/usr_vctkglow.wav --model_path recipes/vctk/glow_tts/coqui_tts-November-04-2021_01+27AM-40c17b22/best_model.pth.tar --config_path recipes/vctk/glow_tts/coqui_tts-November-04-2021_01+27AM-40c17b22/config.json --speakers_file_path recipes/vctk/glow_tts/coqui_tts-November-04-2021_01+27AM-40c17b22/speakers.json --speaker_idx VCTK_p225

> Traceback (most recent call last):
  File "./TTS/bin/synthesize.py", line 265, in <module>
    main()
  File "./TTS/bin/synthesize.py", line 234, in main
    args.use_cuda,
  File "/workspace/Multi-speaker_TTS/TTS/TTS/utils/synthesizer.py", line 72, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/workspace/Multi-speaker_TTS/TTS/TTS/utils/synthesizer.py", line 110, in _load_tts
    speaker_manager = self._init_speaker_manager()
  File "/workspace/Multi-speaker_TTS/TTS/TTS/utils/synthesizer.py", line 129, in _init_speaker_manager
    speaker_manager = SpeakerManager(d_vectors_file_path=self.tts_speakers_file)
  File "/workspace/Multi-speaker_TTS/TTS/TTS/tts/utils/speakers.py", line 77, in __init__
    self.set_d_vectors_from_file(d_vectors_file_path)
  File "/workspace/Multi-speaker_TTS/TTS/TTS/tts/utils/speakers.py", line 164, in set_d_vectors_from_file
    speakers = sorted({x["name"] for x in self.d_vectors.values()})
  File "/workspace/Multi-speaker_TTS/TTS/TTS/tts/utils/speakers.py", line 164, in <setcomp>
    speakers = sorted({x["name"] for x in self.d_vectors.values()})
TypeError: 'int' object is not subscriptable

**Comment by erogol** [comment]
Can you also share your models so that I run the exact command above?

**Comment by Sasha349** [comment]
Have same error. After fix loading skeakers file, error in _speaker_embedding func. [https://drive.google.com/file/d/1CuJvjCRLq_BbtLFK-fum2w21tD1lMKaB/view?usp=sharing](model)

**Comment by atseng17** [comment]
I had the same error when doing inference on a glowTTS trained on libriTTS dataset. @Jaehyoun did you end up solving it?

**Comment by erogol** [comment]
can you try the latest version ?

**Comment by Sasha349** [comment]
TTS-0.5.0 return error
[error.log](https://github.com/coqui-ai/TTS/files/7880233/error.log)
.
