### ISSUE TITLE
[BUG] HiFiGAN Training w/ Multiple GPUs

### ISSUE THREAD

**Issue by automationist** [coqui-ai/TTS#958]
**Describe the bug**
When using `distribute.py` to train HiFiGAN, you get an error message that says `TypeError: get_data_loader() takes 7 positional arguments but 8 were given`.

**To Reproduce**
1. Run the following command `python3 TTS/bin/distribute.py --script recipes/ljspeech/hifigan/train_hifigan.py --restore_path /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2/model_file.pth.tar`
2. See error ```Traceback (most recent call last):
  File "/home/ubuntu/TTS/TTS/trainer.py", line 1007, in fit
Traceback (most recent call last):
  File "/home/ubuntu/TTS/TTS/trainer.py", line 1007, in fit
    self._fit()
  File "/home/ubuntu/TTS/TTS/trainer.py", line 992, in _fit
Traceback (most recent call last):
  File "/home/ubuntu/TTS/TTS/trainer.py", line 1007, in fit
    self._fit()
  File "/home/ubuntu/TTS/TTS/trainer.py", line 992, in _fit
    self.train_epoch()
  File "/home/ubuntu/TTS/TTS/trainer.py", line 804, in train_epoch
    self._fit()
  File "/home/ubuntu/TTS/TTS/trainer.py", line 992, in _fit
    self.train_epoch()
  File "/home/ubuntu/TTS/TTS/trainer.py", line 804, in train_epoch
    verbose=True,
  File "/home/ubuntu/TTS/TTS/trainer.py", line 498, in get_train_dataloader
    return self._get_loader(self.model, self.config, training_assets, False, data_items, verbose, self.num_gpus)
  File "/home/ubuntu/TTS/TTS/trainer.py", line 480, in _get_loader
    verbose=True,
  File "/home/ubuntu/TTS/TTS/trainer.py", line 498, in get_train_dataloader
    self.train_epoch()
Traceback (most recent call last):
  File "/home/ubuntu/TTS/TTS/trainer.py", line 804, in train_epoch
  File "/home/ubuntu/TTS/TTS/trainer.py", line 1007, in fit
    config, assets, is_eval, data_items, verbose, num_gpus, self.args.rank
TypeError: get_data_loader() takes 7 positional arguments but 8 were given```

**FIX/HACK**
I added `rank: int = None` to line 313 in `TTS/TTS/vocoder/models/gan.py`.

**Comment by erogol** [comment]
Can you send a ✨PR✨ for the fix?

**Comment by skol101** [comment]
@automationist does continue_path option works for you when you stop and then continue training of HiFiGAN? Because it doesn't for me — training starts from step 0.

**Comment by arif334** [comment]
@automationist Your fix has solved the problem. Please send a PR.

**Comment by erogol** [comment]
If there is not PR, it'll be fixed in the next version.
