### ISSUE TITLE
[Bug] Unable to load downloaded model as restore point

### ISSUE THREAD

**Issue by DelanoLeslie** [coqui-ai/TTS#980]
I think this is a bug. When I try to load a model from the tts synthesis command, it doesn't work. I get this error: 

`| > Found 135 files in /content
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Using model: Tacotron2
fatal: not a git repository (or any of the parent directories): .git
 > Using CUDA:  True
 > Number of GPUs:  1
 > Restoring from model.pth.tar ...
 > Restoring Model...
 > Restoring Optimizer...
Traceback (most recent call last):
  File "TTS/TTS/bin/train_tts.py", line 73, in <module>
    main()
  File "TTS/TTS/bin/train_tts.py", line 67, in main
    parse_command_line_args=False,
  File "/usr/local/lib/python3.7/dist-packages/TTS-0.4.2-py3.7-linux-x86_64.egg/TTS/trainer.py", line 304, in __init__
    self.config, args.restore_path, self.model, self.optimizer, self.scaler
  File "/usr/local/lib/python3.7/dist-packages/TTS-0.4.2-py3.7-linux-x86_64.egg/TTS/trainer.py", line 438, in restore_model
    optimizer = _restore_list_objs(checkpoint["optimizer"], optimizer)
  File "/usr/local/lib/python3.7/dist-packages/TTS-0.4.2-py3.7-linux-x86_64.egg/TTS/trainer.py", line 429, in _restore_list_objs
    obj.load_state_dict(states)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`

**To Reproduce**
1. First you download a model by using the built in sythesis command like:
`tts --text "Hello" \
--model-name "Modelname here"`
2. You then try to run the training command using the built in config and model, (somethings are changed to change the dataset)
`python TTS/TTS/bin/train_tts.py \
    --restore_path path/to/downloaded/model/model.pth.tar \
    --config_path  path/to/downloaded/model/configjson \
    --coqpit.datasets.0.path /content/ \
    --coqpit.datasets.0.meta_file_train "metadata.txt" `
3. When you run the command it gives that error

**Expected behavior**
The expected behavior is for the model to pick up from the downloaded model and start training.

**Environment (please complete the following information):**
- This is run in google colab pro
- Python 3.7.12
- I am unsure the Cuda version, running it without cuda still gives the same error

**Additional context**
I used the method on the website. I am unsure if I had something wrong.

**Comment by DelanoLeslie** [comment]
Ok so, looking in the config, the biggest line, the default DCC model has one of its decoders pruned, switching to the DCC_ph version fixed this. 💀
